### PR TITLE
Use Relative Path

### PR DESCRIPTION
**Pull request by naveen521kk**
## List of Changes
- Remove some Print statements in `basic.py`
- Made every path to a relative for *readability*.

## Acknowledgement

- [x] I have read the [Contributing Guidelines](https://github.com/ManimCommunity/manim/wiki/Documentation-guidelines-(WIP))

### CODE REVIEW

**Comment by leotrs** [comment]
Thanks for catching those prints! Question: how will the absolute -> relative switch change the way we call manim?

**Comment by naveen521kk** [comment]
> 
> 
> Thanks for catching those prints! Question: how will the absolute -> relative switch change the way we call manim?

Nothing but just the way it prints in log statements that's it. In Windows, the tex templates would be mixed with back and front slashes. `/`,`\` for example `./media\Tex\a6d208c81e4e5843.tex` and looks weird. That the reason I changed it. :)

**Comment by leotrs** [comment]
I see, that makes sense! I'm still confused... I can see why the `media_dir` should/would be better as relative, but the library-wide config file shouldn't be changed to relative, right? I mean, this change will affect where the files are found, not only how they are printed. Am I missing something?

**Comment by naveen521kk** [comment]
Done it!

**Pull request merged**
