### PR TITLE
GrowArrow animation fixed

### LINKED ISSUE #1002: Arrow tip not animating correctly in GrowArrow animation
## Description of bug / unexpected behavior
When displaying a simple ```GrowArrow()``` animation, the arrow tip does not animate correctly. At the beginning of the animation the tip is added to the screen at full scale facing to the left (no matter what direction it faces by the end of the animation). It then animates by shrinking and growing again to full scale by the end of the animation whilst rotating so that it points to the correct direction by the end of the animation also.

## Expected behavior
The arrow should begin small and grow to its full size whilst pointing in the intended direction throughout the entirety of the animation (so that the line and tip appear as one entity).

## How to reproduce the issue
```python
class GrowArrowTest(Scene):
    def construct(self):
        arrow = Arrow(LEFT, RIGHT)
        self.play(GrowArrow(arrow))
```

## Additional media files
<details><summary>Unexpected Behaviour</summary>

GrowArrowUnexpected

</details>

<details><summary>Expected Behaviour (Rendered with Grants version of Manim)</summary>

GrowArrowExpected

</details>

## System specifications

<details><summary>System Details</summary>

- OS: macOS 11.1 (Big Sur)
- RAM: 16 GB
- Python version: 3.9.0
- Installed modules:
```
Package           Version
----------------- -------
colorama          0.4.4
colour            0.1.5
commonmark        0.9.1
decorator         4.4.2
manim             0.3.0
manimpango        0.2.0
networkx          2.5
numpy             1.19.5
Pillow            8.1.0
pip               21.0.1
progressbar       2.5
pycairo           1.20.0
pydub             0.24.1
Pygments          2.7.4
rich              6.2.0
scipy             1.6.0
setuptools        49.2.1
tqdm              4.56.0
typing-extensions 3.7.4.3
```
</details>

<details><summary>FFMPEG</summary>
ffmpeg version 4.3.1
</details>

### PR DESCRIPTION
**Pull request by sparshg**
## Motivation

GrowArrow animation doesn't work correctly as per #1002 which is fixed

### Before
arrows

### After
arrows

<details><summary>Code</summary>

```py
def construct(self):
        self.add(Text("Grow").shift(UP + 2*LEFT).scale(0.6), Text("Scale").shift(2*LEFT).scale(0.6))
        self.play(GrowArrow(Arrow(LEFT, RIGHT).shift(UP)), Arrow(RIGHT, LEFT).animate.scale(0, scale_tips=True, about_point=RIGHT))
```
</details>

## Overview / Explanation for Changes

The fix was suggested by @behackl which I implemented, also another issue is fixed where if you scale an arrow when `scale_tip=True` it won't change the thickness of arrow's line according to its length

## Oneline Summary of Changes

```
- GrowArrow animation fixed (:pr:`1003`)
```
## Acknowledgements
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)

## Reviewer Checklist
- [ ] Newly added functions/classes are either private or have a docstring
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings
- [ ] The oneline summary has been included [in the wiki](https://github.com/ManimCommunity/manim/wiki/Changelog-for-next-release)

### CODE REVIEW

**Review by behackl — APPROVED** [review]
LGTM

**Review by huguesdevimeux — CHANGES_REQUESTED** [review]
SGTM. 

This requires a graphical unit test, please :)

**Comment by behackl** [comment]
> SGTM.
> 
> This requires a graphical unit test, please :)

How would you test this? This PR changes the animation, the last frame is unmodified.

**Comment by huguesdevimeux** [comment]
That's a fair point. Then, SGTM

**Review by huguesdevimeux — APPROVED** [review]

**Comment by huguesdevimeux** [comment]
Thanks for the contribution ;D

**Pull request merged**
