### PR TITLE
Added a seed function to random_color() and random_bright_color()

### PR DESCRIPTION
**Pull request by Jaidenmagnan**
## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by JasonGrace2282** [comment]
Hey, thanks for taking an interest in contributing to Manim!
Out of curiosity, what is the use case for this? It seems to me if you want a certain seed you can set it outside of Manim, e.g.
```py
random.seed(...)
rand_color = random_bright_color()
```
Do you mind elaborating?

**Comment by uwezi** [comment]
>  you can set it outside of Manim, e.g.
> 
> ```python
> random.seed(...)
> rand_color = random_bright_color()
> ```
> 
> Do you mind elaborating?

I believe for that to work you would need to know which random package Manim uses internally, `numpy.random`, `random.random` or something completely different. And if the randomizer in Manim is contained in its own object, seeding a random random number generator will most likely not affect Manim's random numbers.

The meaning of a seed would be to be able to recreate the same (not so random) random sequence of colors for every subsequent rendering of the scene.

Personally I don't like either of Manim's random color pickers, because the regular one also contains black (or any other background color) and the "light" colors have too little color contrast. But I can understand the notion of having a seed.

**Comment by JasonGrace2282** [comment]
> I believe for that to work you would need to know which random package Manim uses internally, numpy.random, random.random or something completely different. And if the randomizer in Manim is contained in its own object, seeding a random random number generator will most likely not affect Manim's random numbers.

Hmm, in that case it might be better to have the seed as a `config` parameter maybe? That might be a cleaner approach than a `seed` parameter in every function that uses `numpy.random` or `random`. What do you think?

**Comment by Jaidenmagnan** [comment]
The config parameter would work well, except you would need a way for
subsequent calls to the random function to be reproducible.

**Comment by JasonGrace2282** [comment]
> except you would need a way for subsequent calls to the random function to be reproducible.

I'm not sure what you mean by this. Setting `config.seed` should just run
```py
np.random.seed(seed)
random.seed(seed)
```

**Comment by Jaidenmagnan** [comment]
For example if you called random_color() with a seed of 5, would you want the function to continuously return red. Or would you want it to return red, blue, yellow, green in the same order.

**Comment by JasonGrace2282** [comment]
> For example if you called random_color() with a seed of 5, would you want the function to continuously return red. Or would you want it to return red, blue, yellow, green in the same order.

Isn't that what setting the seed does?

**Comment by JasonGrace2282** [comment]
I just realized this parameter is included in the `Scene` itself (see the signature in [the docs](https://docs.manim.community/en/stable/reference/manim.scene.scene.Scene.html), although it could be documented better).

This can be used as such
```py
class MyAnimation(Scene):
    def __init__(self) -> None:
        super().__init__(random_seed=MY_CUSTOM_SEED)

    def construct(self):
        # usual stuff
```

**Comment by JasonGrace2282** [comment]
Closing as this solution is not a nice way of working with seeds. A better solution could allow something like
```py
class Scene:
    seed: int | None = None

    def __init__(self, ...):
        ...
        if self.seed is not None:
            random.seed(self.seed)
            np.random.seed(self.seed)
```
But it would be better to create a new PR for that.

**Pull request closed without merging**
