### PR TITLE
Fix camera rotation

### PR DESCRIPTION
**Pull request by sparshg**
## Changelog / Overview

wip

## Code

```py
class Test(ThreeDScene):
    def construct(self):
        frame = self.camera
        self.add(NumberPlane())
        self.play(frame.theta_tracker.animate.set_value(PI))
        self.wait(0.5)
        self.play(frame.phi_tracker.animate.set_value(PI))
        self.wait(0.5)
        self.play(frame.gamma_tracker.animate.set_value(PI))
```

[Documentation Reference](https://manimce--####.org.readthedocs.build)

## Checklist
- [ ] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [ ] I have written a descriptive PR title (see top of PR template for examples)
- [ ] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by sparshg** [comment]
um what who is @masura01r

**Comment by Darylgolden** [comment]
No idea?

**Comment by sparshg** [comment]
whaaaat, I pushed the test commits but my name is replaced what?

**Comment by sparshg** [comment]
ok I relinked the email, now it seems to be good lol

**Pull request closed without merging**
