### PR TITLE
Drop redundant OpenGL files and add metaclass support for `Surface`

### PR DESCRIPTION
**Pull request by hydrobeam**
## Changelog / Overview

`OpenGL<x>` classes from `opengl_geometry.py`, `opengl_text_mobject.py`, `opengl_tex_mobject.py`, `opengl_svg_path.py`, `opengl_svg_mobject.py` and most of `opengl_three_dimensions.py` have been removed. 
`ParametricSurface` has been renamed to `Surface`

## Motivation

Less bloat and easier pathway to OpenGL transition

## Explanation for Changes

Removed:
- `opengl_geometry.py`
- `opengl_tex_mobject.py`
- `opengl_text_mobject.py`
- `opengl_svg_path.py`
- `opengl_svg_mobject.py`
- most of `opengl_three_dimensions.py`
   - `OpenGLSurfaceMesh` was left behind because it's opengl specific (relies on `OpenGLSurface`)
- if `config.renderer == opengl` checks in mobject.py and vmobject.py

### `three_dimensions.py`
- Renamed `ParametricSurface` to `Surface`
- Added metaclass capability for `Surface`/`OpenGLSurface`, now 3D mobs will rely on `OpenGLSurface`/`Surface`. depending on the renderer.
- Resolution adjusts depending on the renderer for `Torus` and `Sphere`
- `Sphere` was reworked and had some of its defaults adjusted since it was producing wrong results with the previous implementation in the `OpenGLRenderer`. essentially ported from `OpenGLSphere`.

### example_scenes/opengl.py
- Adjusted the examples to accomodate for the changes
- Ensured that the scenes look the same.

## Documentation Reference
 
N/A

## Testing Status

Some quick code:

```py
class Test(Scene):
    def construct(self):
        sph = Sphere()
        tor = Torus()
        vgr = Group(sph, tor).arrange()
        self.add(vgr)
        self.interactive_embed()
```
cairo:
Test_ManimCE_v0 7 0

opengl:
image

## Further Comments

Renamed `ParametricSurface` since it was probably going to have to happen eventually.

## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [x] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [x] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by hydrobeam** [comment]
There are some issues stemming from the fact that `OpenGLSurface` is a Mobject, whereas the old surfaces were `VMobjects`, which breaks certain classes (such as the polyhedra) in opengl. Also, I'm not too sure about changing `ParametricSurface`'s name. I've made this PR a draft for now 😅

**Comment by hydrobeam** [comment]
Changes:

- Added a fix to make `BraceLabel` appear (use .add instead of setting submobjects directly, because `assemble_family` needs to be called)
-  Rewrote tests (unnoticeable visual differences)
- Deprecate `ParametricSurface` instead of breaking it
- Removed `if config.renderer==opengl` checks in `mobject.py`

`polyhedra.py` still won't work in opengl since it's mixing the `Mobject` from `OpenGLSurface` with the `VMobject` from `Polyhedra` + `Graph`. Rendering each submobject individually [this commit](https://github.com/ManimCommunity/manim/pull/1843/commits/a4c3ed9eb5d2674bdb5d80e2a6698c9e79220372) allows it to be created, but still doesn't let certain methods like `.rotate` work, since they have different implementations in `opengl_vmobject.py` / `opengl_mobject.py`. I reverted the original fix so that the issue won't be hidden.

**Comment by hydrobeam** [comment]
I'm not sure how to resolve the `polyhedra` problem, since perfectly valid mobjects have some functionality stripped simply because of how they're grouped 🤷. It should probably be taken care of in a separate PR.

**Comment by hydrobeam** [comment]
I've updated the changelog to reflect the fact that this introduces breaking changes to `OpenGL<x>` classes.

**Review by eulertour — APPROVED** [review]

**Comment by hydrobeam** [comment]
This PR is dependent on #1899 now to make `test_attr.py` work.  I've rewritten the `test_opengl.py` graphical test since `OpenGLArc` used 8 components, whereas regular `Arc` uses 9 components.
```py
class Arc(TipapleVMmobject)
    def __init__(
        self,
        radius: float = 1.0,
        start_angle=0,
        angle=TAU / 4,
        num_components=9, # was 8 for opengl
        arc_center=ORIGIN,
        **kwargs,
    ):
``` 
Also I had to add a `config.renderer="cairo"` at the end of `test_set_attr.py` or else the following tests failed. But now that tests work, it's no longer a draft 🎉.

**Comment by alembcke** [comment]
@hydrobeam the error I get, along with the manim command I am running is:

```
alexlembcke@system76-pc:~/ManimDev/manim$ poetry run manim ../surface_gradient.py SurfaceTest --renderer=opengl -p
Manim Community v0.8.0

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/alexlembcke/ManimDev/manim/manim/cli/render/commands.py:109 in render                      │
│                                                                                                  │
│   106 │   │   │   │   │   scene_classes = scene_classes_from_file(file)                          │
│   107 │   │   │   │   │   SceneClass = scene_classes[0]                                          │
│   108 │   │   │   │   │   scene = SceneClass(renderer)                                           │
│ ❱ 109 │   │   │   │   │   status = scene.render()                                                │
│   110 │   │   │   │   │   if status:                                                             │
│   111 │   │   │   │   │   │   continue                                                           │
│   112 │   │   │   │   │   else:                                                                  │
│                                                                                                  │
│ /home/alexlembcke/ManimDev/manim/manim/scene/scene.py:215 in render                              │
│                                                                                                  │
│    212 │   │   """                                                                               │
│    213 │   │   self.setup()                                                                      │
│    214 │   │   try:                                                                              │
│ ❱  215 │   │   │   self.construct()                                                              │
│    216 │   │   except EndSceneEarlyException:                                                    │
│    217 │   │   │   pass                                                                          │
│    218 │   │   except RerunSceneException as e:                                                  │
│                                                                                                  │
│ /home/alexlembcke/ManimDev/manim/../surface_gradient.py:27 in construct                          │
│                                                                                                  │
│   24 │   │   │   v_range=[-3, 3]                                                                 │
│   25 │   │   )                                                                                   │
│   26 │   │                                                                                       │
│ ❱ 27 │   │   saddle_plane.set_fill_by_value(axes=axes, colors=[BLUE, GREEN, YELLOW, ORANGE, R    │
│   28 │   │   self.add(axes, saddle_plane)                                                        │
│   29 │   │                                                                                       │
│   30 │   │   self.interactive_embed()                                                            │
│                                                                                                  │
│ /home/alexlembcke/ManimDev/manim/manim/mobject/three_dimensions.py:233 in set_fill_by_value      │
│                                                                                                  │
│   230 │   │   │   )                                                                              │
│   231 │   │                                                                                      │
│   232 │   │   for mob in self.family_members_with_points():                                      │
│ ❱ 233 │   │   │   z_value = axes.point_to_coords(mob.get_midpoint())[2]                          │
│   234 │   │   │   if z_value <= pivots[0]:                                                       │
│   235 │   │   │   │   mob.set_color(new_colors[0])                                               │
│   236 │   │   │   elif z_value >= pivots[-1]:                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'ThreeDVMobject' object has no attribute 'get_midpoint'
```

And if I copy `~.get_midpoint()` to `ThreeDVMobject` and run `poetry install` then this error goes away.  If others are not experiencing the same thing, then perhaps it is due to something on my side.

**Pull request merged**
