### PR TITLE
Set corners of :class:`~.Rectangle` in counterclockwise direction

### PR DESCRIPTION
**Pull request by abhi3019**
## Changelog / Overview

Set the corners of `Rectangle` in counterclockwise direction to be consistent with other geometry `Mobject`s. `Transform`ations between `Rectangle` and other geometry `Mobject`s look better now. 

## Motivation

Here's how the `Transform`ation from `Square` to `Circle` looks currently

https://user-images.githubusercontent.com/73361366/113511407-3a824a80-957d-11eb-8cbe-8ae1fb070ec7.mp4

Notice how the `Square` gets flipped during the `Transform`.
 
## Explanation for Changes
This is because the corners of `Rectangle`s are set in clockwise direction https://github.com/ManimCommunity/manim/blob/9c96d16db199c3186f53e09673bdb6836e9b2006/manim/mobject/geometry.py#L1823 whereas for `Arc`s the `points` are set in counterclockwise direction https://github.com/ManimCommunity/manim/blob/9c96d16db199c3186f53e09673bdb6836e9b2006/manim/mobject/geometry.py#L288-L295
This is what causes the `Square` to be flipped during the `Transform`. This PR changes the cw-orientation of `Rectangle`'s corners `(UL, UR, DR, DL)` to ccw-orientation `(UR, UL, DL, DR)`

## Testing Status

- Local pass (Windows 10)
- This is how the `Transform`ation looks now

https://user-images.githubusercontent.com/73361366/113512974-e24f4680-9584-11eb-9fa0-285f2dc13755.mp4

## Further Comments

This PR is inspired from [Kolibril13's idea to enhance transformation](https://discord.com/channels/581738731934056449/589666750082187302/827162378511843419). I've looked into the entire `geometry.py` module to check if any other `Mobject` needs this switch in orientation. Turned out it's just the `Rectangle`. Let me know if I missed something.

## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by abhi3019** [comment]
My bad, I ran `pytest` in `master` by mistake. I'll fix them

**Comment by huguesdevimeux** [comment]
Really nice stuff 

you can see why tests are failing with --show_diff flag, but I think it's fine to re-generate the graphical unit data for this test

**Comment by abhi3019** [comment]
I think the failing macos test can be fixed once #1255 is merged?

**Review by jsonvillanueva — APPROVED** [review]
LGTM, yes tests should pass after #1255

**Comment by huguesdevimeux** [comment]
tests still fail on macox -_-

**Comment by jsonvillanueva** [comment]
> 
> 
> tests still fail on macox -_-

That's because the branch hasn't updated to include the changes from #1255; @abhi3019, please update when you can.

**Comment by abhi3019** [comment]
Done @jsonvillanueva

**Review by kolibril13 — APPROVED** [review]

**Comment by behackl** [comment]
Something weird is happening here. I don't have the button for merging the latest master in the GH UI, and I also can't push to the branch. I'll merge it nonetheless now (thanks for your contribution!), and we can revert it in case it causes problems.

**Comment by jsonvillanueva** [comment]
@behackl 
I wonder if this happens when PRs are not created with the checkbox `Allow edits from maintainers`. Looking at the GitHub REST API for [this PR](https://api.github.com/repos/ManimCommunity/manim/issues/1249), I don't see the "maintainer_can_modify" key in the json anywhere. Seems like it should exist regardless if it was True/False: https://docs.github.com/en/rest/reference/pulls#update-a-pull-request

**Comment by behackl** [comment]
> @behackl
> I wonder if this happens when PRs are not created with the checkbox `Allow edits from maintainers`. Looking at the GitHub REST API for [this PR](https://api.github.com/repos/ManimCommunity/manim/issues/1249), I don't see the "maintainer_can_modify" key in the json anywhere. Seems like it should exist regardless if it was True/False: https://docs.github.com/en/rest/reference/pulls#update-a-pull-request

That would be a good explanation.

**Pull request merged**
