### PR TITLE
Fixed :meth:`~OpenGLRenderer.get_frame` when window is created

### PR DESCRIPTION
**Pull request by ryanmccauley211**
## Motivation and Explanation: Why and how do your changes improve the library?

When calling `get_frame` in the opengl renderer, it fails as it is using the wrong pixel shape

```
Traceback (most recent call last):
╭──────────────────────────────────────────────────────────────────────────────╮
│ File                                                                         │
│"/Users/ryan/PycharmProjects/manim-community/manim/cli/render/commands.py",   │
│line 108, in render                                                           │
│    105             while keep_running:                                       │
│    106                 for SceneClass in scene_classes_from_file(file):      │
│    107                     scene = SceneClass(renderer)                      │
│  ❱ 108                     rerun = scene.render()                            │
│    109                     if rerun or config["write_all"]:                  │
│    110                         renderer.num_plays = 0                        │
│    111                         continue                                      │
│ File "/Users/ryan/PycharmProjects/manim-community/manim/scene/scene.py", line│
│215, in render                                                                │
│     212         """                                                          │
│     213         self.setup()                                                 │
│     214         try:                                                         │
│  ❱  215             self.construct()                                         │
│     216         except EndSceneEarlyException:                               │
│     217             pass                                                     │
│     218         except RerunSceneException as e:                             │
│ File "../scenes/playground.py", line 42, in construct                        │
│     39                                                                       │
│     40     def construct(self):                                              │
│     41         self.add(Square())                                            │
│  ❱  42         self.renderer.get_frame()                                     │
│     43                                                                       │
│     44                                                                       │
│     45 # class PMPointExample(Scene):                                        │
│ File "/Users/ryan/PycharmProjects/manim-community/manim/renderer/opengl_rende│
│rer.py", line 497, in get_frame                                               │
│    494         # get current pixel values as numpy data in order to test outp│
│    495         raw = self.get_raw_frame_buffer_object_data(dtype="f1")       │
│    496         result_dimensions = (config["pixel_height"], config["pixel_wid│
│  ❱ 497         np_buf = np.frombuffer(raw, dtype="uint8").reshape(result_dime│
│    498         np_buf = np.flipud(np_buf)                                    │
│    499         return np_buf                                                 │
│    500                                                                       │
╰──────────────────────────────────────────────────────────────────────────────╯
ValueError: cannot reshape array of size 3686400 into shape (480,854,4)

Process finished with exit code 1
```

To reproduce you can run the command `../scenes/example.py --renderer opengl -pql`.

```py
class Test(Scene):

    def construct(self):
        self.add(Square())
        self.renderer.get_frame()
```

The method was only working when there was preview window, such as when outputting a movie file.

## Reviewer Checklist
- [x] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Review by hydrobeam — APPROVED** [review]
LGTM! Just curious, did you just happen to catch this bug or was it impacting another functionality?

**Comment by ryanmccauley211** [comment]
> LGTM! Just curious, did you just happen to catch this bug or was it impacting another functionality?

I have been reusing cairo tests to run with opengl renderer and one of those tests caught the bug

**Review by behackl — APPROVED** [review]

**Comment by behackl** [comment]
@ryanmccauley211, there is a minor merge conflict -- do you have time to resolve it? This can be merged afterwards.

**Comment by ryanmccauley211** [comment]
> @ryanmccauley211, there is a minor merge conflict -- do you have time to resolve it? This can be merged afterwards.

done

**Pull request merged**
