### PR TITLE
A faster method to compute split_factors

### PR DESCRIPTION
**Pull request by Kiran-Raj-Dev**
## Overview: What does this pull request change?

The older method required 47 seconds to compute the split factors this one requires only 5.
Thanks to notkev from the discord server for suggesting this method

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by Kiran-Raj-Dev** [comment]
Build time now is 901 seconds.

**Comment by hydrobeam** [comment]
Do you have a sample scene we can test this with?

**Comment by Kiran-Raj-Dev** [comment]
This is tested on v14.0.0. The [sample scene](https://discord.com/channels/581738731934056449/669259565941915723/940587820404342876)

The reason I didn't test it on main is because you cannot see the difference after Daryl's imporving ~:meth:become PR.

**Comment by Darylgolden** [comment]
I think it might be visible when transforming complex VMobjects, like transforming some long text into another.

**Comment by Kiran-Raj-Dev** [comment]
[Here's](https://colab.research.google.com/drive/1Xt5HtJsA5-DRJ01h6AsoqvINses7EJ73?usp=sharing) a colab notebook which shows the time difference between the two methods

**Review by Darylgolden — APPROVED** [review]
Thank you, LGTM!

**Review by behackl — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
