### PR TITLE
ci: fix release asset upload

### PR DESCRIPTION
**Pull request by naveen521kk**
## Motivation
Previously release failed upload of archive. This would fix it.

## Oneline Summary of Changes

```
- ci: fix release asset upload (:pr:`PR NUMBER HERE`)
```

## Testing Status
this works for [manimpango](https://github.com/ManimCommunity/ManimPango/blob/main/.github/workflows/build.yml)

## Acknowledgements
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)

## Reviewer Checklist
- [x] Newly added functions/classes are either private or have a docstring
- [x] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [x] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings
- [ ] The oneline summary has been included [in the wiki](https://github.com/ManimCommunity/manim/wiki/Changelog-for-next-release)

### CODE REVIEW

**Comment by behackl** [comment]
We will only be able to see whether this actually works for manim as well with the next release, right?

**Comment by naveen521kk** [comment]
yeah, atleast you can see a pretty much similar workflow is used in manimpango, where it worked well.

**Review by behackl — APPROVED** [review]
Well, it *looks* okay to me. 🤷

**Comment by naveen521kk** [comment]
> Well, it looks okay to me. shrug

Well, I had been patching this workflow nearly from the first release and this never worked. Let me see at least this works or not.

**Pull request merged**
