### PR TITLE
Improve sidebar structure of reference manual

### PR DESCRIPTION
**Pull request by behackl**
## Changelog / Overview

This moves around some modules in the reference manual to produce a nicer sidebar structure. Link to rendered documentation: https://manimce--1778.org.readthedocs.build/en/1778/

### CODE REVIEW

**Comment by behackl** [comment]
We could also go one step further and shorten module and class names in general:

image

**Comment by PhotonSpheres** [comment]
> We could also go one step further and shorten module and class names in general:

I prefer the shorter ones as they minimize side-scrolling.

**Comment by WampyCakes** [comment]
Overall, a massive improvement to the docs! I was about to merge when I noticed this:
image

I actually prefer the [current reference page](https://docs.manim.community/en/stable/reference.html). Perhaps the current reference page could use some cleaner separation of the content on the page, but I really like that I can scroll to see everything instead of clicking each link.

I think I would be okay with this change if this:
image
could be added to the top right of each page linked from the first picture so that you can quickly navigate to the other sections without having to go all the way back. (Obviously there would be a couple changes needed in that second picture to stay consistent with your changes and make more sense)

One other thing is: does it actually make more sense to put the module index before the inheritance graph? You can certainly navigate to where you want quicker that way if you know where it is.

**Comment by behackl** [comment]
I've played around with this before I pushed the branch, and I've now also tried some more: I can't find a satisfying solution for what you would like to have.

If the reference manual is structured like before (nice tables in `/reference`), then the sidebar can't be structured into subsections for animations, mobjects, ... – and even worse, with the short names something like this would happen (but for all of Manim's modules): 

image

An alternative could be disabling the max-depth of the table of content tree that is built on the reference page, then the list would look something like this:

image

(I don't really like the super long list and I'd also rather have the table, but I don't think this is possible.)

Out of all these possibilities I personally like the one currently pushed to this PR the most. Feel free to play around with Sphinx yourself; I don't intend to make further substantial changes to this PR.

**Review by jsonvillanueva — APPROVED** [review]
I'm in favor of the new look for the sidebar and don't mind the missing table in the main reference page

**Comment by WampyCakes** [comment]
I still plan to spend a bit more time on looking for solutions. Can't atm however

**Comment by behackl** [comment]
> I still plan to spend a bit more time on looking for solutions. Can't atm however

Can further improvements be delegated to a follow-up PR?

**Review by WampyCakes — APPROVED** [review]
How about setting max-depth (like in your second picture) so that it doesn't show classes like Wait or Create, but does show their categories like animation, fading, etc? I would be happy with that and then regarding a ToC on the top right, this can be investigated later.

**Review by Darylgolden — CHANGES_REQUESTED** [review]
I was just going to merge this, but then I noticed a problem with search. For example, searching for [Polygon](https://manimce--1778.org.readthedocs.build/en/1778/search.html?q=polygon&check_keywords=yes&area=default#), the same page is split into 2 results (`manim.mobject.geometry.Polygon` and `Polygon`, `manim.mobject.geometry.ArcPolygon` and `ArcPolygon`, etc.). If there is no easy fix for this, I'd be happy merging the PR as is and filing an issue to fix it at a later date.

**Comment by hydrobeam** [comment]
Screenshot for reference (duplication + description bugs):
image

**Comment by behackl** [comment]
I get the same behavior for other PRs (like https://manimce--1807.org.readthedocs.build/en/1807/search.html?q=Polygon&check_keywords=yes&area=default), this might just be an issue with documentation built for PRs in general.

I can resolve the conflict and add the change requested by @WampyCakes in a bit.

**Review by Darylgolden — APPROVED** [review]
Ah, LGTM then!

**Comment by behackl** [comment]
Updated and resolved merge conflict. I think this is ready to be merged.

**Pull request merged**
