### PR TITLE
Fix dependent issues action

### PR DESCRIPTION
**Pull request by leotrs**
Follow up from #777.

cc @z0al @naveen521kk

### CODE REVIEW

**Comment by leotrs** [comment]
Uhm I just added a personal token as requested, but I see this: `  Error: env.GITHUB_TOKEN must not be empty`

**Comment by leotrs** [comment]
I think this is what @naveen521kk was warning us of.

**Comment by naveen521kk** [comment]
Simply revert the previous commit and change the schedule cron to 30 min(`*/30 * * * *`) and also remove pull_request event.

**Comment by leotrs** [comment]
Ok let's try it:

Depends on #777

**Comment by naveen521kk** [comment]
Wait it need to be merged with master first for it to work. Or else it will run only 00:00 (UTC).

**Comment by naveen521kk** [comment]
I think it won't work with merged PR? Will it?

**Comment by leotrs** [comment]
Oof, yeah not sure.

**Comment by leotrs** [comment]
It's been more than 30 minutes, so it seems it doesn't work on this closed PR.

**Comment by naveen521kk** [comment]
It's queued and not yet run https://github.com/ManimCommunity/manim/runs/1480948978

**Comment by leotrs** [comment]
Ah thanks

**Comment by leotrs** [comment]
It finished running, it only checked open issues and PRs.

**Comment by naveen521kk** [comment]
I think that is what is expected though.

**Comment by leotrs** [comment]
Yes, I think this is working as best as possible up to now.

Hopefully we can figure out a way of running it on PRs too.

**Comment by leotrs** [comment]
BTW the current schedule `*/30 * * * *` means it will run at each hour-and-thirty minutes (00:30, 01:30, 02:30, etc), not every 30 minutes :sweat_smile:

**Comment by naveen521kk** [comment]
Is https://crontab.guru/#*/30_*_*_*_* wrong then? I think that is right?

**Comment by leotrs** [comment]
I understand this as "every 30th minute after the our" :thinking: Maybe I'm wrong :thinking: :thinking: :thinking: 

But also, the action seems to be running once an hour, no?

**Comment by leotrs** [comment]
Oh wait seems like I am wrong. Welp.

**Comment by z0al** [comment]
> Depends on #777

This needs to be in the PR description, not comments. Just like issues.

The way GitHub handles fork repos still confuses me. 

@naveen521kk regarding the `pull_request` comment you had. I'm not sure about fork repos but for source repos `pull_request` events will work just like any other events and it will have the necessary token permissions. [Here is an example](https://github.com/newnewb/test/pull/4) 

> It finished running, it only checked open issues and PRs.

Do you expect it to update closed/merged issues/PRs? it doesn't.

**Comment by z0al** [comment]
> With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.

Oh, God. Why GitHub? Why

why

**Comment by naveen521kk** [comment]
> @naveen521kk regarding the pull_request comment you had. I'm not sure about fork repos but for source repos pull_request events will work just like any other events and it will have the necessary token permissions. Here is an example

Maybe because this is a forked repo?

**Comment by z0al** [comment]
It's for sure because it's a forked repo :)

**Comment by naveen521kk** [comment]
I had the slightest idea of creating a dummy account on github as a bot and use it's personal token for everything related to this action. So, the bot's name, with our logo maybe will be shown instead of Github Actions. Also, that will be super cool though.

**Comment by z0al** [comment]
That's should work AFAIK. And yeah, that's something I miss from the old bot.

**Comment by leotrs** [comment]
> This needs to be in the PR description, not comments. Just like issues.

Yep, got it! :sweat_smile: 

> Do you expect it to update closed/merged issues/PRs? it doesn't.

Come to think about it, the current behavior is :ok_hand:

**Comment by z0al** [comment]
FYI, I learned that there is another event called [pull_request_target](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request_target) that is suitable for this action use-case. 

When used the action should get read/write token. Reported [here](https://github.com/z0al/dependent-issues/issues/2). I updated the docs accordingly

**Pull request merged**
