### PR TITLE
Enable python -m manim invocation

### PR DESCRIPTION
**Pull request by pedrovhb**
**1. The motivation for making this change (or link the relevant issues)**

The purpose of this PR is to enable the community edition to be invoked as a Python module, i.e. `python -m manim <args>`. Currently it seems the only way to trigger a render is to use the executable `manim`.

The reason one would want to use `python -m manim <args>` is that it makes it possible to attach a debugger to the Scene script and the library execution in general.

**2. How you tested the new behavior (e.g. a minimal working example, before/after
screenshots, gifs, commands, etc.) This is rather informal at the moment, but
the goal is to show us how you know the pull request works as intended.**

I have tested this by succesfully invoking manim via the command line with `python -m manim <file>`:

image

And by setting a breakpoint and dropping to the REPL during runtime of the script with Pycharm, with the following run settings:

image

### CODE REVIEW

**Comment by Kreijstal** [comment]
You could probably rename it manim.py since it's basically what manim.py seemed to do.

**Comment by leotrs** [comment]
@Kreijstal The use of `__main__.py` goes beyond that of a simple module name. See for example [this](https://gist.github.com/rochacbruno/ed19c5d9ba9bb50391a2).

**Comment by pedrovhb** [comment]
@Kreijstal it is, but then it doesn't work to `python -m manim ...`, which I think is more convenient than typing out the directory of the lib installation or repo.

**Comment by zoroppz** [comment]
Is this part of the latest lib? I an unable to use this feature.

**Comment by behackl** [comment]
> Is this part of the latest lib? I an unable to use this feature.

Hello! Yes, this should work in principle. Here is not the correct place for troubleshooting though, please either open a [new issue|(https://github.com/ManimCommunity/manim/issues/new/choose) or a [new discussion](https://github.com/ManimCommunity/manim/discussions/new).

**Pull request merged**
