### PR TITLE
Alternative scaling for tree graph layout

### PR DESCRIPTION
**Pull request by pcouy**
## Overview: What does this pull request change?

* Fix errors when trying to use the tree layout with a single-vertex
  graph (was caused by a division by 0)
* `scale` can now be `None` (or a tuple containing `None`). A
  `None` value keeps the spacings computed by SageMath's tree layout
  implementation in the corresponding dimension (useful for keeping
  trees compact)
* Adds a keyword argument `scaling_type` (that can be used with the
  `layout_config` argument).
* * Its default value is `"relative"`, which keeps the original meaning of the `scale` parameter (but includes the previously described changes).
* * If set to `"absolute"`, the `scale` parameter can either be a scalar
    or a tuple. It now scales SageMath's layout by the given factor in
    each dimension, allowing for a finer control on compact tree
    layouts.

This improvement is especially useful for rendering large trees (deep
and/or wide) when used with the `auto_zoom` method of `MovingCamera`.

## Motivation and Explanation: Why and how do your changes improve the library?

When using manim to make videos of tree search algorithms, I encountered some issues when rendering large trees :

* Setting the `scale` parameter of the layout to a set value in order to fit the scene dimensions led to vertices (which include some custom graphics to display game positions) overlapping for wide trees, and edges disappearing behind vertices for deep trees.
* Trying to dynamically compute values for the `scale` parameter in order to make compact layouts led to re-computing the whole tree layout (as already done in `tree_layout(...)`

I've used the `scaling_type` parameter (from this PR) in order to keep the tree layout as small as possible (using the `scale` parameter to account for vertex size). Together with the `auto_zoom` method of `MovingCamera`, I've been very happy with the results.

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by behackl** [comment]
This looks very interesting! Your have marked your proposed changes as a draft, but as soon as you want anyone to look over them, please mark this as ready for review and/or request a review from me! :-)

**Comment by pcouy** [comment]
Oh, I've only marked it as a draft because I was thinking it needed more input before oficially submitting it for review. But I can mark it ready for review now.

I tried to make sure the previous behaviour was kept when using previously valid values for the `scale` parameter.

I also planned to include videos demonstrating the change, but did not have the time to render them...

**Comment by behackl** [comment]
Apologies for things moving rather slow here! In general the changes look good to me; do you, by any chance, have some code fro an example scene where you do this?

> I've used the scaling_type parameter (from this PR) in order to keep the tree layout as small as possible (using the scale parameter to account for vertex size). Together with the auto_zoom method of MovingCamera, I've been very happy with the results.

I'm curious to see how exactly you have pieced things together.

Other than that, to get this merged all that remains is adapting the documentation of the parameters. The current situation is slightly inconvenient (in the sense that only the Graph constructor itself has all the documentation for the parameters). Maybe `_tree_layout` should be unprivated and renamed to `tree_layout` so that the corresponding docstring also gets rendered. But that might be a story for another day; if you could adapt the description of `layout_scale` and `layout_config` in the docstring of `Graph`, and add a minimal docstring like

```
"""Determine a suitable tree layout.

Parameters
----------
```

for the tree layout function, that would be much appreciated.

**Comment by pcouy** [comment]
> do you, by any chance, have some code fro an example scene where you do this?

I do have a piece of code I used to produce a video of the negamax algorithm being applied to tic tac toe. It is however quite messy and has some pretty heavy dependencies. I will try to make a minimal working example that only requires this branch to work.

> I'm curious to see how exactly you have pieced things together.

The current implementation of the tree layout uses fixed distances between nodes, then uses the scale parameter as a target size for the whole tree. What I did is provide a way to use the scale parameter to contract or dilate the fixed-distance layout by a constant factor (that does not depend on the number of nodes). I then use the bounding box of the resulting tree as the target field of fiew for the `auto_zoom` method of `MovingCamera`. The fundamental difference is that adding nodes to the tree and refreshing the whole thing causes the tree to expand and the camera to zoom out in sync, while the current implementation only allows for fixed-size trees.

The motivation behind this is that nodes started to overlap when the number of nodes grew too large. This variation allows for larger trees to be displayed without nodes overlapping, at the cost of the nodes becoming smaller and smaller on screen as you add more nodes to the tree.

I will also look into updating the docstring, and post an update here with the minimal code example along with thesponding rendered video when it is done

**Comment by pcouy** [comment]
Hey @behackl ! I've provided with a code example (see commit https://github.com/ManimCommunity/manim/pull/2478/commits/c86c11affa8c70fd0b645944de3b798eb6d33b0c ) that shows the differences between the absolute and relative scaling types. You can see the results without rendering them yourself at https://www.youtube.com/watch?v=uu0DFlO8tWA&list=PLOefHdC8B_hxok0rrylz4xVnixBYJZYoa

I've also updated the docsting for `Graph` (https://github.com/ManimCommunity/manim/pull/2478/commits/223684adfd4fd9d27239994036a4f16f375516b0). Is this good for merging ?

PS : There are some issues in `pre-commit.ci` (has to do with mypy) but I think it comes from upstream.

**Comment by behackl** [comment]
The reworked docstring looks good, thank you @pcouy! I'm not sure whether the code snippets should be included in `example_scenes`, I think chances for someone finding them there are rather low. It might be better to move the sample scenes to an examples-section of the module docstring of `graph.py` so that the scenes also appear in our documentation; what do you think?

I can help move the code there if you would like me to.

I'm not entirely sure I understand why the pre-commit action fails. Seems weird.

**Comment by pcouy** [comment]
@behackl 

> The reworked docstring looks good, thank you @pcouy! I'm not sure whether the code snippets should be included in `example_scenes`, I think chances for someone finding them there are rather low. It might be better to move the sample scenes to an examples-section of the module docstring of `graph.py` so that the scenes (or at least their code) also appear in our documentation; what do you think?

I agree with you. In my opinion, the examples are the best way to show what this new argument does. Documentation seems to be the right place to display them. Is there a way to add the resulting in the doc as well ?
 
> I can help move the code there if you would like me to.

I'd love that :)

> I'm not entirely sure I understand why the pre-commit action fails. Seems weird.

Yeah. I don't know wht it is about. I did not even touch the `manim/cli/render/commands.py` file, and I don't know what the `global_options` modifier does.

**Comment by behackl** [comment]
I quickly wanted to take care of this earlier today, but then unfortunately ran into a not so easy to resolve issue: your code doesn't run on the latest main branch, basically because recent changes have made it impossible to run both `graph.animate.add_vertices` and `graph.animate.add_edges` in the same play call.

A more or less clean workaround I can think of is improving the `add_edges` method so that keyword arguments like position, vertex type, ... can be passed to `add_edges` as well so that these arguments are then properly respected when creating new vertices within that method.

I'll try to implement that in a separate PR. As for this PR, we could either merge this without the additional example code and take care of that in a follow-up PR after the improved `add_edges` is available, or we wait with merging this including the example code until this is the case. What do you think @pcouy?

**Review by behackl — APPROVED** [review]
I have made some changes:

- the tree layout method now has a new argument, `vertex_spacing` which can be used to explicitly use the former "relative" type from this PR. This is so that `layout_scale` does not have to be overloaded, and it actually also simplifies the implementation in the layout method a bit
- I have adapted the code in the example, also with respect to the simplified interface made available via #2565 
- and I have moved the example to the documentation. Trying to include it as an actually rendered example, if it takes too long to render we can just add it as a code-only one.

Depending on how the documentation build time behaves, I'm happy to merge this afterwards. Thanks again for your contribution!

**Comment by behackl** [comment]
The example took 8 seconds to render, which is too long to comfortably add to the docs. I have downgraded the example to a code-only one.

**Comment by pcouy** [comment]
Wow ! Thank you @behackl for sorting this out and merging it ! :)

**Pull request merged**
