### PR TITLE
Fix typing of `Animation`

### PR DESCRIPTION
**Pull request by dandavison**
`FunctionOverride` was being typed as returning `None` whereas it in fact returns `Animation`. This was resulting in the result of `Animation(...)` being inferred as `Animation | None` (by Pyright, at least).

This PR addresses this by casting to the true type at the call site in `Animation.__new__()`. It also changes the type to simply be `Callable` seeing as `None` was misleading, and we're also unable to type the arguments correctly.

### How this was tested

In VSCode using Pylance, I confirmed that the return type of `Animation(...)` is `Animation` (not `Animation | None`), and, outside VSCode, that manim could still be used.

### CODE REVIEW

**Comment by JasonGrace2282** [comment]
Before accepting this change, I would like to look into if there's any way to fix the `FunctionOverride` type alias. It might be worth looking into whether `import manim.animation.animation as anim;anim.Animation` works, or some other workaround. In my view, this should be considered a last resort.

**Comment by dandavison** [comment]
> I would like to look into if there's any way to fix the `FunctionOverride` type alias. It might be worth looking into whether `import manim.animation.animation as anim;anim.Animation` works

Hm, that won't work -- we need the result of `Animation.__new__(cls)` to be typed as `cls` (or `typing.Self` in recent Python versions). E.g. if `Animation.__new__(cls)` is changed like this:

```python
    func: Callable[..., Animation] = mobject.animation_override_for(cls)
    if func is not None:
        anim = func(mobject, *args, **kwargs)
        return anim
```

then we end up with a subclass such as `Transform` yielding a union type that includes the parent class:

image

**Comment by Viicos** [comment]
@dandavison this was being tackled in https://github.com/ManimCommunity/manim/pull/3457, but I'm missing some time to continue working on it. Maybe you can apply the sames changes I did? Once merged, I'll rebase.

---

Regarding `FunctionOverride`, what was the reason to have `None` as a return type?

I think we can now define it as:

```python
FunctionOverride: TypeAlias = Callable[Concatenate[Mobject, ...], Animation]
```

**Comment by dandavison** [comment]
Hi @Viicos, nice to meet you.

> Regarding `FunctionOverride`, what was the reason to have `None` as a return type?

I didn't write it, but I was assuming it was meant as a placeholder because an appropriate type couldn't be imported in `manim/typing.py`.

> I think we can now define it as:
> 
> ```python
> FunctionOverride: TypeAlias = Callable[Concatenate[Mobject, ...], Animation]
> ```

Doesn't that suffer from the problem I outlined above?

> @dandavison this was being tackled in #3457, but I'm missing some time to continue working on it. Maybe you can apply the sames changes I did? Once merged, I'll rebase.


I didn't quite understand what you're suggesting that I do there. (In general, I don't have time to contribute to Manim currently, so I'm happy for my changes in this PR to be merged, or copied into another PR. It would be nice to fix the types for `Animation` in an upcoming release though!)

**Comment by Viicos** [comment]
> I didn't write it, but I was assuming it was meant as a placeholder because an appropriate type couldn't be imported in `manim/typing.py`.

This was discussed a bit on the Discord, indeed this seems to be the reason. However, this can be fixed by importing `Animation` in a `if TYPE_CHECKING` block and using a string reference instead.

But anyway, this does not really matter for now. I'll add a suggestion to your PR that would allow the return type to be correctly inferred (so that this can be merged quickly), and I'll see if I can fix more things https://github.com/ManimCommunity/manim/pull/3457 when I get some time.

**Comment by dandavison** [comment]
Hi @Viicos, thanks I'd forgotten that `Self` was available as a backport from `typing_extensions`. So I've made that change. That should make the types sane for users.

Of course, manim itself still won't type check, even if we import `Animation` under `TYPE_CHECKING` and define `FunctionOverride` to be `Callable[..., "Animation"]`, since we'd still be specifying the parent class to the exclusion of subclasses:

image

**Comment by Viicos** [comment]
Hi @dandavison,

great. Yeah regarding the `FunctionOverride` return type it will not play nice with `Self`. But this file is not type checked yet (it will after my PR), so this is fine. Thanks for fixing this!

**Comment by Viicos** [comment]
Thanks!

**Review by Viicos — APPROVED** [review]

**Pull request merged**
