### PR TITLE
Add unit test to #960

### PR DESCRIPTION
**Pull request by Pragyaan-6988**
## Motivation

Unit test for #960 

## Oneline Summary of Changes

```
- Added unit test for #960 (:pr:`964`)
```

## Testing Status

Before #960 : Test fails as expected
```py
(env) PS E:\ManimCE> pytest .\tests\test_coordinate_system.py --show_diff
============================================ test session starts =============================================
platform win32 -- Python 3.8.6, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: E:\ManimCE, configfile: pyproject.toml
collected 4 items

tests\test_coordinate_system.py ..F.                                                                    [100%]

================================================== FAILURES ================================================== 
___________________________________________ test_axes_unit_vectors ___________________________________________ 

    def test_axes_unit_vectors():
        """Check if the magnitude of unit vectors along the
        axes are equal to their corresponding unit_size."""
        plane = NumberPlane(axis_config={"unit_size": 0.4})
        for axis in plane.axes:
>           assert get_norm(axis.get_unit_vector()) == axis.unit_size
E           assert 1.0 == 0.4
E            +  where 1.0 = get_norm(array([1., 0., 0.]))
E            +    where array([1., 0., 0.]) = <bound method Line.get_unit_vector of NumberLine>()
E            +      where <bound method Line.get_unit_vector of NumberLine> = NumberLine.get_unit_vector       
E            +  and   0.4 = NumberLine.unit_size

tests\test_coordinate_system.py:42: AssertionError
========================================== short test summary info =========================================== 
FAILED tests/test_coordinate_system.py::test_axes_unit_vectors - assert 1.0 == 0.4
======================================== 1 failed, 3 passed in 1.98s ========================================= 
```
After #960 : Tests pass
```py
(env) PS E:\ManimCE> pytest .\tests\test_coordinate_system.py --show_diff
============================================ test session starts ============================================= 
platform win32 -- Python 3.8.6, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: E:\ManimCE, configfile: pyproject.toml
collected 4 items                                                                                              

tests\test_coordinate_system.py ....                                                                    [100%] 

============================================= 4 passed in 0.68s ============================================== 
```

## Further Comments

This is the first time I wrote a unit test after reading the wiki and going through unit tests of other modules, so apologies if something basic is done wrong. 

## Acknowledgements
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)

## Reviewer Checklist
- [ ] Newly added functions/classes are either private or have a docstring
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings
- [ ] The oneline summary has been included [in the wiki](https://github.com/ManimCommunity/manim/wiki/Changelog-for-next-release)

### CODE REVIEW

**Comment by Pragyaan-6988** [comment]
Should the test be actually written for `NumberLine`? As in,
```py
axis1 = NumberLine(unit_size = 0.4)
axis2 = NumberLine(unit_size = 2.5)
for axis in (axis1, axis2):
    assert get_norm(axis.get_unit_vector()) == axis.unit_size
  ```
Because the current test is only for `NumberPlane` , but what about `ThreeDAxes`? I think adding a test to `NumberLine` instead as above would generalize the test since axes are basically just `VGroups` of `NumberLine`s.

**Comment by huguesdevimeux** [comment]
Yes, adding a test for NumberLine is more coherent as you touched this in your previous PR.

**Comment by Pragyaan-6988** [comment]
> Yes, adding a test for NumberLine is more coherent as you touched this in your previous PR.

Yeah, done!

**Review by huguesdevimeux — APPROVED** [review]
SGTM

**Pull request merged**
