### PR TITLE
Update cairo-windows.py to use newer download links.

### PR DESCRIPTION
**Pull request by Aathish04**
The location of the pycairo .whl files have been updated by LFD UC Irvine. 

This updates the script to download the newer .whl files if required.

### CODE REVIEW

**Comment by leotrs** [comment]
THANK YOU. 

1. Have you tested this?
2. How often do we need to change this script?

**Comment by Aathish04** [comment]
@leotrs This'll be the first test. (I wasn't sure if travis would be used for all branches or just ones with pull requests to master.)

I really don't know when or if we'll have to change the links, since LFD have just sorta done this in the background... worst come to worst we could just obtain the direct download link by doing whatever mumbo jumbo LFD does on their end, on _our_ side.

**Comment by leotrs** [comment]
Yeah getting the right URL would be a good first step to add to the script.

**Comment by Aathish04** [comment]
@leotrs Yay, this works! I guess it can be merged when someone else comes along and approves it.

Now, again, I'm not sure if/when the links need to be updated. I got the JavaScript function that the website executes when you click on the link, and it just seems to replace stuff with more stuff.

**Pull request merged**
