### PR TITLE
Remove 3b1b-specific files

### PR DESCRIPTION
**Pull request by safinsingh**
I think we should remove 3b1b-specific files for this community-based repo.

### CODE REVIEW

**Comment by safinsingh** [comment]
Do we need the travis file? Those are for pushing the repo to PyPi, which we're not deploying to (as of now). Also, setup.py was for travis to push the repo to PyPi.

**Comment by Aathish04** [comment]
> Do we need the travis file? Those are for pushing the repo to PyPi, which we're not deploying to (as of now). Also, setup.py was for travis to push the repo to PyPi.

@eulertour has mentioned that he would like to update the PyPI package in the near future, so it's probably better to leave it in.

**Comment by safinsingh** [comment]
Sure; in that case, let me add those back

**Comment by safinsingh** [comment]
Never mind, EulerTour says we don't need it for now.

**Pull request merged**
