### PR TITLE
Moved functionality over from `manim new` to `manim init` and added deprecation warning for `manim new`

### PR DESCRIPTION
**Pull request by Phosphorescentt**
## Overview: What does this pull request change?
This PR implements the changes discussed in issue #2695

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by Kiran-Raj-Dev** [comment]
The tests fail because you haven't updated them to reflect this new behaviour.

**Comment by Phosphorescentt** [comment]
> The tests fail because you haven't updated them to reflect this new behaviour.

Ah of course. I will update this some time next week

**Review by Kiran-Raj-Dev — APPROVED** [review]

**Review by behackl — APPROVED** [review]

**Comment by behackl** [comment]
Thank you for your contribution! I've resolved the merge conflict and added one test checking that running `manim init project` actually properly creates a boilerplate project. Please cross-check, then we can merge this.

**Comment by behackl** [comment]
(Tests pass, so it should be fine regardless.)

**Comment by Phosphorescentt** [comment]
> Thank you for your contribution! I've resolved the merge conflict and added one test checking that running `manim init project` actually properly creates a boilerplate project. Please cross-check, then we can merge this.

Was going to action this today but you beat me to it :)

Thanks for writing the test :)

**Pull request merged**
