### PR TITLE
Quick commit to add the new logo.

### PR DESCRIPTION
**Pull request by MysaaJava**
Well, everything is said

## Acknowledgement
- [X] I have read the [Contributing Guidelines](https://github.com/ManimCommunity/manim/wiki/Documentation-guidelines-(WIP))

### CODE REVIEW

**Comment by leotrs** [comment]
Uhm could you tell us what each file is for? Or perhaps show us the PNGs somehow? (You can just include PNG files in GitHub comments).

I was expecting two files only! (one light, one dark.) Do the others have transparency? (I assume "alpha" stands for transparency in your file names?...)

**Comment by MysaaJava** [comment]
W is for white background, B for black background, alpha means with transparency and B&W is the svg as used  in the competition (black next to white, without transparency)

**Comment by leotrs** [comment]
Thanks, that makes sense! This LGTM, except that I would change the names of the png files (they currently have a double extension `.svg.png`).

**Comment by leotrs** [comment]
Uhm I think you added comits from a different branch :sweat_smile:

**Comment by MysaaJava** [comment]
Yes, i struggle to revert it !
My local git master is correct (one commit ahead) but i can't replace the remote master...

**Comment by kolibril13** [comment]
Is this pr not redundant, as the logo was already added in https://github.com/ManimCommunity/manim/pull/577/files#diff-41863f24c1a182bef77f696767e8d5193b4096d4b65117e685462379d96ecd8a?
So I would suggest we close this pr.

**Comment by MysaaJava** [comment]
Well, the folder /logo is still having the old logo and should be changed (that is what this PR was supposed to do) But my remote repository branches are all messed up. I struggle with moving HEAD back in time (see discord #miscellaeous-help ). You can close this PR if you want but the /logo folder still needs to be changed (or removed)

**Pull request closed without merging**
