### PR TITLE
Added BuiltinAnimation Animation

### PR DESCRIPTION
**Pull request by GameDungeon**
## Changelog / Overview

Added BuiltinAnimation Animation: An animation that grabs built-in animations from Mobjects.

## Motivation

I needed this for my plugin and it seems useful so I'm suggesting adding it to manim

## Explanation for Changes

This is an animation that calls the function get_animation to get an animation built-in to this function.

```python
class BuiltinAnimation(Animation):
    def __init__(
        self,
        graph: Graph,
        animation_name: str = "default",
        **kwargs,
    ) -> None:

        self.animation = graph.get_animation(animation_name)
        print(self.animation.group.submobjects)
        self.graph = graph
        self.check()

        prepare_animation(self.animation)

        super().__init__(self.animation.mobject, **kwargs)

    def check(self):
        if self.animation is None:
            raise TypeError(
                f"{self.graph.__class__.__name__} does not support this animation"
            )
```

Why would I ever need this? you ask.

- Allows for default animations to be set
- Allows for complex animations to be built into Mobjects, with timings and all other stuff you can normally do
- Allow for as many of the above as you want, without creating new classes
- Allows for new animations that would be infeasible to add as a class.

Here is an example form my plugin:

```python
class LinePlot(Plot):
    def __init__(
        self, *values: typing.List[typing.Union[float, int]], dot_points: bool = False
    ) -> None:
        """Plots s line

        Parameters
        ----------
        dot_points : bool, optional
            Put dots at points, by default False
        """
        super().__init__()

        self.dot_points = dot_points

        self.colors = ["RED", "BLUE", "GREEN"]

        self.animations = list()
        self.line_animations = list()

        self.axes = Axes(
            x_range=[0, max([len(x) for x in values]) - 1, 1],
            y_range=[0, max([max(a) for a in values]) + 1, 1],
            x_length=9,
            y_length=6,
            axis_config={"include_tip": False, "include_numbers": True},
        )

        self.add(self.axes)
        self.animations.append(Create(self.axes))

        for i, value in enumerate(values):
            self.value = value
            self.plot(self.colors[i])

    def plot(self, color: str) -> None:
        last_point = None
        for i, value in enumerate(self.value):
            point = self.axes.coords_to_point(i, value)

            if last_point is not None:
                line = Line(last_point, point, stroke_width=3, color=color)
                self.add(line)
                self.line_animations.append(Create(line, run_time=0.1))

            last_point = point

            if self.dot_points:
                d = Dot(point, color=color)
                self.add(d)
                self.line_animations.append(Create(d, run_time=0.5))

    def get_animation(self, animation_name: str = "default") -> typing.Optional[AnimationGroup]:
        animations = None

        if animation_name == "default":
            lines = AnimationGroup(*self.line_animations, lag_ratio=0.5)
            animations = AnimationGroup(*self.animations, lines, lag_ratio=1)

        return animations
```

## Checklist
- [X] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [X] I have written a descriptive PR title (see top of PR template for examples)
- [X] I have written a changelog entry for the PR or deem it unnecessary
- [X] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [X] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by WampyCakes** [comment]
If I am understanding this correctly, it does seem useful. But it's far from clear to me exactly how this is intended to work/when it should be used :/

**Comment by GameDungeon** [comment]
I think this could be used for stuff like axes or number lines to break up their show creation animation into something that looks nicer. This is designed for those more complex Mobjects with ugly Create animations.

**Comment by WampyCakes** [comment]
So is the underlying idea that each mobject has the ability to override how an animation (like `Create`) looks when played on it?

**Comment by GameDungeon** [comment]
> So is the underlying idea that each object has the ability to override how an animation (like `Create`) looks when played on it?

Yes, that is a use, and likely the main one. Only when this animation is called of course. The other main use is Mobject specific animations.

**Comment by behackl** [comment]
I like the general idea of being able to override animations, but I question whether it is necessary to introduce a new class for it.

In the spirit of the `override_animate` approach for the `.animate` syntax (CC @friedkeenan) I think it would be cleaner to introduce a decorator `override_animation` (or something like that) which could be used something like

```py

class MyMobject:
    ...

    @override_animation(Create)
    def _custom_create(self, *args, **kwargs):
        # build a custom create animation
        return my_custom_animation

```

such that when `self.play(Create(mymob))` is called for a `MyMobject` `mymob`, the custom animation is played instead.

**Comment by GameDungeon** [comment]
@behackl I can get on board with that, but what about the other use, Mobject-specific animations?

**Comment by WampyCakes** [comment]
I second behackl's idea. Though I'd go a step further and say that you should, as a user, be able to override the override and say use the normal Create animation (or any other animation).

Regarding mobject specific animations, I think this is definitely a good feature, but it's unclear how this PR works for that in my eyes. Also, it seems like it would limit each mobject to having only 1 custom animation. Am I wrong?

**Comment by GameDungeon** [comment]
> I second behackl's idea. Though I'd go a step further and say that you should, as a user, be able to override the override and say use the normal Create animation (or any other animation).
> 
> Regarding mobject specific animations, I think this is definitely a good feature, but it's unclear how this PR works for that in my eyes. Also, it seems like it would limit each mobject to having only 1 custom animation. Am I wrong?

That is what the animation_name is for. 
In get_animation you can add checks for names. and return something different based off of it.

**Comment by behackl** [comment]
> @behackl I can get on board with that, but what about the other use, Mobject-specific animations?

Can you give an example of how you'd like to use it for Mobject-specific animations?

> Also, it seems like it would limit each mobject to having only 1 custom animation. Am I wrong?

That's the impression that I get as well.

**Comment by GameDungeon** [comment]
We could make something different to fix the Mobject specific animations.

**Comment by friedkeenan** [comment]
> I like the general idea of being able to override animations, but I question whether it is necessary to introduce a new class for it.
> 
> In the spirit of the `override_animate` approach for the `.animate` syntax (CC @friedkeenan) I think it would be cleaner to introduce a decorator `override_animation` (or something like that) which could be used something like
> 
> ```python
> class MyMobject:
>     ...
> 
>     @override_animation(Create)
>     def _custom_create(self, *args, **kwargs):
>         # build a custom create animation
>         return my_custom_animation
> ```
> 
> such that when `self.play(Create(mymob))` is called for a `MyMobject` `mymob`, the custom animation is played instead.

Yeah, that sounds good to me. Could probably change current `override_animate` to `override_animation` for consistency, but yeah should be perfectly possible. Could have a custom `Animation.__new__` function and all, would probably be similar in implementation to current `override_animate`.

**Comment by jsonvillanueva** [comment]
What's the status on this PR? It sounds like we want to add a decorator to override animations instead?

Should we close this PR and open an issue for overriding animation for more discussion?

**Comment by GameDungeon** [comment]
Yes, I think so as I'm too busy to fix this right now.

**Comment by jsonvillanueva** [comment]
> 
> 
> Yes, I think so as I'm too busy to fix this right now.

Alrighty, closing!

**Pull request closed without merging**
