### PR TITLE
Fix bug using z_index in VGroup

### PR DESCRIPTION
**Pull request by pdcxs**
An easy but not elegant solution of problem in https://github.com/ManimCommunity/manim/issues/327

### CODE REVIEW

**Comment by leotrs** [comment]
Thanks! Did you mean to open this PR as a draft? It's unclear whether you are proposing we review this now.

1. Please use the PR template next time.
2. This has broken virtually every test. This doesn't mean the fix is wrong, but it means it's incomplete. (This is what makes me think this is not ready for review.)
3. As we move toward using `z_index` more extensively, I would very much like to see new tests for it. Can you please add tests to the final version of this PR? If you are unsure of how to do that, we can of course discuss it here.

Marking as draft for now.

**Comment by leotrs** [comment]
@pdcxs did you have time to look into this? :)

**Comment by pdcxs** [comment]
> @pdcxs did you have time to look into this? :)
Sorry, I'm too busy to write codes these days. I just put a sort according to the z-index in mobject add method to fix the bug #327. But I really cannot understand why all checks are failed. Maybe it is because I directly edit the code on github web page and the format is not correct?

**Comment by leotrs** [comment]
Thanks for your answer.

Unfortunately, I do believe that changes in z_order must come with tests on them because they may change virtually every scene in existence. I think this is why the tests are failing.

I'd rather live with a known bug than merge this to fix a bug that breaks everything else. So, until you have time to look into this again, or someone else takes this branch up, I'm closing this.

**Pull request closed without merging**
