### PR TITLE
Allow for Developer Installations Without Poetry

### PR DESCRIPTION
**Pull request by Aathish04**
## List of Changes
- Re-add `setup.py` file that was removed by #165 in commit a281afd89e0ef3e010bffeded654e0864f8a4d1a
- Add `setuptools` to `build-system` requirements in `pyproject.toml`
- Add a convenience script to extract the `setup.py` file from the `tar.gz` file generated by `poetry build`.

## Motivation
Using `poetry` in tandem with `python3.9` and MacOS Big Sur is extremely inconvenient for the time being.
This is due to the fact that, since Python3.9 is so new, `poetry` attempts to install all (nearly all) the dependencies by building from source, which inevitably fail on MacOS Big Sur since _it_ is also extremely new.

An alternative, unobtrusive method would be much better, not just in this specific case, but for any other similar scenarios that may pop up in the future.

## Explanation for Changes

Re-adding the `setup.py` file and adding `setuptools` to the `build-system` requirements allows the developer to do an editable install via pip, the "old fashioned" way (by `python3 -m pip install -e .`).
As such, one need not use `poetry`, unless they are building the project at the very end, which works regardless of whether `poetry` is used to install the library in the first place. 

For the sake of convenience, the python script `./script/make_manim_setup.py` has been added to easily extract the `setup.py` file and place it in the appropriate location, as well as clean up after it.

## Testing Status
Tested several times on Python3.9 with MacOS Big Sur. Installs perfectly each time, provided you have the python package `wheel` installed.

## Further Comments
I am unsure of whether this method needs to go into the documentation, since it just provides an alternate route to installation instead of `poetry`.

## Acknowledgement
- [x] I have read the [Contributing Guidelines](https://github.com/ManimCommunity/manim/wiki/Documentation-guidelines-(WIP))

### CODE REVIEW

**Comment by eulertour** [comment]
This looks very redundant to me. If you want to install with `setup.py` why not just do it after running `poetry build` in your own checkout?

**Comment by Aathish04** [comment]
> This looks very redundant to me. If you want to install with `setup.py` why not just do it after running `poetry build` in your own checkout?

You're right. In _my_ case, I was able to build the package since I had poetry installed. 

With the changes I made in this P.R, the would-be developer won't need `poetry` at all since you have a `setup.py` file, and the appropriate one-line change to `pyproject.toml`.

**Comment by eulertour** [comment]
It doesn't seem like being unable to install poetry is a common problem, but if you really wanted to avoid it you can ask @cobordism about his setup.

This change feels a lot like overfitting manim to suit a specific computer in the same way that grant did in the old version.

**Comment by Aathish04** [comment]
Alright, so after concluding _NEGOTIATIONS_ with @eulertour , I've made the changes that we agreed on by deleting both the `setup.py` file, as well as the `make_manim_setup.py` script.

The only change now made is the inclusion of `setuptools` in the build requirements section of `pyproject.toml`.

**Review by leotrs — APPROVED** [review]

**Review by eulertour — APPROVED** [review]

**Pull request merged**
