### PR TITLE
Implemented :meth:`.CoordinateSystem.plot_antiderivative_graph`

### PR DESCRIPTION
**Pull request by icedcoffeeee**
## Overview: What does this pull request change?

This is something I made for one of my projects, and thought this might be useful for anyone else.
## Motivation and Explanation: Why and how do your changes improve the library?

```py
class AntiderivativeExample(Scene):
    def construct(self):
        ax = Axes()
        graph1 = ax.plot(
            lambda x: (x ** 2 - 2) / 3,
            color=RED,
        )
        graph2 = ax.plot_antiderivative_graph(graph1, color=BLUE)
        self.add(ax, graph1, graph2)
```
Output:

AntiderivativeExample_ManimCE_v0 12 0
## Links to added or changed documentation pages

[Documentation for the method](https://manimce--2267.org.readthedocs.build/en/2267/reference/manim.mobject.coordinate_systems.CoordinateSystem.html#manim.mobject.coordinate_systems.CoordinateSystem.plot_antiderivative_graph)

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [x] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Review by behackl — APPROVED** [review]
This seems fine to me. Thank you!

**Comment by behackl** [comment]
Just revisited this: the implementation actually seems very slow and the test takes several seconds, which is not particularly great.

Suggestion: instead of computing the area ourselves, we could change the implementation to use `np.trapz`. Something along the lines of
```py
def antideriv(x):
    x_vals = np.linspace(0, x, some number of points)
    f_vec = np.vectorize(curve.function)
    y_vals = f_vec(x_vals)
    return np.trapz(y_vals, x_vals)
```
or so should be orders of magnitude faster.

**Comment by icedcoffeeee** [comment]
You're right, it is orders of magnitudes faster! from 21 seconds, to 0.12 seconds (on a fairly simple x^2 graph). I'm not familiar with the `np.trapz` functions, but it's good to know about it. :)

**Review by behackl — APPROVED** [review]
Perfect, thank you!

**Pull request merged**
