### PR TITLE
Remove more 3b1b files

### PR DESCRIPTION
**Pull request by eulertour**
Some files and functions missed in #2.

### CODE REVIEW

**Comment by Tony031218** [comment]
I think some people want to construct their own creature by modifying the code about pi_creature. 
Is it better to delete this part of the code?

**Comment by leotrs** [comment]
@eulertour were you able to run the example scenes after these deletions?

**Comment by leotrs** [comment]
@Tony031218 , the pi creatures are property of 3b1b, so we should totally delete them from this repo. If people are interested in mimicking them, they can always use the original 3b1b repository.

**Comment by eulertour** [comment]
@leotrs Yes, I was still able to run them.

**Comment by Aathish04** [comment]
> @eulertour were you able to run the example scenes after these deletions?

I wasn't able to run any of the example scenes after the removal of the files in `once_useful_constructs`. After manimlib.imports was suitably modified, then yeah, everything worked fine.

Why can't we leave `once_useful_constructs` in, anyway? They're just classes and methods that were useful before and might be in the future.

**Comment by eulertour** [comment]
@Aathish04 It's last moments are documented [here](https://github.com/ManimCommunity/manim/pull/20#issuecomment-631179923). It isn't part of the master branch anymore so you might have to pull.

**Comment by Aathish04** [comment]
> @Aathish04 Its last moments are documented [here](https://github.com/ManimCommunity/manim/pull/20#issuecomment-631179923). It isn't part of the master branch anymore so you might have to pull.

I'm all for removing stale code. Can we also edit manimlib.imports and remove references to said cleaned up code then?

**Comment by eulertour** [comment]
I'm not sure what you mean. This PR is already removing for_3b1b_videos from manimlib.imports and once_useful_constructs was removed in 3f5f0cb0021eab67f2f09dc450ffe1a18be1f57a.

**Comment by Aathish04** [comment]
> I'm not sure what you mean. This PR is already removing for_3b1b_videos from manimlib.imports and once_useful_constructs was removed in [3f5f0cb](https://github.com/ManimCommunity/manim/commit/3f5f0cb0021eab67f2f09dc450ffe1a18be1f57a).

Huh. The imports were still in the manimlib.imports on my computer... odd. It's probably just an issue on my end...

**Pull request merged**
