### PR TITLE
Updaters fix

### PR DESCRIPTION
**Pull request by eulertour**
## List of Changes

Update `Scene.moving_mobjects ` in `Scene.add()`. Depends on #830 for its Scene refactoring.

## Motivation

When a mobject is added by an updater in the middle of an animation, `Scene.moving_mobjects` isn't updated. As a result, the added mobject won't appear in the Scene.

## Changelog Entry
Mobjects added during an updater are added to Scene.moving_mobjects.

## Testing Status

As long as we can only test the final frame this change can't be tested.

## Further Comments

The way that manim removes submobjects within a group by splitting the group apart and re-adding the parts that weren't removed is very strange. It make much more sense to me to remove submobjects by removing the reference in their parent's submobjects list and leave out the logic in `Scene.restructure_mobjects()` entirely. In particular, I've never encountered another graphics program that handles nested objects the way manim currently does.

## Acknowledgements
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [ ] I have added an entry describing the changes from this PR to the [Changelog](https://docs.manim.community/en/latest/changelog.html) at `docs/source/changelog.rst`

### CODE REVIEW

**Comment by eulertour** [comment]
These videos showcase the difference between the code with and without the fix; both were rendered from the same script.

https://user-images.githubusercontent.com/43117506/102700597-aecdf380-4203-11eb-8784-3aad7c5953f8.mp4

https://user-images.githubusercontent.com/43117506/102700543-3c5d1380-4203-11eb-9486-9b8d84896cdd.mp4

**Review by behackl — APPROVED** [review]
LGTM. I also agree with your assessment that the removal of submobjects currently is  ... unintuitive, and should be refactored eventually.

(I also checked the rendered animations in our documentation for good measure, they all still seem fine.)

**Review by huguesdevimeux — APPROVED** [review]
SGTM.

A test would be useful IMO.

**Review by huguesdevimeux — CHANGES_REQUESTED** [review]
On second though this actually _needs_ a test.

COuld you create one?

**Review by huguesdevimeux — APPROVED** [review]

**Pull request merged**
