### PR TITLE
OpenGL compatibility via metaclass: svg_mobject, text_mobject, tex_mobject

### PR DESCRIPTION
**Pull request by behackl**
## Changelog / Overview

This PR uses the metaclass mechanism from #1272 to make SVG rendering, as well as the `tex_mobject` and `text_mobject` modules compatible with cairo as well as opengl.

## Testing Status

Tested rendering locally for a while, didn't really run into any problems.

The only discrepancy I found: It seems that the stroke width is by default a bit thicker, I haven't found a way yet to fix that. Help debugging this would be welcome:

Screenshot 2021-05-14 at 13 43 11

(Upper window: OpenGL, lower window: cairo.)

## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by behackl** [comment]
For reviewing this it might be easiest to look at the changes commit per commit, I've tried to cleanly document the changes via the commit messages.

**Comment by TRoboto** [comment]
I've played a few scenes full of latex texts with both renderers, and it worked like a charm. Although I see few things need to change, but it would be better to leave them for future PRs. For example, I think `init_points` function name should be changed to `generate_points` instead of this line `init_points = generate_points`.

**Comment by behackl** [comment]
> I've played a few scenes full of latex texts with both renderers, and it worked like a charm. Although I see few things need to change, but it would be better to leave them for future PRs. For example, I think `init_points` function name should be changed to `generate_points` instead of this line `init_points = generate_points`.

Thanks for checking it out! I think as long as OpenGL and cairo rendering are as different as they currently are, it is sort of convenient to have two different methods for generating the points of a mobject. I feel that the metaclass approach would also allow us to merge the interfaces of OpenGLVMobject and VMobject, in case this would still be desireable (which I'm actually not too sure about).

**Comment by behackl** [comment]
The seemingly thicker stroke comes from `OpenGLRenderer.anti_alias_width`. Reducing the value there (from currently `1.5`) to `1` or even `0.5` reduces the thickness of the SVG rendered lines.

I think that discussions about the anti-aliasing should be delegated to a general follow-up or so, I don't think it is worth delaying this PR over it.

**Review by naveen521kk — APPROVED** [review]
SGTM!, I am thinking about removing everything `OpenGL*` since we already announced that these methods or classes aren't going to stay around. Or we can remove it once everything uses the Metaclasses approach.

Can you make an issue about https://github.com/ManimCommunity/manim/pull/1511#issuecomment-842162049?

**Comment by behackl** [comment]
> SGTM!, I am thinking about removing everything `OpenGL*` since we already announced that these methods or classes aren't going to stay around. Or we can remove it once everything uses the Metaclasses approach.
> 

I suggest that we keep the dedicated classes around for a little while longer, until more people have experimented with the metaclass mechanism to verify that things actually work as they are supposed to.

> Can you make an issue about [#1511 (comment)](https://github.com/ManimCommunity/manim/pull/1511#issuecomment-842162049)?

Done, #1529.

**Comment by TRoboto** [comment]
> Thanks for checking it out! I think as long as OpenGL and cairo rendering are as different as they currently are, it is sort of convenient to have two different methods for generating the points of a mobject. I feel that the metaclass approach would also allow us to merge the interfaces of OpenGLVMobject and VMobject, in case this would still be desireable (which I'm actually not too sure about).

Fair point. I feel this PR is ready to get merged.

**Review by TRoboto — APPROVED** [review]

**Pull request merged**
