### PR TITLE
Set fixed resolution for OpenGL renderer window.

### PR DESCRIPTION
**Pull request by e4coder**
## Changelog / Overview
Changed the size of the OpenGL renderer window to a fixed resolution of (854x480).

## Motivation

The size of OpenGL renderer window depended on the resolution of the rendered scene. that was problematic for small screens and devices such as laptops.
## Explanation for Changes

A comfortable Resolution has been given to the OpenGl renderer window of:
```
854 x 480
```
## Testing Status

Tested all qualities with this change on Ubuntu.
## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [ ] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by naveen521kk** [comment]
@e4coder Were you able to render 4k videos with this change?

**Comment by e4coder** [comment]
yes i was able to render all qualities with this change.

**Comment by e4coder** [comment]
I am on ubuntu. i have not tested it on windows

**Comment by naveen521kk** [comment]
> yes i was able to render all qualities with this change.

Can you post those videos?

It doesn't work for me, I mean the video were rendered in 854*480 even when resolution was set to 4k.

**Comment by e4coder** [comment]
okay i will post them in an hour or two

**Comment by e4coder** [comment]
I thought OpenGL renderer was for previewing only. I did not know that it could also output as a video file. When i was asked to post the video i thought to screen capture the renderer_window when it was rendring a scene. my bad.

I will try to work on a fix for this.

**Comment by e4coder** [comment]
actually it works fine. you just have to make sure not use -p flag. when rendring the scene to a file. and the out put file will have 4k resolution.

i got confused sorry

**Comment by e4coder** [comment]
https://user-images.githubusercontent.com/64578468/116823553-9e108f80-ab9e-11eb-8339-d8c559defce7.mp4

**Comment by e4coder** [comment]
https://user-images.githubusercontent.com/64578468/116823640-0495ad80-ab9f-11eb-96a1-8ad861fc40cd.mp4

**Pull request closed without merging**
