### PR TITLE
Fix -s skipping issue

### LINKED ISSUE #874: save_last_frame not working properly
## Description of bug / unexpected behavior

The `-s` flag is intended to skip past all animations and output the last frame only, making it a frequently used tool for prototyping and debugging. However, as of late, when invoking manim as follows: `manim <file.py> <scene> -ps` , the scene is rendered fully as it would were the command be `manim file.py scene -p`, except for the resulting media being the expected output of the former.

This behavior is time consuming and defeats the original purpose of the flag. However, if a command of the following pattern is used instead, the expected behaviour returns: `manim file.py scene -ps -n <some_anim_number>`

## Expected behavior

Single image being produced quickly with all animations being skipped from rendering.

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
## Happens with literally any scene, but here's the UpdatersExample code anyways.

class UpdatersExample(Scene):
    def construct(self):
        decimal = DecimalNumber(
            0,
            show_ellipsis=True,
            num_decimal_places=3,
            include_sign=True,
        )
        square = Square().to_edge(UP)

        decimal.add_updater(lambda d: d.next_to(square, RIGHT))
        decimal.add_updater(lambda d: d.set_value(square.get_center()[1]))
        self.add(square, decimal)
        self.play(
            square.to_edge,
            DOWN,
            rate_func=there_and_back,
            run_time=5,
        )
        self.wait()


```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

UpdatersExample

</details>

## Logs
<details><summary>Terminal output</summary>

https://pastebin.com/wfqSgz8u

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)): Windows 10 v20H2
- RAM: 12GB
- Python version (`python/py/python3 --version`): 3.7.5
- Installed modules (provide output from `pip list`):
```
➜ pip list
Package                       Version    Location
----------------------------- ---------- -------------------------------------------------------------------------------------------------------
alabaster                     0.7.12
appdirs                       1.4.4
astroid                       2.4.2
atomicwrites                  1.4.0
attrs                         20.2.0
av                            8.0.2
Babel                         2.8.0
backcall                      0.2.0
beautifulsoup4                4.9.3
black                         20.8b1
CacheControl                  0.12.6
cachy                         0.3.0
cairocffi                     1.1.0
certifi                       2020.6.20
cffi                          1.14.3
chanim                        0.1.0      c:\codeprojects\python\manim_and_related_stuff\manimcommunity\manim\chanim
chardet                       3.0.4
cleo                          0.8.1
click                         7.1.2
clikit                        0.6.2
colorama                      0.4.3
colour                        0.1.5
commonmark                    0.9.1
crashtest                     0.3.1
decorator                     4.4.2
distlib                       0.3.1
docutils                      0.16
filelock                      3.0.12
google                        3.0.0
grpcio                        1.32.0
grpcio-tools                  1.32.0
guzzle-sphinx-theme           0.7.11
html5lib                      1.1
idna                          2.10
imagesize                     1.2.0
importlib-metadata            2.0.0
iniconfig                     1.0.1
ipython                       7.16.1
ipython-genutils              0.2.0
isort                         5.6.3
jedi                          0.17.1
Jinja2                        2.11.2
jsonschema                    3.2.0
keyring                       21.4.0
lazy-object-proxy             1.4.3
lockfile                      0.12.2
manimlib                      0.2.0      c:\codeprojects\python\manim_and_related_stuff\manimcommunity\kilacoda\new-manim-venv\lib\site-packages
MarkupSafe                    1.1.1
mccabe                        0.6.1
more-itertools                8.5.0
msgpack                       1.0.0
mypy-extensions               0.4.3
numpy                         1.19.2
packaging                     20.4
pangocairocffi                0.3.2
pangocffi                     0.6.0
parso                         0.7.0
pastel                        0.2.1
pathspec                      0.8.0
pathtools                     0.1.2
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        7.2.0
pip                           20.2.3
pkginfo                       1.5.0.1
pluggy                        0.13.1
poetry                        1.1.2
poetry-core                   1.0.0
pprintpp                      0.4.0
progressbar                   2.5
prompt-toolkit                3.0.5
protobuf                      3.13.0
ptyprocess                    0.6.0
py                            1.9.0
pycairo                       1.20.0
pycparser                     2.20
pydub                         0.24.1
Pygments                      2.7.1
pylev                         1.3.0
pylint                        2.6.0
pyparsing                     2.4.7
pyreadline                    2.1
pyrsistent                    0.14.11
PySimpleGUI                   4.29.0
pytest                        6.1.1
pytz                          2020.1
pywin32-ctypes                0.2.0
recommonmark                  0.6.0
regex                         2020.10.11
requests                      2.24.0
requests-toolbelt             0.9.1
rich                          8.0.0
scipy                         1.5.2
setuptools                    41.2.0
shellingham                   1.3.2
six                           1.15.0
snowballstemmer               2.0.0
soupsieve                     2.0.1
Sphinx                        3.2.1
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
toml                          0.10.1
tomlkit                       0.7.0
tqdm                          4.50.2
traitlets                     4.3.3
typed-ast                     1.4.1
typing-extensions             3.7.4.3
urllib3                       1.25.10
virtualenv                    20.0.33
watchdog                      0.10.3
wcwidth                       0.2.5
webencodings                  0.5.1
wrapt                         1.12.1
zipp                          3.3.0
```
</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
➜ ffmpeg -version
ffmpeg version N-94943-g1db6e47e85 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 9.1.1 (GCC) 20190807
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 
--enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
libavutil      56. 35.100 / 56. 35.100
libavcodec     58. 56.102 / 58. 56.102
libavformat    58. 32.104 / 58. 32.104
libavdevice    58.  9.100 / 58.  9.100
libavfilter     7. 58.102 /  7. 58.102
libswscale      5.  6.100 /  5.  6.100
libswresample   3.  6.100 /  3.  6.100
libpostproc    55.  6.100 / 55.  6.100

```
</details>

## Additional comments

N/A

### PR DESCRIPTION
**Pull request by kilacoda**
## Motivation

To fix #874.
## Overview / Explanation for Changes

Adds a conditional to check for `config["save_last_frame"]` in `CairoRenderer.update_skipping_status` and set `self.skip_animations = True`, fixing the skipping issue.

## Testing Status

Tried on a few scenes, works as expected.
## Further Comments

This only applies to the `CairoRenderer`, if this issue exists in the OpenGL/WebGL renderers is unknown.
Closes #874.
## Acknowledgements
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have chosen a descriptive PR title (see top of PR template for examples)

## Reviewer Checklist
- [ ] Newly added functions/classes are either private or have a docstring
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings
- [ ] The PR title is descriptive enough

### CODE REVIEW

**Comment by huguesdevimeux** [comment]
Isn't that done in #1019 ?

**Comment by kilacoda** [comment]
....Indeed it is. Though it seems that would take a while to merge, given it's been open for more than a month now? Given it's just a two line fix that already works, we could merge it here instead.

**Comment by huguesdevimeux** [comment]
Yes, why not. I haven't tested, but I'm juste a little scared that it didn't break anything, given that skip_animations logic is very .. complex.

Are you sure everything is working ?

**Comment by kilacoda** [comment]
Yep. No issues till now.

**Comment by jsonvillanueva** [comment]
It's worth note that I just approved #1019 to move things there more quickly. I'd prefer to make the change there instead to prevent merge conflicts that would delay it futher.

**Comment by huguesdevimeux** [comment]
I think this PR is now useless now that #1019 has been merged

**Comment by behackl** [comment]
Indeed, this should be resolved by the recently merged #1019.

**Pull request closed without merging**
