### PR TITLE
New function for 3D scenes: 3dillusion_camera_rotation

### PR DESCRIPTION
**Pull request by kolibril13**
This is a function, that gives the 3d camera a slow circular precession around the center so that there is a nice 3D effect.
Can be tested with:
```python
class RotateNice(ThreeDScene):
    def construct(self):
        self.camera.frame_center.shift(2 * OUT)
        self.add(Square())
        self.add(Square().shift(OUT * 2))
        self.set_camera_orientation(phi=75 * DEGREES, theta=-60 * DEGREES) 
        self.begin_3dillusion_camera_rotation()
        self.wait(TAU)
        self.stop_3dillusion_camera_rotation()
        self.wait(1)
        self.begin_3dillusion_camera_rotation()
        self.wait()

```
RotateNice

### CODE REVIEW

**Comment by leotrs** [comment]
Beautiful!

**Comment by leotrs** [comment]
We just need one more approval and this can be merged.

Also, could you please run `black` locally and then update this PR? It is the only check that is not passing. Thanks.

**Comment by kolibril13** [comment]
I think that te black test did not fail.
My github shows me, that the "format" test fails. 
Unfortunately, I don't understand the output message. 
bb

**Comment by leotrs** [comment]
The format check is running `black` under the hood. The output you see is showing you what `black` is suggesting you to do: look at the pairs of consecutive lines starting with a `+` and a `-`. All the changes are just formatting changes, like adding spaces around an operator.

**Comment by kolibril13** [comment]
ok, done!
But at one point it looks a little odd:
```python
def begin_3dillusion_camera_rotation(
        self, rate=1, origin_theta=-60 * DEGREES, origin_phi=75 * DEGREES
    ):
        val_tracker_theta = ValueTracker(0)
```
Black gave me this  ): sad emoji   :D

**Comment by leotrs** [comment]
Yes, black sometimes gives odd code. It is what it is. Thanks for running it!

**Comment by leotrs** [comment]
Thanks @kolibril13 , this is awesome!

**Pull request merged**
