### PR TITLE
Updated documentation contribution flowchart (external script to iframe)

### PR DESCRIPTION
**Pull request by kolibril13**
## Checklist
- [ ] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [ ] I have written a descriptive PR title (see top of PR template for examples)
- [ ] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [x] The PR title is descriptive enough
- [x] The PR is labeled correctly
- [x] The changelog entry is completed if necessary
- [x] Newly added functions/classes either have a docstring or are private
- [x] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [x] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by kolibril13** [comment]
can be seen here:
https://manimce--1289.org.readthedocs.build/en/1289/contributing/development.html#further-useful-guidelines

**Comment by behackl** [comment]
You updated the old file in Google drive, right? Then there is nothing left to do, the change is already live; no PR required.

**Comment by behackl** [comment]
Closing, as the file has already been updated; no link change is required.

**Comment by kolibril13** [comment]
Yes, but I am not completely sure if the embedded version is pointing to the latest saved version of the diagram or a previous one. And also, the embedding syntax changed to "iframe" which is much more readable, so I think it's a good idea to change it this way.

**Comment by jsonvillanueva** [comment]
> And also, the embedding syntax changed to "iframe" which is much more readable, so I think it's a good idea to change it this way.

I actually disagree for two reasons:
1. The width is hardcoded in this PR.
2. 
image
It's not a vector image in this PR so when you zoom in it's not very readable. I think this PR should be closed in favor of the other if it's fixed -- or iFrame shouldn't be used with a PNG and hardcoded/unresponsive styling

**Review by behackl — CHANGES_REQUESTED** [review]
I also just looked at it on mobile: by fixing the width of the iframe, there is an overflow and the right side of the diagram cannot be viewed.

While the embedding itself is simpler via the iframe, I agree with @jsonvillanueva that for users this doesn't seem to improve the situation.

**Pull request closed without merging**
