### PR TITLE
Correcting class ArrowCircleTip()

### PR DESCRIPTION
**Pull request by Tapyu**
## List of Changes

- I overwrote the `get_start()` and `tip_point()` function inside the `ArrowCircleTip()` class.
## Motivation

The starting/ending point of the `DoubleArrow()` class ought to match with the center point of `tip_shape_start=ArrowCircleFilledTip` or `tip_shape_end=ArrowCircleFilledTip`

## Explanation for Changes

This problem arises when I tried to create two objects that inherit from the class `DoubleArrow`. Both are concatenated, that Is, the ending point of the first is equal to the starting point of the second. In line codes, we would have:

`obj1 = DoubleArrow(init_pos, end_pos, tip_shape_start=ArrowCircleFilledTip, tip_shape_end=ArrowCircleFilledTip, buff=0)`
`obj2 = DoubleArrow(end_pos, another_pos, tip_shape_start=ArrowCircleFilledTip, tip_shape_end=ArrowCircleFilledTip, buff=0)`

where `init_pos`, `end_pos`, and `another_pos` are `np.array()` values. I was expected to have to double dot-shaped tip lines connected, forming a single path, like that

image

But It didn't happen because the initial/ending point parameters in `DoubleArrow` was not equal to the center point in the dots. Actually, It seems to behave as if it were an `Arrow()` class. Without my changes, the manim community has the following output:

image

Even if I set a negative `buff` parameter, the initial point of `DoubleArrow()` doesn't match with the center point of `ArrowCircleFilledTip()`. With my changes, in addition to this sensible match, we can increase the distance from the center of the dot. Hence, we can match the dots with the borders again just setting the `buff` parameter.

## Testing Status

Tested on my machine.

## Further Comments

- This is my first pull request, so please, have mercy.
- Thanks are due to @behackl and the Discord Manim Community.

## Acknowledgement
- [x] I have read the [Contributing Guidelines](https://github.com/ManimCommunity/manim/wiki/Documentation-guidelines-(WIP))

### CODE REVIEW

**Comment by behackl** [comment]
Thank you for your contribution!

This certainly fixes the behavior for `ArrowCircleFilledTip`. I wonder: What happens if you move your changes to `ArrowCircleTip`? Are the lines poking into the circles, or are they shortened appropriately?

Ideally, it would be good to fix the behavior for both kinds of circle tips at once.

**Comment by Tapyu** [comment]
> Thank you for your contribution!
> 
> This certainly fixes the behavior for `ArrowCircleFilledTip`. I wonder: What happens if you move your changes to `ArrowCircleTip`? Are the lines poking into the circles, or are they shortened appropriately?
> 
> Ideally, it would be good to fix the behavior for both kinds of circle tips at once.

It worked as well. I moved these changes to `ArrowCircleTip()` class.

**Review by behackl — COMMENTED** [review]
Great!

Now that the functionality is here, there are two things to take care of:

- Make sure the tests pass. There is (1) a formatting issue which you can either fix by running `black` on `geometry.py` -- or, alternatively, if you want to do it manually: there always has to be a newline without indentation between functions. Add a newline before L1069 and remove the indentation in L1072.
- Then, (2) our integration tests fail because the arrows render in a different way. IIRC, you can fix this by running `pytest` from the root directory of the git repository; then the file `DoubleArrowTest.npy` should change; the tests are fixed after you commit this changed file. (You can learn more about our testing framework here: https://github.com/ManimCommunity/manim/wiki/Testing)
- And finally, please document explicitly that the arrow tip determined by `ArrowCircleTip` and `ArrowCircleFilledTip` is located at the center of the circle. You can do so simply by adding a sentence to the docstrings in L1062 and L1078.

Let me know if you need help along the way! :-)

**Comment by leotrs** [comment]
Psst let's not forget the changelog ;)

**Comment by kolibril13** [comment]
The tests are failing:
```console
E           AssertionError: The frames don't match. CustomDoubleArrow has been modified.
E           Please ignore if it was intended.
E           First unmatched index is at [270 382]: [  0   0   0 255] != [ 26  26  26 255]
```
At the moment, all new control data that is produced in any pr contains only zero, see issue here:
https://github.com/ManimCommunity/manim/issues/571

**Comment by Tapyu** [comment]
I'm aware. Well, currently I'm in a hurry but I gonna handle it ASAP.

Best regards.

**Comment by behackl** [comment]
> I'm aware. Well, currently I'm in a hurry but I gonna handle it ASAP.
> 
> Best regards.

Don't stress youself! Let me/us here know, if you need help with any of the steps; we are glad to help!

**Comment by Tapyu** [comment]
> Great!
> 
> Now that the functionality is here, there are two things to take care of:
> 
> * Make sure the tests pass. There is (1) a formatting issue which you can either fix by running `black` on `geometry.py` -- or, alternatively, if you want to do it manually: there always has to be a newline without indentation between functions. Add a newline before L1069 and remove the indentation in L1072.
> * Then, (2) our integration tests fail because the arrows render in a different way. IIRC, you can fix this by running `pytest` from the root directory of the git repository; then the file `DoubleArrowTest.npy` should change; the tests are fixed after you commit this changed file. (You can learn more about our testing framework here: https://github.com/ManimCommunity/manim/wiki/Testing)
> * And finally, please document explicitly that the arrow tip determined by `ArrowCircleTip` and `ArrowCircleFilledTip` is located at the center of the circle. You can do so simply by adding a sentence to the docstrings in L1062 and L1078.
> 
> Let me know if you need help along the way! :-)

I notice that you helped me with the `black-check` issue. Thank you very much! Well, regarding the second issue, I typed `poetry run pytest` from the root directory, and I got the following error

image

and

image

You said that I would have a file 'DoubleArrowTest.npy' which would be changed in this process. However, I couldn't even find this file (I just found `.\tests\control_data\graphical_units_data\geometry\DoubleArrowTest.npz`)

PS: I typed `git pull upstream master` to keep my repository up to date.

**Comment by Tapyu** [comment]
> The tests are failing:
> 
> ```
> E           AssertionError: The frames don't match. CustomDoubleArrow has been modified.
> E           Please ignore if it was intended.
> E           First unmatched index is at [270 382]: [  0   0   0 255] != [ 26  26  26 255]
> ```
> 
> Thats because at the moment, all new control data that is produced in any pr contains only zero, see issue here:
> #571

As far as I am concerned (which isn't too much), that is the problem. I thought that this problem is because I didn't have a control data for this test. But after striving with this issue, I realized that the control data exists and its position is `[  0   0   0 255]` (at least for the `CustomDoubleArrowTest` class).

My PR is really meant to shift the `CustomDoubleArrow` to be able to chain a sequence of `DoubleArrow`. But how to change the control in order to match your positions?

**Comment by behackl** [comment]
> My PR is really meant to shift the `CustomDoubleArrow` to be able to chain a sequence of `DoubleArrow`, so it is reasonable that my output frame position differs from the expected output. But how to change the control in order to match your positions?

Hello @Tapyu, sorry for the slow response! Yes, your change here actually modifies the way an arrow is drawn, so it is no surprise that the control data does not match anymore; you should update it, here is how I usually do it:

1. Add the lines
```
from ..helpers.graphical_units import set_test_scene
set_test_scene(CustomDoubleArrowTest, "geometry")
```
after the `CustomDoubleArrowTest` class in `tests/test_graphical_units/test_geometry.py`.
2. Run `pytest` again. Don't worry about whether it fails or not (it does for me, with actually really weird tests that I don't fully understand why, but it does not matter). This will generate the updated `CustomDoubleArrowTest.npz` file containing the control data.
3. Remove the lines added in the first step again. Running pytest should now pass.
4. Commit and push the updated file.

**Comment by Tapyu** [comment]
Thank you again behackl for the precise instructions. The changes were done. What is the next step?

**Comment by Tapyu** [comment]
> Psst let's not forget the changelog ;)

Ok! I would like to know where the path to the changelog file. Is there an instruction on how to change the changelog? I've never changed a changelog before, so probably I won't do it as it is expected.

**Comment by behackl** [comment]
This looks pretty good!

The changelog can be found at `docs/source/changelog.rst`. Simply add an entry
```
#. The tip point for arrows using `ArrowCircleTip` has been moved to the center of the circle (via :pr:`557`).
```
or something like that -- whatever you feel describes this change the best -- to the `Mobjects, Scenes and Animations` section of the `v0.2.0`-Release. You might want to merge the current version of master to your branch first, though, in order to avoid a merge conflict.

Maybe I add one small test to make sure that this functionality stays the same in the future -- and then this is good to go. :-)

**Comment by Tapyu** [comment]
Done.

**Review by behackl — APPROVED** [review]
Thank you! I've moved your entry to the section for the upcoming release and slightly expanded the docstring with an additional test. Please cross-check my changes and let me know whether this is okay for you.

Other than that, this looks good to me now; thank you again for your contribution!

**Comment by Tapyu** [comment]
It's great for me Thanks for the guidance!

**Comment by jsonvillanueva** [comment]
Any updates on this? Is this PR safe to merge/close?

**Comment by behackl** [comment]
I am not sure any more. I think that with the recent introduction of `Graph` to manim, it might no longer be necessary to make sure that arrow with circular tips can be chained easily -- but I'd like to hear more opinions on that first before taking any action.

**Comment by leotrs** [comment]
Agreed, `Graph` sounds like the way to go

**Comment by Tapyu** [comment]
Yeah, I would like to know if my PR is still useful after the `v0.2.0` release. I hope so.  Anyway, if you all need anything, just let me know, I am following it. Best regards.

**Comment by leotrs** [comment]
@Tapyu , if you find yourself wanting to do something that cannot currently be done with the Graph class, then by all means let's revisit this. 

We look forward to your future contributions!

**Comment by tapyu** [comment]
@leotrs Ok. I appreciated the support given by y'all.  I hope to try to make more contributions in the future. Sya.

**Pull request closed without merging**
