### PR TITLE
Bring ManimCommunity/shaders up-to-date with 3b1b/shaders

### PR DESCRIPTION
**Pull request by Aathish04**
While we've been cracking down on master, 3b1b has committed to the shaders branch.

This is to bring our shaders branch up-to-date with his.

Also... some of the changes he made elsewhere, like commit 38cc0a7, 51eb9de and some others feel like we could also use them in master.

### CODE REVIEW

**Comment by safinsingh** [comment]
This seems to bring back some of the 3b1b files, can you remove them?

**Comment by Aathish04** [comment]
> This seems to bring back some of the 3b1b files, can you remove them?

@safinsingh I won't be able to remove them in _this_ PR, since it's directly from 3b1b/shaders.

I can remove them after this is merged and I'll probably make a new PR for that after this gets merged (if it _does_ get merged in the first place).

**Comment by yoshiask** [comment]
What's the point of working with the shaders branch at all? Most of the changes there aren't relevant to our plan at all.

**Comment by leotrs** [comment]
I think we want ManimCommunity to support shaders, yes? If so, we have to decide whether the best way of doing that is by pulling from 3b1bManim. And even in that case, merging 3b1b's branches to our repo is not going to be trivial.

**Comment by yoshiask** [comment]
Why would we want Manim CE to support shaders? The only reason 3b1b is doing it is to get GPU acceleration, but we're planning to use OpenGL (and others) in the same way Cairo is used, without shaders

**Comment by leotrs** [comment]
Ah, good point. Actually I don't know anything about graphics so I'll follow your lead there.

**Comment by yoshiask** [comment]
Pinging @eulertour for his input on this

**Comment by eulertour** [comment]
I don't think it's necessary. It won't be supported and will probably never be merged to master, so it'd probably be better to just use the upstream shaders branch if you wanted to.

**Comment by Aathish04** [comment]
Alright then. So, if we won't be working on the shaders branch at all, can we delete it? Just for the sake of cleanliness?

**Comment by leotrs** [comment]
Yes please.

**Pull request closed without merging**
