### PR TITLE
Migrated file_ops.py and scene_file_writer.py from os.path to Pathlib

### PR DESCRIPTION
**Pull request by WillSoltas**
## Overview: What does this pull request change?

In file_ops.py and scene_file_writer.py: Uses of str type file names have have been mostly (see further information) converted to Pathlib Path objects. Uses of os.path methods have been converted to equivalent Pathlib methods. 

## Motivation and Explanation: Why and how do your changes improve the library?

We focused on the Issue/enhancement/feature request [here](https://github.com/ManimCommunity/manim/issues/485)

Migrating to Pathlib objects and methods conforms to the maintainability and "built-in" standards of the project. Generally, Pathlib tends to conform better to OOP standards in python than os.path. This refactoring contributes to making the project—and its path types—consistent.

## Links to added or changed documentation pages

N/A

## Further Information and Comments

There is still a single use of str-based path objects with self.sections_output_dir = "" (scene_file_writer.py:128). We considered /dev/null or NUL as a default path. We ultimately left it as a str object as the Path() default constructor creates a path to the current directory (instead of ""), which might cause unwanted issues with path concatenation.

Additionally, we ran pytest on the entire suite to ensure our changes did not introduce any unwanted I/O behavior.

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by WillSoltas** [comment]
Multiple commits are from differences between Path objects and WindowsPath objects and me not being able to test this on a Windows file system.

**Review by Kiran-Raj-Dev — APPROVED** [review]
Thank you for your work! This looks good to me 👍

**Comment by Darylgolden** [comment]
Thank you! Can you help resolve the merge conflict?

**Comment by Kiran-Raj-Dev** [comment]
Looking at the merge conflicts, I think it would be nice to have the `guarantee_empty_existence` and `guarantee_existence` methods to only accept paths. Most methods in the library do pass a `Path` object to it only two tests in `tests/test_file_ops.py` pass strings. 

Would you change those tests to pass paths as well?

**Comment by Kiran-Raj-Dev** [comment]
So then the methods would look like, with type hints as:

```py
def guarantee_existence(path: Path) -> Path:
    if not path.exists():
        path.mkdir(parents=True)
    return path.resolve(strict=True)


def guarantee_empty_existence(path: Path) -> Path:
    if path.exists():
        shutil.rmtree(str(path))
    path.mkdir(parents=True)
    return path.resolve(strict=True)


def seek_full_path_from_defaults(file_name: str, default_dir: Path, extensions: list[str]) -> Path:
```

**Comment by WillSoltas** [comment]
Yep I’ll work on it today. Thanks for the feedback!

**Comment by WillSoltas** [comment]
Added the type hints to the methods in file_ops.py and changed the file_ops tests to use path lib

**Review by Darylgolden — APPROVED** [review]
LGTM!

**Pull request merged**
