### PR TITLE
CI: Fix macOS pipeline failure

### PR DESCRIPTION
**Pull request by RickyC0626**
## Changelog / Overview

Update `ci.yml` to update and upgrade brew if necessary before installing dependencies, and remove the unsupported `dvisvgm.86_64-darwin` package.

## Motivation

CI macOS pipeline failure due to installation of a basictex package that no longer exists.

Exploring this avenue has also revealed that `dvisvgm.86_64-darwin` is [no longer supported](https://www.preining.info/blog/2021/04/tex-live-2021-released/), as part of TeX Live 2021 release to support both ARM and Intel architectures. Instead, `dvisvgm.universal-darwin` will be used for MacTex, supporting macOS 10.14+. The legacy `dvisvgm.x86_64-darwinlegacy` binary folder will support macOS 10.6+, but it is only available with Unix install-tl.

## Explanation for Changes

```yml
- name: Install system dependencies (MacOS)
        if: runner.os == 'macOS'
        run: |
          brew update && brew upgrade && brew cleanup
          brew install openssl readline ffmpeg pyenv pyenv-virtualenv
          brew install --cask basictex
          eval "$(/usr/libexec/path_helper -s)"
          sudo tlmgr update --self
          brew install pkg-config libffi pango glib
          sudo tlmgr install --reinstall standalone preview doublestroke relsize fundus-calligra wasysym physics dvisvgm rsfs wasy cm-super
          echo "/Library/TeX/texbin" >> $GITHUB_PATH
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
```

## Checklist
- [X] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [X] I have written a descriptive PR title (see top of PR template for examples)
- [X] I have written a changelog entry for the PR or deem it unnecessary
- [X] My new functions/classes either have a docstring or are private
- [X] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [X] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [x] The PR title is descriptive enough
- [x] The PR is labeled correctly
- [x] The changelog entry is completed if necessary
- [x] Newly added functions/classes either have a docstring or are private
- [x] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [x] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Review by behackl — APPROVED** [review]
LGTM, thank you for investigating and fixing the pipeline!

**Comment by MrMallIronmaker** [comment]
This is super helpful. Thanks for the hard work and speedy fix.

I'm not familiar with brew; is the update / upgrade / cleanup necessary given we're running this in a CI env, or was it more a temporary fix?

**Comment by RickyC0626** [comment]
> This is super helpful. Thanks for the hard work and speedy fix.
> 
> I'm not familiar with brew; is the update / upgrade / cleanup necessary given we're running this in a CI env, or was it more a temporary fix?

It was more of a temporary fix to solve the basictex issue, but it led to finding out about the legacy package. I think we can keep it as redundancy in case a similar issue occurs in the future.

**Comment by MrMallIronmaker** [comment]
How much time does it add to the build? If we compare it to #1200 's build, it looks like it adds 4 minutes across the board. That is a lot of time for a "might be helpful" change.

**Comment by RickyC0626** [comment]
> How much time does it add to the build? If we compare it to #1200 's build, it looks like it adds 4 minutes across the board. That is a lot of time for a "might be helpful" change.

I do plan on working on caching as described in #824, for dependency-heavy packages such as ffmpeg to make the installation process faster.

**Comment by MrMallIronmaker** [comment]
That will be helpful. For the time being, though - and assuming it still builds - can you take out that update line? Otherwise it LGTM.

**Comment by jsonvillanueva** [comment]
Looks like that line was necessary

**Comment by RickyC0626** [comment]
> How much time does it add to the build? If we compare it to #1200 's build, it looks like it adds 4 minutes across the board. That is a lot of time for a "might be helpful" change.

Sped up the time by a few minutes by only upgrading the brew packages we need.

**Review by jsonvillanueva — APPROVED** [review]

**Comment by MrMallIronmaker** [comment]
Amazing, thank you!

**Pull request merged**
