### PR TITLE
Added test for :class:`~.Broadcast`

### PR DESCRIPTION
**Pull request by gammamathematics**
## Overview: What does this pull request change?

- This PR add a test for the class Broadcast

## Motivation and Explanation: Why and how do your changes improve the library?

- Solve the issue #1811, and enhance issue number #1802 
- I simply add a file named ``test_specialized.py`` in the following directory ``manim/tests/test_graphical_units`` with this content: 
```python
from manim import *
from tests.test_graphical_units.testing.frames_comparison import frames_comparison

__module_test__ = "specialized"


@frames_comparison(last_frame=False)
def test_Broadcast(scene):
    circle = Circle()
    scene.play(Broadcast(circle))
```

## Links to added or changed documentation pages

***Any document file changed***

## Further Information and Comments

***No further information***

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Review by Darylgolden — CHANGES_REQUESTED** [review]
There're now 2 control data files, can you remove the unused one?

**Comment by gammamathematics** [comment]
Yeah, ok

**Comment by gammamathematics** [comment]
> There're now 2 control data files, can you remove the unused one?

did it

**Review by gammamathematics — COMMENTED** [review]
Already done

**Review by Darylgolden — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
