### PR TITLE
Prepare new release, ``v0.14.0``

### PR DESCRIPTION
**Pull request by behackl**
Preparation of new release, `v0.14.0`. Might be the last one for a while, see corresponding announcement on our [Discord](https://manim.community/discord).

Link to rendered changelog: TBA

### CODE REVIEW

**Comment by GameDungeon** [comment]
Could I get this one in there, It's already approved:  #1972

**Review by kolibril13 — APPROVED** [review]
Looks good to me, here is the changelog:
https://manimce--2411.org.readthedocs.build/en/2411/changelog/0.14.0-changelog.html

**Review by Darylgolden — APPROVED** [review]
LGTM, thank you!

**Review by GameDungeon — APPROVED** [review]
Agreed, LGTM :)

**Comment by GameDungeon** [comment]
It's probably too late, but getting #2396 before the freeze would have been nice.

**Comment by Darylgolden** [comment]
Merged #2415, converted to draft

**Pull request merged**
