### PR TITLE
can't pass list of colors in set_color() fixed

### PR DESCRIPTION
**Pull request by sparshg**
## Motivation

Trying to fill gradient into a VMobject was returning error because of [this commit](https://github.com/ManimCommunity/manim/commit/84fb96bce9b41174481ce21182c7e153f4d7c183)
## Overview / Explanation for Changes

The change in the commit mentioned above didn't take care of lists passed to set_color(). So I added a check to avoid that and gradient works correctly now.

### Example:

<details><summary>Code</summary>

```py
class gradient(Scene):
    def construct(self):
        circle = Circle(fill_opacity=1).set_color(color=[YELLOW, GREEN])
        self.play(ShowCreation(circle))
```
</details>

## Before:
```
File "/home/user/.local/lib/python3.9/site-packages/colour.py", line 664, in web2hex
    if web.startswith('#'):
AttributeError: 'list' object has no attribute 'startswith'
```

## After
gradient
## Oneline Summary of Changes

```
- Can't fill gradient bug fixed (:pr:`990`)
```

## Acknowledgements
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)

## Reviewer Checklist
- [ ] Newly added functions/classes are either private or have a docstring
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings
- [ ] The oneline summary has been included [in the wiki](https://github.com/ManimCommunity/manim/wiki/Changelog-for-next-release)

### CODE REVIEW

**Comment by behackl** [comment]
Looks good to me! Could you take the code you have added above, replace `self.play` by `self.add`, and make it a graphical unit test?

We should make sure that we don't break this again in the future.

**Review by behackl — APPROVED** [review]
LGTM, thank you!

**Comment by huguesdevimeux** [comment]
Question: why nit making `set_color` only accepts one color, and using `set_color_by_gradient` when one wants to create a gradient ?

**Comment by sparshg** [comment]
idk but Circle().set_color_by_gradient(BLUE, GREEN) doesn't set a gradient for me

**Comment by huguesdevimeux** [comment]
yes, that's kind of the problem. I think this PR is the right place to fix this, don't you think ? (it shouldn't be long, only a few lines)

**Comment by behackl** [comment]
I think `Mobject.set_color_by_gradient` has its own right to exist, I would not want to remove that functionality here.

**Comment by huguesdevimeux** [comment]
yes, but it should be renamed. It's very confusing, in my opinion at least.

**Comment by behackl** [comment]
Deprecating the old name and switching to a new one (together with adding some documentation maybe :-)) is a good idea. I don't see a reason to block this PR over it, though.

**Comment by huguesdevimeux** [comment]
If you say so. Then, SGTM

**Review by huguesdevimeux — APPROVED** [review]

**Comment by huguesdevimeux** [comment]
thanks for the contribution @sparshg :D

**Pull request merged**
