### PR TITLE
Update pycairoinstall.py to use newer download links.

### PR DESCRIPTION
**Pull request by Aathish04**
I just realised that this script is still using the older dead links.
It's been updated now.

On a side note, should we make travis use this script instead of rewriting the whole thing for travis? Like, it would save us the trouble of checking whether both of them use the same source etc...

### CODE REVIEW

**Comment by naveen521kk** [comment]
I think we can make Travis use this `script` instead of one located there.

**Comment by Aathish04** [comment]
> I think we can make Travis use this `script` instead of one located there.

Both files are exactly the same, just copy-pasted over.

**Comment by naveen521kk** [comment]
Edit https://github.com/ManimCommunity/manim/blob/master/.travis.yml to use the one in `scripts` folder rather than `.travis` folder. Also, remove this script from the `travis` folder. Having the same script twice is waste.

**Comment by Aathish04** [comment]
> Edit https://github.com/ManimCommunity/manim/blob/master/.travis.yml to use the one in `scripts` folder rather than `.travis` folder. Also, remove this script from the `travis` folder. Having the same script twice is waste.

#140 has done this, and it works! I'll wait until two other Members approve it.

**Pull request closed without merging**
