### PR TITLE
Fix :meth:`~OpenGLMobject.shuffle` function and add :meth:`~.invert` to OpenGL

### LINKED ISSUE #1777: `OpenGLVMobject` does not appear to take into account the order of the list of submobjects when running animations
## Description of bug / unexpected behavior
While this may be intentional, there are some places where it causes problems. For example, 

```py
class ShuffleSubmobjectsExample(Scene):
    def construct(self):
        s= VGroup(*[Dot().shift(i*0.1*RIGHT) for i in range(-20,20)])
        s2= s.copy()
        s2.shuffle()
        s2.shift(DOWN)
        self.play(Write(s), Write(s2))
```

produces the expected result on cairo:

https://user-images.githubusercontent.com/9102529/124756197-c7fb7f00-df5e-11eb-8f48-2168e9789c45.mp4

but not on opengl:

https://user-images.githubusercontent.com/9102529/124756306-e6617a80-df5e-11eb-9f86-769e95cc68bd.mp4

If you try to add an `invert` method to `OpenGLVMobject` to make `Write` and `Unwrite` reversal possible, the same problem happens (inverting the list does nothing).

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
Paste your code here.
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

### PR DESCRIPTION
**Pull request by TRoboto**
## Changelog / Overview

Fixes #1777 

## Explanation for Changes

Apparently, `~.assemble_family` function should be called every time the order of the submobject list changes.

## Checklist
- [ ] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [ ] I have written a descriptive PR title (see top of PR template for examples)
- [ ] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Review by behackl — APPROVED** [review]
I have added some minor docstring improvements via 05261ac7 – please cross-check! – otherwise this looks good to me.

(In general, I'd like to rename `invert` to something that's less overshadowed by mathematical terminology; something like `reverse_submobjects` – but that should probably be done when we design a stable and uniform Mobject interface.)

**Comment by TRoboto** [comment]
> I have added some minor docstring improvements via [05261ac](https://github.com/ManimCommunity/manim/commit/05261ac7d8e12095f52ce10030acdfc352d27745) – please cross-check! – otherwise this looks good to me.
> 
> (In general, I'd like to rename `invert` to something that's less overshadowed by mathematical terminology; something like `reverse_submobjects` – but that should probably be done when we design a stable and uniform Mobject interface.)

Thank you for the improvements, they look good to me. 

There are many things that need to be changed in `OpenGLMobject` to make it compatible with the regular mobject. Even small things like a parameter name (e.g. `recurse` vs `recursive`). If we agree on the current state of the `Mobject`class, we probably need to start working on the implementation of `OpenGLMobject`

**Review by Darylgolden — APPROVED** [review]
Hi! Thank you for your PR, tested locally and can confirm that it does fix the shuffle submobjects example. However, trying out the following code:

```py
class ShowWriteReversed(Scene):
    def construct(self):
        self.play(Write(Text("Hello").scale(3)))
```

with the OpenGL renderer gives the following error:

```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\Daryl\manim-dev\manim\manim\cli\render\commands.py:109 in render                        │
│                                                                                                  │
│   106 │   │   │   │   │   scene_classes = scene_classes_from_file(file)                          │
│   107 │   │   │   │   │   SceneClass = scene_classes[0]                                          │
│   108 │   │   │   │   │   scene = SceneClass(renderer)                                           │
│ ❱ 109 │   │   │   │   │   status = scene.render()                                                │
│   110 │   │   │   │   │   if status:                                                             │
│   111 │   │   │   │   │   │   continue                                                           │
│   112 │   │   │   │   │   else:                                                                  │
│                                                                                                  │
│ C:\Users\Daryl\manim-dev\manim\manim\scene\scene.py:210 in render                                │
│                                                                                                  │
│    207 │   │   """                                                                               │
│    208 │   │   self.setup()                                                                      │
│    209 │   │   try:                                                                              │
│ ❱  210 │   │   │   self.construct()                                                              │
│    211 │   │   except EndSceneEarlyException:                                                    │
│    212 │   │   │   pass                                                                          │
│    213 │   │   except RerunSceneException as e:                                                  │
│                                                                                                  │
│ C:\Users\Daryl\manim-dev\manim\test.py:5 in construct                                            │
│                                                                                                  │
│    2                                                                                             │
│    3 class ShowWriteReversed(Scene):                                                             │
│    4 │   def construct(self):                                                                    │
│ ❱  5 │   │   self.play(Write(Text("Hello").scale(3), reverse=True))                              │
│    6                                                                                             │
│    7 class ShuffleSubmobjectsExample(Scene):                                                     │
│    8 │   def construct(self):                                                                    │
│                                                                                                  │
│ C:\Users\Daryl\manim-dev\manim\manim\scene\scene.py:862 in play                                  │
│                                                                                                  │
│    859 │   │   │   return np.max([animation.run_time for animation in animations])               │
│    860 │                                                                                         │
│    861 │   def play(self, *args, **kwargs):                                                      │
│ ❱  862 │   │   self.renderer.play(self, *args, **kwargs)                                         │
│    863 │                                                                                         │
│    864 │   def wait(self, duration=DEFAULT_WAIT_TIME, stop_condition=None):                      │
│    865 │   │   self.play(Wait(run_time=duration, stop_condition=stop_condition))                 │
│                                                                                                  │
│ C:\Users\Daryl\manim-dev\manim\manim\utils\caching.py:58 in wrapper                              │
│                                                                                                  │
│   55 │   │   │   "List of the first few animation hashes of the scene: %(h)s",                   │
│   56 │   │   │   {"h": str(self.animations_hashes[:5])},                                         │
│   57 │   │   )                                                                                   │
│ ❱ 58 │   │   func(self, scene, *args, **kwargs)                                                  │
│   59 │                                                                                           │
│   60 │   return wrapper                                                                          │
│   61                                                                                             │
│                                                                                                  │
│ C:\Users\Daryl\manim-dev\manim\manim\renderer\cairo_renderer.py:46 in wrapper                    │
│                                                                                                  │
│    43 │   def wrapper(self, scene, *args, **kwargs):                                             │
│    44 │   │   self.animation_start_time = time.time()                                            │
│    45 │   │   self.file_writer.begin_animation(not self.skip_animations)                         │
│ ❱  46 │   │   func(self, scene, *args, **kwargs)                                                 │
│    47 │   │   self.file_writer.end_animation(not self.skip_animations)                           │
│    48 │   │   self.num_plays += 1                                                                │
│    49                                                                                            │
│                                                                                                  │
│ C:\Users\Daryl\manim-dev\manim\manim\renderer\opengl_renderer.py:355 in play                     │
│                                                                                                  │
│   352 │   │   # TODO: Handle data locking / unlocking.                                           │
│   353 │   │   if scene.compile_animation_data(*args, **kwargs):                                  │
│   354 │   │   │   scene.begin_animations()                                                       │
│ ❱ 355 │   │   │   scene.play_internal()                                                          │
│   356 │                                                                                          │
│   357 │   def clear_screen(self):                                                                │
│   358 │   │   window_background_color = color_to_rgba(config["background_color"])                │
│                                                                                                  │
│ C:\Users\Daryl\manim-dev\manim\manim\scene\scene.py:972 in play_internal                         │
│                                                                                                  │
│    969 │   │   │   │   break                                                                     │
│    970 │   │                                                                                     │
│    971 │   │   for animation in self.animations:                                                 │
│ ❱  972 │   │   │   animation.finish()                                                            │
│    973 │   │   │   animation.clean_up_from_scene(self)                                           │
│    974 │   │   if not self.renderer.skip_animations:                                             │
│    975 │   │   │   self.update_mobjects(0)                                                       │
│                                                                                                  │
│ C:\Users\Daryl\manim-dev\manim\manim\animation\creation.py:333 in finish                         │
│                                                                                                  │
│   330 │   def finish(self) -> None:                                                              │
│   331 │   │   if self.reverse:                                                                   │
│   332 │   │   │   self.reverse_submobjects()                                                     │
│ ❱ 333 │   │   super().finish()                                                                   │
│   334                                                                                            │
│   335                                                                                            │
│   336 class Unwrite(Write):                                                                      │
│                                                                                                  │
│ C:\Users\Daryl\manim-dev\manim\manim\animation\animation.py:191 in finish                        │
│                                                                                                  │
│   188 │   │   This method gets called when the animation is over.                                │
│   189 │   │                                                                                      │
│   190 │   │   """                                                                                │
│ ❱ 191 │   │   self.interpolate(1)                                                                │
│   192 │   │   if self.suspend_mobject_updating and self.mobject is not None:                     │
│   193 │   │   │   self.mobject.resume_updating()                                                 │
│   194                                                                                            │
│                                                                                                  │
│ C:\Users\Daryl\manim-dev\manim\manim\animation\animation.py:278 in interpolate                   │
│                                                                                                  │
│   275 │   │   │   The relative time to set the aniamtion to, 0 meaning the start, 1 meaning      │
│   276 │   │   │   the end.                                                                       │
│   277 │   │   """                                                                                │
│ ❱ 278 │   │   self.interpolate_mobject(alpha)                                                    │
│   279 │                                                                                          │
│   280 │   def interpolate_mobject(self, alpha: float) -> None:                                   │
│   281 │   │   families = list(self.get_all_families_zipped())                                    │
│                                                                                                  │
│ C:\Users\Daryl\manim-dev\manim\manim\animation\animation.py:284 in interpolate_mobject           │
│                                                                                                  │
│   281 │   │   families = list(self.get_all_families_zipped())                                    │
│   282 │   │   for i, mobs in enumerate(families):                                                │
│   283 │   │   │   sub_alpha = self.get_sub_alpha(alpha, i, len(families))                        │
│ ❱ 284 │   │   │   self.interpolate_submobject(*mobs, sub_alpha)                                  │
│   285 │                                                                                          │
│   286 │   def interpolate_submobject(                                                            │
│   287 │   │   self,                                                                              │
│                                                                                                  │
│ C:\Users\Daryl\manim-dev\manim\manim\animation\creation.py:264 in interpolate_submobject         │
│                                                                                                  │
│   261 │   │   │   submobject.pointwise_become_partial(outline, 0, subalpha)                      │
│   262 │   │   │   submobject.match_style(outline)                                                │
│   263 │   │   else:                                                                              │
│ ❱ 264 │   │   │   submobject.interpolate(outline, starting_submobject, subalpha)                 │
│   265                                                                                            │
│   266                                                                                            │
│   267 class Write(DrawBorderThenFill):                                                           │
│                                                                                                  │
│ C:\Users\Daryl\manim-dev\manim\manim\mobject\types\opengl_vectorized_mobject.py:892 in           │
│ interpolate                                                                                      │
│                                                                                                  │
│    889 │   │   return np.vstack(new_points)                                                      │
│    890 │                                                                                         │
│    891 │   def interpolate(self, mobject1, mobject2, alpha, *args, **kwargs):                    │
│ ❱  892 │   │   super().interpolate(mobject1, mobject2, alpha, *args, **kwargs)                   │
│    893 │   │   if config["use_projection_fill_shaders"]:                                         │
│    894 │   │   │   self.refresh_triangulation()                                                  │
│    895 │   │   else:                                                                             │
│                                                                                                  │
│ C:\Users\Daryl\manim-dev\manim\manim\mobject\opengl_mobject.py:1399 in interpolate               │
│                                                                                                  │
│   1396 │   │   │   else:                                                                         │
│   1397 │   │   │   │   func = interpolate                                                        │
│   1398 │   │   │                                                                                 │
│ ❱ 1399 │   │   │   self.data[key][:] = func(mobject1.data[key], mobject2.data[key], alpha)       │
│   1400 │   │   for key in self.uniforms:                                                         │
│   1401 │   │   │   self.uniforms[key] = interpolate(                                             │
│   1402 │   │   │   │   mobject1.uniforms[key], mobject2.uniforms[key], alpha                     │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
```

I'm fine with merging this PR as is and fixing the issue in a future PR. However, if you do happen to know how to fix this problem quickly, it'd be great if you can do so here.

**Comment by TRoboto** [comment]
@Darylgolden  the problem is with these two lines https://github.com/ManimCommunity/manim/blob/13369e3ad5de5ee1c47a622d731ef854f447f75e/manim/animation/creation.py#L331-L332 

Removing them doesn't make much difference as the animation still works without them. Should I move forward and push the changes?

**Comment by Darylgolden** [comment]
It would affect the `Unwrite` animation if it were subsequently applied on the same Text, no?

**Comment by TRoboto** [comment]
> It would affect the `Unwrite` animation if it were subsequently applied on the same Text, no?

I've just pushed a change to fix this. You are right, the animation shouldn't manipulate any mobject.

BTW, I think `Unwrite(reverse=True)` is broken, reversing does nothing even with Cairo renderer.

**Comment by Darylgolden** [comment]
> BTW, I think `Unwrite(reverse=True)` is broken, reversing does nothing even with Cairo renderer.

It's not broken, it's just been changed in #1774 so that the default value of `reverse` is `True`.

LGTM, I was originally going to leave #1795 as a comment in this PR, but I realized that it was a problem that existed on `main` too, which your PR fixes for OpenGL.

**Pull request merged**
