### PR TITLE
Added line to mention the existence of subhelp pages when using manim --help

### PR DESCRIPTION
**Pull request by joybh98**
## Overview: What does this pull request change?

The PR makes the user aware of  the existence of subhelp pages when using ```manim --help```
as suggested by @Darylgolden  in #1912 

## Motivation and Explanation: Why and how do your changes improve the library?

NA
## Links to added or changed documentation pages
 

NA
## Further Information and Comments

Right now the pre-commit hooks are not passing the flake8 test when using ```console.print(f``` ,hopefully it will be sorted out by the time this PR is merged.

## Reviewer Checklist
- [x] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by PhotonSpheres** [comment]
I think the pre-commit test fails because there is no need for this message being an f-string. Would you look into that?

**Comment by joybh98** [comment]
> I think the pre-commit test fails because there is no need for this message being an f-string. Would you look into that?

i've removed the f-string and pushed the commit, please take a look when you have time.

**Comment by PhotonSpheres** [comment]
Now all checks pass. 
When using your changes, the sentence also gets printed when rendering a normal scene. I think @Darylgolden only wanted this remark to show when running `manim --help`, not every time when running _any_ manim command. Or am I misunderstanding something here?

**Comment by joybh98** [comment]
> Now all checks pass.
> When using your changes, the sentence also gets printed when rendering a normal scene. I think @Darylgolden only wanted this remark to show when running `manim --help`, not every time when running _any_ manim command. Or am I misunderstanding something here?

You're right, the issue stated that it should make the user aware of the existence of subhelp pages when running ```manim --help```, I'll make the changes. I didn't notice that, thanks !

**Comment by Darylgolden** [comment]
> 
> 
> Now all checks pass.
> When using your changes, the sentence also gets printed when rendering a normal scene. I think @Darylgolden only wanted this remark to show when running `manim --help`, not every time when running _any_ manim command. Or am I misunderstanding something here?

Yes, that's what I meant.

**Comment by behackl** [comment]
If I understood the discussion over on Discord correctly, this still needs some work. I'll convert it to a draft in the meantime (apologies if I got that wrong).

**Comment by Darylgolden** [comment]
Hi, are you still working on the PR? Due to refactoring plans, if this PR is not ready to be merged by the end of the year, it may have to be closed.

**Comment by Darylgolden** [comment]
I'll close this due to inactivity. Feel free to reopen if you would like to work on it again!

**Pull request closed without merging**
