### PR TITLE
Update copyright year in documentation to 2020-2021

### PR DESCRIPTION
**Pull request by darigovresearch**
Updates year in conf.py to correct year in the footer of the documentation.

Would resolve Issue https://github.com/ManimCommunity/manim/issues/1709 if merged

## Changelog / Overview

Updates year in docs to 2020-2021

## Motivation

Keeping year correct helps encourage people to use the project since if it is out of date people may think the project & docs are no longer being maintained

## Explanation for Changes

[Documentation Reference](https://manimce--####.org.readthedocs.build)

## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [x] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by Nikhil0504** [comment]
Can’t we just remove the year altogether?

**Comment by darigovresearch** [comment]
Original source does not use year (https://3b1b.github.io/manim/) however up to the maintainers of this repository to say if/why they put the year and if they wish to keep it moving forward.

Happy to make the changes either way

**Comment by Darylgolden** [comment]
I would prefer to have it "2020-2021", like how [Python](https://docs.python.org/3/) and [Numpy](https://numpy.org/doc/stable/) do it.

**Comment by darigovresearch** [comment]
@Darylgolden the year has been updated & so has the PR title and changelog texts to match "2020-2021"

**Review by Darylgolden — APPROVED** [review]
LGTM! Thank you for your contribution.

**Comment by darigovresearch** [comment]
Thanks for the feedback & for merging!

**Pull request merged**
