### PR TITLE
Switch to compressed numpy arrays for test control data

### PR DESCRIPTION
**Pull request by behackl**
## List of Changes
As pointed out by @kolibril13 in #599, we should store the control data for the graphical unit tests in a compressed format. This PR switches `set_up_scene` and `_load_data` to the compressed format, and changes all control files to the compressed format.

The size of the `control_data` directory actually reduces from 132MB to 620KB (!!!).

## Testing Status
Tests pass locally -- and this should be easy to review: either the tests pass, or they don't. 🙃

## Acknowledgement
- [x] I have read the [Contributing Guidelines](https://github.com/ManimCommunity/manim/wiki/Documentation-guidelines-(WIP))

### CODE REVIEW

**Review by leotrs — APPROVED** [review]

**Comment by leotrs** [comment]
What a hero.

**Review by yoshiask — APPROVED** [review]
Looks good to me

**Comment by behackl** [comment]
To have this live *somewhere*, here is the code I used for converting the `.npy` files to their compressed counterparts:

```py
import numpy as np
from pathlib import Path

p = Path(".")
control_files = [f for f in list(p.rglob("*")) if f.name[-4:] == ".npy"]

for file in control_files:
    data = np.load(file)
    np.savez_compressed(file.as_posix()[:-4], frame_data=data)
```

**Comment by behackl** [comment]
Docs don't only fail to build here, but apparently master as well. This is not related to the changes here, seems we forgot to remove some `PangoText` somewhere. I'll have a look at that in a moment.

**Review by naveen521kk — APPROVED** [review]
Too many files to review 😂

**Review by kolibril13 — APPROVED** [review]

**Comment by huguesdevimeux** [comment]
How is this miracle even possible

**Comment by kolibril13** [comment]
One method is called Huffman coding:
https://www.youtube.com/watch?v=0kNXhFIEd_w
Actually, this topic would be very suitable to make a manim video of it :D

**Pull request merged**
