### PR TITLE
Fix Wait-animations adding empty Mobjects to the Scene

### LINKED ISSUE #1524: Wait-animation adds an empty Mobject to the Scene
## Description of bug / unexpected behavior
Playing a `Wait` animation (and therefore using `Scene.wait` adds an empty `Mobject` to the Scene:

```py
class WaitExample(Scene):
    def construct(self):
        print(self.mobjects) # []
        self.wait()
        print(self.mobjects) # [Mobject]
        self.play(Wait())
        print(self.mobjects) # [Mobject, Mobject]
```
The underlying problem is, that Animations without Mobects cannot exist right now - if they get non they create one themselves. This is definitely where the added Mobject comes from - I already tested that by giving that Mobject a special name...

Probably that should be fixed as a whole - `Wait` should not require a Mobject internally.

## Additional comments
I already tried simply pasing Wait the `remover=True` keyword and removing it's `clean_up_from_scene` method, but that didn't fix it.

### PR DESCRIPTION
**Pull request by AntonBallmaier**
## Changelog / Overview

Fix `Scene.wait` adding an empty mobject to the scene.

## Motivation
closes #1524 

## Explanation for Changes
Mobjects added as placeholders to Animations created without one are marked. Those are then not added to the scene.  

## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [x] My new functions/classes either have a docstring or are private
- [x] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [x] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Review by huguesdevimeux — CHANGES_REQUESTED** [review]
Two things :
- This needs tests. 
- Why not just checking if the current animation is a `Wait`, and if so not adding the mobject ?

**Comment by behackl** [comment]
I think it would be semantically cleaner if `empty_anim_placeholder` would be set to `False` on `Mobject` (or `OpenGLMobject`) initialization, so that we can rather check the value of the attribute, rather than its existence.

(This is only a very, very minor preference though, and if you'd rather like to keep it as-is, I'm also fine with it.)

**Comment by huguesdevimeux** [comment]
Another suggestion : 
In animation, there is [`clean_up_from_scene`](https://github.com/ManimCommunity/manim/blob/6e4b02a4d1250e462a88489c826dc5af795947ca/manim/animation/animation.py#L197-L209) method that just remove the associated mobject if the animation is a remover.
For  Wait, this method is overriden but is not defined ([here](https://github.com/ManimCommunity/manim/blob/6e4b02a4d1250e462a88489c826dc5af795947ca/manim/animation/animation.py#L478-L479))
*
I think the best solution is make Wait's `clean_up_from_scene` always remove its mobject - which is a blank mobject)

**Comment by Darylgolden** [comment]
I'll close this because of inactivity, and to hopefully signal to others that they can work on this.

**Pull request closed without merging**
