### PR TITLE
Correct type hint for `labels` parameter of :class:`~.Graph`

### PR DESCRIPTION
**Pull request by citrusmunch**
change type hint from `bool` to `Union[bool, dict]`

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Review by behackl — APPROVED** [review]
LGTM, thanks!

**Review by hydrobeam — COMMENTED** [review]
Maybe it would be more inline to have labels be `None`, not `False` as a default. Then the type would be `Optional[dict]`, which would be more inline with the rest of the library. (checks for `bool` would need to be updated elsewhere in the file)

**Comment by citrusmunch** [comment]
> Maybe it would be more inline to have labels be `None`, not `False` as a default. Then the type would be `Optional[dict]`

I'm happy to do this, but then we will lose the automatic labeling, since currently it's no labels vs auto labels vs custom labels (false vs true vs dict).

Lemme know if you want that, or if there's a better design.

**Comment by hydrobeam** [comment]
> I'm happy to do this, but then we will lose the automatic labeling, since currently it's no labels vs auto labels vs custom labels (false vs true vs dict).

Ah I wasn't aware of this. I'd say that the current design could probably be improved upon, but is beyond the scope of this PR.

**Pull request merged**
