### PR TITLE
Improve design of documentation

### LINKED ISSUE #612: Redesign manim-example blocks
At the very least the blocks should be easier to distinguish from each other.

### PR DESCRIPTION
**Pull request by behackl**
## List of Changes
- Completely redesign example blocks with included source code
- Introduce colors from color palette across our docs
- Improve design of non-example code blocks

## Motivation
As discussed in #607, our manim-directive generated example blocks did not have a very good design. This PR improves this. And while throwing on some custom design, I also changed some colors in our docs to match the color palette of our new logo.

Closes #612. 

## Acknowledgement
- [x] I have read the [Contributing Guidelines](https://github.com/ManimCommunity/manim/wiki/Documentation-guidelines-(WIP))

### CODE REVIEW

**Comment by behackl** [comment]
Here is a quick look at how this proposed redesign looks like, I hope you like it. :-)

image

**Comment by kolibril13** [comment]
Wow, what a great enhancement!
Some points I see right now:
abc
I think this blue banner in the middle does not need the title, as one can already see it in the class name. It feels a bit redundant.
Further, I think the blue is a bit too obtrusive, probably we can choose a bit lighter colour.
Especially here, it is not optimal.
ccd
 Maybe one can make the "Example References" text white, or the background of it white.

**Comment by kolibril13** [comment]
ddd
Oh, and this looks a bit scary, good for Halloween, but not the best font colour I would say

**Comment by kolibril13** [comment]
also here, I think the orange and the orange-red are a bit itchy together.
ddd

**Comment by leotrs** [comment]
This is great. Will review at length later, but this is the original
palette https://coolors.co/f4f1de-e07a5f-3d405b-81b29a-f2cc8f

**Comment by behackl** [comment]
> I think this blue banner in the middle does not need the title, as one can already see it in the class name. It feels a bit redundant.

I can see where you are coming from; I experimented quite a bit and found that without a "title", the code seems a bit "lost". And especially for users not too deep into Python, the class name can be overlooked easily.

> Further, I think the blue is a bit too obtrusive, probably we can choose a bit lighter colour.

Well, this is a personal preference but I'd really like to stick with the colors from our logo. I feel that using too many other colors introduces a sort of unrest to the overall color scheme.

> Especially here, it is not optimal.
> Maybe one can make the "Example References" text white, and maybe even a bit bigger font,

Good catch, I forgot about the reference blocks. Will fix in a moment.

> Oh, and this looks a bit scary, good for Halloween, but not the best font colour I would say

High-contrast link colors are an absolute must, and I'd still like to stick with the logo color scheme. Blue is too dark, green is too bright -- which is why all links are orange-ish (@leotrs palette says the color actually is terracotta).

> also here, I think the orange and the orange-red are a bit itchy together.

We could resolve that, although I felt that the code references should not have the standard link color (because actually not all of them do link somewhere...). I'm open for suggestions, but personally I don't mind the "itchyness" here, because I feel that the different fonts are sufficient to separate them.

**Comment by behackl** [comment]
> I can see where you are coming from; I experimented quite a bit and found that without a "title", the code seems a bit "lost". And especially for users not too deep into Python, the class name can be overlooked easily.

This remark is especially true given that we were discussing imports to the examples over at #593.

**Comment by behackl** [comment]
New suggestion for example references (9c4276be):

image

**Comment by leotrs** [comment]
> I think this blue banner in the middle does not need the title, as one can already see it in the class name. It feels a bit redundant.

This is not true in the image that @behackl posted [here](https://github.com/ManimCommunity/manim/pull/617#issuecomment-716141594). The `CustomTipExample` is not at the top of that chunk of code, so I think it works very well to also give it the title in blue background.

> Further, I think the blue is a bit too obtrusive, probably we can choose a bit lighter colour.

I also have no problem with this blue. But if we need to, I suggest you [scroll down here to "Variations"](https://coolors.co/525893) and choose one from tints, shades, or tones.

> Maybe one can make the "Example References" text white, and maybe even a bit bigger font,

I suggest #F5F5F5 or #F4F1DE or something in the middle.

> Oh, and this looks a bit scary, good for Halloween, but not the best font colour I would say

[See here](https://coolors.co/e07a5f) for variations of orange. I'm okay with the font not matching *exactly* the logo color, but it should be pretty close. For regular text, suggest #353535 or some other warm-ish gray. Although, I'm less married to this one than to my other suggestions. Just black (or near-black) works too.

Overall great stuff. I like the blue border around the code!

**Comment by leotrs** [comment]
As a reminder to all of us: we should have a .txt file inside manim/logo that contains the hex codes of the logo colors, as well as perhaps a few variations.

**Comment by kolibril13** [comment]
Ok, I am fine with that.
I see, with the import statement, it should be fine to have the title displayed twice.
And with the colours I guess we just have to experiment until it looks good 👍🏼 
Another idea: do we want to have a "Fork me un GitHub"  Ribbon?
https://tqdev.com/2019-fork-me-on-github-svg-ribbons

**Comment by leotrs** [comment]
In general, the documentation should point to our landing page, and the GH repo. I've never liked the ribbons that say "fork me", because we actually don't want them to fork it, we want them to contribute to our repo! Also, sometimes there are "see this page on GH" buttons and it leads directly to the documentation page source code, not to the GH repo README page. I think this is annoying. Just my thoughts :)

**Comment by behackl** [comment]
> See here for variations of orange. I'm okay with the font not matching exactly the logo color, but it should be pretty close. For regular text, suggest #353535 or some other warm-ish gray. Although, I'm less married to this one than to my other suggestions. Just black (or near-black) works too.

I checked the current colors for accessibility and noticed that the link color orange was indeed a bit too bright. A better choice is `#b0604b`, which is of course also darker than the logo, but still a good fit (and it is closer to the color of literals), which makes the pages also appear more homogeneous.

Regular text is currently `#333`, changing it to `#353535` does not make a lot of difference, but I'm happy to follow your suggestion.

> I suggest #F5F5F5 or #F4F1DE or something in the middle.

Hmmm. I tried around a bit, but I think also contrast-wise, choosing either just white, or `#fafafa` (the background color of the code segment in the examples) yields the best result. Whatever color we decide on, both the example caption and the reference caption should use it. I'll leave them both white for my next commit, we can revisit it in the next iteration.

**Comment by leotrs** [comment]
> checked the current colors for accessibility and noticed that the link color orange was indeed a bit too bright. A better choice is `#b0604b`, which is of course also darker than the logo, but still a good fit (and it is closer to the color of literals), which makes the pages also appear more homogeneous.

Good call. Let's go with that one.
 
> Regular text is currently `#333`, changing it to `#353535` does not make a lot of difference, but I'm happy to follow your suggestion.

Thanks for pointing out my useless suggestion ;)
 

> Hmmm. I tried around a bit, but I think also contrast-wise, choosing either just white, or `#fafafa` (the background color of the code segment in the examples) yields the best result. Whatever color we decide on, both the example caption and the reference caption should use it. I'll leave them both white for my next commit, we can revisit it in the next iteration.

SGTM!

**Comment by kolibril13** [comment]
Looks really good already.
I just noted that we have lot of blank space on the right:
ddd
What do you think of making the page maybe 50px longer to the right side?
And do we currently match the resolution of the imgs and the videos in a way, that it is directly how they are displayed in the embedded video player?
If not, then we could also use this as a measure for the frame width.

**Comment by eulertour** [comment]
Is it possible to disable scrollbars on the code blocks? For some zoom levels they appear but only scroll a few pixels. Also, I think it makes more sense for the examples to come before the reference section, since the examples will illustrate a lot of concepts quickly. And finally, I think the Mathematical Objects section should just be names Mobjects so that it follows the class name the way the other sections do.

**Comment by leotrs** [comment]
> I just noted that we have lot of blank space on the right:
> What do you think of making the page maybe 50px longer to the right side?

I think you have this sense because your monitor is really wide. What we really need to do is check the site with different viewport sizes (using chrome dev tools for example). If anything, instead of incrementing the width, I'd suggest centering the whole content. Whitespace is inevitable on wide monitors.

**Comment by leotrs** [comment]
Ditto what @eulertour said about scroll bars but for the navigation bar.
2020-10-25-184124_341x978_scrot

**Comment by kolibril13** [comment]
Interesting.
I don't have these scroll bars at a zoom level of 100%:
ddd

**Comment by leotrs** [comment]
I'm at 110% on this PR's build at 1920x1080 resolution. (You are not seeing the latest build - you have the blue title "manim documentation")

**Comment by leotrs** [comment]
Also, I think this was meant to be a quick look&feel update, but now we're going down the rabbit hole of responsive web design. Which is a *huge* rabbit hole.

**Comment by behackl** [comment]
@eulertour 

> Is it possible to disable scrollbars on the code blocks? For some zoom levels they appear but only scroll a few pixels. 

Everything is possible in principle. I assume we are talking about vertical scroll bars?

> Also, I think it makes more sense for the examples to come before the reference section, since the examples will illustrate a lot of concepts quickly.

Sure thing, I agree. I would actually like to reorder the items a bit more, see my suggestion in fd11553b.

>  And finally, I think the Mathematical Objects section should just be names Mobjects so that it follows the class name the way the other sections do.

Agreed. ae97a02e

**Comment by kolibril13** [comment]
> Also, I think this was meant to be a quick look&feel update, but now we're going down the rabbit hole of responsive web design. Which is a _huge_ rabbit hole.

Good point. 
How do we want to proceed?
I would be fine with approving right now and discussing further things in a future pr.

**Comment by behackl** [comment]
@kolibril13 

> What do you think of making the page maybe 50px longer to the right side?

Ahhh, I am **very** cautious when it comes to changing the general layout. As @leotrs mentioned, these kind of adaptions usually bring a ton of ramifications on different screen sizes. I'd like to stay away from that within this PR -- we can revisit the idea on a follow-up PR, or when we decide that it is time to build our own theme.

> And do we currently match the resolution of the imgs and the videos in a way, that it is directly how they are displayed in the embedded video player?

We do, and would need to change that if the content width on the page changed.

**Comment by leotrs** [comment]
If the scroll bar thing is easy, let's do it now. Otherwise, let's merge this bad boi.

**Comment by behackl** [comment]
@eulertour @leotrs on screens that are close to the fullsize-breakpoint (i.e., wider than ~768px), removing scrollbars effectively breaks navigation on the page. An iPhone X in landscape mode is an example for a weird screen size like that: 

image

I fear I can't offer an easy solution for now. I suggest moving this to a follow-up issue (where we maybe change the general layout / write our own documentation theme instead of using the guzzle sphinx theme).

**Review by kolibril13 — APPROVED** [review]

**Review by leotrs — APPROVED** [review]

**Comment by behackl** [comment]
I think I took care of all issues raised that are not related to scrollbars or changing the overall layout.

Feel free to shout at me via Discord or open follow-up issues in case I did miss something; we can take care of it in a follow-up PR. 👍

**Pull request merged**
