### PR TITLE
Reduce complexity of AngleExample

### PR DESCRIPTION
**Pull request by kolibril13**
As the current syntax   `line_list = VGroup( *[VGroup() for k in range(4)] )`
can be simplified, I made according changes.

### CODE REVIEW

**Review by PhotonSpheres — APPROVED** [review]
LGTM, thanks for making my spaghetti code a bit nicer to look at!

**Comment by kolibril13** [comment]
Its a pleasure :)
Btw. I first thought, it would be nice to have a branch `docs_improvements` where all the small docs enhancements can go, but now I think that master might be the better place, as it is one step less in the development process.

**Review by TRoboto — APPROVED** [review]
LGTM!

**Review by naveen521kk — APPROVED** [review]
sgtm

**Pull request merged**
