### PR TITLE
Deprecated :meth:`.VMobject.get_points`

### PR DESCRIPTION
**Pull request by GameDungeon**
## Overview: What does this pull request change?

Deprecate get_points() and remove it from use.

Self.points works fine and get_points() is currently just a source of warnings. Despite those warnings, it was still in use. I think now that it is deprecated that use will stop. 

## Reviewer Checklist
- [x] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by GameDungeon** [comment]
I apparently can't name a pull request in github lol

**Review by leleogere — APPROVED** [review]
LGTM! This is a good idea, but some current PR might reintroduce a few `get_points` like the #1980 for example (last line).

**Comment by huguesdevimeux** [comment]
Please resolve the merge conflicts so we can merge this !

**Comment by GameDungeon** [comment]
@huguesdevimeux Fixed it, did not notice the conflict :)

**Review by behackl — APPROVED** [review]

**Comment by GameDungeon** [comment]
Is it too late to get the merged into version 10?

**Comment by behackl** [comment]
Yes, here are my reasons:

- This is not critical in any sense and I don't want to merge non-necessary changes (especially to something so fundamental) at this point,
- semantically, deprecating `get_points` to use `obj.points` while `set_points` is still needed to set points is odd.

**Comment by GameDungeon** [comment]
understandable. I was just hoping to get it in to speed up the process of people moving away from it.

**Review by huguesdevimeux — APPROVED** [review]

**Pull request merged**
