### PR TITLE
Deprecation of ShowCreation

### PR DESCRIPTION
**Pull request by Nikhil0504**
## Changelog / Overview

Deleted ShowCreation()

## Motivation

I deleted the deprecated function
## Explanation for Changes

Less clutter and confusion overall
## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by RickyC0626** [comment]
IIRC, deprecated code is deleted after 2 releases. Since #1124 was merged for `0.5.0` release, it is likely that this PR will be merged after the release of `0.6.0`, for `0.7.0`.

**Comment by Darylgolden** [comment]
Yes, we can just put this PR on hold until then (probably early May).

**Comment by Nikhil0504** [comment]
Should I open this up again?

**Review by PhilippImhof — APPROVED** [review]
SGTM

**Comment by Darylgolden** [comment]
LGTM

**Review by naveen521kk — APPROVED** [review]
SGTM

**Pull request merged**
