### PR TITLE
fix: issue with ImageMobject bounding box

### PR DESCRIPTION
**Pull request by vaclavblazej**
A missing point resulted in smaller bounding box causing issues it to be smaller when the object is rotated. Added the missing fourth point to ImageMobject points and altered call from camera. Filled in docstring that used to propagate from superclass, saying that ImageMobject has no points.

## Further Information and Comments

* discussed in [discord thread](https://discord.com/channels/581738731934056449/1143479267372572792)
* fixes issue #3067
* credit ought to be given to @abul4fia who resolved the issue

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by vaclavblazej** [comment]
<details>
<summary>Output for #3067 with this change (fixes the rotation center)</summary>

https://github.com/ManimCommunity/manim/assets/6208643/f4242efd-bc07-4192-a3ff-bed1e4b42242

</details>

**Review by naveen521kk — APPROVED** [review]
sgtm

**Comment by naveen521kk** [comment]
On second thought, adding a test for testing this would be better.

**Comment by behackl** [comment]
Thanks for your contribution!

**Pull request merged**
