### PR TITLE
Removed deprecated CairoText class

### LINKED ISSUE #1250: Removing CairoText
It's long that Pango is working with no or very few bugs and it's time to remove `CairoText`. We have deprecated it long back and it should be fine to remove it in the next release. See https://github.com/ManimCommunity/manim/projects/9#card-56126541

## Additional comments
Marking it as a good first issue.

### PR DESCRIPTION
**Pull request by erik-tastepe**
Closes #1250

## Changelog / Overview

 - Removed `CairoText` class from `manim.mobject.text_mobject`
 - Removed `'CairoText'` from `__all__`
 - Removed reference to `CairoText` in docstring

## Motivation

`CairoText` is deprecated and should be removed from the library

## Testing Status

`tests/test_graphical_units/test_opengl.py` failed during testing, though the removal of `CairoText` should not have influenced this test

## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Review by jsonvillanueva — APPROVED** [review]
LGTM! I don't think CairoText is mentioned anywhere else in docs either.

**Review by naveen521kk — APPROVED** [review]
sgtm, thanks.

**Comment by naveen521kk** [comment]
oh, no that check is failing for no reason. maybe do a dummy commit? (I think it should be fixed then.), I should fix it soon

**Comment by erik-tastepe** [comment]
> oh, no that check is failing for no reason. maybe do a dummy commit? (I think it should be fixed then.), I should fix it soon

Hey Naveen, should I try making the dummy commit? You're thinking it'll fix itself then?

**Comment by naveen521kk** [comment]
> Hey Naveen, should I try making the dummy commit? You're thinking it'll fix itself then?

yes, it should ideally fix itself. I will anyhow squash while merging so that doesn't matter.

**Review by kolibril13 — APPROVED** [review]

**Pull request merged**
