### PR TITLE
Fixed two issues of :class:`~.SVGMobject`

### LINKED ISSUE #2489: `SVGMobject` cannot parse SVG files correctly
## Description of bug / unexpected behavior

There are many issues in your `SVGMobject`:
- in `SVGMobject.generate_points`, every element with tag `svg` will be taken in `SVGMobject.get_mobjects_from`. But some of them are nested inside, which are used to generate mobjects for multiple times (this results in a thick line on the far left in the example below)
- in `SVGMobject.handle_transforms`, all transforms are applied from left to right, but should be applied from right to left (this causes the subscripts to be too close to the left text in the example below)

## How to reproduce the issue

<details><summary>Example</summary>

```py
class Code(Scene):
    def construct(self):
        svg = SVGMobject("formula.svg", stroke_opacity=0, color=WHITE)
        self.add(svg)
```
formula

**Result**:
image

**Expected**:
image

</details>

## Additional comments

See also: https://github.com/3b1b/manim/pull/1712

### PR DESCRIPTION
**Pull request by TonyCrane**
## Overview: What does this pull request change?

Fixed #2489.

## Motivation and Explanation: Why and how do your changes improve the library?

See #2489 and https://github.com/3b1b/manim/pull/1712.

## Further Information and Comments

See #2489 and https://github.com/3b1b/manim/pull/1712.

After this pr:
image

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by Darylgolden** [comment]
cc @MrMallIronmaker

**Comment by TonyCrane** [comment]
The test fails because the expected behavior is wrong when testing the MultipleTransform.

**Review by Darylgolden — APPROVED** [review]
Visually, this LGTM! Can you regenerate the control data?

**Comment by behackl** [comment]
Thanks for your efforts @TonyCrane, much appreciated! Indeed, it is a bit odd that this test was added in the first place.

One question, in case you have made yourself more familiar with the implementation: rendering the test on this branch yields
image
(which is actually much better than what we had before), but as you can see the position of the y-axis labels still is a bit odd -- see https://github.com/ManimCommunity/manim/blob/main/tests/test_graphical_units/img_svg_resources/multiple_transforms.svg for the file and for how it should actually look like.

Given that this PR improves the behavior nonetheless I'm certainly willing to simply merge it (I can regernerate the control data for you, no need to worry about that), but I'd be curious to hear any thoughts on the remaining positioning issue.

Again, thanks for taking your time and fixing this!

**Comment by behackl** [comment]
> I can regernerate the control data for you, no need to worry about that

Actually, it seems you have disabled maintainer commits on this PR, so I can't push the required changes myself; it'd be the checkbox in the image below.

image

Anyhow, if you'd like to fix it yourself, simply run `pytest --set_test tests/test_graphical_units/test_img_and_svg.py::test_MultipleTransform` from the repository root.

**Comment by TonyCrane** [comment]
I found the problem.
Notice here:
https://github.com/ManimCommunity/manim/blob/29028fa61dbfc6a51b6742b1970e092008527711/manim/mobject/svg/svg_mobject.py#L487

If the element only has one attribute x or y, then it will be ignored.
I fixed it, and this time it looks good:
image

**Comment by TonyCrane** [comment]
> > I can regernerate the control data for you, no need to worry about that
> 
> Actually, it seems you have disabled maintainer commits on this PR, so I can't push the required changes myself; it'd be the checkbox in the image below.
> 
> image
> 
> Anyhow, if you'd like to fix it yourself, simply run `pytest --set_test tests/test_graphical_units/test_img_and_svg.py::test_MultipleTransform` from the repository root.

image
That is enabled.

And when I ran the command, I got:
```text
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --no-cov-on-fail --cov=manim --cov-report --cov-report term -n auto --dist=loadfile tests/test_graphical_units/test_img_and_svg.py::test_MultipleTransform
  inifile: /Users/crane/Desktop/manim/manimce_pr/pyproject.toml
  rootdir: /Users/crane/Desktop/manim/manimce_pr
```

**Review by behackl — APPROVED** [review]
Thank you very much, again -- there is nothing left to say here. :-)

**Pull request merged**
