### PR TITLE
Add logging info to tex errors

### PR DESCRIPTION
**Pull request by NeoPlato**
## Changelog / Overview
Add information to tex errors.

## Motivation
This code is definitely leading up to a tex error:

```python
class WriteTex(Scene):
    def construct(self):
        tex = Tex("\\sqrt{3}")
        self.play(Write(tex))
        self.wait()
```

This is the information given on the error currently:

```bash
[05/07/21 15:00:25] ERROR    LaTeX compilation error! latex reports:                                     tex_file_writing.py:178
                    ERROR    ! Missing $ inserted.                                                       tex_file_writing.py:189

                    ERROR    <inserted text>                                                             tex_file_writing.py:189

                    ERROR                    $                                                           tex_file_writing.py:189

                    ERROR    l.27 \sqrt{                                                                 tex_file_writing.py:189
```

This is what it could look like:

```bash
[05/06/21 18:04:39] ERROR    LaTeX compilation error! LaTeX reports:
                    ERROR    Missing $ inserted.
                             Here is the tex content:

                             \begin{center}
                             \sqrt{3}
                             ^
                             \end{center}
```

More information on tex errors. That's the entire PR.

## Testing Status
As far as I can tell it can identify the location of basic errors like missing dollar signs. It probably works with more complicated examples but time will test the truth of that.

## Further Comments
If curious, attempt all sorts of errors and see the result.

## Quick note. 
This add-on will not magically give the user the information required to fix tex errors. The user needs some decent knowledge of Latex to fix the error, but this gives a kind of assist along that path. For example, in this case surrounding `\\sqrt{3}` with `$` signs or using the `align*` environment takes care of it, and that's clear from the information given.

## Checklist
- [ ] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [ ] I have written a descriptive PR title (see top of PR template for examples)
- [ ] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [x] The PR title is descriptive enough
- [x] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [x] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [x] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Review by naveen521kk — APPROVED** [review]
sgtm

**Comment by behackl** [comment]
I find it a bit odd that the entire environment in which the error occurs is printed. Most of the time this will include the center or align environment that is built hidden from the user, and personally I'd be somewhat confused by that if I ran into an error like that for the first time.

**Comment by behackl** [comment]
I don't want to stall this indefinitely (again), but would like to know what @cobordism and @PhilippImhof think about this change.

**Comment by PhilippImhof** [comment]
I am all in favour of adding this. Whatever helps people find their LaTeX errors is good. I see no downside.

**Review by PhilippImhof — APPROVED** [review]
SGTM

**Comment by cobordism** [comment]
I approve. Let's not let perfect be the enemy of good.
This is an improvement.

**Review by cobordism — APPROVED** [review]

**Pull request merged**
