### PR TITLE
OpenGL compatibility via metaclass: ValueTracker

### PR DESCRIPTION
**Pull request by charburgx**
## Changelog / Overview

Add OpenGL compatibility for ValueTracker through the ConvertToOpenGL metaclass and get/set_points,

[Documentation Reference](https://manimce--1589.org.readthedocs.build)

## Testing Status

Tested locally on Ubuntu 20.10.

## Further Comments

Originally part of #1577.

## Checklist
- [ ] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [ ] I have written a descriptive PR title (see top of PR template for examples)
- [ ] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Review by friedkeenan — APPROVED** [review]
LGTM, though I think it would also be appropriate to remove `OpenGLValueTracker` and such, particularly since they're currently broken.

**Review by TRoboto — COMMENTED** [review]
I agree with @friedkeenan, OpenGLValueTracker is broken and should be removed.

**Review by TRoboto — APPROVED** [review]
LGTM

**Review by behackl — APPROVED** [review]

**Comment by behackl** [comment]
Thank you for fixing the `ValueTracker` implementation!

**Pull request merged**
