### PR TITLE
Remove all Carriage Return characters in our files

### PR DESCRIPTION
**Pull request by cobordism**
## Motivation
I have been getting inexplicable diffs where it appears that a line was taken away and an identical line added.
The reason this happens is that most text editors mark the end of a line with a linefeed LF character, while a few (mostly on MS windows) mark it with a LF+CR. This CR is a carriage return character and is not needed anymore. It dates back to the days of mechanical printers and typewriters in which the linefeed pushes the paper up and the carriage return moves the typing/printing carriage to the left of the line.

## Explanation for Changes
I have removed all the carriage return characters in .py .rst. .toml and .yaml files.

## Testing Status
Nothing functional has changed. Everything should work exactly as before.

## Further Comments
Perhaps we can add to our CI a step of removing all CRs so that we have a canonical version of our files.

## Checklist
- [ ] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [x] My new functions/classes either have a docstring or are private
- [x] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [x] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by friedkeenan** [comment]
Some sort of check to make sure these characters don't get back into the codebase would be nice

**Comment by RickyC0626** [comment]
Perhaps add this to `.gitattributes`
```gitattributes
* text eol-lf
```

**Comment by naveen521kk** [comment]
Pre-commit should be having checks for things like this.

**Review by naveen521kk — APPROVED** [review]

**Review by jsonvillanueva — APPROVED** [review]
LGTM! Sorry about the issues with new files I made. I've changed `core.autocrlf=input` so hopefully that fixes stuff on my end. A CI option would be nice to look into as well.

**Pull request merged**
