### PR TITLE
Hide more private methods from the docs.

### PR DESCRIPTION
**Pull request by hydrobeam**
## Overview: What does this pull request change?

Made many methods private by prefixing them with `_`. Especially those annotated with `"Used Internally"`. Where applicable, public methods were moved to go after private methods. (Also wrote docs for `_pointify` 🤷).

Files affected:
- text_mobject.py
- tex_mobject.py
- code_mobject.py
- svg_mobject.py
- geometry.py
- matrix.py
- numbers.py
- three_dimensions.py

Also, removed `SVGPathMobject` from `__init__.py` to stop it from being imported by default since I couldn't think of a situation where it would be used outside of `svg_mobject.py`. 

The criteria for making a method private was: "Would it make sense for someone to use this?". And in most cases it was pretty clear. In the case of ambiguity I just opted to leave it in.

## Motivation and Explanation: Why and how do your changes improve the library?
While working on #2467, I noticed that there were many methods with "Used Internally" in their docstrings. To not clutter that PR, I decided to remove them in a separate one. I then began removing these methods from the rest of the library in the files that I was familiar with. I didn't touch `vmobject.py/mobject.py` even though they had some low hanging fruit via `generate_points`, since these would be undergoing big changes through the refactor.

Makes the docs much easier to read and parse.

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by GameDungeon** [comment]
I really like this, and wish we had done it more. When looking through the docs I commonly find the internal methods for things and not what I'm actually looking for.

**Review by Darylgolden — APPROVED** [review]
LGTM!

**Review by behackl — APPROVED** [review]
LGTM, thanks!

**Comment by hydrobeam** [comment]
Hmm, just realized that I only removed svg_path from the `__init__.py`, not the docs. I'll fix that soon

**Pull request merged**
