### PR TITLE
Matrix brackets

### PR DESCRIPTION
**Pull request by niklebedenko**
## Overview: What does this pull request change?

Improves how brackets look for the `Matrix` class.

## Motivation and Explanation: Why and how do your changes improve the library?

Before, the brackets looked warped vertically due to the use of `stretch_to_fit_height()`, which was particularly noticeable when using square brackets. Now, the `_add_brackets()` function uses LaTeX to create brackets which match the required height.

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by niklebedenko** [comment]
The VectorScene test fails due to the brackets being less warped than before - specifically, note how the tips of the old brackets are much thicker than the rest. The new brackets look much closer to what LaTeX would give natively (more uniform thickness), so imo the test should be changed to reflect this.

**Comment by behackl** [comment]
This looks good to me, thank you! Could you post the output of the updated `VectorScene` test here in a comment so that we can see the change visually ourselves, without having to checkout and render it locally? :-)

**Comment by niklebedenko** [comment]
**VectorScene**
Before:
image

After:
image

**With taller matrices**
Before:
Test_ManimCE_v0 15 2

After:
Test_ManimCE_v0 15 2

**Review by behackl — APPROVED** [review]
Much appreciated!

**Pull request merged**
