### PR TITLE
Refactored and deprecated a few functions in space_ops.py

### PR DESCRIPTION
**Pull request by Darylgolden**
## Changelog / Overview

- Rewrite `:func:get_norm` to directly use `np.linalg.norm`
- Rewrite `:func:cross` to directly use `np.cross`
- Rewrite `:func:norm_squared` to use a numpy dot product
- Rewrite `:func:angle_between_vectors` to use a more numerically stable method
- Deprecated `:func:angle_between` as it duplicates the functionality of `:func:angle_between_vectors` and isn't used anywhere

## Motivation
While rewriting `put_start_and_end_on` to work in 3D, I encountered weird numerical errors in `angle_between_vectors` which made working with almost (anti-)parallel vectors unreliable, with that function returning NaN pretty frequently. This PR rewrites that function to use a more numerically stable approach. I also rewrite some other functions to directly use the numpy result, rather than reinventing the wheel.

## Testing Status
Tests pass in CI.

## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by WampyCakes** [comment]
It's best if we deprecate `angle_between` before fully removing it.

**Comment by Darylgolden** [comment]
It seems like the changes in this branch cause the following scene to render non-deterministically, for some reason:
```py
class MovingVertices(ThreeDScene):
    def construct(self):
        self.set_camera_orientation(phi=75 * DEGREES, theta=30 * DEGREES)
        vertices = [1, 2, 3, 4]
        edges = [(1, 2), (2, 3), (3, 4), (1, 3), (1, 4)]
        g = Graph(vertices, edges)
        self.play(Create(g))
        self.wait()
```
I installed this branch on Colab and also got the non-deterministic errors, so it's not just my system.
I genuinely have no idea why this is the case, any ideas?

**Comment by eulertour** [comment]
At the point where some of the utility functions are only a single line it'd be better just to replace the call sites with the implementation.

**Comment by Darylgolden** [comment]
> 
> 
> At the point where some of the utility functions are only a single line it'd be better just to replace the call sites with the implementation.

I can do it, but is there general agreement for this?

**Comment by Darylgolden** [comment]
> 
> 
> It's best if we deprecate `angle_between` before fully removing it.

Done.

**Comment by behackl** [comment]
> > At the point where some of the utility functions are only a single line it'd be better just to replace the call sites with the implementation.
> 
> I can do it, but is there general agreement for this?

I strongly agree. Fewer functions to worry about regarding testing and documentation is an excellent idea. +1 for deprecating all of the functions that just directly call numpy in space_ops.

**Review by eulertour — APPROVED** [review]

**Comment by Darylgolden** [comment]
Should I do `import numpy as np` and call the functions like `np.cross` and `np.linalg.dot`? Or should I specifically import those functions (`from numpy import cross`, `from numpy.linalg` import dot)? I'm leaning towards the second, but I would like to know before I begin refactoring because there's a lot of places these functions are used and I don't know of an automated way to replace them (simple find and replace won't work because it doesn't automatically sort the imports).

**Comment by jsonvillanueva** [comment]
> 
> 
> Should I do `import numpy as np` and call the functions like `np.cross` and `np.linalg.dot`? Or should I specifically import those functions (`from numpy import cross`, `from numpy.linalg` import dot)? I'm leaning towards the second, but I would like to know before I begin refactoring because there's a lot of places these functions are used and I don't know of an automated way to replace them (simple find and replace won't work because it doesn't automatically sort the imports).

I'd prefer an explicit `import numpy as np` and usage of `np.X` in our library code as this will not introduce namespace/variable name conflicts. We may already have variables named `dot`/`cross`/`norm`/etc. in our library code and doing `from numpy.linalg import dot as dot_` doesn't seem like a good solution.

**Comment by Darylgolden** [comment]
I've deprecated `get_norm` and `cross`, which has resulted in a lot of changed files. I did not deprecate `norm_squared` because it's not immediately obvious that it should be replaced with the dot product of a vector with itself. This will potentially break a lot of PRs that use `get_norm` or `cross` in some way. I'm hoping this can get merged quickly to prevent the conflicts and deprecation workload to build up here.

**Review by jsonvillanueva — APPROVED** [review]

**Review by behackl — APPROVED** [review]

**Pull request merged**
