### PR TITLE
Added `get_polar_graph` method to `PolarPlane`

### PR DESCRIPTION
**Pull request by icedcoffeeee**
## Motivation and Explanation: Why and how do your changes improve the library?

[Relevant discord discussion](https://discord.com/channels/581738731934056449/662792187779612692/892343257764352010)
Code Used:
```py
class PolarGraphExample(Scene):
    def construct(self):
        plane = PolarPlane()
        r = lambda theta: 2 * np.sin(theta * 5)
        graph = plane.get_polar_graph(r, [0, 2 * PI], color=ORANGE)
        self.add(plane, graph)
```
Output:

PolarGraphExample_ManimCE_v0 10 0
## Links to added or changed documentation pages

[Documentation](https://manimce--2157.org.readthedocs.build/en/2157/reference/manim.mobject.coordinate_systems.CoordinateSystem.html#manim.mobject.coordinate_systems.CoordinateSystem.get_polar_graph)

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by Darylgolden** [comment]
Why not add this method to `CoordinateSystem` so that it can be used by other classes? In fact, why not add a `PolarFunction` class and call it, just like how explicit and implicit graphing is implemented?

**Comment by icedcoffeeee** [comment]
@Darylgolden 
> add this method to CoordinateSystem

If i were to do that, methods like `polar_to_point` and `point_to_polar` would also need to be ported over to `CoordinateSystem`, which is not a bad idea.

>add a PolarFunction class

My reference in this implementation is `.get_graph` which also utilizes `ParametricFunction` and not `FunctionGraph`. 🤔

**Comment by PhotonSpheres** [comment]
I don't have anything against a general PolarFunction class, but I like the idea of having a get_polar_graph method here analogous to get_graph.

**Review by behackl — APPROVED** [review]
LGTM!

**Review by PhotonSpheres — APPROVED** [review]
Yip, LGTM! Cheers again!

**Pull request merged**
