### PR TITLE
Fix the problem of self.chars index in class Paragraph

### PR DESCRIPTION
**Pull request by shnovaj30101**
## Motivation and Explanation: Why and how do your changes improve the library?

I wanted to define a instance of class Paragraph `code` whose content is a simple code, and then use a SurroundingRectangle instance `rect` to enclose it, and then move the rectangle line by line. 

The following is a pseudo code:

```
code_raw_text = '''
layer_threshold = int(input())
layer_count = 1
num_count = 1
while layer_count <= layer_threshold:
    print_num = 2 * layer_count - 1
    blank_num = layer_threshold - layer_count
    for i in range(blank_num):
        print("    ", end = '')
    for i in range(print_num):
        print(str(num_count).ljust(4), end = '')
        num_count += 1
    print('')
    layer_count += 1
'''

text_list = code_raw_text.strip().split('\n')
code = Paragraph(*text_list, line_spacing=1)

rect = SurroundingRectangle(code.chars[0], buff = .1)
next_rect = SurroundingRectangle(code.chars[1], buff = .1)
self.play(ReplacementTransform(rect, next_rect))
```

But I found that the rectangle always enclosed the wrong code:

https://user-images.githubusercontent.com/12492724/130363972-8cef193a-f60f-4624-b9c2-55541ecc56a7.mp4

Then I found it was because that `code.chars[0]` and `code.chars[1]` were VGroups including the wrong  characters:

code.chars[0]:
Expectedly: `layer_threshold = int(input())`
Actually: `layer_threshold = int(input())\nla`

code.chars[1]:
Expectedly: `layer_count = 1`
Actually: `yer_count = 1\nnum_`

Both they contained the characters of the next lines.

After some research I found that `self.lines_text.chars` in class Paragraph did not include the blank characters, but the method `gen_chars` in class Paragraph did not notice that when constructing `chars`. 

The following code was in manim/manim/mobject/svg/text_mobject.py:

```
    def gen_chars(self, lines_str_list):
        ......
        for line_no in range(lines_str_list.__len__()):
            chars.add(self.get_group_class()())
            chars[line_no].add(
                *self.lines_text.chars[
                    char_index_counter : char_index_counter
                    + lines_str_list[line_no].__len__()   ====> lines_str_list contained blank characters
                    + 1                                   ====> but self.lines_text.chars did not contain blank characters
                ]
            )
            char_index_counter += lines_str_list[line_no].__len__() + 1
        return chars
```

So I removed the blank characters of lines_str_list when constructing chars:

```
    def gen_chars(self, lines_str_list):
        .......
        for line_no in range(lines_str_list.__len__()):
            chars.add(self.get_group_class()())
            chars[line_no].add(
                *self.lines_text.chars[
                    char_index_counter : char_index_counter
                    + re.sub(r"\s+", "", lines_str_list[line_no]).__len__()
                ]
            )
            char_index_counter += re.sub(r"\s+", "", lines_str_list[line_no]).__len__()
        return chars
```

The outcome after updating code:

https://user-images.githubusercontent.com/12492724/130364019-342ccda2-d6ea-41f0-ab33-d87c32b4039d.mp4

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Review by hydrobeam — COMMENTED** [review]
Thanks for the PR(and the detailed explanation)! I've tested the changes and it does seem to work as expected for `Paragraph` mobjects. However, it seems to break the colouring of `Code` and introduces some weird indexing:

SurroundingRectangle around `rendered_code.code.chars[1]`.
cmh_ManimCE_v0 9 0

```py
class cmh(Scene):
    def construct(self):
        code = '''from manim import Scene, Square

class FadeInSquare(Scene):
    def construct(self):
        s = Square()
        self.play(FadeIn(s))
        self.play(s.animate.scale(2))
        self.wait()
'''
        rendered_code = Code(code=code, tab_width=4, background="window",
                            language="Python", font="Monospace")
        self.add(rendered_code)
        sur = SurroundingRectangle
        self.add(SurroundingRectangle(rendered_code.code.chars[1]))
```

How it normally looks:

image

**Comment by Darylgolden** [comment]
I think it would also be good to add a graphical unit test for this.

**Review by behackl — CHANGES_REQUESTED** [review]
This cannot be merged until the problem described by @hydrobeam has been resolved.

**Comment by behackl** [comment]
Closing due to inactivity.

**Pull request closed without merging**
