### PR TITLE
Fixed :meth:`.ThreeDCamera.remove_fixed_orientation_mobjects`

### PR DESCRIPTION
**Pull request by Viicos**
`self.fixed_orientation_mobjects` is a dictionnary, not a set as it is for `self.fixed_in_frame_mobjects`.

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Review by Darylgolden — CHANGES_REQUESTED** [review]
Hi, thank you for your PR! Can you add a test for this change? (test that the method removes a fixed orientation mobject)

**Comment by behackl** [comment]
I have added a test.

**Comment by Viicos** [comment]
Sorry forgot to get back on this issue. Thanks @behackl!

**Review by Darylgolden — APPROVED** [review]
LGTM!

**Pull request merged**
