### PR TITLE
#Update readme so that it does not throw error in PyCharm

### PR DESCRIPTION
**Pull request by kolibril13**
Hi, my IDE looks like this:
Screenshot from 2020-05-31 11-23-28
and I found no way to get rid of the red sonar lid.
I don't know if this happens to you as well, but for me this is quit annoying, so I applied the changes the ide suggested to me.

### CODE REVIEW

**Comment by PgBiel** [comment]
I don't think I understood the purpose of this

**Comment by leotrs** [comment]
Can you please explain what is the purpose of `IGNORE-PREVIOUS` anchor? It seems unlikely that it will only change the behavior on your IDE. I must be changing the resulting page as well, no?

**Comment by PgBiel** [comment]
Closing this PR. If you think this still deserves some light, make sure to talk to us about this in Discord or here if you want.

**Comment by kolibril13** [comment]
Hi, sorry for not responding. 
My ide has a problem with this:
Screenshot from 2020-06-03 12-22-10
It saies "Anchor reference "ffmpeg-installation-1" is not resolved.
I see this error every time I fetch the newest master, so it would be cool to find a way to not get the red sonar lid in my project-folder.

**Comment by PgBiel** [comment]
The reference is resolved because there are multiple sections with the name `Cairo installation`, `FFMPEG installation` etc, so GitHub numbers them. It seems the IDE is not doing that, so it's not parsing the references. In that case, just find a way to have your IDE ignore the file.

**Comment by kolibril13** [comment]
ok

**Comment by leotrs** [comment]
If/when this has been settled, please delete the branch @kolibril13

**Pull request closed without merging**
