### PR TITLE
Specify Black Version

### PR DESCRIPTION
**Pull request by naveen521kk**
- Make the tests Pass

### CODE REVIEW

**Comment by huguesdevimeux** [comment]
Sorry, I missed something. Why don't we keep black up to date?

**Review by kolibril13 — APPROVED** [review]

**Comment by leotrs** [comment]
I have the same question as @huguesdevimeux

**Comment by naveen521kk** [comment]
> I have the same question

I really don't know how to answer those question. As black is in beta stage this would be the best option for now. Maybe later once black becomes stable we shall keep it to latest version. Or we would have to change the codebase for each new version of black and spoils `git blame`.

**Comment by leotrs** [comment]
It being in beta is actually a good reason. Alternatively, we can try to see what changed that made all our checks break. I think they may have changed the default line width. If that's all there is, we can just set a hard default and continue to use the new version.

**Comment by leotrs** [comment]
Ok I think I found the reason. As you can see in black's [changelog](https://github.com/psf/black/blob/master/CHANGES.md).
```
re-implemented support for explicit trailing commas: now it works consistently within any bracket pair, including nested structures (#1288 and duplicates)
```
This means that now black will reformat _every single bracket pair that contains elements with a trailing comma_. So if you run the latest version of black, you will see that it is converting this chunk
```python
             self.put_start_and_end_on(
                 self.get_start(), tip.get_base(),
             )
```
into this chunk
```python
             self.put_start_and_end_on(
                 self.get_start(),
                 tip.get_base(),
             )
```
And that is because of the trailing comma. For example, this code
```python
             self.put_start_and_end_on(
                 self.get_start(), tip.get_base()
             )
```
does not get converted, because there is no trailing comma.

So most of the diffs we are seeing since the black version upgraded are because of this. So we have a few paths forward:

1. Fix the version to the previous version. I don't think this is the right thing to do, as we will be missing out on any bug fixes and new features, and someone will have to remember to upgrade black every once in a while.
2. Run the new version on the whole codebase and just commit the changes.
3. Remember to upgrade black on our local computers so that the trailing commas are dealt with one file at a time.
4. Go through the codebase and eliminate those pesky trailing commas at once.
5. Uninstall black altogether.

Remember, the black documentation says `By using [black], you agree to cede control over minutiae of hand-formatting`. So I think we either cede total control (which is either of the options 2 or 3), or we uninstall it and look for a different solution (option 5).

**Comment by naveen521kk** [comment]
Maybe let's set up a GitHub Action to upgrade to latest version of black and also makes a PR when the new version, by formatting the code.

**Comment by naveen521kk** [comment]
Also, here #165 gonna help us. We can specify the black version there and say users to do `poetry run black .` so we can maintain consistency.(It creates a virtual environment).

**Comment by huguesdevimeux** [comment]
> Maybe let's set up a GitHub Action to upgrade to latest version of black and also makes a PR when the new version, by formatting the code.

Yes, this seems good to me, along with 

> Honestly, I think the fix is to just ask everyone to upgrade their local black and enforce running it before submitting a PR.

No need to specify a version of black, let's keep it updated :D

**Comment by naveen521kk** [comment]
Closing this in favour of discussion.

**Comment by leotrs** [comment]
We have five alternatives as mentioned in an earlier comment, and it'd be great to reach a consensus soon! The failing black checks are starting to get annoying (see #385).

**Comment by naveen521kk** [comment]
Just saying I am working on a GitHub Action which does this. So it's better to wait. As in the git blam it would be named `github-action` and not anybody's name.

**Comment by leotrs** [comment]
@naveen521kk How exactly will that work? Will it push black's edits immediately to the repo? Also, should we just let all black checks fail until that's done?

**Comment by naveen521kk** [comment]
> Will it push black's edits immediately to the repo?

It will create a branch and then a PR. 

> Also, should we just let all black checks fail until that's done?

I will do it in a day or two.

**Comment by leotrs** [comment]
Hmmm how often will it open a branch and PR? Because we were trying with the restyled bot which did the same thing after _each PR_ and most of us found it really annoying...

**Comment by naveen521kk** [comment]
@leotrs You can check #396 . It doesn't actually check for a PR. It just checks for master daily and if it fails it will make an PR.

**Comment by leotrs** [comment]
Ok great. Once a day sounds a lot better. Thanks.

**Comment by leotrs** [comment]
Ok so after trying a bot, and a GH action, and after having BIG RED black checks on all PRs for a few days, it seems that the best way to enforce this is to ask all devs to always run the latest version of `black` before submitting a PR. That's it.

Devs, please do not merge PRs with a red `black` check.

**Pull request closed without merging**
