### PR TITLE
Fixed :class:`~.ShowIncreasingSubsets`, :class:`~.ShowSubmobjectsOneByOne`, and :class:`~.AddTextLetterByLetter`

### LINKED ISSUE #1221: Seemingly broken creation animations
## Description of bug / unexpected behavior
It seems to me that the following animations are broken. Rather than doing what the class name suggests, they all just add the mobjects passed to them to the scene.

- `AddIncreasingSubsets`
- `AddTextLetterByLetter`
- `ShowSubmobjectsOneByOne`
- `AddTextWordByWord` - this one is known to be broken per the comment in manim's code

Likely, `AddIncreasingSubsets` is broken and caused the others to break.

## Additional comments
It's _possible_ that I am trying to use these wrong, but I'm 90% sure that isn't the case. It would be helpful if someone could confirm that they're broken.

### PR DESCRIPTION
**Pull request by behackl**
## Changelog / Overview

At some point, the refactors to `play` (and the fact that the mobject associated to an animation at initialization time is automatically added to a scene -- `add_mobjects_from_animations`) broke the implementation of `ShowIncreasingSubsets` and `ShowSubmobjectsOneByOne`.

In this PR, an alternative implementation is proposed.

## Motivation
Animations are currently broken.

## Explanation for Changes

Example:
```py
class IncreasingSubsetsEx(Scene):
    def construct(self):
        t = Text("this is a test :-)")
        self.play(ShowIncreasingSubsets(t))
        self.wait()
```
renders as

https://user-images.githubusercontent.com/11851593/113358094-6b783a80-9345-11eb-9bc9-f26c65637b43.mp4

## Testing Status

Tried the example above for `ShowIncreasingSubsets` and `ShowSubmobjectsOneByOne`, looks good to me in general.

## Further Comments

Fixes #1221.

## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [x] My new functions/classes either have a docstring or are private
- [x] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Review by WampyCakes — CHANGES_REQUESTED** [review]
It would be helpful for me if you kept `self.all_submobs` around and referenced that instead of changing all the occurrences of it. [You can see here](https://github.com/ManimCommunity/manim/pull/1222/files#diff-d25310d24cec2b3c27fb7720e6ace43f65738b39564107b3b7ae83272d5f5a3bR409) where that will come into play as we start to accept more than one mobject to animations (assuming that PR gets merged). Otherwise, this fixes the animations for me and looks good. Seems like a really good fix to rush into v0.5.0.

**Comment by WampyCakes** [comment]
I'll open a new issue regarding the still broken `AddTextWordByWord` since this closes the other issue.

**Comment by behackl** [comment]
> It would be helpful for me if you kept `self.all_submobs` around and referenced that instead of changing all the occurrences of it. [You can see here](https://github.com/ManimCommunity/manim/pull/1222/files#diff-d25310d24cec2b3c27fb7720e6ace43f65738b39564107b3b7ae83272d5f5a3bR409) where that will come into play as we start to accept more than one mobject to animations (assuming that PR gets merged). Otherwise, this fixes the animations for me and looks good. Seems like a really good fix to rush into v0.5.0.

I don't particularly like the identifier name `all_submobs`, but I'll comply for now. We can refactor it at a later point.

96c6f1d1 should have brought it back.

**Review by WampyCakes — APPROVED** [review]
Looks good now. I see now that this animation is working that even passing a Group of Texts breaks these animations. It's unfortunate that these won't natively accept groups, but I can work on that in #1222 since it would be best to get these fixes into `v0.5.0`.

What would you like `all_submobs` renamed to? I can rename that in #1222 as well.

**Comment by behackl** [comment]
> that even passing a Group of Texts breaks these animations

I'm not sure I follow. What is broken for groups? The behavior that this (currently) doesn't recurse into all of the submobject's submobjects is, as far as I can tell, intended.

(It might make sense to change the implementation, though.)

**Comment by WampyCakes** [comment]
I just mean that this won't work. It adds them both to the scene immediately. This may be intended, but I was under the naive impression that all animations in manim would work on a group.
```py
class Test(Scene):
    def construct(self):
        t = Text("this is a test :-)")
        t2 = Text("this is another test").shift(UP)
        self.play(AddTextLetterByLetter(Group(t, t2)))
        self.wait()
```

**Comment by behackl** [comment]
> I just mean that this won't work. It adds them both to the scene immediately. This may be intended, but I was under the naive impression that all animations in manim would work on a group.
> 
> ```python
> class Test(Scene):
>     def construct(self):
>         t = Text("this is a test :-)")
>         t2 = Text("this is another test").shift(UP)
>         self.play(AddTextLetterByLetter(Group(t, t2)))
>         self.wait()
> ```

It works for me though; there is a *very* short moment without anything in the scene, then just the first line, and then the second line.

**Comment by WampyCakes** [comment]
Indeed. It works as expected with the current implementation. In the future, `AddTextLetterByLetter` should if check the mobject type is a group and if so venture into the next level of submobjects to work on the actual text. Otherwise it doesn't do what the class name suggests. That's all I was saying

**Comment by behackl** [comment]
> Indeed. It works as expected with the current implementation. In the future, `AddTextLetterByLetter` should if check the mobject type is a group and if so venture into the next level of submobjects to work on the actual text. Otherwise it doesn't do what the class name suggests. That's all I was saying

I fully agree!

I think it would be worthwhile to go over all of the currently implemented animations and clean them up a bit. There is a lot of confusing stuff in there. 😵

**Comment by behackl** [comment]
Nice, the excellent illustration in https://manimce--1224.org.readthedocs.build/en/1224/reference/manim.animation.creation.html#module-manim.animation.creation is not broken any longer. Merging this.

**Pull request merged**
