### PR TITLE
Bugfix: make Scene.add_sound work again (when running with --disable_caching)

### LINKED ISSUE #902: Sound in manimce
I want to add sound to my video in manimce like manim by 3b1b 

I use the following code -: 

`self.add_sound(" sound file name in assets folder", gain = value)`

But it's giving an error in manimce

I think there will be some other syntax in manimce.

Please resolve this!!

### PR DESCRIPTION
**Pull request by behackl**
## Motivation
`Scene.add_sound` is currently broken.

## Overview / Explanation for Changes

The reference to `self.time` has to be changed to `self.renderer.time`. Closes #902, #816.

## Oneline Summary of Changes

```
- Bugfix: make Scene.add_sound work again when running with --disable_caching (:pr:`PR NUMBER HERE`)
```

## Testing Status

Tested this change locally, and it works. We don't have a sample audio file in the library to test this with, so I can't really add a unit test for it.

## Further Comments
See https://github.com/ManimCommunity/manim/issues/851#issuecomment-748120731 for an excellent and very thorough report on the problems of `add_sound` without `--disable_caching`.

## Acknowledgements
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)

## Reviewer Checklist
- [x] Newly added functions/classes are either private or have a docstring
- [x] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [x] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings
- [ ] The oneline summary has been included [in the wiki](https://github.com/ManimCommunity/manim/wiki/Changelog-for-next-release)

### CODE REVIEW

**Review by leotrs — COMMENTED** [review]
This was fixed at some point but I guess it was reverted - can we add a quick test please?

**Comment by behackl** [comment]
> This was fixed at some point but I guess it was reverted - can we add a quick test please?

How?

**Comment by leotrs** [comment]
I'd go with the first one.

**Comment by behackl** [comment]
I've pushed a test making sure that calling `Scene.add_sound` doesn't raise an exception.

**Review by leotrs — APPROVED** [review]
Thanks!

**Comment by kolibril13** [comment]
Nice!
I think it would be nice to have an example as well in the docs.
https://docs.manim.community/en/latest/reference/manim.scene.scene.Scene.html?highlight=add_sound#manim.scene.scene.Scene.add_sound
There, I'd say we include a free sound sample, e.g. this one:
https://freesound.org/people/Druminfected/sounds/250551/ (it is Creative Commons 0 License.) and its only 0.6 seconds/ 103.6 KB so it still keeps the repo small.

**Comment by behackl** [comment]
I'd like to keep this PR about making sure `add_sound` doesn't raise an error and suggest to do documentation in a separate commit. We could also add a warning describing the currently existing problems as reported in #851.

**Comment by clarfonthey** [comment]
Is there anything in particular that needs to be done before this is merged? On 0.2.0 add_sound is broken and it would be nice to have it fixed.

**Comment by behackl** [comment]
I don't think that there is anything left to do here. If there are no further change requests for this PR, I'll merge it in a day or two -- except if there is another approval, then it can be merged sooner.

**Comment by kolibril13** [comment]
I just tested this with this script:

```py
class ABC(Scene):
    def construct(self):
        dot = Dot().set_color(GREEN)
        self.add(dot)
        self.wait(1)
        self.add_sound("click.wav")
        dot.set_color(BLUE)
        self.wait()
```
and it is working when rendering the video.

**Review by leotrs — APPROVED** [review]

**Review by kolibril13 — APPROVED** [review]

**Comment by leotrs** [comment]
I just approved. @behackl are we still doing the oneline on the wiki thing?

**Pull request merged**
