### PR TITLE
Improved VectorField's Nudge Accuracy Per Step

### PR DESCRIPTION
**Pull request by PaulCMurdoch**
## Changelog / Overview

Implemented the Runge-Kutta algorithm in VectorField's nudge function. This increases the accuracy as an object moves along a vector field. This also increases efficentcy as the nudge function requires less loops to achieve accuracy than the previous implementation.

## Motivation

The changes increase the accuracy per step of the VectorField's nudge function. This increases the accuracy of the path along the vector field while decreasing the number of loops needed.
## Explanation for Changes

The Runge-Kutta algorithm implementation provides increased accuracy per step for the vector field.

[Documentation Reference](https://manimce--1562.org.readthedocs.build)

## Testing Status

Performed on a Pixelbook Linux terminal.
A visual test comes from modifying the example code for nudge. After 15 seconds the circle and dot should return to their initial positions. This forms a circle that overlaps with the one on screen with a dot in the center.
The code used:
```py
from manim import *
class Nudging(Scene):
    def construct(self):
        func = lambda pos: np.sin(pos[1]/2)*RIGHT+np.cos(pos[0]/2)*UP
        vector_field = ArrowVectorField(func, delta_x=1, delta_y=1, length_func=lambda x:x/2)
        self.add(vector_field)
        circle = Circle(radius=2).shift(LEFT)
        self.add(circle.copy().set_color(GRAY))
        dot = Dot().move_to(circle)
           
        vector_field.nudge(circle, -30, 100, True)
        vector_field.nudge(dot, -30, 100)

        circle.add_updater(vector_field.get_nudge_updater(speed=2,pointwise=True))
        dot.add_updater(vector_field.get_nudge_updater(speed=2))
        self.add(circle, dot)
        self.wait(18)

```
Note in the manim6 version they do not form the original circle.
Manim6
Note in the new version they do form the original circle.
New

## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [x] My new functions/classes either have a docstring or are private
- [x] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [x] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by PaulCMurdoch** [comment]
Sorry for any confusion I was having trouble fixing the error from before so I decided to start the pull request from scratch. I implemented the suggested change to make runge_kutta a single function. For some reason there is still a byte file that was changed.

**Review by Darylgolden — APPROVED** [review]
LGTM

**Review by GameDungeon — APPROVED** [review]
LGYM, Good job on your first pull :)

**Comment by PaulCMurdoch** [comment]
Thank you very much.

**Review by naveen521kk — APPROVED** [review]
sgtm

**Review by behackl — APPROVED** [review]
Thank you very much for this, LGTM!

Something to discuss internally: I think it would be a good idea to encourage people to include references when implementing algorithms from the literature. Maybe we should introduce a new docstring section for that. (Not for this PR though.)

**Pull request merged**
