### PR TITLE
Reuse shader wrappers and shader data

### PR DESCRIPTION
**Pull request by ryanmccauley211**
## Motivation and Explanation: Why and how do your changes improve the library?

Currently everytime we call get `get_fill_shader_wrapper` or `get_stroke_shader_wrapper` it creates new objects so this will happen for each frame when rendering. This allows them to be reused and updated instead of creating a new object each time.

This PR also uses `init_shader_data` which wasn't being used before an reuses `self.fill_data` and `self.stroke_data`. It seems to have some small performance improvements, but the performance fluctuates so much it is difficult to tell.

## Further Information and Comments

**Benchmarks**

I ran the following scenes and checked elapsed time with timeit, in all cases preview was disabled, quality was low and caching disabled. I ran 5 times for each scenario and took the average time.

```py
class SineCurveUnitCircle(Scene):
    # contributed by heejin_park, https://infograph.tistory.com/230
    def construct(self):
        start = timer()
        self.show_axis()
        self.show_circle()
        self.move_dot_and_draw_curve()
        self.wait()
        end = timer()
        print(end - start)  # Time in seconds, e.g. 5.38091952400282

    def show_axis(self):
        x_start = np.array([-6,0,0])
        x_end = np.array([6,0,0])

        y_start = np.array([-4,-2,0])
        y_end = np.array([-4,2,0])

        x_axis = Line(x_start, x_end)
        y_axis = Line(y_start, y_end)

        self.add(x_axis, y_axis)
        self.add_x_labels()

        self.origin_point = np.array([-4,0,0])
        self.curve_start = np.array([-3,0,0])

    def add_x_labels(self):
        x_labels = [
            MathTex("\pi"), MathTex("2 \pi"),
            MathTex("3 \pi"), MathTex("4 \pi"),
        ]

        for i in range(len(x_labels)):
            x_labels[i].next_to(np.array([-1 + 2*i, 0, 0]), DOWN)
            self.add(x_labels[i])

    def show_circle(self):
        circle = Circle(radius=1)
        circle.move_to(self.origin_point)
        self.add(circle)
        self.circle = circle

    def move_dot_and_draw_curve(self):
        orbit = self.circle
        origin_point = self.origin_point

        dot = Dot(radius=0.08, color=YELLOW)
        dot.move_to(orbit.point_from_proportion(0))
        self.t_offset = 0
        rate = 0.25

        def go_around_circle(mob, dt):
            self.t_offset += (dt * rate)
            # print(self.t_offset)
            mob.move_to(orbit.point_from_proportion(self.t_offset % 1))

        def get_line_to_circle():
            return Line(origin_point, dot.get_center(), color=BLUE)

        def get_line_to_curve():
            x = self.curve_start[0] + self.t_offset * 4
            y = dot.get_center()[1]
            return Line(dot.get_center(), np.array([x,y,0]), color=YELLOW_A, stroke_width=2 )


        self.curve = VGroup()
        self.curve.add(Line(self.curve_start,self.curve_start))
        def get_curve():
            last_line = self.curve[-1]
            x = self.curve_start[0] + self.t_offset * 4
            y = dot.get_center()[1]
            new_line = Line(last_line.get_end(),np.array([x,y,0]), color=YELLOW_D)
            self.curve.add(new_line)

            return self.curve

        dot.add_updater(go_around_circle)

        origin_to_circle_line = always_redraw(get_line_to_circle)
        dot_to_curve_line = always_redraw(get_line_to_curve)
        sine_curve_line = always_redraw(get_curve)

        self.add(dot)
        self.add(orbit, origin_to_circle_line, dot_to_curve_line, sine_curve_line)
        self.wait(8.5)

        dot.remove_updater(go_around_circle)
```

|| Opengl Current | Opengl Reusing objects | Cairo | 
|----| ---------- | ------------- | ------------- | 
|**Elapsed time in seconds**|  5.77 | 5.09  | 4.01 |

The below scene can be ran with cairo or opengl, however using `Point` for opengl uses compatibility mode, it adds around 0.05 seconds, so is still faster than cairo, however for these benchmarks I changed `Point` to `OpenGLPMPoint` as this is how opengl will actually be used when cairo is deprecated. This uses a much simpler shader than the one used in the previous example which I think is why it is faster than cairo, so for bigger performance gains reworking the shaders might be the best approach.

```py
class PMPointExample(Scene):
    def construct(self):
        start = timer()
        colorList = [RED, GREEN, BLUE, YELLOW]
        for i in range(200):
            point = Point(location=[0.63 * np.random.randint(-4, 4), 0.37 * np.random.randint(-4, 4), 0],
                                  color=np.random.choice(colorList))
            self.add(point)
        for i in range(200):
            point = Point(location=[0.37 * np.random.randint(-4, 4), 0.63 * np.random.randint(-4, 4), 0],
                                  color=np.random.choice(colorList))
            self.add(point)
        self.add(point)
        end = timer()
        print(end - start)
```

|| Opengl Current | Opengl Reusing objects | Cairo | 
|-----| ---------- | ------------- | ------------- | 
**Elapsed time in seconds**|  0.19 | 0.17  | 0.34 |

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by hydrobeam** [comment]
Could you share some scenes that you've used as a benchmark?

**Comment by ryanmccauley211** [comment]
> Could you share some scenes that you've used as a benchmark?

Sure, added some scenes and benchmarks

**Review by GameDungeon — APPROVED** [review]
This looks great :)

**Comment by Darylgolden** [comment]
Sorry for the very long wait, can you fix the merge conflicts?

**Comment by ryanmccauley211** [comment]
> Sorry for the very long wait, can you fix the merge conflicts?

Done!

**Comment by Darylgolden** [comment]
With the following scene:
```py
from manim import *

# prepare animations for the arrows
def get_anim(Grid, angle, WHITE=True):
    anim_group = []
    for i in range(len(Grid)):
        for j in range(len(Grid[0])):
            anim_group.append(
                Rotate(Grid[i][j], angle=angle, about_point=Grid[i][j].get_center())
            )
    return anim_group


# Change the group accordingly after each iteration
def prepare_group(Grid, angle):
    for i in range(len(Grid)):
        for j in range(len(Grid[0])):
            Grid[i][j].rotate(angle)
    return Grid


class Illusion(Scene):
    def construct(self):
        a = 0.1  # side length of square

        Right_isoceles = Polygram(
            [[-a, 0, 0], [0, a, 0], [a, 0, 0]],
            stroke_width=0,
        )

        Rectangle = Polygram(
            [
                [-a / 2, 0.01, 0],
                [a / 2, 0.01, 0],  # the 0.01 for floating point madness
                [a / 2, -a, 0],
                [-a / 2, -a, 0],
            ],
            stroke_width=0,
        )

        base_white = VGroup(Right_isoceles, Rectangle).set_fill(WHITE, 1)
        base_black = base_white.copy().set_fill(BLACK, 1)
        base_white.shift(
            config["frame_width"] / 2 * LEFT + config["frame_height"] / 2 * DOWN
        )
        base_black.shift(
            (config["frame_width"] / 2 - base_black.width / 2) * LEFT
            + (config["frame_height"] / 2 - base_black.height / 2) * DOWN
        )

        a_row_white = VGroup(
            *[
                base_white.copy().shift(base_white.width * n * RIGHT)
                for n in range(int(config["frame_width"] / base_white.width) + 2)
            ]
        )

        a_row_black = VGroup(
            *[
                base_black.copy().shift(base_black.width * n * RIGHT)
                for n in range(int(config["frame_width"] / base_black.width) + 2)
            ]
        )

        Grid_white = VGroup(
            *[
                a_row_white.copy().shift(UP * i * base_white.height)
                if i % 2 == 0
                else a_row_white.copy().shift(
                    UP * i * base_white.height + LEFT * base_white.width
                )
                for i in range(int(config["frame_height"] / base_white.height) + 1)
            ]
        )

        Grid_black = VGroup(
            *[
                a_row_black.copy().shift(UP * i * base_black.height)
                if i % 2 == 0
                else a_row_black.copy().shift(
                    UP * i * base_black.height + LEFT * base_black.width
                )
                for i in range(int(config["frame_height"] / base_black.height) + 1)
            ]
        )

        prepare_group(
            Grid_black, -PI
        )  # because I haven't constructed the grid properly

        self.play(AnimationGroup(*get_anim(Grid_white, PI / 2)), lag_ratio=0.00)
        self.add(prepare_group(Grid_black, PI / 2))
        self.camera.background_color = WHITE
        self.play(AnimationGroup(*get_anim(Grid_black, PI / 2)), lag_ratio=0.00)
        self.camera.background_color = BLACK
        self.add(prepare_group(Grid_white, PI / 2))


with tempconfig({"quality" : "medium_quality", "disable_caching": True, "renderer": "opengl"}):
    scene = Illusion()
    scene.render()
```

Before this PR:
before2062full

before2062render

After this PR:
after2062full

after2062render

There is definitely an improvement, but it still seems to spend an awful lot of time getting shader wrappers. Do you happen to know how to optimize them out completely?

**Comment by ryanmccauley211** [comment]
> With the following scene:
> 
> ```python
> from manim import *
> 
> # prepare animations for the arrows
> def get_anim(Grid, angle, WHITE=True):
>     anim_group = []
>     for i in range(len(Grid)):
>         for j in range(len(Grid[0])):
>             anim_group.append(
>                 Rotate(Grid[i][j], angle=angle, about_point=Grid[i][j].get_center())
>             )
>     return anim_group
> 
> 
> # Change the group accordingly after each iteration
> def prepare_group(Grid, angle):
>     for i in range(len(Grid)):
>         for j in range(len(Grid[0])):
>             Grid[i][j].rotate(angle)
>     return Grid
> 
> 
> class Illusion(Scene):
>     def construct(self):
>         a = 0.1  # side length of square
> 
>         Right_isoceles = Polygram(
>             [[-a, 0, 0], [0, a, 0], [a, 0, 0]],
>             stroke_width=0,
>         )
> 
>         Rectangle = Polygram(
>             [
>                 [-a / 2, 0.01, 0],
>                 [a / 2, 0.01, 0],  # the 0.01 for floating point madness
>                 [a / 2, -a, 0],
>                 [-a / 2, -a, 0],
>             ],
>             stroke_width=0,
>         )
> 
>         base_white = VGroup(Right_isoceles, Rectangle).set_fill(WHITE, 1)
>         base_black = base_white.copy().set_fill(BLACK, 1)
>         base_white.shift(
>             config["frame_width"] / 2 * LEFT + config["frame_height"] / 2 * DOWN
>         )
>         base_black.shift(
>             (config["frame_width"] / 2 - base_black.width / 2) * LEFT
>             + (config["frame_height"] / 2 - base_black.height / 2) * DOWN
>         )
> 
>         a_row_white = VGroup(
>             *[
>                 base_white.copy().shift(base_white.width * n * RIGHT)
>                 for n in range(int(config["frame_width"] / base_white.width) + 2)
>             ]
>         )
> 
>         a_row_black = VGroup(
>             *[
>                 base_black.copy().shift(base_black.width * n * RIGHT)
>                 for n in range(int(config["frame_width"] / base_black.width) + 2)
>             ]
>         )
> 
>         Grid_white = VGroup(
>             *[
>                 a_row_white.copy().shift(UP * i * base_white.height)
>                 if i % 2 == 0
>                 else a_row_white.copy().shift(
>                     UP * i * base_white.height + LEFT * base_white.width
>                 )
>                 for i in range(int(config["frame_height"] / base_white.height) + 1)
>             ]
>         )
> 
>         Grid_black = VGroup(
>             *[
>                 a_row_black.copy().shift(UP * i * base_black.height)
>                 if i % 2 == 0
>                 else a_row_black.copy().shift(
>                     UP * i * base_black.height + LEFT * base_black.width
>                 )
>                 for i in range(int(config["frame_height"] / base_black.height) + 1)
>             ]
>         )
> 
>         prepare_group(
>             Grid_black, -PI
>         )  # because I haven't constructed the grid properly
> 
>         self.play(AnimationGroup(*get_anim(Grid_white, PI / 2)), lag_ratio=0.00)
>         self.add(prepare_group(Grid_black, PI / 2))
>         self.camera.background_color = WHITE
>         self.play(AnimationGroup(*get_anim(Grid_black, PI / 2)), lag_ratio=0.00)
>         self.camera.background_color = BLACK
>         self.add(prepare_group(Grid_white, PI / 2))
> 
> 
> with tempconfig({"quality" : "medium_quality", "disable_caching": True, "renderer": "opengl"}):
>     scene = Illusion()
>     scene.render()
> ```
> 
> Before this PR: before2062full
> 
> before2062render
> 
> After this PR: after2062full
> 
> after2062render
> 
> There is definitely an improvement, but it still seems to spend an awful lot of time getting shader wrappers. Do you happen to know how to optimize them out completely?

Not really tbh, it was a while since I did this but if I remember correctly there is a part of the code where the self.data numpy arrays get copied to another numpy array before being used in the moderngl So one place to improve would be if the self.data objects could be passed directly to the mesh where it is passed to moderngl. IIRC it wasn’t straight forward to do that

**Review by Darylgolden — APPROVED** [review]
Approving since it's still an improvement, but we should definitely try to optimize so that getting shader wrappers no longer takes such a long time.

**Pull request merged**
