### PR TITLE
Fix `SyntaxWarnings` when building the docs and bump `readthedocs` to Python 3.13

### PR DESCRIPTION
**Pull request by JasonGrace2282**
- Bump readthedocs to use python ~3.12~ _3.13_ (so it's easier to confirm there being no `SyntaxWarning` without having to build it)
- Use raw strings to avoid syntax warnings
- Don't access the deprecated `.tags` attribute so that we can upgrade to Sphinx 9.0 without problems in the future

### CODE REVIEW

**Comment by behackl** [comment]
Curiously, this change apparently bumps up our documentation build time by about 2 minutes -- I can't really tell why.

Should we try to bump the version of Python directly to 3.13 to see whether it makes a difference?

**Comment by JasonGrace2282** [comment]
We could try bumping to 3.13. I'm not sure if that would make it faster, though - there was an issue with 3.13 that made it 30% slower with Sphinx. Python reverted the change, but it's possible it could still be slower.

I'm all for trying, though!

For reference, the build times are:
Python 3.11 - 16min 23s
Python 3.12 - 17min 56s

**Comment by JasonGrace2282** [comment]
It did get slightly faster, with 15min 45 seconds!

**Review by chopan050 — APPROVED** [review]
LGTM!

**Pull request merged**
