### PR TITLE
added seed parameter to random color, and an RNG to config

### PR DESCRIPTION
**Pull request by ajmcculley**
## Overview: What does this pull request change?

Added a seed parameter to random color that defaults to none and an RNG to config. Also added the current random seed to config under seed. Only modified random_color() using this RNG, though this could be extended to all places where random is used. This was from issue #1671 and attempts to not fall into the same pitfalls as pull requests #2515 and #1676.

## Further Information and Comments

This is my first time contributing to any open source project ever (for a class project), so I apologize if I made any mistakes (either in the code or with the wording on the pull request). I tried to follow the guides presented. I'm grateful that this project is so beginner friendly.

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by ajmcculley** [comment]
I see a small error that can lead to calling config.rng when it is uninitialized, will fix that ASAP.

**Comment by ajmcculley** [comment]
That should have fixed the issue I was referring to

**Comment by behackl** [comment]
Thanks for contributing!

> That should have fixed the issue I was referring to

Not quite: you will need to explicitly add the `rng` in `config/utils.py` as a property of `ManimConfig`, otherwise the check you have added will simply error out with an `AttributeError`.

**Comment by behackl** [comment]
I am converting this to a draft for now. Please let us know if you intend to continue with this PR, thanks! :-)

**Pull request closed without merging**
