### PR TITLE
Account for dtype in the pixel array so the maximum value stays correct in the invert function

### PR DESCRIPTION
**Pull request by jeertmans**
This fixes an issue where the `invert` argument would only work for `uint8` dtypes. Now the `max` value is updated according to the pixel array dtype.

Maybe we should add unit tests for that, but haven't found an obvious place to put unit tests.

### CODE REVIEW

**Comment by behackl** [comment]
Yes please, just create a new file `tests/module/mobject/test_image.py` or so. Thanks!

**Comment by jeertmans** [comment]
> Yes please, just create a new file `tests/module/mobject/test_image.py` or so. Thanks!

Will do that in the following days :-)

**Comment by jeertmans** [comment]
@behackl done :-)

**Review by behackl — APPROVED** [review]
Thank you!

**Pull request merged**
