### PR TITLE
Fix segfault when using `--enable_gui`

### PR DESCRIPTION
**Pull request by hydrobeam**
## Overview: What does this pull request change?

Previously, running a scene with `--renderer=opengl --enable_gui` with dearpygui installed at all would cause a segfault every time.  

I thought the API must've changed, so I looked at the first steps guide and added in the necessary components: https://dearpygui.readthedocs.io/en/latest/tutorials/first-steps.html 

First I added `dpg.create_context`, then `dearpygui`  said that `setup_viewport` was deprecated, so I replaced it with the suggested fix.  
```bash
/home/aquabeam/Documents/Github/manim/manim/gui/gui.py:27: DeprecationWarning: Call to deprecated function setup_viewport (Use: 
create_viewport()
setup_dearpygui()
show_viewport()).
  dpg.setup_viewport()

fish: Job 1, 'poetry run manim -p --renderer=…' terminated by signal SIGSEGV (Address boundary error)
```

Then I could spawn the gui and switch scenes successfully.

## Further Information and Comments

~~GuiTest2 doesn't work~~: fixed

```bash
poetry run manim -p --renderer=opengl --enable_gui example_scenes/opengl.py GuiTest2


Manim Community v0.14.0

Python 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.0.1 -- An enhanced Interactive Python. Type '?' for help.

Exception in thread Thread-2 (configure_pygui):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aquabeam/Documents/Github/manim/manim/gui/gui.py", line 77, in configure_pygui
    getattr(dpg, f"add_{widget}")(name, **widget_config_copy)
TypeError: add_slider_float() takes 0 positional arguments but 1 positional argument (and 4 keyword-only arguments) were given
```

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Review by naveen521kk — COMMENTED** [review]
This is only needed for DearPyGui `1.x` release see https://github.com/hoffstadt/DearPyGui/issues/1439. So, can you update the dependency on `pyproject.toml`?

**Comment by behackl** [comment]
I haven't followed the discussion on Discord about this – but this works, right?

**Comment by behackl** [comment]
Just tried it, I think there might be another issue (or it is currently broken under MacOS). Here is what I did:

- switched to the branch of the PR
- ran `poetry install -E gui`, stuff got installed (including `dearpygui` 1.3.1)
- ran `manim -p -qm --renderer=opengl --enable_gui opengl.py GuiTest` from within `poetry shell`

Result: window opens for a very brief moment and closes immediately again, shell output:
```sh
(manim-U7iPD1cl-py3.9) behackl@draven example_scenes % manim -p -qm --renderer=opengl --enable_gui opengl.py GuiTest
Manim Community v0.14.0

2022-02-06 11:39:34.767 Python[19849:1347324] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/pf/3tbrb7fs72x8sm5_cpp95j1c0000gn/T/org.python.python.savedState
Python 3.9.9 (main, Nov 21 2021, 03:16:13) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.30.1 -- An enhanced Interactive Python. Type '?' for help.

zsh: trace trap  manim -p -qm --renderer=opengl --enable_gui opengl.py GuiTest
```

**Comment by Kiran-Raj-Dev** [comment]
The arm wheels need to be compiled from source. Lemme try that

**Review by naveen521kk — COMMENTED** [review]
We should ask dpg to destroy the context (using `dpg.destroy_context()`) it created after the work is done in v1.x.

**Comment by Kiran-Raj-Dev** [comment]
The gui seems to not work on mac even for `0.x` #1859

**Comment by ryanmccauley211** [comment]
> Just tried it, I think there might be another issue (or it is currently broken under MacOS). Here is what I did:

I've never been able to use the GUI on mac, not sure if it is related but I raised an issue as I think it was related to manim not running the gui on the main thread https://github.com/ManimCommunity/manim/issues/1859

**Review by behackl — APPROVED** [review]

**Comment by behackl** [comment]
Merged main and ran `poetry lock` to resolve the conflict, ready to merge now. Thanks everyone!

**Comment by behackl** [comment]
Perhaps spoken too soon; the `windows-latest` pipeline for Python 3.10 *seems* to fail deterministically now. @naveen521kk, any idea?

**Comment by Kiran-Raj-Dev** [comment]
Can you run `poetry update` and then see if that solves it?
I saw a similar problem last time and `poetry update` solved it.

**Comment by Kiran-Raj-Dev** [comment]
Is it worth adding commands like `poetry update` to the `pre-commit` hook?

**Pull request merged**
