### PR TITLE
Fixes #91

### LINKED ISSUE #91: change Scripts to scripts

### PR DESCRIPTION
**Pull request by Aathish04**
Renames  the `Scripts` folder to `scripts`.

Removes trailing whitespaces in `Scripts/pycairoinstall.py`

### CODE REVIEW

**Comment by leotrs** [comment]
Does it actually? The diff only shows the whitespaces being removed

**Comment by Aathish04** [comment]
> Does it actually? The diff only shows the whitespaces being removed

Huh, apparently git doesn't care about directory renames.

**Comment by naveen521kk** [comment]
I also tried the same and got disappointed. @Aathish04

**Comment by Aathish04** [comment]
> I also tried the same and got disappointed. @Aathish04 

You could have told us then. It's not a noticeable change...

**Comment by naveen521kk** [comment]
Wait.

**Comment by Aathish04** [comment]
The URL in the master branch _is_ the proper one.

It points to `https://raw.githubusercontent.com/ManimCommunity/manim/master/scripts/pycairoInstall.py`

Which is what the link _should_ be.

After this is merged, the proper file will be in that location.

**Pull request merged**
