### PR TITLE
add manim_directive module to reference manual

### PR DESCRIPTION
**Pull request by behackl**
The module located in `docs/source/manim_directive.py` for the `.. manim::` stuff in the documentation was not included in the reference manual so far.

This is changed here.

## Explanation for Changes
This is one of two possible approaches. Unfortunately, there does not seem to be a way to "unset" the `.. currentmodule:: manim` directive in `reference.rst`, so the path to all other entries need to be rewritten here.

The alternative would be to move `manim_directive.py` back into the manim module (which also seems to be a common approach, e.g., matplotlib does the same). Personally, I am fine with either solution.

## Acknowledgement
- [x] I have read the [Contributing Guidelines](https://github.com/ManimCommunity/manim/wiki/Documentation-guidelines-(WIP))

### CODE REVIEW

**Comment by leotrs** [comment]
Another alternative is to not add the manim directive to the reference manual, and refer to it at some point in the contributing guidelines e.g.

**Comment by behackl** [comment]
> Another alternative is to not add the manim directive to the reference manual, and refer to it at some point in the contributing guidelines e.g.

True. We could refer to it from https://manimce.readthedocs.io/en/latest/contributing.html -- but in order to get sphinx autodoc magic to work from the contributing page, we would need to convert `contributing.md` to an `.rst` file.

**Comment by leotrs** [comment]
I think I'd rather do that!

**Comment by kolibril13** [comment]
> True. We could refer to it from https://manimce.readthedocs.io/en/latest/contributing.html -- but in order to get sphinx autodoc magic to work from the contributing page, we would need to convert `contributing.md` to an `.rst` file.

This means that the normal auto summary from manim functions will be separated from the `.. manim::` stuff ?
Sounds good to me!

**Comment by behackl** [comment]
I'll convert the contribution manual and prepare a suggestion. Stay tuned. :-)

**Comment by behackl** [comment]
While converting the contribution guide to restructuredText, I found (and remembered) that following a 14 + 7 step guide to start contributing actually was a bit intimidating. I've split the guide in some smaller sections and updated the parts describing what happens in our pipeline.

Review at will, the page can be found at https://manimce--463.org.readthedocs.build/en/463/contributing.html

**Comment by kolibril13** [comment]
Thanks a lot for this!
One thing that just pops up:
Do we want to have capitalization in the titles?
ccc

**Comment by kolibril13** [comment]
When navigating over the website, I found it a bit strange that when being here:
https://manimce--463.org.readthedocs.build/en/463/reference/manim_directive.html ,
you don't have a corresponding tree on the left side.
This is somehow a hidden page, only accessible by clicking this one button in notes.
Maybe, is it possible, to show in which section this page is located?

Further, it would be nice, to have an overview, of what kind of contribution guide can be found where, like a table of contents in the beginning of the document.

> I've split the guide in some smaller sections and updated the parts describing what happens in our pipeline.

Great idea!

Maybe we can bring even a bit more overview into this section, and probably also bring together the wiki pages:
1. https://github.com/ManimCommunity/manim/wiki/Documentation-guidelines-(WIP)
2. https://github.com/ManimCommunity/manim/wiki/Guide-to-contribute-examples-to-docs

into this contribution document.
Note that I wrote (2), today, and it has some redundancies to [manim reference](https://manimce--463.org.readthedocs.build/en/463/reference/manim_directive.html)

**Comment by behackl** [comment]
> Thanks a lot for this!
> One thing that just pops up:
> Do we want to have capitalization in the titles?
> ccc

Ah, I've been pretty inconsistent here, sorry about that. Judging from the other section headings, we mostly don't do capitalization, so I'll remove it here as well.

**Comment by behackl** [comment]
> When navigating over the website, I found it a bit strange that when being here:
> https://manimce--463.org.readthedocs.build/en/463/reference/manim_directive.html ,
> you don't have a corresponding tree on the left side.

I am not sure how to resolve this. The document is rooted in the "Changing manim's source code" section, which is why this menu is active in the side bar in https://manimce--463.org.readthedocs.build/en/463/reference/manim_directive.html#module-manim_directive. This is analogous to how modules in the reference manual are rendered.

> Maybe, is it possible, to show in which section this page is located?

I am not sure I understand what you mean. Introducing a third level of submenus would be inconsistent compared to the rest of the documentation, though. (Besides, I did not manage to do that, even if I wanted to; maybe our theme does not support that.)

I'm very open for suggestions.

> Further, it would be nice, to have an overview, of what kind of contribution guide can be found where, like a table of contents in the beginning of the document.

I agree, but would like to keep this PR manageable and talk about further unification in a dedicated issue.

**Review by leotrs — APPROVED** [review]

**Comment by kolibril13** [comment]
> Introducing a third level of submenus would be inconsistent compared to the rest of the documentation, though

That is what I meant. But you are right, this would be inconsistent, and it really does not bother a lot at the moment.

**Review by kolibril13 — APPROVED** [review]

**Comment by behackl** [comment]
There was an unformatted list, now fixed with the latest commit.

**Comment by leotrs** [comment]
This has two approvals - what are we waiting for?

**Comment by behackl** [comment]
> This has two approvals - what are we waiting for?

Nothing, as far as I can tell. :-)

I don't seem to have write permissions for the repo; someone else has to merge it.

**Comment by leotrs** [comment]
You now have write permissions. Sorry about that.

**Comment by behackl** [comment]
> You now have write permissions. Sorry about that.

No worries. Thanks!

**Pull request merged**
