### PR TITLE
Converted all the graphical tests to the new syntax (Tests PR 3/3).

### PR DESCRIPTION
**Pull request by huguesdevimeux**
## Changelog / Overview

Converted all the graphical tests to the new syntax.

## Motivation

Now, tests follow the new system. (commit 9e24a3d)

## Explanation for Changes

I also fixed a bunch of things, but minor (see the first three commits).

**Note : I couldn't make the openGL tests work. It's not that big deal there was only one test, and the system is in theory flexible enough to allow mutli renderer tests.**

### CODE REVIEW

**Comment by huguesdevimeux** [comment]
Depends on #1835

**Comment by hydrobeam** [comment]
I glanced through the changes and it really does look much simpler to add tests 👍!. Although, there seems to be some leftover imports for the testing files:
```py
from ..utils.GraphicalUnitTester import GraphicalUnitTester
from ..utils.testing_utils import get_scenes_to_test
```
Should those also be removed?

Also, I noticed that the files include a `__module_test__`:
```py
__module_test__ = "plot"
```

which should probably be mentioned in the docs pr too #1835

**Comment by behackl** [comment]
From the failing pipeline:

```
E           AssertionError: 
E           Arrays are not equal
E           Frame no -1. You can use --show_diff to visually show the difference.
E           Mismatched elements: 3 / 1639680 (0.000183%)
E           Max absolute difference: 1.
E           Max relative difference: 0.00396825
```

Can we increase the maximal absolute difference for these 3D tests somehow? (I think we'll have to live with the fact that for some tests, output is not 100% the same across OSes.)

And also: should the reference to `{frame_number}` actually be `{frame_number + 1}`? (As you can see, here it says the problem is with frame number -1.)

**Comment by behackl** [comment]
And another question: to which degree did the configuration with which tests are made change?

image

There seems to be a substantial increase in file size with this PR.

**Comment by huguesdevimeux** [comment]
> From the failing pipeline:
> 
> ```
> E           AssertionError: 
> E           Arrays are not equal
> E           Frame no -1. You can use --show_diff to visually show the difference.
> E           Mismatched elements: 3 / 1639680 (0.000183%)
> E           Max absolute difference: 1.
> E           Max relative difference: 0.00396825
> ```
> 
> Can we increase the maximal absolute difference for these 3D tests somehow? (I think we'll have to live with the fact that for some tests, output is not 100% the same across OSes.)
> 
> And also: should the reference to `{frame_number}` actually be `{frame_number + 1}`? (As you can see, here it says the problem is with frame number -1.)

Frame -1 means the last frame. Seeing your question I wonder if I should change it.

**Comment by huguesdevimeux** [comment]
> And another question: to which degree did the configuration with which tests are made change?
> 
> image
> 
> There seems to be a substantial increase in file size with this PR.

I just looked at `test_DrawBorderThenFill`, and it appears that everything looks correct. There are 13 frames 240 x 427. The size increasing is probably due to the compression done by numpy ?

**Comment by huguesdevimeux** [comment]
I also added an absolute tolerance, arbitrarily to 1.01 (it's the tolerance that was already set up for OpenGL tests).

**Review by Darylgolden — COMMENTED** [review]
I understand the size of the multiple frame tests increasing, but do you know why the size of the single frame tests also increase?

**Comment by behackl** [comment]
d6a62e0 fixes the file size issue: the frame array is now explicitly converted to a `uint8`-array, that saves a lot of disk space.

**Review by behackl — APPROVED** [review]
I'm not sure I have praised the rework of the testing system enough: thank you very much, Hugues -- I think the general system is now much easier to use (and including multiple frame tests even so that we finally have a chance of noticing when changes cause regressions in animations).

I am very, very happy with this!

**Pull request merged**
