### PR TITLE
(Test) Increase RTD build speed

### PR DESCRIPTION
**Pull request by Darylgolden**
## Explanation for Changes

[Documentation Reference](https://manimce--####.org.readthedocs.build)

## Checklist
- [ ] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [ ] I have written a descriptive PR title (see top of PR template for examples)
- [ ] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by friedkeenan** [comment]
I don't believe RTD uses the makefile, they read `source/conf.py` themselves

**Comment by Darylgolden** [comment]
801 seconds, looks like this change did nothing

**Comment by Darylgolden** [comment]
Doesn't work

**Comment by Darylgolden** [comment]
Actually [this](https://github.com/readthedocs/readthedocs.org/pull/7128) may work? possibly?

**Comment by behackl** [comment]
Does it work locally?

**Comment by Darylgolden** [comment]
> 
> 
> Does it work locally?

Doesn't seem like it, in fact it even

**Comment by behackl** [comment]
> > Does it work locally?
> 
> Doesn't seem like it, in fact it even seems to have made it slower. I tested this branch first then master, deleting the contents of `docs/build` between them; is that sufficient for ensuring that sphinx has to rerender the Manim output? Otherwise, that might be the reason why. (this closing and reopening was a misclick)

For rerendering that should definitely be sufficient. But I do wonder whether the manim directive would have to be refactored a bit in order to actually support parallel rendering: currently, we have set `metadata = {"parallel_read_safe": False, "parallel_write_safe": True}` which might explain why enabling parallel rendering doesn't improve the time.

**Comment by Darylgolden** [comment]
> For rerendering that should definitely be sufficient. But I do wonder whether the manim directive would have to be refactored a bit in order to actually support parallel rendering: currently, we have set `metadata = {"parallel_read_safe": False, "parallel_write_safe": True}` which might explain why enabling parallel rendering doesn't improve the time.

I changed `parallel_read_safe` to True, still takes around the same amount of time. As for RTD, they said they can enable parallelization if a maintainer requests it, but we should probably figure out whether it improves the speed locally before asking them.

**Comment by behackl** [comment]
I'd prefer to have this PR closed for now; we can reopen it once we know that parallelization improves build time locally (and I'm still somewhat sure that we'll need to rewrite the directive in order for that to be the case).

Maybe we should open an issue instead?

**Pull request closed without merging**
