### PR TITLE
Updated ``winget`` command for installing MiKTeX in documentation

### PR DESCRIPTION
**Pull request by Joey451-OG**
## Overview: What does this pull request change?

In the docs the winget command to install MiKTeX was changed from `winget install ChristianSchenk.MiKTeX` to `winget install MiKTeX.MiKTeX`. I have changed the docs to reflect this change. 

## Motivation and Explanation: Why and how do your changes improve the library?
 Changed small error in Installation --> Windows --> Optional Dependencies because I noticed a command was incorrect.

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Review by behackl — APPROVED** [review]
Thank you!

**Comment by Joey451-OG** [comment]
@behackl For some reason the change was reverted??? I looked through latest PR's but couldn't find any change on that file.

Link: https://docs.manim.community/en/stable/installation/windows.html#optional-dependencies
change-reverted

**Comment by Joey451-OG** [comment]
Hmmm, the file wasn't changed.... I'm really confused now, it was working Sunday

**Comment by behackl** [comment]
> Hmmm, the file wasn't changed.... I'm really confused now, it was working Sunday

It's there, you are just looking at the "stable" version of the documentation, which corresponds to the documentation of the latest release. Change to `latest` to see the updated version: https://docs.manim.community/en/latest/installation/windows.html

**Comment by Joey451-OG** [comment]
Oh 🤦‍♂️. Sorry for the ping...

**Pull request merged**
