### PR TITLE
Add setup.py

### PR DESCRIPTION
**Pull request by eulertour**
Add a `setup.py` with an `entry_points` entry which replaces `manim.py`, and remove `manim.py`.

### CODE REVIEW

**Comment by XorUnison** [comment]
What exactly would this do though? How would this manim fork be run with that setup.py in place, and would that help in running the 3b1b manim and this community manim in parallel?

**Comment by leotrs** [comment]
@XorUnison I think now we will be able to run this one by using `python -m manim` and `python -m manimcm`. The second one will be used when there is another version installed.

**Comment by leotrs** [comment]
I'm still not 100% about the manimcm name, but this can be merged and the name can be changed elsewhere...

**Comment by leotrs** [comment]
Merged. The next step here @eulertour is to add minimal tests for running manim using either `manim` or `manimcm`. A simple run-this-scene-without-crashing should suffice for now. What do you think?

**Pull request merged**
