### PR TITLE
Update pyproject.toml

### PR DESCRIPTION
**Pull request by eulertour**
We don't plan to use dataclasses, so this line is unnecessary.

### CODE REVIEW

**Review by PgBiel — APPROVED** [review]

**Review by kilacoda — APPROVED** [review]

**Comment by naveen521kk** [comment]
No, this caused problems with dependency resolving with poetry and that why it was added. That was because of rich and pycairo and could possibly break installation for everyone. We should have dataclasses or else everybody's installation would break.

**Comment by eulertour** [comment]
That doesn't seem right. rich specifies the dataclasses requirement on its own, so we shouldn't have to do it again (https://github.com/willmcgugan/rich/blob/f092b1d04252e6f6812021c0f415dd1d7be6a16a/pyproject.toml#L27). That said, there does seem to be something fishy with how rich interacts with poetry.

**Comment by naveen521kk** [comment]
Also, from next if changing any dependency please change the lock file also. Using
```
poetry lock
```

**Comment by naveen521kk** [comment]
> That doesn't seem right. rich specifies the dataclasses requirement on its own, so we shouldn't have to do it again 

That caused a deps resolving issue in poetry latest, (possibly fixed in poetry's beta version), adding dataclassess fixes the install. If you commit the lock files all the tests would fail. ;-)

**Comment by eulertour** [comment]
Is there an issue for this you can link to? This error still occurs when we attempt to add new dependencies. If we can't use poetry without having to work around its bugs it may be best to hold off on it.

**Comment by naveen521kk** [comment]
> Is there an issue for this you can link to?

I don't know. But on discussing with them on discord told me that this is fixed in latest pre-release. So we can possibly wait until it is released. 

> This error still occurs when we attempt to add new dependencies. 

One thing which can possibly be done is remove support for python 3.6 and we have no problem on that. Or else have the current configuration and wait for new release from poetry. I don't think we need to add any new dependency for now.

**Comment by naveen521kk** [comment]
Pretty much a thing which can be done is remove support for python 3.6 and remove the line. Or else keeping the current config does it.

**Comment by leotrs** [comment]
Python 3.6 is no longer active or receiving bugfixes (only security updates), but it is not officially at "end of life" until Dec 2021.

https://www.python.org/dev/peps/pep-0494/

**Comment by naveen521kk** [comment]
So its probably better to close this PR and wait until either python 3.6 is EOL or poetry has a new release.(Which fixes this issue)

**Comment by eulertour** [comment]
Shouldn't we wait for a new poetry release and then merge this PR? @naveen521kk

**Comment by naveen521kk** [comment]
Yes. Pretty much they will having one very soon. I can confirm from their pre-release that it is fixed there.

**Comment by leotrs** [comment]
Uuuh so @naveen521kk just _left the chat_. So who is in charge of determining when this PR can be merged? @eulertour ?

**Comment by naveen521kk** [comment]
I remember removing it in another PR. So this can be closed.

**Pull request closed without merging**
