### PR TITLE
Explain ``.Transform`` vs ``.ReplacementTransform`` in quickstart examples

### PR DESCRIPTION
**Pull request by JasonGrace2282**
Resolves Issue #3139 

## Changed Documentation
https://manimce--3500.org.readthedocs.build/en/3500/tutorials/quickstart.html

### CODE REVIEW

**Review by behackl — APPROVED** [review]
LGTM.

I would have probably done it slightly differently by rewriting the existing examples to use `Transform` and then adding a dedicated section on `Transform` vs `ReplacementTransform` motivated by transformation chaining (`Transform(a, b) -> Transform(a, c)` vs `ReplacementTransform(a, b) -> ReplacementTransform(b , c)`), but this is fine too.

**Comment by MrDiver** [comment]
```
For the a->b, a->c part it follows more of a foldl pattern in that sense so you can apply a list of functions to one mobject and it still work, so it enables you to write for loops without having to switch between different references.
Whereas a->b->c makes more sense for manual transforms that only happen once.
```
Discord discussion copy paste

It might also be useful to add this for the explanation why Transform is useful

```py
class Test(Scene):
    def construct(self):
        a = Circle()
        t1 = Square()
        t2 = Triangle()
        self.add(a)
        self.wait()
        for t in [t1,t2]:
            self.play(Transform(a,t))
```

**Comment by MrDiver** [comment]
Docs are not updated by now, we need to rerun the render

**Comment by JasonGrace2282** [comment]
@MrDiver am I misunderstanding? The docs have been rebuilt
image

**Comment by MrDiver** [comment]
Ah now it updated! Looks good to me!

**Review by MrDiver — APPROVED** [review]

**Pull request merged**
