### PR TITLE
Set default value of keyword ``random_seed`` in Scene to None (was 0 and fixed before)

### PR DESCRIPTION
**Pull request by behackl**
## Changelog / Overview

One-line change. The default value of `random_seed` in `Scene` was `0` before, now it is `None`, making different renders of the same Scene output different random numbers again. The old behavior can be restored by instantiating your scene yourself with a `random_seed` value of your choice.

## Motivation
It is good to be able to fix the random seed, but I don't think it makes sense to have that as the default behavior.

## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Review by friedkeenan — APPROVED** [review]
Not totally sure if this should even be a thing, but seeing as it sets both `random` and `np.random` seeds, I can see it perhaps having a benefit. This is still fine to me though

**Review by sparshg — COMMENTED** [review]
I don't know why would there be a preset seed though

**Review by sparshg — APPROVED** [review]

**Comment by behackl** [comment]
> I don't know why would there be a preset seed though

I can imagine that it might be useful from time to time to fix the seed in order to have deterministic output when rendering -- but I agree that this shouldn't be the default behavior.

**Comment by huguesdevimeux** [comment]
I think it should be removed : $
- It is not used anywhere in the code base
- If it happends to be used, it could compltetly destroys scene caching (because some random elements could make the hash inconsistent)

**Comment by behackl** [comment]
> I strongly think it should be removed: $
> 
> * It is not used anywhere in the codebase

Lots of features and classes are meant primarily for users and are not used anywhere within the library.

> * If it happens to be used, it could completely destroys scene caching (because some random elements could make the hash inconsistent)

... which is expected behavior if users choose to use randomness in their scenes.


I won't insist of getting this merged, ultimately I don't really care. I just find it weird that manim currently forces randomness to be deterministic by default.

**Review by jsonvillanueva — APPROVED** [review]

**Pull request merged**
