### PR TITLE
Fixed passing custom arrow shapes to :class:`~.CurvedArrow`

### PR DESCRIPTION
**Pull request by vinnniii15**
## Reviewer Checklist
- [x] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [x] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by sparshg** [comment]
I think this is for #1928 
LGTM

**Review by sparshg — APPROVED** [review]
I think this is for #1928
LGTM

**Review by Darylgolden — COMMENTED** [review]
@vinnniii15 Can you edit the title of the PR to something that's more descriptive?

**Review by behackl — APPROVED** [review]
I've changed the title and added a test. LGTM now.

**Pull request merged**
