### PR TITLE
ci: test python 3.9

### PR DESCRIPTION
**Pull request by naveen521kk**
## List of Changes
I think it would be ok now to test for python 3.9

## Acknowledgement
- [x] I have read the [Contributing Guidelines](https://github.com/ManimCommunity/manim/wiki/Documentation-guidelines-(WIP))

### CODE REVIEW

**Comment by leotrs** [comment]
Did np and mpl release their wheels? I must have missed that.

**Comment by naveen521kk** [comment]
> Did np and mpl release their wheels? I must have missed that.

numpy did it. I don't know about mpl though. If the test pass then yes they did it. Or else we would have to wait.

**Comment by leotrs** [comment]
Well I don't think any of the tests actually use mpl!

**Review by leotrs — APPROVED** [review]

**Comment by leotrs** [comment]
How does this related to @Aathish04 's problems with using poetry with py3.9?

**Comment by naveen521kk** [comment]
> How does this related to @Aathish04 's problems with using poetry with py3.9?

He is sitting in an extreme case, because of MacOs Big Sur release where all wheels became incompatible.

**Review by eulertour — APPROVED** [review]

**Comment by eulertour** [comment]
If we're doing this can we drop testing for python 3.6 soon? That'll allow us to safely use new features eventually and shorten the time for testing.

**Comment by leotrs** [comment]
Python 3.6 hits end of life late next year.

Se can run py3.6 tests but not report if they fail, to still make sure that
all failures are due to new python features and not due to manim's fault.

**Comment by naveen521kk** [comment]
I am merging this. We can think about dropping test for python 3.6 on a later PR.

**Pull request merged**
