### PR TITLE
Standardize docstrings with ruff pydocstyle rules

### PR DESCRIPTION
**Pull request by JasonGrace2282**
Replace  `flake8-docstrings` with `pydocstyle`. This should allow for fixing/standardization of doc strings automatically by ruff (via `pre-commit`).
If you disagree with any of the changes, feel free to comment!

> [!NOTE]
> We might want to add this to git blame ignore sha list

### Documentation
https://manimce--3881.org.readthedocs.build/en/3881/

### CODE REVIEW

**Review by Viicos — APPROVED** [review]
I like it, I generally prefer having single line docstrings not on 3 lines, so looks good!

**Comment by Viicos** [comment]
Does this need any change in the Ruff pyproject config?

**Comment by JasonGrace2282** [comment]
> Does this need any change in the Ruff pyproject config?

If you're talking about https://docs.astral.sh/ruff/rules/fits-on-one-line/ then no, it's included with pydocstyle and not ignored.

**Comment by JasonGrace2282** [comment]
This will probably need to be reviewed again once I push a commit fixing the docs build, marking as a draft for now.

**Comment by Viicos** [comment]
> If you're talking about https://docs.astral.sh/ruff/rules/fits-on-one-line/ then no, it's included with pydocstyle and not ignored.
> Other than that the only change I made to the pyproject was adding `pydocstyle` and ignoring some rules.

I was talking about the ruff pyproject configuration we have, but it seems it was added in your last commit 👍 

> I was also hoping this PR would fix the `SyntaxWarning`s, but I still can't seem to find where they originate 🤔

Do you have an example of such a `SyntaxWarning` being raised?

**Comment by JasonGrace2282** [comment]
> Do you have an example of such a SyntaxWarning being raised?

After running `make cleanall` and then `make html` I end up with messages like this
```
<string>:28: SyntaxWarning: invalid escape sequence '\p'
<string>:14: SyntaxWarning: invalid escape sequence '\D'
<string>:14: SyntaxWarning: invalid escape sequence '\c'
```
Interestingly, the build log for the docs CI doesn't show it, so it might be some sort of weird setup on my part.

**Comment by MrDiver** [comment]
Does this automagically work with the CI ? because we should probably make sure it's done automagically here too

**Comment by JasonGrace2282** [comment]
> Does this automagically work with the CI ? because we should probably make sure it's done automagically here too

A lot of the formatting ones do (see the ones marked with tools here https://docs.astral.sh/ruff/rules/#pydocstyle-d)

Sometimes, with regards to `\`s manual changes are needed (see my manual changes commit), but it should be relatively uncommon.

**Comment by JasonGrace2282** [comment]
This is now the last PR before we can remove `flake8` from Manim!

**Comment by JasonGrace2282** [comment]
If there are no other thoughts on this, I might merge it within the next few days.

**Comment by Viicos** [comment]
> After running `make cleanall` and then `make html` I end up with messages like this
> 
> ```
> <string>:28: SyntaxWarning: invalid escape sequence '\p'
> <string>:14: SyntaxWarning: invalid escape sequence '\D'
> <string>:14: SyntaxWarning: invalid escape sequence '\c'
> ```

Is this still an issue now? Python 3.12 started warning about invalid escape sequences but iirc it is planned to error in some later versions. You can use the `r` prefix if necessary. Other than that, happy to see this one merged!

**Comment by JasonGrace2282** [comment]
> > After running `make cleanall` and then `make html` I end up with messages like this
> > 
> > ```
> > <string>:28: SyntaxWarning: invalid escape sequence '\p'
> > <string>:14: SyntaxWarning: invalid escape sequence '\D'
> > <string>:14: SyntaxWarning: invalid escape sequence '\c'
> > ```
> 
> Is this still an issue now? Python 3.12 started warning about invalid escape sequences but iirc it is planned to error in some later versions. You can use the `r` prefix if necessary. Other than that, happy to see this one merged!

Ah right I'd forgotten about that change in python 3.12, now it makes sense why it wasn't in the ci log (which runs 3.11).

I think I figured out why the `SyntaxWarning` appears - it's from when the Manim directive rendering the docs examples, not at the Sphinx level. As such, they're unrelated to the PR, and considering the size of the PR already, I think I'll tackle fixing them in a follow-up PR.

**Pull request merged**
