### PR TITLE
solve issue 542 - no requirements.txt

### LINKED ISSUE #542: requirements.txt is incomplete. `pip install` is broken
**Describe the bug**
The requirements.txt file is missing some entries.
This means manim is not currently installable through pip

**To Reproduce**
An a clean system, run `pip3 install -r ./requirements.txt` and then try to run manim to compile a scene.

**Output**
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/cobordism/.local/lib/python3.8/site-packages/manim/__init__.py", line 45, in <module>
    from .mobject.svg.text_mobject import *
  File "/home/cobordism/.local/lib/python3.8/site-packages/manim/mobject/svg/text_mobject.py", line 13, in <module>
    import pangocairocffi
ModuleNotFoundError: No module named 'pangocairocffi'

```

### PR DESCRIPTION
**Pull request by cobordism**
remove requirements.txt
It is not needed and causes problems.

Solves issue #542
Fixes #542

### CODE REVIEW

**Comment by cobordism** [comment]
issue 542*

**Review by naveen521kk — APPROVED** [review]
LGTM!

**Comment by leotrs** [comment]
After this, the way to update the dependencies is to just do `poetry install`, correct? @naveen521kk

**Comment by cobordism** [comment]
"pip3 --install ."

**Comment by leotrs** [comment]
But I thought poetry removed the need for pip? :weary: Perhaps I just don't understand poetry well enough yet.

Ok, whatever, as long as we are able to fix the issues that this will surely bring up!

**Review by leotrs — APPROVED** [review]

**Comment by cobordism** [comment]
no no.
You can use poetry if you like.
I don't want to. I use pip... and then as I ubderstand it, the correct command is no longer `install -r requiremenrs.txt` but `install .`

**Comment by leotrs** [comment]
Ah ok gotcha so that sounds good then.

**Pull request merged**
