### PR TITLE
Bugfix: TeXTemplate class did not include inputenc / fontenc

### PR DESCRIPTION
**Pull request by PhilippImhof**
This solves https://github.com/ManimCommunity/manim/issues/251

`TeXTemplate` was supposed to default to the exact same configuration as `manim/tex_template.tex`, but somehow the equivalents of `\usepackage[UTF8]{inputenc}` and `\usepackage[T1]{fontenc}` were missing.

### CODE REVIEW

**Comment by PhilippImhof** [comment]
I have no idea why the rendering test fails. The change is so small anyone can see that there is no problem with it.

**Comment by PgBiel** [comment]
can you try running a test of your own in your machine?

**Comment by PhilippImhof** [comment]
The result is basically the same: `test_writing.py` fails, all other tests are successful

```
E           AssertionError: The frames don't match. TextMobject has been modified.
E           Please ignore if it was intended.
E           First unmatched index is at [229 382]: [ 16  16  16 255] != [ 17  17  17 255]
```

The only difference is that the first unmatched index is not the same. The difference is also off by one (16 instead of 17, 184 instead of 185 in the Ubuntu test)

**Comment by PhilippImhof** [comment]
Probably got it: Has the test comparison data been created with the buggy version of `tex.py`? The missing `\usepackage[T1]{fontenc}` might have an impact on that data. If I just add `inputenc` without `fontenc`, the test passes.

However, in this case, we would have to regenerate the test data, as `fontenc` is supposed to be loaded.

**Comment by PhilippImhof** [comment]
Just did a quick check with a MWE based on `manim/manim/tex_template.tex`:

```latex
\documentclass[preview]{standalone}

\usepackage[english]{babel}
\usepackage[utf8]{inputenc}
%\usepackage[T1]{fontenc}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{dsfont}
\usepackage{setspace}
\usepackage{tipa}
\usepackage{relsize}
\usepackage{textcomp}
\usepackage{mathrsfs}
\usepackage{calligra}
\usepackage{wasysym}
\usepackage{ragged2e}
\usepackage{physics}
\usepackage{xcolor}
\usepackage{microtype}
\DisableLigatures{encoding = *, family = * }
%\usepackage[UTF8]{ctex}
\linespread{1}

\begin{document}

Hello world !

\end{document}
```

With `\usepackage[T1]{fontenc}` commented out:
`$ pdfinfo without-t1.pdf` I get
```
Page size:      343.711 x 6.918 pts
Page rot:       0
File size:      11744 bytes
```

And with `\usepackage[T1]{fontenc}` activated it is:
`$ pdfinfo with-t1.pdf` I get
```
Page size:      343.711 x 6.861 pts
Page rot:       0
File size:      10569 bytes
```

**Comment by PhilippImhof** [comment]
Pinging @huguesdevimeux on this: I suggest we regenerate the reference data for `test_writing.py`

Also, asking @leotrs and maybe @PgBiel for review in order to get the bugfix merged.

**Comment by leotrs** [comment]
The fix looks good to me, and ready to be merged as soon as the tests pass.

**Comment by PhilippImhof** [comment]
> The fix looks good to me, and ready to be merged as soon as the tests pass.

Thanks. `test_writing.py` will not pass, as long as the reference data is not regenerated. Even without special chars (like umlaut etc.) the resulting image will be slightly (unnoticeably) different depending on whether `\usepackage[T1]{fontenc}` enabled or not

**Comment by huguesdevimeux** [comment]
> Probably got it: Has the test comparison data been created with the buggy version of tex.py? 

Yes, probably, as it has been generated a long time ago. 
I think you're right; reference data must be generated again. Check the wiki id you don't know how to do it :)

**Comment by PhilippImhof** [comment]
> > Probably got it: Has the test comparison data been created with the buggy version of tex.py?
> 
> Yes, probably, as it has been generated a long time ago.

Actually the test data was committed on June 4th, one day after `utils/tex.py` which introduced the bug. But you probably worked on it earlier and used the old template.

> I think you're right; reference data must be generated again. Check the wiki id you don't know how to do it :)

I will do so

**Comment by PhilippImhof** [comment]
As you can see, `test_writing.py` still fails, even though it was successful on my computer. I generated the test data on OS X, it might be different on Ubuntu. (This is my theory, but it is backed up by the fact that on Ubuntu 3.8 `test_graph.py` fails whereas it passed on Ubuntu 3.6.

**Comment by PhilippImhof** [comment]
@huguesdevimeux  As discussed in chat, I finally cleaned up the cache stuff and everything. All checks are finally passing. Ready for your review.

**Pull request merged**
