### PR TITLE
Removing z_index

### PR DESCRIPTION
**Pull request by kolibril13**
## Motivation
https://github.com/ManimCommunity/manim/pull/122 introduced the z_index feature.
As this turned out to not be very robust in animations (https://github.com/ManimCommunity/manim/issues/327), this pr will remove this feature again.
## Overview / Explanation for Changes
Removed z_index code in Mobject, in camera, and some other files
## Acknowledgements
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)

## Reviewer Checklist
- [ ] Newly added functions/classes are either private or have a docstring
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings
- [ ] The oneline summary has been included [in the wiki](https://github.com/ManimCommunity/manim/wiki/Changelog-for-next-release)

### CODE REVIEW

**Comment by behackl** [comment]
I am against removing `z_index` without a suitable replacement. Especially because I think that the change from my latest comment in #327 could potentially solve the issue.

**Comment by kolibril13** [comment]
> I am against removing `z_index` without a suitable replacement. Especially because I think that the change from my latest comment in #327 could potentially solve the issue.

It would be very great if we can keep this feature without its bug.
I made this a draft pr for now, do you think you could make a pr implementing your latest idea from #327 ?

**Comment by eulertour** [comment]
The alternative is to use the z coordinate of the mobject, which we actually should have been doing from the start

**Comment by behackl** [comment]
I also think that switching from `z_index` to the z coordinate makes sense; full support for that. I just don't want to fully remove the feature (granted, as #327 demonstrates, it's not a very well-working and/or stable one) that allows rearranging the mobjects in the scene independent of the order in the list of mobjects / submobjects.

**Comment by kolibril13** [comment]
closing this one in favour of #872

**Pull request closed without merging**
