### PR TITLE
Allow axes' CONFIG to be passed through GraphScene

### PR DESCRIPTION
**Pull request by ToxicGLaDOS**
## List of Changes

- Added two new entries to CONFIG for `GraphScene` (x_axis_config and y_axis_config) which can be used to set the CONFIG of the underlying `NumberLine`s for the `GraphScene`
- Added a test for x_axis_config and y_axis_config including overriding variables previously set by the `GraphScene`
- Removed various entries from the `GraphScene` CONFIG that had no use in the `GraphScene` itself and were only being passed along to the NumberLine, because now we can just pass them in through x_axis_config and y_axis_config

## Motivation

There was no way to modify the "decimal_number_config" part of the `NumberLine` within the `GraphScene` as far as I could tell.

Example:

Prior to these changes running this code
```
from manim import *


class Graph(GraphScene):
    CONFIG = {
        "x_min": -10,
        "x_max": 10,
        "y_min": -1,
        "y_max": 1,
        "graph_origin": ORIGIN,
        "function_color": RED,
        "axes_color": GREEN,
        "y_labeled_nums": [x * 1 / 10 for x in range(0, 11)],
        "x_labeled_nums": range(-10, 12, 2),
    }

    def construct(self):
        self.setup_axes()
        graph = self.get_graph(self.func)
        self.play(ShowCreation(graph))

    def func(self, x):
        return np.sin(x)
```

Would give this output
Y-axis Decimal points are rounded

Now if we add the y_axis_config like this

```
from manim import *


class Graph(GraphScene):
    CONFIG = {
        "x_min": -10,
        "x_max": 10,
        "y_min": -1,
        "y_max": 1,
        "graph_origin": ORIGIN,
        "function_color": RED,
        "axes_color": GREEN,
        "y_labeled_nums": [x * 1 / 10 for x in range(0, 11)],
        "y_axis_config":{
            "decimal_number_config": {
                "num_decimal_places": 1,
            },
        },
        "x_labeled_nums": range(-10, 12, 2),
    }

    def construct(self):
        self.setup_axes()
        graph = self.get_graph(self.func)
        self.play(ShowCreation(graph))

    def func(self, x):
        return np.sin(x)
```

We get this output
Y-axis is not rounded

## Explanation for Changes

While I could have just added another keyword argument to the big list we already had passed in to `NumberLine` (similar to [this pr](https://github.com/3b1b/manim/pull/917) to 3b1b/manim), if I wanted to change the colors of the axes independently, or modify anything else I would've had to add keyword arguments for each of the things I wanted to pass along to the `NumberLine` which feels like it defeats the purpose of the CONFIG. So instead, I took the sensible default values we already were passing through keyword arguments and constructed a dictionary of those and then updated that dictionary with the values passed along by x_axis_config and y_axis_config.

This does allow for some (maybe) weird behavior. If you pass an "x_min" through x_axis_config larger than the `GraphScene` "x_min" then you can see the graph being drawn where there isn't a number line. Like this

Missing part of x-axis

I'm not really sure if this is weird behavior necessarily, because its kinda of what you were asking for by setting them differently, but I thought it was worth mentioning.

Additionally, there are CONFIG options in `GraphScene` that _probably_ could've been taken away with little consequence and left to (x/y)_axis_config (x_leftmost_tick, y_leftmost_tick, axes_color...), but I chose not to because they have different default values in a `GraphScene` than in a `NumberLine` which seemed bad for backwards compatibility.

## Testing Status

The previous `PlotFunctions` test in graph_scene.py still works like it did and the new test I wrote also works. 

## Further Comments

On [the wiki page for testing](https://github.com/ManimCommunity/manim/wiki/Testing) it says "Scene names must follow a precise syntax. Its name must be `<thing_tested>`Test." which `PlotFunctions` doesn't follow. Is there some reason for this or is this an issue?

## Acknowledgement
- [X] I have read the [Contributing Guidelines](https://github.com/ManimCommunity/manim/wiki/Documentation-guidelines-(WIP))

### CODE REVIEW

**Comment by leotrs** [comment]
> On the wiki page for testing it says "Scene names must follow a precise syntax. Its name must be <thing_tested>Test." which PlotFunctions doesn't follow. Is there some reason for this or is this an issue?

The reason is that `test_graph`, as well as other files, are actually using the `test_scenes` function to run the tests, not the Scene classes themselves. If it was called `PlotFunctionsTest`, then pytest would try to use it as a test which would not work for our purposes.

**Comment by ToxicGLaDOS** [comment]
@leotrs 
> One question tho: why does your PR overwrite every file in `tests_cache`? cc @huguesdevimeux

Unless I'm missing something, it doesn't. It creates a whole bunch of _new_ files in `tests/tests_cache/graph/NumberLineTest/` (the cache files for PlotFunctions are in  `tests/tests_cache/graph/PlotFunctions/`) which are required because test_graph.py has the `caching_needed=True` flag set.

**Comment by ToxicGLaDOS** [comment]
@leotrs 
> The reason is that `test_graph`, as well as other files, are actually using the `test_scenes` function to run the tests, not the Scene classes themselves. If it was called `PlotFunctionsTest`, then pytest would try to use it as a test which would not work for our purposes.

I don't think I completely understand how the testing works then. `test_geometry.py` uses `test_scene` as well, but all the tests are `<thing-tested>`Test. I guess I'm not really sure where the difference lies.

**Comment by huguesdevimeux** [comment]
> > On the wiki page for testing it says "Scene names must follow a precise syntax. Its name must be <thing_tested>Test." which PlotFunctions doesn't follow. Is there some reason for this or is this an issue?
> 
> 
> 
> The reason is that `test_graph`, as well as other files, are actually using the `test_scenes` function to run the tests, not the Scene classes themselves. If it was called `PlotFunctionsTest`, then pytest would try to use it as a test which would not work for our purposes.

I would like to tell you that it is true and it's not a mistake by my fault but ... it's actually a mistake by my fault.
This should be PlotFunctionsTest. 

Feel free to open a quick issue about this. I will fix that in the future PR that will refactor tests

**Pull request merged**
