### PR TITLE
Added support for PySide coordinate system

### PR DESCRIPTION
**Pull request by kevcen**
## Overview: What does this pull request change?

The function `pixel_coords_to_space_coords` is used to find the coordinates of a mouse event on the Manim preview window. However, the coordinate system (where the origin is bottom left) is specific to Pyglet only. To support coordinate systems where the origin is at the top left, such as PySide or PyQT, I have added a parameter to flip between the two.

`topLeft` defaults to `False` to support existing code without needing any changes.

## Motivation and Explanation: Why and how do your changes improve the library?

As above.

## Links to added or changed documentation pages

None, it is an internally used function in the opengl_renderer_window.Window class.

## Further Information and Comments

None.

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Review by behackl — CHANGES_REQUESTED** [review]
Thank you for your contribution! The change looks fine to me in general, I do have one change request and two comments:

- `topLeft` should be renamed to `top_left` (snake_case is preferred over CamelCase via PEP8),

And the comments:
- The parameter description in the comment above is okay, although I would like to see it moved to a docstring of the method.
- A (non-graphical) unit test for this method and the new parameter would be good to ensure it won't break in the future. Do you have an idea for how this could be tested?

**Comment by kevcen** [comment]
> Thanks! Any idea how we could test `pixel_coords_to_space_coords`?

I'm not sure, how are the GUI functions currently tested? I guess we could do simple tests to see the calculations are being calculated properly but not sure how to mock stuff like `self.get_pixel_shape`

**Comment by behackl** [comment]
> > Thanks! Any idea how we could test `pixel_coords_to_space_coords`?
> 
> I'm not sure, how are the GUI functions currently tested? I guess we could do simple tests to see the calculations are being calculated properly but not sure how to mock stuff like `self.get_pixel_shape`

Take a look at `tests/test_scene_rendering/opengl/test_opengl_renderer.py`, we have some rendering tests in there. Here, I don't think a graphical unit test (where some image is rendered and compared to corresponding test data) is necessary. Rendering some scene and then `assert`ing that `pixel_coords_to_space_coords` yields the expected values probably does the trick.

**Comment by kevcen** [comment]
> > > Thanks! Any idea how we could test `pixel_coords_to_space_coords`?
> > 
> > 
> > I'm not sure, how are the GUI functions currently tested? I guess we could do simple tests to see the calculations are being calculated properly but not sure how to mock stuff like `self.get_pixel_shape`
> 
> Take a look at `tests/test_scene_rendering/opengl/test_opengl_renderer.py`, we have some rendering tests in there. Here, I don't think a graphical unit test (where some image is rendered and compared to corresponding test data) is necessary. Rendering some scene and then `assert`ing that `pixel_coords_to_space_coords` yields the expected values probably does the trick.


Done!

**Pull request merged**
