### PR TITLE
Use actions/checkout for cloning repository; black-checks

### PR DESCRIPTION
**Pull request by naveen521kk**
## Changelog / Overview

https://github.com/ManimCommunity/manim/pull/1194/checks?check_run_id=2241875101 failed because of this. This should fix it probably.

## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by eulertour** [comment]
Why isn't this done with the checkout action github provides?

**Comment by naveen521kk** [comment]
> Why isn't this done with the checkout action github provides?

It's done using it https://github.com/ManimCommunity/manim/pull/1216/files#diff-107e910e9f2ebfb9a741fa10b2aa7100cc1fc4f5f3aca2dfe78b905cbd73c0d2R24
This check wants some history to work, which is passed as `fetch-depth:`. Default is clone without any history which isn't helpful.

**Comment by eulertour** [comment]
I didn't realize you changed it just now.

It looks like most of this work is done so the black check can report which files need to be formatted, but black does that by default already. Is there any other reason why the history is needed?

**Comment by naveen521kk** [comment]
> It looks like most of this work is done so the black check can report which files need to be formatted, but black does that by default already. Is there any other reason why the history is needed?

Black does print the files changed, but this check runs black only on files which were changed in that particular PR, that's the aim of all that extra code there. Black is still unreleased or doesn't has a stable release so, it could change anytime, and that's why this is done. You could have a look at what happened previously when black was set up for more context on why this is done so.

**Comment by eulertour** [comment]
Would either/both of the following changes have any drawback:
1. Using an action (even if it isn't provided by github) to get the changed files
2. Making a single call to black rather than passing each file to `black` and `black --diff` separately

**Review by eulertour — APPROVED** [review]

**Comment by naveen521kk** [comment]
> Using an action (even if it isn't provided by github) to get the changed files

Don't know if there exists one. If it exists it should be fine I think.

> Making a single call to black rather than passing each file to black and black --diff separately

Irrc, someone complained that they want to see the diffs seperately. Or else it should be fine with single call.

**Pull request merged**
