### PR TITLE
Removed various return annotations that were stifling type inference

### PR DESCRIPTION
**Pull request by BorisTheBrave**
## Overview: What does this pull request change?
Changes the type annotations of methods on Mobject and VMobject

## Motivation and Explanation: Why and how do your changes improve the library?

Code like the following is very common when using manim.

```python
rect = Rectangle(width=1.0, height=4.0).shift(RIGHT)
```

You really want type inference to realize that `rect` is of type `Rectangle` to get good auto completion

The current annotations explicitly force the return type to MObject, which is far less useful.

I've simply removed all the annotations, as mypy inference is perfectly capable of realizing the correct return type by inspecting the function body, and the docs generally explicitly say "returns self".

Alternatively, we could use a TypeVar, which is what Mobject.copy does. But I felt that was unneccessary.

I've only attacked the two largest classes - the same issue is all over the code base. I've not touched methods that don't `return self`, though I suspect a few of them could have more specific return types.

I've also updated the docstrings to be more consistent about what is returned.

## Links to added or changed documentation pages
https://manimce--2408.org.readthedocs.build/en/2408/

## Further Information and Comments
You may want to create an issue to update the rest of the codebase in a similar fashion.

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [x] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [x] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by behackl** [comment]
In terms of documentation you are right, nothing changes. I've also tested the behavior of this locally in my VS Code, and I can confirm that the type inference improves.

> Alternatively, we could use a TypeVar, which is what Mobject.copy does. But I felt that was unneccessary.

I somewhat dislike going for two different type hint approaches simultaneously. Could you maybe elaborate why you felt that adding a return type via a `TypeVar` was unneccessary?

**Comment by christopher-besch** [comment]
> I somewhat dislike going for two different type hint approaches simultaneously.

So do I.
We're already defining `T`, so my first idea was to do something like this:
```py
def add(self, *mobjects: T) -> T:
```
The problem with that is:
```py
s = Square()
t = Circle()
a = s.add(t)
```
Here the inferred type of `a` is `Circle`. And if you do
```py
a = s.add(s, t)
```
instead, you end up with a `Square | Circle` type.
So this can't be done.


But what about this:
```py
def add(self: T, *mobjects: "Mobject") -> T:
```
This should always work, right?

**Comment by christopher-besch** [comment]
I just realized, that's exactly how `Mobject.copy` does it and I reinvented the wheel...

**Comment by BorisTheBrave** [comment]
`copy` needs annotations as type inference isn't capable of figuring it out. That's not the case for `return self` methods, which are easily inferred. Of which there are millions (the vast majority of return self methods in the code base have no return annotation).

I feel adding type hints would be a large change, and a lot of extra code, for no tangible benefit.

**Comment by christopher-besch** [comment]
> [...] no tangible benefit.

I do think there's an advantage to being more explicit: Without having to dive into anything else, I can tell by just looking at this one line
```py
def add(self: T, *mobjects: "Mobject") -> T:
```
that this method returns `self` (or something of that type).

If we don't have that, it'd be very easy for a forgotten `return self` to slip through the cracks and end up in production.

> I feel adding type hints would be a large change [...]

That kind of change is exactly what we need moving forward with Manim. Everything has to be more explicit, better checked and less inferred or implicit.

**Comment by BorisTheBrave** [comment]
> Without having to dive into anything else, I can tell by just looking at this one line

It's already in the docstring.

> That kind of change is exactly what we need moving forward with Manim. Everything has to be more explicit, better checked and less inferred or implicit.

Ok, have fun doing that. I am no longer interested enough in this PR to push it further.

**Comment by christopher-besch** [comment]
> It's already in the docstring.

Yes it is, but it isn't enforced:
> If we don't have that, it'd be very easy for a forgotten `return self` to slip through the cracks and end up in production.

And I think everything that can easily be expressed in code (which this in my opinion can) should be, rather than in comments.

> I am no longer interested enough in this PR to push it further.

I'm very sorry to hear that. Thanks for your contribution, anyway!

**Comment by Darylgolden** [comment]
>If we don't have that, it'd be very easy for a forgotten return self to slip through the cracks and end up in production.

I don't see how something like that can realistically happen with tests and our review process. IMO, `return self` methods are common and simple enough that adding explicit typehints adds no real benefit. But if someone takes the time to do it, I won't oppose.

**Comment by christopher-besch** [comment]
I personally want Manim to use type hints *everywhere*. I think that would generally improve the code a lot.
It's true that types are a pain most of the time. But the few times when they do save your butt, you're damn glad you have them.
So I think there should be a very good reason for not using that safety net, and I don't think `return self` methods offer such a reason.

But yeah, that's just my opinion: I use C++ everywhere I can because of it's amazing static typing, I use TypeScript rather than JavaScript even if it takes +5h to set up and I use Python typehints for everything that I care about in the slightest.

**Review by behackl — APPROVED** [review]
This PR improves the current situation for autocompletion, while at the same time not regressing the documentation. I think it is fine to merge this. We can still revisit our global type hint strategy later on.

**Review by christopher-besch — APPROVED** [review]

**Pull request merged**
