### PR TITLE
Fixed type annotations in :mod:`.mobject.three_dimensions`

### PR DESCRIPTION
**Pull request by citrusmunch**
wherever possible, use an object as the type instead of a string
avoid recursive types as they only have partial support

## Links to added or changed documentation pages

https://manimce--2401.org.readthedocs.build/en/2401/

## Further Information and Comments

Also seems like a lot of the diff is for black formatting :)

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Review by Darylgolden — CHANGES_REQUESTED** [review]
Changes to types LGTM, but it seems like your editor or linter has added a bunch of trailing commas, which we've agreed not to use.

**Comment by citrusmunch** [comment]
> Changes to types LGTM, but it seems like your editor or linter has added a bunch of trailing commas, which we've agreed not to use.

Right, the black formatter did this automatically, which I have configured to execute on save. Is this not also in the pre-commit [hook](https://github.com/ManimCommunity/manim/blob/main/.pre-commit-config.yaml#L37-L40)?

I'm not sure how to configure it but maybe in the [`pyproject.toml`](https://github.com/ManimCommunity/manim/blob/main/pyproject.toml#L110) (the link in that comment is dead, prob meant [here](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-format)).

In the meantime I can disable it and remove those commas, I just want to make sure they won't be introduced again by the pre-commit.

**Comment by Darylgolden** [comment]
Strange, it should have been disabled in #2191. Can you try removing the trailing commas?

**Comment by citrusmunch** [comment]
Done! Seems like black doesn't apply itself in the pre-commit (or I can't find the configuration to only apply in diffed regions)? Not sure exactly how that works, but hopefully this is inline with the style!

One question: should I be avoiding trailing commas in all cases, or just refrain from touching irrelevant code?

**Review by Darylgolden — APPROVED** [review]
LGTM

**Pull request merged**
