### PR TITLE
Prepare new release: v0.2.0

### PR DESCRIPTION
**Pull request by behackl**
This PR prepares the upcoming release: it bumps the version number and includes the oneline summaries for all merged PRs (including a reference to them) in the changelog.

### CODE REVIEW

**Comment by behackl** [comment]
@eulertour: feel free to use this branch for preparing the release; I've mainly just copy/pasted the changelog we've maintained in the wiki to `changelog.rst` (and made sure that everything is formatted correctly + minor consistency edits). 

I'll try to monitor whether further PRs are merged before I go to sleep and update the changelog on this PR accordingly -- if I miss something, please copy the summary of the merged PR to the correct place in the changelog. Thanks! :-)

**Review by kolibril13 — APPROVED** [review]

**Review by naveen521kk — CHANGES_REQUESTED** [review]
Looks like changelog misses about ManimPango.

**Comment by behackl** [comment]
> Looks like changelog misses about ManimPango.

https://github.com/ManimCommunity/manim/pull/894/files#diff-ef86237172bb2f91c585e845b38d6fb28bb6ac128ff8efa541cdd86f81751bf2R71 ?

**Review by naveen521kk — APPROVED** [review]

**Comment by eulertour** [comment]
Although I don't know if the automated release action works yet, doing this each time will make the release process more manual which is something we should try to avoid.

**Pull request merged**
