### PR TITLE
Example and test for TexTemplate

### PR DESCRIPTION
**Pull request by kolibril13**
As there are currently no Text and Tex tests, I thought it's a good idea to get started with this.
I also added one example using a Custom template to the docs.

### CODE REVIEW

**Comment by kolibril13** [comment]
Interesting.
Locally (mac os) the tests are passing, and also ubuntu is passing here.
However, mac and windows are failing:
```
    @pytest.mark.parametrize("scene_to_test", get_scenes_to_test(__name__), indirect=False)
    def test_scene(scene_to_test, tmpdir, show_diff):
>       GraphicalUnitTester(scene_to_test[1], MODULE_NAME, tmpdir).test(show_diff=show_diff)

tests\test_graphical_units\test_tex_and_text.py:26: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests\utils\GraphicalUnitTester.py:69: in __init__
    self.scene.render()
manim\scene\scene.py:185: in render
    self.construct()
tests\test_graphical_units\test_tex_and_text.py:17: in construct
    tex = CustomMathTex(r"dx dy = |r| dr d\phi").scale(3)
tests\test_graphical_units\test_tex_and_text.py:15: in CustomMathTex
    return MathTex(*tex_strings, tex_template=stix2)
manim\mobject\svg\tex_mobject.py:462: in __init__
    raise compilation_error
manim\mobject\svg\tex_mobject.py:445: in __init__
    **kwargs,
manim\mobject\svg\tex_mobject.py:276: in __init__
    tex_template=self.tex_template,
manim\utils\tex_file_writing.py:45: in tex_to_svg_file
    tex_file, tex_template.tex_compiler, tex_template.output_format
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

tex_file = 'C:/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/test_scene_scene_to_test0_13/test_graphical_units/tests_cache/tex_and_text/TexTemplateFontTest/Tex/2fbe160d4d573819.tex'
tex_compiler = 'latex', output_format = '.dvi'
```
Unfortunately, I don't know what to do about it, but I will leave this pr open for a few weeks.
If someone finds the error, nice! If not I'd close this pr again.

**Comment by huguesdevimeux** [comment]
`Tex` and `Text` used to be tested a long time ago (~10 months ago) but were removed due to laTex and Text SVG being too erratic and system-dependent. See #157. It's possible that this has changed given the number of improvements in these two features.

I don't know this error, though.

**Comment by kolibril13** [comment]
> `Tex` and `Text` used to be tested a long time ago (~10 months ago) but were removed due to laTex and Text SVG being too erratic and system-dependent. See #157. It's possible that this has changed given the number of improvements in these two features.
> 
> I don't know this error, though.

Thanks for digging into this.
But as there were some occasions, where the custom template was breaking, I think it would be nice to include this test, not for all os systems, but maybe only for a few like this:
```py
@pytest.mark.skipif(sys.platform != 'linux', reason="Linux tests")
def test_linux():
    assert True
```
I know it is not perfect, but I think testing latex on only one os is better then not testing it at all.

**Review by behackl — CHANGES_REQUESTED** [review]
The documentation fails to build:

```
ERROR    LaTeX compilation error!    tex_file_writing.py:178
                             latex reports:                                     
                    ERROR    ! LaTeX Error: File         tex_file_writing.py:189
                             `stix2.sty' not found.                             
```

**Comment by kolibril13** [comment]
ok, as I think that this pr is not that important, I am closing this.

**Pull request closed without merging**
