### PR TITLE
Fix typo in import statement

### PR DESCRIPTION
**Pull request by Pragyaan-6988**
## List of Changes
- Fix typo in import statement

### CODE REVIEW

**Comment by behackl** [comment]
Thank you for your contribution! This looks good to me in general.

There is a second import over at https://github.com/ManimCommunity/manim/blob/6585871ec96a0f6f85b5f319373b9538aa842c34/tests/helpers/video_utils.py#L7 which should also be changed (but probably rather to `from manim import logger` -- @leotrs?).

**Comment by leotrs** [comment]
Yes. All imports related to config or logger should just get it from the top level package. `from manim import logger, config`.

**Comment by Pragyaan-6988** [comment]
Ah, looks like I messed up something. Am I supposed to update my fix-import branch with the upstream/master before any further commits? Or is this a different issue? Sorry for the possibly naive question, I'm new to these things.

**Comment by behackl** [comment]
Your changes actually look good to me, the pipeline is failing for an unrelated reason. We'll have to investigate, but from what I can see in the logs, this will affect all pipelines.

**Review by behackl — APPROVED** [review]
Seemed to have been an unrelated hiccup, restarting the pipelines fixed the problem.

LGTM, thank you very much for your contribution!

**Review by leotrs — APPROVED** [review]

**Pull request merged**
