### PR TITLE
Added a GitHub Action for automatic validation of your citation metadata

### PR DESCRIPTION
**Pull request by fdiblen**
## Overview: What does this pull request change?

- adds a workflow to validate `CITATION.cff` file

## Motivation and Explanation: Why and how do your changes improve the library?

Hello!

We noticed that your repository is using the Citation File Format to store citation metadata in `CITATION.cff`. This Pull Request automates validation of that file using the [cffconvert GitHub Action](https://github.com/marketplace/actions/cffconvert). That way, it's a little bit easier to be robust against future changes to the `CITATION.cff` file.

BTW it's perfectly fine if you don't feel like accepting this Pull Request for whatever reason -- we just thought it might be helpful is all.

We found your repository using a partially automated workflow; if you have any questions about that, feel free to create an issue over at https://github.com/cffbots/filtering/issues/

On behalf of the cffbots team,
@abelsiqueira / @fdiblen / @jspaaks

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by Darylgolden** [comment]
Hi, thanks for your PR!

I'm not sure if I'm missing something, but the action doesn't appear to have been run?

**Comment by fdiblen** [comment]
> Hi, thanks for your PR!
> 
> I'm not sure if I'm missing something, but the action doesn't appear to have been run?

Hi @Darylgolden,
As the Pull Request is coming from the fork of your repository, the action will run when it is merged. The fork of the repository is here: https://github.com/cffbots/manim

**Comment by Darylgolden** [comment]
Ah, I see now. Won't it be better if it's set to run upon a pull request too, like our other actions? Also, can you provide more details on what your action does? What exactly does it validate?

**Comment by Darylgolden** [comment]
I also don't see the action run on your [fork](https://github.com/cffbots/manim/actions).

**Comment by fdiblen** [comment]
> Ah, I see now. Won't it be better if it's set to run upon a pull request too, like our other actions? Also, can you provide more details on what your action does? What exactly does it validate?

The action validates `CITATION.cff` file against [CFF schema](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md). When there is a problem in the `CITATION.cff` it will warn you and give you hints to fix it.

The action will be triggered on every push that includes changes in `CITATION.cff` file. This covers Pull Requests, too.

**Comment by fdiblen** [comment]
> I also don't see the action run on your [fork](https://github.com/cffbots/manim/actions).

That is expected as I haven't modified `CITATION.cff` when creating the Pull Request.
I have just updated the `cff-version` to 1.2.0 to trigger the action. You can see the running action here: https://github.com/cffbots/manim/runs/5093186774?check_suite_focus=true

**Review by behackl — APPROVED** [review]
I think this is fine. Thank you for PRing this!

**Pull request merged**
