### PR TITLE
Makes windows build faster, by using a prebuild Latex from TinyTex CI and avoid using Choco

### PR DESCRIPTION
**Pull request by naveen521kk**
In this PR;
- Makes windows build faster, by using a prebuild Latex from [TinyTex CI](https://ci.appveyor.com/project/yihui/tinytex) and avoid using Choco and download directly from the site as Choco is slower in actions.

### CODE REVIEW

**Comment by leotrs** [comment]
This looks good to me, but I'm not a windows expert. I'll let others approve/request changes.

**Comment by leotrs** [comment]
I believe @XorUnison is on Windows? @XorUnison, if you are not available to review this, could you mention somebody else who is on windows? Please and thanks!

**Comment by XorUnison** [comment]
> 
> 
> I believe @XorUnison is on Windows? @XorUnison, if you are not available to review this, could you mention somebody else who is on windows? Please and thanks!

Not sure who else is on windows, and I'd rather not bother with switching branches before I at least have the next commit for #210 done. But once that's dealt with I can have a look at this and test it.

**Comment by Aathish04** [comment]
> > I believe @XorUnison is on Windows? @XorUnison, if you are not available to review this, could you mention somebody else who is on windows? Please and thanks!
> 
> Not sure who else is on windows, and I'd rather not bother with switching branches before I at least have the next commit for #210 done. But once that's dealt with I can have a look at this and test it.

I don't think you'll have to do much "testing", considering that this PR just changes the Github CI workflow for windows.

**Comment by XorUnison** [comment]
> I don't think you'll have to do much "testing", considering that this PR just changes the Github CI workflow for windows.

It's purely focused on the building, eh... But I also have to say I don't quite know what's going on with the builds.

**Comment by naveen521kk** [comment]
It does nothing but downloads some zip from the respective places then extracts it adds to path, installs what is not there. 
Previous, it did used a batch script which had build (Takes about 2 min) now it just downloads the prebuild thing. Also, previously it used choco for ffmpeg and sox, now it directly downloads from respective sites and adds to path.

**Pull request merged**
