### PR TITLE
creation of a test for add_fixed_in_frame_mobjects

### PR DESCRIPTION
**Pull request by lucasricci**
## Overview: What does this pull request change?

This PR basically add a test for ``add_fixed_in_frame_mobjects``, this solves partially the issue #193.
- The code that I write was:
```python
@frames_comparison(base_scene=ThreeDScene)
def test_AddFixedInFrameMobjects(scene):
    scene.set_camera_orientation(phi=75 * DEGREES, theta=-45 * DEGREES)
    text = Text("This is a 3D text")
    scene.add_fixed_in_frame_mobjects(text)
```
And the output of the test is:
```python
-----------------------------------------------------------------------------------------
TOTAL                                                                 18679  13057    30%
Coverage XML written to file coverage.xml

=============================== 1 passed, 5 warnings in 4.76s ================================
```

## Motivation and Explanation: Why and how do your changes improve the library?

This PR was motivated by issue #193, and it contribute for the library because with more tests the code is less sucetible to mistakes and bugs, what make the usual user experience much better and pleasant.

## Links to added or changed documentation pages

***Nothing to add***

## Further Information and Comments

***Nothing to comment***

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by lucasricci** [comment]
Why are the tests failing? Can someone help me?

**Comment by lucasricci** [comment]
@Darylgolden can you help me? Idk why the tests from windows and mac are failing, I can't see any incongruence in my code, maybe another person looking the code might spot an error.

**Comment by behackl** [comment]
Don't use `Text` in your tests: the default font which is used to render text is different for different operating systems. This is why your tests fail on MacOS and Windows, they use a different font to render the text.

**Comment by lucasricci** [comment]
@behackl I see, my mistake.

**Comment by lucasricci** [comment]
Just fixing, the correct code is:
```py
def test_AddFixedInFrameMobjects(scene):
    scene.set_camera_orientation(phi=75 * DEGREES, theta=-45 * DEGREES)
    text = Tex("This is a 3D tex")
    scene.add_fixed_in_frame_mobjects(text)
```

**Review by huguesdevimeux — APPROVED** [review]

**Comment by lucasricci** [comment]
@behackl Problem fixed!

**Pull request merged**
