### PR TITLE
Fix UpdateFromFunc neglecting rate_func

### PR DESCRIPTION
**Pull request by sparshg**
## Overview: What does this pull request change?

`UpdateFromAlphaFunc` animation didn't follow `rate_func` due to #1678 

## Motivation and Explanation: Why and how do your changes improve the library?

https://user-images.githubusercontent.com/43041139/131846727-6cb9eb00-6b3f-4e02-9915-4fbd4f8fe315.mp4

https://user-images.githubusercontent.com/43041139/131846705-0d5b1a5e-a714-4b46-b579-8957614346d3.mp4

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by huguesdevimeux** [comment]
Correct me if I'm wrong, but I don't think this is the right way to fix this issue, given that these two animations are wrongly written.

The problem with the current implementation of `UpdateFromFunc` and `UpdateFromAlphaFunc` is that they use `interpolate_mobject`, instead of `interpolate_submobject`.
The major difference between the two is that [`interpolate_mobject`](https://github.com/ManimCommunity/manim/blob/73f87bd66a2208c4309adf53deb0c281644547df/manim/animation/animation.py#L278-L291) computes the `subalpha` ( which is essentially` rate_func(alpha)`), and only **then** feeds `interpolate_submobject`, with the `subalpha,` not the alpha. `Interpolate_mobject` compute the subalpha while taking other parameters, such as lag_ratio, etc, and this is not done in your fix (you only compute `rate_func(alpha)` ). Hence, for example, with a `lag_ratio`, the animation won't work.

i think the fix should instead look like it (**I didn't test it, so it's can be completely wrong !**) :

```class UpdateFromFunc(Animation):
    """
    update_function of the form func(mobject), presumably
    to be used when the state of one mobject is dependent
    on another simultaneously animated mobject
    """

    def __init__(
        self,
        mobject: "Mobject",
        update_function: typing.Callable[["Mobject"], typing.Any],
        suspend_mobject_updating: bool = False,
        **kwargs
    ) -> None:
        self.update_function = update_function
        super().__init__(
            mobject, suspend_mobject_updating=suspend_mobject_updating, **kwargs
        )

    def interpolate_submobject(self, submobject, starting_submobject, alpha: float):
        self.update_function(self.mobject)
    # def interpolate_mobject(self, alpha: float) -> None:
    #     self.update_function(self.mobject)


class UpdateFromAlphaFunc(UpdateFromFunc):
    # def interpolate_mobject(self, alpha: float) -> None:
    #     self.update_function(self.mobject, alpha)
    def interpolate_submobject(self, submobject, starting_submobject, alpha: float):
        self.update_function(self.mobject, alpha)
```

**Comment by sparshg** [comment]
hmm, before that PR, `interpolate_mobjects` was fed `rate_func(alpha)` for animations, but as it was changed, and `interpolate_mobjects` is simply fed `alpha`, the animations like Rotating also neglects `rate_func`

**Comment by sparshg** [comment]
Also, `PhaseFlow` and `MoveAlongPath` were fixed using similar approach as in [this commit](https://github.com/ManimCommunity/manim/pull/1678/commits/964df0b8d0382854b310bb46548f7b2b43582283)

**Comment by huguesdevimeux** [comment]
Do this work when you use a `lag_ratio` ?

**Comment by sparshg** [comment]
I see the `lag_ratio` doesn't work (neither it did before #1678), but applying the function to `submobjects` individually isn't same as applying to whole mobject, and we are not interpolating between initial and final state like transform..
Though I tried something like this, make a `current_submobject` (that is the copy of our initial mobject) and then interpolate submobjects to the `current_submobject` which will follow `rate_func` and `lag_ratio`

This approach does work,
```py
 v = VGroup(*[Square() for _ in range(2)]).arrange()
 self.play(UpdateFromAlphaFunc(v, lambda m, a: m.move_to(UP * a)), lag_ratio=0.5)
```

https://user-images.githubusercontent.com/43041139/133144589-d140b7ef-7988-45d9-ab36-7d10fe54818a.mp4

I can play `ManimBanner().create()` also, but with `ManimBanner.expand()` it fails coz `current_mobject` because the fed function removes a submobject at `alpha == 1` ig, due to which interpolation for submobjects fail

**Review by behackl — CHANGES_REQUESTED** [review]
While the tests pass, the documentation build fails with

```py
TypeError: <lambda>() takes 1 positional argument but 2 were given
```

**Comment by behackl** [comment]
This has actually been taken care via #2211. Closing.

**Pull request closed without merging**
