### PR TITLE
Fixed bugs and added examples to methods and classes in matrix.py

### PR DESCRIPTION
**Pull request by PhotonSpheres**
## Motivation

I wanted to do some examples of the Matrix-Mobjects but it seemed to be broken, so I added some changes and some examples.

## Explanation for Changes

MobjectMatrix was broken, for me at least. The issue was some sort of weird numpy array creation. I removed the dependency of numpy in this PR.

https://manimce--1636.org.readthedocs.build/en/1636/reference/manim.mobject.matrix.html?highlight=matrix#module-manim.mobject.matrix

https://manimce--1636.org.readthedocs.build/en/1636/reference/manim.mobject.matrix.Matrix.html

https://manimce--1636.org.readthedocs.build/en/1636/reference/manim.mobject.matrix.MobjectMatrix.html

https://manimce--1636.org.readthedocs.build/en/1636/reference/manim.mobject.matrix.DecimalMatrix.html

https://manimce--1636.org.readthedocs.build/en/1636/reference/manim.mobject.matrix.IntegerMatrix.html

## Testing Status

I didn't write any tests, should I for this?

## Further Comments

Not sure if I improved this module - any comments are highly appreciated.

## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [ ] I have written a descriptive PR title (see top of PR template for examples)
- [ ] I have written a changelog entry for the PR or deem it unnecessary
- [x] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [x] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [x] The PR title is descriptive enough
- [x] The PR is labeled correctly
- [x] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by kolibril13** [comment]
Really great stuff!
Only one remark:
image
The streamline example takes nearly 6 seconds of build time, while the other examples take only 0.1 seconds.
Maybe you can choose another background?
Maybe a star or the manim banner?

**Comment by PhotonSpheres** [comment]
> The streamline example takes nearly 6 seconds of build time, while the other examples take only 0.1 seconds.
> Maybe you can choose another background?
> Maybe a star or the manim banner?

Cheers! That it was quite steep, I agree. I will try to find something else. Thanks for the suggestions!

**Comment by PhotonSpheres** [comment]
Okay, the current one takes 1.9s. Still a little much maybe, but I think it gets the point across even better. I didn't quite feel it that well with a mobject or the banner in the background. How do you feel about this one?

**Comment by kolibril13** [comment]
image
I like it! :)

**Review by kolibril13 — APPROVED** [review]

**Review by jsonvillanueva — COMMENTED** [review]
Is the image in the background for `BackgroundRectanglesExample` added purely just to see the backgrounds for the matrices? I think if we're going for simplicity we could add a colored rectangle in the background instead of an ImageMobject?

**Comment by kolibril13** [comment]
I think the long rendering time of that example comes from rendering latex of the digits, not because of the ImageMobject.
When I rendered it locally, the first rendering was slow, the second time rendering was fast.
```py
class Example(Scene):
    def construct(self):
        background= Rectangle().scale(3.2)
        background.set_fill(opacity=.5)
        background.set_color([TEAL, RED, YELLOW])
        self.add(background)
        m0 = Matrix([[12, -30], [-1, 15]],
            add_background_rectangles_to_entries=True)
        m1 = Matrix([[2, 0], [-1, 1]],
            include_background_rectangle=True)
        m2 = Matrix([[12, -30], [-1, 15]])
        g = Group(m0, m1, m2).arrange(buff=2)
        self.add(g)
        ```
image

here is an alternative idea.

**Comment by jsonvillanueva** [comment]
> I think the long rendering time of that example comes from rendering latex of the digits, not because of the ImageMobject.
> When I rendered it locally, the first rendering was slow, the second time rendering was fast.

Okay! Thanks for clarifying!

> here is an alternative idea.

I like it.

**Pull request merged**
