### PR TITLE
Adding spell checker as a pre-commit hook

### PR DESCRIPTION
**Pull request by Skaft**
## Changelog / Overview

* Adds a pre-commit hook for [codespell](https://github.com/codespell-project/codespell)
* Fixes a bunch of spelling mistakes in code and documentation

## Motivation

Removes existing spelling mistakes, and prevents future ones.
## Explanation for Changes

Spelling errors will keep cropping up, with a pre-commit hook to hunt them down we can reduce the problem. Of course `codespell` is not the only option for that, and there might be better alternatives. This is the first I tried, but it seems to work well out of the box.

## Testing Status

Most changes are in documentation, but some variable names have been changed. So I ran the pytest suite which passed. 

## Further Comments

* Possibly controversial: There are a few cases where it will treat truncated variable names as spelling errors. I have changed the ones it complained about, so you can see the extent of that meddling within this PR. In my opinion, they are either variable names that benefit from a full name anyway, or names that can be changed without consequence. But maybe this could be an annoyance at some later point.
* I'm not sure the dependency setup is complete. Should I tweak the poetry files in some way?
* The errors fixed here are all it could find in the current state of the repo, **except** for a false positive in a .svg file. Lines triggering false positives can be listed in `.codespell_ignorelines`.
* Codespell works by looking for common spelling mistakes, and there are different dictionaries it can use to find those. It's currently running on defaults, but tweaking that setup might improve results.

## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [x] My new functions/classes either have a docstring or are private
- [x] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [x] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by Skaft** [comment]
Ah-hmm. Right. I guess I can't just ignore the changelog. Should I correct the spelling errors in it, or set up codespell to ignore that folder? I'll make it skip svg files, those aren't texty enough I suppose.

**Comment by Skaft** [comment]
Tried to add the `.codespellrc` and use it to make it skip the changelog directory and svg files. Seems to work locally, not sure why it's different on CI?

**Comment by naveen521kk** [comment]
> Should I correct the spelling errors in it, or set up codespell to ignore that folder?

You can correct spelling in the changelog, no problems with that :).

**Comment by Skaft** [comment]
> You can correct spelling in the changelog, no problems with that :).

Thanks for input ^_^

* Looks like this is passing CI now! I've been having some issues with line endings. Not sure how much of that struggle is my own fault, and how much is on the shoulders of codespell / pre-commit. This currently [unmerged PR](https://github.com/codespell-project/codespell/pull/1889) could be worth keeping an eye on though in case these problems resurface.
* I've added the file `.codespell_ignorelines` where any lines triggering false positives can be chucked. There's currently a line from a .svg file in it, but that was the only troublesome line so far.

I'll open this for review now as I think it's working properly.

**Review by naveen521kk — APPROVED** [review]
LGTM! Thanks.

**Comment by peternewman** [comment]
>     * Looks like this is passing CI now! I've been having some issues with line endings. Not sure how much of that struggle is my own fault, and how much is on the shoulders of codespell / pre-commit. This currently [unmerged PR](https://github.com/codespell-project/codespell/pull/1889) could be worth keeping an eye on though in case these problems resurface.

Was it just the line endings of the ignore file you were having issues with then @Skaft ?

**Comment by Skaft** [comment]
@peternewman Sorry, I don't recall the specifics, it's been over a year since I looked at this.

**Comment by peternewman** [comment]
Heh, no worries @Skaft .

**Pull request merged**
