### PR TITLE
deprecate get_updaters and just use the updaters member

### PR DESCRIPTION
**Pull request by leotrs**

### CODE REVIEW

**Comment by PgBiel** [comment]
I think that it's better to make a big PR about removing `.get_<x>` in general and replacing them with either `@property` or just an assignable value instead of making small PRs about them

**Comment by huguesdevimeux** [comment]
@PgBiel Could you create an issue on this ?

**Comment by PgBiel** [comment]
on it

**Comment by leotrs** [comment]
I'm closing this in favor of #134

**Pull request closed without merging**
