### PR TITLE
Typo substring to isolate

### PR DESCRIPTION
**Pull request by asjadaugust**
## Overview: What does this pull request change?

Fixes a minor documentation bug.

## Motivation and Explanation: Why and how do your changes improve the library?

There was a minor typo in the documentation as explained in the issue #1917 

## Links to added or changed documentation pages
 
[Example: CorrectLaTeXSubstringColoring](https://docs.manim.community/en/stable/tutorials/using_text.html#correctlatexsubstringcoloring)

## Reviewer Checklist
- [x] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [x] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [x] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by huguesdevimeux** [comment]
Fixes #1917

**Review by huguesdevimeux — APPROVED** [review]
SGTM !

**Comment by behackl** [comment]
> SGTM !

Please don't forget to label PRs correctly before you are merging, @huguesdevimeux. :-)

Thanks for your contribution, @asjadaugust!

**Comment by huguesdevimeux** [comment]
woops sorry !

**Pull request merged**
