### PR TITLE
Added neat projects from example_scenes folder

### PR DESCRIPTION
**Pull request by kolibril13**
As title.
One more chapter for the docs

### CODE REVIEW

**Comment by kolibril13** [comment]
I think we should reduce example_scenes/basic.py to only 3 very nice looking examples and get rid of the rest.
Also in this PR, I think now every example are super necessary.
What do you think, which one should be removed?
See here:
https://manimce--538.org.readthedocs.build/en/538/examples/neat_projects.html

**Review by leotrs — APPROVED** [review]

**Comment by eulertour** [comment]
The name of the page doesn't make sense for these; they aren't projects.

**Comment by kolibril13** [comment]
I partly agree on that.
I thought they are small projects, that users can discover easily.
But what would be alternatives, @eulertour ?
Maybe somethink like "Manim Overview"?
Or  "Basic Scenes"
But I think neat projects is a good title when we would add one sentence like:
"In this section you can see some scenes that will help you to get to know manim in several contexts"

**Comment by eulertour** [comment]
Since we don't have any projects listed yet we can just rename it to "Examples" and create a projects page when we've decided on some to showcase.

**Comment by kolibril13** [comment]
> Since we don't have any projects listed yet we can just rename it to "Examples" and create a projects page when we've decided on some to showcase.

As Examples is already the chapter name, I don't like the subchapter to have the same name.
See here:https://manimce.readthedocs.io/en/latest/examples.html
I would be also fine with  "Demonstration of manim", "Our Favorite Scenes".

And I just had the idea of a new section called "Release Highlights" for new features, that are not possible in the 3b1b version

**Comment by leotrs** [comment]
What is the difference between the current "neat projects" and "advanced examples"? I think we can put these under "advanced" for now.

**Review by leotrs — APPROVED** [review]

**Comment by eulertour** [comment]
This is fine for now but we should update it with examples that are advanced when we find some.

**Review by eulertour — APPROVED** [review]

**Comment by eulertour** [comment]
I didn't realize you were taking the examples out of `examples/basic.py`. Those provided a quick way to see how updaters and tex rendering worked, so they should be replaced.

**Comment by leotrs** [comment]
Uuuh I didn't realize this either. @kolibril13 next time please add a more precise description of all changes you are making. In order to do this, I suggest you use the PR template. 

Also, @reviewers (me included), let's pay more attention to what we are reviewing :sweat_smile:

**Comment by kolibril13** [comment]
> I think we should reduce example_scenes/basic.py to only 3 very nice looking examples and get rid of the rest.

I interpreted the thumbs up as a sign that this would be ok. But alright, I will add them back! :)
see here: https://github.com/ManimCommunity/manim/pull/564

**Pull request merged**
