### PR TITLE
Porting Developer Docs from github wiki to Documentation 

### PR DESCRIPTION
**Pull request by GameDungeon**
## Overview: What does this pull request change?
Ports the Developer Docs from github wiki to official Documentation.

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by Darylgolden** [comment]
As @hydrobeam said in Discord, I think RST is harder to use than markdown, and for developer documentation I'd like to reduce the friction towards writing them as much as possible. Could you look into using a markdown parser and using the original markdown instead?

**Comment by GameDungeon** [comment]
I think using rst is far better. ( There is a good reason that we use it for every other piece of documentation ) Markdown can't be easily translated and with rst we use the manim directive for examples, and also seamlessly integrate with the rest of the docs.

Also IMO, people think rst is a lot harder because they use it less, but after working with it for a bit you can pick it up fast.

**Comment by hydrobeam** [comment]
It's not only that writing rst is more difficult, but contributing to the dev docs would now require a PR and a review, which makes the process a lot more tedious. Markdown is more convenient, and we can use something like https://rust-lang.github.io/mdBook/ instead of adding developer information to the main page, where it isn't really relevant to the rest of the docs.

Also, in the case that this is merged, each section should be under its own sub article, instead of all on one page.

**Comment by GameDungeon** [comment]
To avoid confusion I think we should first decide on what the Developer Docs are. ( I currently think this is the main disconnect )

My personal idea behind them is an overview of the process of turning the input code (I'm not sure what to call it) into a rendered animation. A piece of documentation that allows new contributors to understand the internals of manim. Instead of just going over fine details for devs. My version of this might require a name change. 

I do wonder when you heard the name Developer Docs what info did you think would go in them ( as I think this could have other solutions )

**Comment by behackl** [comment]
Removed from the milestone due to need of discussion.

I agree with @hydrobeam regarding separation, this should not really be one big file. Personally, I feel that documentation giving an in-depth description of a specific module should actually live in the "normal" docs, e.g., in a specific section in the module documentation.

Other parts, like the details about the rendering loop and such, deserve their own page somewhere. Maybe our tutorial category should be cleaned up / renamed to something that can also house these things. (Basically, the "building blocks" article isn't too much different from that, conceptually.)

**Comment by Darylgolden** [comment]
Closed in favor of #2549.

**Pull request closed without merging**
