### PR TITLE
Add links from reference manual to source code on GitHub

### PR DESCRIPTION
**Pull request by behackl**
## List of Changes
- Enable links from reference manual to source code on GitHub

## Explanation for Changes
The actual work is carried out by the `codelink` extension of Sphinx, in order to work the function `linkcode_resolve` is added. The way this is currently written ensures (in theory) that deployed documentation at RTD links to the correct versions, and when building everywhere else it links to our current master.

## Testing Status
Links work in locally built documentation.

## Further Comments
It is not (easily?) possible to have correct links for documentation previews deployed from merge requests.

## Acknowledgement
- [x] I have read the [Contributing Guidelines](https://github.com/ManimCommunity/manim/wiki/Documentation-guidelines-(WIP))

### CODE REVIEW

**Review by naveen521kk — APPROVED** [review]
LGTM! But on readthedocs theme it is done automatically. How? And why not in this theme?

**Comment by behackl** [comment]
> But on readthedocs theme it is done automatically. How? And why not in this theme?

I don't know.

**Review by leotrs — APPROVED** [review]

**Comment by leotrs** [comment]
I believe some themes come with pre-defined extensions. So maybe RTD theme is doing this already.

@behackl can you post an image of what the end product looks like? Where does the link show up and how? etc

**Comment by behackl** [comment]
Here is how it looks locally:

image

... and while writing this, RTD has also finished deploying, see it in action here: https://manimce--703.org.readthedocs.build/en/703/reference/manim.mobject.mobject.Mobject.html#manim.mobject.mobject.Mobject

**Comment by naveen521kk** [comment]
Eventhough for PR it doesnt work but ok.

**Comment by behackl** [comment]
Ah, let me be more precise: for PRs, it also just defaults to link to our master branch. The links will still be there!

**Comment by behackl** [comment]
... ah, that was wrong; maybe I can do something. I'll investigate some more and send a follow-up PR in case this can be fixed.

**Comment by naveen521kk** [comment]
Hmm, I get a 404 page when I tried it. The version number was the PR number?

**Pull request merged**
