### PR TITLE
docs: improve installation FAQ's

### PR DESCRIPTION
**Pull request by SirJamesClarkMaxwell**
## Overview: What does this pull request change?

I added it because it is so common that in Windows installation has failed and in almost all cases this approach, presented in the section of docs is working. 

## Links to added or changed documentation pages

https://docs.manim.community/en/stable/faq/installation.html#different-versions

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Review by JasonGrace2282 — COMMENTED** [review]
A lot of the stuff here is mentioned in the [installation guide](https://docs.manim.community/en/stable/installation/windows.html). It might be more helpful to include the `choco` warning in there, and reference the installation docs for things like changing `$PATH`.

It might be a good idea to also add a troubleshooting section to the installation guide with `manim checkhealth` and asking users to make sure they only have one python on their system.

**Comment by SirJamesClarkMaxwell** [comment]
So, maybe I will add a new section in [here](https://docs.manim.community/en/stable/installation/windows.html) for the simplex installation? Without any additional features like choco, scoop, or virtual environments?

**Comment by SirJamesClarkMaxwell** [comment]
Where is my previous message? Does it disappear after you have changed your original one?

**Comment by SirJamesClarkMaxwell** [comment]
I see one problem. When I was installing manim, with cleaning pytnon installation. I have two version of python. The only thing  i did is pure python installation and after that pip install manim. Potentially this is a common problem.

**Comment by JasonGrace2282** [comment]
> So, maybe I will add a new section [here](https://docs.manim.community/en/stable/installation/windows.html) for the simple installation

The installation is already covered on that page, but a section on troubleshooting could help, maybe?

> create from 3  files, one for each operating system where all things will be installed manually?

So, an installer? Regardless, that would be a different matter than what the PR is about, so it should be discussed elsewhere.

**Comment by SirJamesClarkMaxwell** [comment]
1. I have to create a new PR for a simple installer. 
2. I see at least one problem: if in official installation, there would be a warning that if something will not work go into this section of docs, undo what you have done, and then do something else. It would annoy me quite a bit. But if you say this is what I should do, I will do it.🫡

**Pull request closed without merging**
