### PR TITLE
Fixes #840

### LINKED ISSUE #840: Axes class no longer sets x_min, x_max, y_min, y_max values to self.x_min, self.x_max, self.y_min and self.y_max respectively.
## Description of bug / unexpected behavior

When Axes class instance is created with kwargs ->`` x_min``, ``x_max``, ``y_min``,`` y_max``, they are not shown in the generated Axes animation.
This issue arose after migration from dictionaries.
P.S. I have also started getting a warning "Creating a dummy animation" which if I am right is because animation receives mobject as None.

## Expected behavior

Previoulsy, it worked just fine. Thus, setting these kwargs to ``self.x_min``, ``self.x_max``, ``self.y_min`` and ``self.y_max`` was expected.

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
from manim import *


class AxesExample(Scene):
    def construct(self):
        axes1 = Axes(
            x_min = 0,
            x_max = 5,
            y_min = -1,
            y_max = 1,
            axis_config = {
                "include_numbers": True,
                "include_tip" : False,
                "decimal_number_config" : {"num_decimal_places": 1, "color": LIGHT_GREY}
            },
            x_axis_config={
                # "x_min" : 0,
                # "x_max":5,
                "numbers_to_show": np.arange(1,6)
                },
            y_axis_config={
                # "y_min" : 0,
                # "y_max":5,
                "numbers_to_show": np.arange(-1,2)
                }
            )
        # axes1.stretch_to_fit_width(4)
        # axes1.stretch_to_fit_height(3)
        self.play(ShowCreation(axes1))
        self.wait()
        graph = axes1.get_graph(lambda x:np.sinc(x), x_min = 0, x_max = 5, color = RED)
        self.play(ShowCreation(graph))
        self.wait()
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

image

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

## Additional comments

It seems to be that the ``CoordinateSystem`` class is not able to find the ``"x_min"``, ``"x_max"``, ``"y_min"`` and ``"y_max"`` attributes in self thereby setting the ``self.x_min``, ``self.x_max``, ``self.y_min`` and ``self.y_max`` to the dimensions of the frame.

https://github.com/ManimCommunity/manim/blob/62f0147f8135e68323fd2a2a2f8258772faa8c9f/manim/mobject/coordinate_systems.py#L132-L148

https://github.com/ManimCommunity/manim/blob/62f0147f8135e68323fd2a2a2f8258772faa8c9f/manim/mobject/coordinate_systems.py#L26-L40

### PR DESCRIPTION
**Pull request by Ammar34**
Fixed an issue where the  keyword arguments ``x_min``,``x_max``,``y_min`` and ``y_max`` passed in ``Axes`` call were not set to ``self.x_min``,``self.x_max``,``self.y_min`` and ``self.y_max``.

Fixes https://github.com/ManimCommunity/manim/issues/840

## List of Changes

- The ``CoordinateSystem`` class now accepts ``x_min``,``x_max``,``y_min`` and ``y_max`` as keyword arguments and sets these values to ``self.x_min``,``self.x_max``,``self.y_min`` and ``self.y_max``.

- ``x_min``,``x_max``,``y_min`` and ``y_max`` passed either directly into ``Axes()`` class or in ``x_axis_config`` and ``y_axis_config`` are now extracted and passed upstairs.

## Motivation

Fix for https://github.com/ManimCommunity/manim/issues/840

### CODE REVIEW

**Comment by naveen521kk** [comment]
**PRO TIP:** Use something like `Fixes #840` so that GitHub automatically links the corresponding issue.

**Review by MysaaJava — COMMENTED** [review]
Looks good !

**Comment by leotrs** [comment]
@Ammar34 thank you for your contribution. Unfortunately, this broke the tests - would you be able to look into those and try to fix them?

**Comment by Ammar34** [comment]
Sorry for not getting back on this. Was away for a while. The tests are failing because the Coordinate System class has been changed to let the setting of `x_min` and other kwargs. Previously it was not handled:
https://github.com/ManimCommunity/manim/blob/ff1696c065937dc55abecbd41f562b0d29843dfd/manim/mobject/coordinate_systems.py#L26-L40
https://github.com/ManimCommunity/manim/blob/ff1696c065937dc55abecbd41f562b0d29843dfd/manim/mobject/coordinate_systems.py#L208-L222

The ThreeDAxes class by default sets the values of `x_min` through `y_max` to some values which obviously were not set in the previous implementation of Coordinate System Class to `x_min` through `z_max`.  The test data needs updating to allow for this change.

**Pull request closed without merging**
