### PR TITLE
flake8: Set max-line-length instead of ignoring long lines

### PR DESCRIPTION
**Pull request by cclauss**
[`./manim/manim/grpc/gen/frameserver_pb2.py:21:89: E501 line too long (3454 > 88 characters)`](https://github.com/ManimCommunity/manim/blob/main/manim/grpc/gen/frameserver_pb2.py#L21)

[`manim/cli/render/commands.py:35:1: C901 'render' is too complex (35)`](https://github.com/ManimCommunity/manim/blob/main/manim/cli/render/commands.py#L35)

## Reviewer Checklist
- [x] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Review by Darylgolden — COMMENTED** [review]
Can I ask why you chose a max-line-length of 284?

**Comment by cclauss** [comment]
$ `mv .flake8 was.flake8`
$ `flake8 --exclude="./.*,manim/grpc/gen/*,manim/mobject/svg*" --max-line-length=283 --select=E501`
```
./manim/mobject/vector_field.py:179:284: E501 line too long (284 > 283 characters)
```
$ `mv was.flake8 .flake8`

**Comment by behackl** [comment]
I don't really see the benefit of enabling the line length check with such a high limit. We currently have about 700 lines that exceed 88 characters (which, theoretically, is the line length [suggested by black](https://black.readthedocs.io/en/stable/)).

I would be happy to merge this if we reduced the limit down to something a bit more reasonable like 150 characters or so, such that we at least kill the extreme line length violations with this PR. There are not too many of those:

```
./tests/test_deprecation.py:158:151: E501 line too long (153 > 150 characters)
./tests/test_deprecation.py:160:151: E501 line too long (167 > 150 characters)
./tests/assert_utils.py:24:151: E501 line too long (161 > 150 characters)
./tests/utils/logging_tester.py:40:151: E501 line too long (211 > 150 characters)
./tests/helpers/graphical_units.py:21:151: E501 line too long (187 > 150 characters)
./manim/camera/camera.py:815:151: E501 line too long (156 > 150 characters)
./manim/utils/tex.py:123:151: E501 line too long (205 > 150 characters)
./manim/utils/deprecation.py:299:151: E501 line too long (153 > 150 characters)
./manim/utils/hashing.py:27:151: E501 line too long (166 > 150 characters)
./manim/utils/hashing.py:30:151: E501 line too long (182 > 150 characters)
./manim/utils/hashing.py:45:151: E501 line too long (194 > 150 characters)
./manim/utils/hashing.py:138:151: E501 line too long (160 > 150 characters)
./manim/utils/hashing.py:154:151: E501 line too long (221 > 150 characters)
./manim/utils/hashing.py:196:151: E501 line too long (193 > 150 characters)
./manim/utils/hashing.py:197:151: E501 line too long (184 > 150 characters)
./manim/scene/scene_file_writer.py:504:151: E501 line too long (175 > 150 characters)
./manim/scene/scene_file_writer.py:581:151: E501 line too long (184 > 150 characters)
./manim/scene/scene.py:911:151: E501 line too long (159 > 150 characters)
./manim/mobject/vector_field.py:52:151: E501 line too long (185 > 150 characters)
./manim/mobject/vector_field.py:54:151: E501 line too long (152 > 150 characters)
./manim/mobject/vector_field.py:56:151: E501 line too long (151 > 150 characters)
./manim/mobject/vector_field.py:272:151: E501 line too long (167 > 150 characters)
./manim/mobject/vector_field.py:277:151: E501 line too long (178 > 150 characters)
./manim/mobject/vector_field.py:384:151: E501 line too long (185 > 150 characters)
./manim/mobject/vector_field.py:386:151: E501 line too long (152 > 150 characters)
./manim/mobject/vector_field.py:388:151: E501 line too long (151 > 150 characters)
./manim/mobject/vector_field.py:546:151: E501 line too long (185 > 150 characters)
./manim/mobject/vector_field.py:548:151: E501 line too long (152 > 150 characters)
./manim/mobject/vector_field.py:550:151: E501 line too long (151 > 150 characters)
./manim/mobject/vector_field.py:570:151: E501 line too long (165 > 150 characters)
./manim/mobject/vector_field.py:572:151: E501 line too long (170 > 150 characters)
./manim/mobject/vector_field.py:788:151: E501 line too long (177 > 150 characters)
./manim/mobject/table.py:195:151: E501 line too long (171 > 150 characters)
./manim/mobject/coordinate_systems.py:1601:151: E501 line too long (171 > 150 characters)
./manim/mobject/coordinate_systems.py:1690:151: E501 line too long (159 > 150 characters)
./manim/mobject/coordinate_systems.py:1713:151: E501 line too long (152 > 150 characters)
./manim/mobject/coordinate_systems.py:1719:151: E501 line too long (211 > 150 characters)
./manim/mobject/mobject.py:309:151: E501 line too long (240 > 150 characters)
./manim/mobject/mobject.py:880:151: E501 line too long (210 > 150 characters)
./manim/mobject/mobject.py:882:151: E501 line too long (152 > 150 characters)
./manim/mobject/svg/brace.py:70:151: E501 line too long (929 > 150 characters)
./manim/mobject/svg/brace.py:250:151: E501 line too long (259 > 150 characters)
./manim/mobject/svg/text_mobject.py:4:151: E501 line too long (182 > 150 characters)
./manim/mobject/svg/text_mobject.py:712:151: E501 line too long (329 > 150 characters)
./manim/mobject/svg/tex_mobject.py:9:151: E501 line too long (173 > 150 characters)
./manim/mobject/types/vectorized_mobject.py:583:151: E501 line too long (266 > 150 characters)
./manim/mobject/types/vectorized_mobject.py:594:151: E501 line too long (181 > 150 characters)
./manim/mobject/types/vectorized_mobject.py:942:151: E501 line too long (162 > 150 characters)
./manim/mobject/types/image_mobject.py:30:151: E501 line too long (212 > 150 characters)
./manim/mobject/types/image_mobject.py:54:151: E501 line too long (156 > 150 characters)
./manim/mobject/types/image_mobject.py:55:151: E501 line too long (163 > 150 characters)
./manim/mobject/types/image_mobject.py:59:151: E501 line too long (180 > 150 characters)
./manim/mobject/types/image_mobject.py:71:151: E501 line too long (232 > 150 characters)
./manim/mobject/types/image_mobject.py:100:151: E501 line too long (212 > 150 characters)
./manim/_config/utils.py:1191:151: E501 line too long (177 > 150 characters)
```

**Comment by cclauss** [comment]
As the title of the PR says, it is better to set a limit to prevent new contributions from adding even longer lines instead of merely ignore all long lines.

**Comment by behackl** [comment]
I can see where you are coming from. In that case I'm fine with checking for E501, but without the exclusion of `manim/mobject/svg*`.

Could you change the limit to 930 (or whatever covers `brace.py`)? We can then merge this and open a new issue for bringing down the limit to something that actually makes sense.

**Review by behackl — APPROVED** [review]
Thank you for your efforts!

**Pull request merged**
