### PR TITLE
Fixed the positioning of line graph that was under the graph 

### PR DESCRIPTION
**Pull request by vasek123**
## Overview: What does this pull request change?

Removed a part of code that caused the `line_graph` to be positioned behind the `Axes` / `NumberPlane`. Fixes the issue #1464.

## Motivation and Explanation: Why and how do your changes improve the library?

There was a line of code in the `coordinate_systems.py` that pushed `line_graph` behind the `Axes` / `NumberPlane`. This caused it to have an incorrect color and also obscurred parts of the `line_graph`, as seen in the image below.

line_graph_before

As proposed by @abhi3019 in #1464, removing a single line that changed the `z_index` of the `graph` fixed this issue.

line_graph_after

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by huguesdevimeux** [comment]
Fixes #1464

**Review by huguesdevimeux — APPROVED** [review]
SGTM. 

Do you mind adding a [graphical test](https://docs.manim.community/en/stable/contributing/testing.html?highlight=test#graphical-unit-test) for that ?

**Comment by vasek123** [comment]
I added the test, though I'm not exactly sure whether the test should have been placed into `test_coordinates_systems.py` or `test_axes.py`.

**Comment by huguesdevimeux** [comment]
That's fine. Thanks for the contribution !

**Pull request merged**
