### PR TITLE
FullScreenRectangle doesn't work on all screen resolutions

### PR DESCRIPTION
**Pull request by jaguaryang**
## Overview: What does this pull request change?
fix: frame.py has been changed. The frame.py is updated, and the screen ratio is added to read the configuration file, which is no longer hard-coded 16:9.

### CODE REVIEW

**Comment by MrDiver** [comment]
It kind of only works for the config file then, if you use `python -m manim -p -r "1500,1500"` it breaks apart and doesn't fix the issue with the screen size

**Comment by jaguaryang** [comment]
@MrDiver Your test is correct. But that is a function config bug, not related to any specific component such as this one.

Like config["frame_width"] should be able to get the current config parameter based on the order of precedence:

1. Library-wide config file,
2. user-wide config file, if it exists,
3. folder-wide config file, if it exists OR custom config file, if passed via --config_file,
4. other CLI flags, and
5. any programmatic changes made after the config system is set.

**Comment by MrDiver** [comment]
I guess that will not fix itself, i would probably search for it in the spirit of fixing future problems. Or just create an issue that this one is actually not passed to the config object

**Comment by MrDiver** [comment]
Stale for now

**Comment by jaguaryang** [comment]
> Stale for now

That is incorrect.

**Pull request closed without merging**
