### PR TITLE
Ported value_tracker to OpenGL

### PR DESCRIPTION
**Pull request by Nikhil0504**
## Changelog / Overview

Added `OpenGLValueTracker` and `OpenGLComplexValueTracker` which does the same things as the original ones but in OpenGL

## Motivation

Adds the functionality of `value_tracker` to OpenGL.
## Explanation for Changes

This is an Example for `OpenGLValueTracker` in OpenGL
```py
class ValueTrackerExample(Scene):
    def construct(self):
        pointer_tracker = OpenGLValueTracker(0)
        label = OpenGLDot(radius=3).add_updater(
            lambda x: x.set_x(pointer_tracker.get_value())
        )
        self.add(label)
        self.add(pointer_tracker)
        pointer_tracker.add_updater(lambda mobject, dt: mobject.increment_value(dt))
        self.wait(2)
```

https://user-images.githubusercontent.com/34582615/117926784-f0784b80-b316-11eb-9f7a-3cbdeac8866a.mp4

## Testing Status

Worked locally (Windows 10, RTX 3070).
## Further Comments

@eulertour I hope this makes your tutorial more better and easier.
## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [x] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Review by eulertour — APPROVED** [review]

**Review by naveen521kk — APPROVED** [review]
sgtm

**Comment by Nikhil0504** [comment]
I will make some more changes after #1382 gets merged so don't merge this yet.

**Comment by Nikhil0504** [comment]
Done.

**Review by behackl — APPROVED** [review]
Thank you, I think this is good enough for now.

(And just for good measure, as my *ceterum censo*: I don't like code duplication, especially if all that happened here is a replacement of "Mobject" to "OpenGLMobject". I'll resume work on #1272, and soon I hope that we'll be able to remove these duplicated classes again.)

**Pull request merged**
