### PR TITLE
Renamed `get_graph` (and the like) to `plot`

### PR DESCRIPTION
**Pull request by icedcoffeeee**
## Overview: What does this pull request change?

* Renamed:
  * `get_graph` to `plot`
  * `get_implicit_curve` to `plot_implicit_curve`
  * `get_parametric_curve` to `plot_parametric_curve`
  * `get_line_graph` to `plot_line_graph`
  * `get_derivative_graph` to `plot_derivative_graph`
* Deprecated their previous names
## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Review by hydrobeam — DISMISSED** [review]
Suggested extending deprecation date to `v0.13.0`, + the renaming should be applied where `get_x` are used in the docs too. But I do support the name change! 👍

**Comment by kolibril13** [comment]
Looks good to me in general! 
 plot is more intuitive than get_graph
Just one thing to note:
In manim this wont show the graph directly
```
ax.plot(lambda x: x ** 2, color=PURPLE_B)
```

In matplotlib, this would show the graph directly:
```
ax.plot(x, y)
```
That is not a big issue, but might cause confusion.
Suggestion:
Should we, maybe in a future pr, directly add the plot as an submobject to the ax mobject?

**Comment by Darylgolden** [comment]
> 
> 
> Looks good to me in general! plot is more intuitive than get_graph Just one thing to note: In manim this wont show the graph directly
> 
> ```
> ax.plot(lambda x: x ** 2, color=PURPLE_B)
> ```
> 
> In matplotlib, this would show the graph directly:
> 
> ```
> ax.plot(x, y)
> ```
> 
> That is not a big issue, but might cause confusion. Suggestion: Should we, maybe in a future pr, directly add the plot as an submobject to the ax mobject?

Not sure, but since this isn't directly related to this PR, maybe open a new discussion/issue?

**Review by Darylgolden — DISMISSED** [review]
Still some remnants of the old syntax [here](https://github.com/icedcoffeeee/manim/blob/rename-get-graph/tests/test_coordinate_system.py#L113-L114) and [here](https://github.com/icedcoffeeee/manim/blob/rename-get-graph/manim/scene/moving_camera_scene.py#L56) (there may be more, I haven't checked exhaustively). Could you go over it again with Ctrl+F to make sure there isn't anything missed?

**Review by Darylgolden — COMMENTED** [review]
Can you resolve the merge conflicts?

**Review by christopher-besch — CHANGES_REQUESTED** [review]
I just gave it a quick `grep -R` and found [this](https://github.com/icedcoffeeee/manim/blob/38d9c774fe5a625d778dba0bed7d6cf5f94698f5/tests/test_graphical_units/test_axes.py#L257) and [this](https://github.com/icedcoffeeee/manim/blob/38d9c774fe5a625d778dba0bed7d6cf5f94698f5/tests/test_coordinate_system.py#L114).
Besides that this looks good.

**Comment by icedcoffeeee** [comment]
> found this and this.

Thanks! They were probably added sometime after I left this PR and I didn't notice

**Review by christopher-besch — APPROVED** [review]

**Review by behackl — APPROVED** [review]
LGTM, I also (strongly) support renaming `get_graph` to `plot`.

**Pull request merged**
