### PR TITLE
Update Docs Url

### PR DESCRIPTION
**Pull request by cobordism**
I replaced https://manimce.readthedocs.io with https://docs.manim.community

I changed one link of https://pypi.org/project/manimce to https://pypi.org/project/manim
Note: it looks like manim is still on version 0.1.0 while manimce is 0.1.1. This should not be. manim should be the newest version, manimce should redirect to manim ... or sth like that, no?

I did not change the line `choco install manimce` because I have no idea about choco

### CODE REVIEW

**Comment by leotrs** [comment]
Pinging @eulertour about pypi and @naveen521kk about choco

**Comment by naveen521kk** [comment]
> I did not change the line `choco install manimce` because I have no idea about choco

I am sorry. That would be `manimce` until we release a version `1.0.0`. There was some problem with `manim` choco package that it had version `1.0.0` already released so other version wasn't able to work. Let it be `manimce` for now.

**Comment by leotrs** [comment]
Perhaps we should add a warning or note admonition to the docs saying that.

**Comment by eulertour** [comment]
I don't know anything about the choco package, but otherwise LGTM

**Review by eulertour — APPROVED** [review]

**Review by naveen521kk — APPROVED** [review]
LGTM!

**Pull request merged**
