### PR TITLE
Implementing a ``Zoom`` parameter to :class:`~.ThreeDScene`

### PR DESCRIPTION
**Pull request by icedcoffeeee**
## Motivation and Explanation: Why and how do your changes improve the library?

Currently, there's no way to "zoom" into a ThreeDScene. This PR aims to implement it.

Code Used:
```py
class Test(ThreeDScene):
    def construct(self):
        self.set_camera_orientation(PI/3, -PI/4)
        self.add(ThreeDAxes())
        self.add(Sphere())
        self.move_camera(zoom=2)
        self.move_camera(zoom=1)
        self.wait()
```
Outcome:

https://user-images.githubusercontent.com/83535735/130083061-e28f33ec-5bed-494f-bdcf-31d31234e628.mp4

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by behackl** [comment]
What is the relation between `distance` and `zoom`?

The implementation looks good to me, but I don't use 3D features a lot; it would be good to get some more opinions here.

**Comment by icedcoffeeee** [comment]
Honestly, i think the term 'distance' is unintuitive for some users of manim. It refers to the focal distance of the camera, which increases the field of view as the camera gets closer.
From [Wikipedia](https://en.wikipedia.org/wiki/3D_projection)


Example code:
```py
class Test(ThreeDScene):
    def construct(self):
        a = Sphere()
        self.add(ThreeDAxes(), a)
        self.set_camera_orientation(PI / 3, -PI / 4)
        self.move_camera(distance=7.5)
        self.wait()
```
Output:

https://user-images.githubusercontent.com/83535735/130308572-9a565ee6-8858-4bb4-b75b-0da56a38ba79.mp4

Zoom would be a more used feature in most situations imo, since not a lot of users want to adjust the camera's depth of field.

**Comment by WampyCakes** [comment]
Would it be too much to ask if you could change the name of distance to something like `focal_distance` in this PR? I think this PR looks great overall. I've looked it over twice, but will leave an approving review with any thoughts when I'm not on mobile.

**Comment by behackl** [comment]
> Would it be too much to ask if you could change the name of distance to something like `focal_distance` in this PR? I think this PR looks great overall. I've looked it over twice, but will leave an approving review with any thoughts when I'm not on mobile.

It might make sense to deprecate distance, but I'd prefer if this happened in a separate PR (to have things clearer in the changelog).

**Comment by WampyCakes** [comment]
Idk, I think since we have it, we might as well keep it. What if someone actually needed that? What would make sense to me is removing the limit of (I think +-6) distance. It's not really holding us back to keep it since OpenGL changes how scenes work.

**Comment by behackl** [comment]
> Idk, I think since we have it, we might as well keep it. What if someone actually needed that? What would make sense to me is removing the limit of (I think +-6) distance. It's not really holding us back to keep it since OpenGL changes how scenes work.

I don't want to remove `distance`. But in order to rename it to `focal_distace`, it has to be deprecated.

**Comment by WampyCakes** [comment]
Ohhhh, I gotcha

**Comment by icedcoffeeee** [comment]
So, the renaming and deprecation of `distance` will be done in another PR, right? Is there anything else I should improve in this PR?

**Review by behackl — APPROVED** [review]
This looks good to me. I think this is safe to merge before the release, given that this is a straightforward extension of the existing `ThreeDScene`.

**Review by WampyCakes — CHANGES_REQUESTED** [review]
LGTM, but can you add a test?

**Comment by WampyCakes** [comment]
I think the tests should contain both zooming in _and_ out, and making one test an int and one a float is a good idea.

**Comment by icedcoffeeee** [comment]
Yup, all done :)

**Review by WampyCakes — APPROVED** [review]

**Pull request merged**
