### PR TITLE
Improve handling of specified font name

### PR DESCRIPTION
**Pull request by staghado**
This PR fixes an issue with the specified font names mentioned here : #3413
The proposed fix does two things : 
- If the specified font is  'sans-serif' : change it to 'sans' as this is the name used in the list of fonts
- if the font name is not in the list of fonts, automatically check if the capitalized version of the font exists in the list of fonts. If not, print a warning to the user.

To have a more robust handling of the font names, we can use a dictionary that maps between all lower letter fonts and their corresponding name in  `manimpango.list_fonts()`, this would allow fonts such as "**HanaMinB**" to be declared simply as "**hanaminb**".

@behackl

### CODE REVIEW

**Comment by MrDiver** [comment]
Tip: you do not need to notify the devs that you made a PR, we get a notification for that anyway.

I would like this to be a cross platform working solution with the fonts list because it is different between Windows, Mac and Linux which makes it really difficult to get this right

Sooooo if you are willing to some more research on this how this might be handled well it would be great.

This would also require that you write some tests for this because currently we do not have tests for missing fonts because the runners still go through the same thing.

**Comment by staghado** [comment]
I have only a Linux platform so i dont know how I can test for other platforms. 
This is aimed at solving the specific issue here #3413

**Comment by JasonGrace2282** [comment]
This might be a bit of work, but maybe a VM?

**Comment by JasonGrace2282** [comment]
Just tested on my windows installation, no font warnings :)

**Review by JasonGrace2282 — APPROVED** [review]

**Review by behackl — APPROVED** [review]
Just tested building the documentation on my Mac too; after installing the not inherently available Open Sans font there were no further warnings.

I'd be happy to merge this in its current form, although the comparison against the `font.lower()` name would also be very nice to have. Maybe this and an appropriate test is something for a follow-up PR?

**Pull request merged**
