### PR TITLE
Remove end to end tests

### PR DESCRIPTION
**Pull request by eulertour**
The frame comparison tests make pixel-perfect comparisons which are too sensitive to test effectively. The tests are currently giving false negatives for every commit. This PR removes the tests until we can decide on a more effective way to test.

### CODE REVIEW

**Comment by eulertour** [comment]
Pinging @huguesdevimeux for their input.

**Comment by huguesdevimeux** [comment]
**The tests work.**
I just found why they were failing, I will make a PR soon. They undercovered two bugs : one related to the core of manim and one related to #98. 

One again, I'm deeply convinced that removing tests when they fail is not the right solution and it goes against the very essence of testing.

**Comment by eulertour** [comment]
It's not that we should remove all tests, only that we shouldn't have tests that fail when nothing is wrong.

The failures on each commit are confusing, and even with a fix it likely won't be sustainable to ensure each pixel of output is never changed. It'd probably be best to rethink our approach to testing.

**Comment by huguesdevimeux** [comment]
> It's not that we should remove all tests, only that we shouldn't have tests that fail when nothing is wrong.

Believe me, nothing was not wrong.

These tests were at the beginning supposed to be useful when adding a new graphical functionality, like a new animation, to be sure that the new feature has not broken anything. They are not designed IMO for other additions, as the CONFIG refactoring.
I do think those tests are useful, they allow me to spot a lot of bugs. But If you have a better idea, that's cool.
And I agree, we should have other tests.

**Comment by leotrs** [comment]
I think we should make all of these tests optional, not remove them, until such a time when they are passing again. I agree with @huguesdevimeux that the tests do work in principle. Also it seems like #185 is going to deprecate this PR?

**Pull request closed without merging**
