### PR TITLE
 Removed :class:`CameraFrame`

### PR DESCRIPTION
**Pull request by zzzzz1st**
## Overview: What does this pull request change?
It removes the CameraFrame class from the moving_camera module for issue #2689 

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Review by behackl — APPROVED** [review]
Thank you for your contribution, this looks good to me!

I'll leave it open for a little while in case other devs want to take a look, and then merge it in a bit. No further action required from your side. :-)

**Comment by zzzzz1st** [comment]
Ok very good. Thanks.

**Comment by Kiran-Raj-Dev** [comment]
Can you resolve the conflict?
Just remove the VGroup import and keep the rest.
And while you are at also remove the comment `# TODO, think about how to incorporate perspective`

**Comment by behackl** [comment]
Resolved conflict, removed comment. Ready to merge.

**Review by naveen521kk — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
