### PR TITLE
Finalized translation process and documentation

### PR DESCRIPTION
**Pull request by MysaaJava**
## Overview: What does this pull request change?
This pull-requests updates the internationalization docs section to the Crowdin system that will (let's hope) work without breaking.

## Links to added or changed documentation pages

https://manimce--2313.org.readthedocs.build/en/2313/contributing/internationalization.html

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by Darylgolden** [comment]
Rewritten the guidelines, @MysaaJava please have a look :)

**Review by lucasricci — APPROVED** [review]
LGTM

**Comment by MysaaJava** [comment]
This looks great ! Maybe it misses a text dercribing how to discuss translation controversies in one language, like we had for english terms that have a french translation that is used less. (Or like what kilacoda had for indian languages)  Something like a GitHub discussion or a #translation-discussions under the `Languages` category. And maybe having   language-specific rules written at the bottom of the files for translators to refer to.

**Review by behackl — APPROVED** [review]
I think this is fine for now; we can see how the process goes, and if there are many (non-language specific) questions about it. If so, adding a corresponding Discord channel might make sense, but I also think that these sort of discussions are probably better kept at Crowdin.

Thank you for your work! :-)

**Pull request merged**
