### PR TITLE
Improve `scripts/dev_changelog.py`

### PR DESCRIPTION
**Pull request by naveen521kk**
## Overview: What does this pull request change?
- Use `\n` as line endings by default, https://github.com/ManimCommunity/manim/commit/0d714b006fce53a696159a87984d7a59b0312509
- Use threads to fetch Github API, https://github.com/ManimCommunity/manim/commit/f05b4004bc107bbf01f6d43d09b79d11da3dcaa3

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Review by behackl — APPROVED** [review]
Both changes look good to me; the line ending one is definitely fine. I have not tried to run the script, but if it works for you, that is good enough for me right now. :-)

**Comment by naveen521kk** [comment]
Thanks for the quick review, the script works for me and is a lot faster than it previously was.

**Comment by naveen521kk** [comment]
Ah, this is causing an issue. The order of the pull requests is changed each time I render it, I think the list where it stores this info should be sorted before writing it.

**Comment by behackl** [comment]
I guess it would be okay to sort the PRs by number in their categories.

**Pull request merged**
