### PR TITLE
fix :class:`~.Paragraph` shape, clean internals, and add tests

### PR DESCRIPTION
**Pull request by citrusmunch**
## Overview: What does this pull request change?

clean up internals of :class:`~.Paragraph` and fix bug of wrong shape #2366 
this amounted to entirely removing `gen_chars` and making all the loops with manual indices into mostly list comprehensions. i should note this changes the `Paragraph` from a `VGroup` of `VGroup`s to a `VGroup` of `Text`s.

also added a few tests (and also didn't test a lot of things like alignment)

## Motivation and Explanation: Why and how do your changes improve the library?

bugfix :D

## Links to added or changed documentation pages

https://manimce--2384.org.readthedocs.build/en/2384/

## Further Information and Comments

i actually found it difficult to write appropriate tests, so any suggestions there would be very welcome! (i.e. `Text` comparison was hard and what i have currently might not be granular enough)
also wasn't sure how many to write either since we're replacing this soon™️. i'm happy to write more.

todo as of yet:
- [x] set ligatures to `False` (platform consistency)
- [ ] update documentation
- [x] visually check for regressions
- [ ] add types while we're touching the code?

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by citrusmunch** [comment]
seems like some tests for windows failed because i wrote them to account for the "fi" ligature in `"first"`. i guess font defaults are different; something to keep in mind when making tests for the new `Text` api #2355 .

**Comment by behackl** [comment]
> seems like some tests for windows failed because i wrote them to account for the "fi" ligature in `"first"`. i guess font defaults are different; something to keep in mind when making tests for the new `Text` api #2355 .

Exactly, the issue is varying default fonts. If we had a free font that we were allowed to distribute, we could include it with our tests and make sure all OSes use the same font.

In case you stumble over an appropriate free font, feel free to let us know and/or try including it here!

**Comment by naveen521kk** [comment]
> Exactly, the issue is varying default fonts. If we had a free font that we were allowed to distribute, we could include it with our tests and make sure all OSes use the same font.

I don't think that's true. I have tried adding a free font in ManimPango's test suite but it still the SVG file differed. I think we should wait for something like https://gitlab.gnome.org/GNOME/pango/-/merge_requests/484.

**Comment by citrusmunch** [comment]
a million font collection websites and none of them filter by license 😩 (i found [font squirrel](https://www.fontsquirrel.com/) only afterwards; it's not perfect but where i would recommend anyone to start)

i was looking for OFL fonts for [compatibility](https://scripts.sil.org/cms/scripts/page.php?item_id=OFL-FAQ_web#68092c0f) with a floss project, as well as OpenType support so we can have features like ligatures

seems like there's a few options:
- [Libertine](https://libertine-fonts.org/) seems featureful and well-supported.
- [Libertinus](https://github.com/alerque/libertinus) is less opinionated but maybe less maintained?
- [Noto](https://github.com/googlefonts/noto-fonts) is the most featureful and most supported. (I'm pretty anti-google but this satisfies all the requirements and font choice isn't a hill i'm willing to die on... yet)


> I have tried adding a free font in ManimPango's test suite but it still the SVG file differed.

would the discrepancy between os's be noticeable in the tests i have, where we're only testing glyph quantities (not a visual test)? is there no font choice that would eliminate that issue? or is that the whole problem?

> If we had a free font that we were allowed to distribute, we could include it with our tests and make sure all OSes use the same font.

i assume that's in the scope of a different PR. should i just disable ligatures for the tests while we wait for [pango \#484](https://gitlab.gnome.org/GNOME/pango/-/merge_requests/484)?

**Comment by naveen521kk** [comment]
> would the discrepancy between os's be noticeable in the tests i have, where we're only testing glyph quantities (not a visual test)? is there no font choice that would eliminate that issue? or is that the whole problem?

If you are testing only glyph quantities, yes having a default font should work. If it's about testing visual differences, then the test will depend on the operating system.

**Comment by citrusmunch** [comment]
So I opened a new branch to start over with my work in this PR for a few reasons. But long story short: the current implementation of `Paragraph` is fine as long as ligatures are disabled (reading back, it feels like everyone but me already knew this lol). I don't know how to work around that without interfering with `Text`, so I think it's best to just wait for that API rewrite.

In the meantime the workaround is just `Paragraph(..., disable_ligatures=True)`.

The other branch I have ended up just being a cleaner version of what's already implemented; so easier to read, but same bug. I can include that here if there's interest, but again it's probably best to just wait for the `Text` rewrite.

**Pull request closed without merging**
