### PR TITLE
Hot reloading for the OpenGL renderer

### PR DESCRIPTION
**Pull request by eulertour**
## Changelog / Overview

Rerun scene when the input file is modified

## Motivation

Allows for instant feedback when editing scenes.

## Explanation for Changes

Automatically updates the preview window when the input file is modified. Also adds `Scene.skip_animation_preview` to control which parts of the watched scene are played when the file is modified.

## Testing Status

I tested locally with the following scene:
```py
class Test(Scene):
    def construct(self):
        config["background_color"] = "#333333"
        self.skip_animation_preview = True

        s = OpenGLCircle(stroke_color=BLUE, fill_opacity=0.5, fill_color=BLUE).shift(
            RIGHT + 2 * UP
        )
        self.play(ShowCreation(s))

        d = OpenGLCircle(stroke_color=RED, fill_opacity=0.5).shift(UL + DOWN)
        self.play(Create(d))

        self.skip_animation_preview = False
        c = OpenGLSquare(fill_color=BLUE, fill_opacity=0.7).shift(RIGHT + 2 * DOWN)
        self.play(ShowCreation(c), run_time=0.5)

        self.play(Uncreate(c), run_time=1)
        self.interactive_embed()
```

## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [x] My new functions/classes either have a docstring or are private
- [x] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by kilacoda** [comment]
Is this intended only for OpenGL or all renderers?

**Comment by eulertour** [comment]
It's only intended for OpenGL.

**Comment by kilacoda** [comment]
Guess I'd rename it accordingly then so there isn't any confusion.

**Review by behackl — APPROVED** [review]
Code LGTM, and I've just tested this locally -- seems good to me! Pretty neat!

**Pull request merged**
