### PR TITLE
Fixed :class:`~.DrawBorderThenFill` to support OpenGL and improved type hints for some functions

### PR DESCRIPTION
**Pull request by TRoboto**
## Overview / Explanation for Changes

Fixed a bug in :class:`~.DrawBorderThenFill` that prevented :class:`~.Write` animations from working with :class:`~.OpenGLVMobjects` and slightly improved type hints for some animation functions to include :class:`~.OpenGLVMobject`.

## Acknowledgements
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have chosen a descriptive PR title (see top of PR template for examples)

## Reviewer Checklist
- [ ] Newly added functions/classes are either private or have a docstring
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings
- [ ] The PR title is descriptive enough

### CODE REVIEW

**Comment by MrMallIronmaker** [comment]
LGTM - thanks! I was running in to a lot of these issues myself. 

Ideally we'd have tests for the OpenGL stuff but that's still in the works... Do you have any local scenes you've been testing with?

**Comment by TRoboto** [comment]
Yes, compatibility with OpenGL still needs improvement.

It would be nice to have these tests ASAP... I detected most issues when trying to play [these animations](https://github.com/3b1b/videos/tree/43cb5e2dd74a5e69f33772582b8af46c8972dd8c/_2020/18S191).

**Comment by MrMallIronmaker** [comment]
FWIW I'm in the middle of tests on #1160

**Review by MrMallIronmaker — APPROVED** [review]

**Review by naveen521kk — APPROVED** [review]
sgtm

**Pull request merged**
