### PR TITLE
Upkeep and revamping GraphScene

### PR DESCRIPTION
**Pull request by protonlaser91**
## List of Changes
- Created new class to replace GraphScene called TwoDScene (extends Scene and NumberPlane), but it is a base class and requires added functionality.
- Modified ParametricFunction by adding vector_derivative and derivative (dy/dx). 
- Deprecated FunctionGraph and warning for GraphScene
- Made input_to_graph_point work for parametric curves as well.
- Created new evaluate(t) method in ParametricFunction that is the same as ParametricFunction.function(t)

## Motivation

#782 and #775 
The current GraphScene class is messy and ugly. It is in dire need of a revamping which can utilize pre-existing methods to make itself more efficient. FunctionGraph is also not used at all except in the building_blocks.rst. 
ParametricFunction lacks some functionality.

## Explanation for Changes

A new class TwoDScene that will be consistent with the rest of the changes made to coordinate_system.py.
ParametricFunction can now be used for derivatives.

## Testing Status

Ran `poetry run pytest` and it passed all checks.

## Acknowledgement
- [x] I have read the [Contributing Guidelines](https://github.com/ManimCommunity/manim/wiki/Documentation-guidelines-(WIP))

### CODE REVIEW

**Comment by leotrs** [comment]
Hi @protonlaser91, why was this closed? Are you no longer working on this? If you are but it is not ready, you can also just mark it as a draft instead of closing it :slightly_smiling_face:

**Comment by protonlaser91** [comment]
👍 I just figured that it really isn't a good replacement for GraphScene yet. I'm wondering if it's alright to forgo the config dictionary for TwoDScene and just implement my own version of kwargs. I know you have been working on eliminating config dicts so I figure you are the best person to ask for advice on this matter. Thank you again!

**Comment by leotrs** [comment]
Yes, if something can be done without CONFIG, then please do so. We are currently working on a PR to get rid of all CONFIG dicts anyway.

**Comment by protonlaser91** [comment]
Don't see a point in continuing this when Axes does a much better job and is a standalone class.

**Pull request closed without merging**
