### PR TITLE
Format Imports using Isort

### PR DESCRIPTION
**Pull request by naveen521kk**
## Motivation
Also, add a check for that.
Got the idea from https://github.com/ManimCommunity/manim/pull/1176

## Testing Status
Local pass

## Acknowledgements
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have chosen a descriptive PR title (see top of PR template for examples)

## Reviewer Checklist
- [ ] Newly added functions/classes are either private or have a docstring
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings
- [ ] The PR title is descriptive enough

### CODE REVIEW

**Review by kolibril13 — APPROVED** [review]
Works fine locally!
We should note that this pr will produce a lot of conflicts in other prs, however, they will be easy to resolve.

**Comment by naveen521kk** [comment]
>  We should note that this pr will produce a lot of conflicts in other prs, however, they will be easy to resolve.

They can simply run isort again in a way to fix those. :wink:

**Comment by behackl** [comment]
I am not particularly happy with merging this right now. I'd suggest we do so shortly before the release so that we don't produce unnecessary merge conflicts in all other currently active PRs.

**Comment by naveen521kk** [comment]
Fine, just ping me when I need to update.

**Comment by GameDungeon** [comment]
How hard would it be to add isort to CI and Pre-commit?

**Comment by naveen521kk** [comment]
I already added a check in CI, and soon after the pre-commit pr is merged, I will add that too.

**Review by huguesdevimeux — APPROVED** [review]

**Comment by naveen521kk** [comment]
I will fix the conflicts and then it can be merged.

**Review by kolibril13 — APPROVED** [review]

**Comment by naveen521kk** [comment]
I think this has waited long, I am merging this.

**Pull request merged**
