### PR TITLE
Fixed positioning of :class:`~.Flash`

### LINKED ISSUE #2257: Flash(...) is not using the location of the point it is given
## Description of bug / unexpected behavior
You can not move the point at which the Flash(...) happens, instead, it always occurs around [0,0,0]


## Expected behavior
<!-- Add a clear and concise description of what you expected to happen. -->
That the Flash is animated centered at the point it was given.

## How to reproduce the issue
<!-- Provide a piece of code illustrating the undesired behavior. -->

<details>

<summary>I expect to see to flashes but I only see one at [0,0,0]</summary>

```py
class FlashError(Scene):
    def construct(self):
        self.play(Flash(point=LEFT*3), Flash(point=RIGHT*3))
```

</details>


## Additional media files
<!-- Paste in the files manim produced on rendering the code above. -->

<details><summary>Images/GIFs</summary>

<!-- PASTE MEDIA HERE -->
https://user-images.githubusercontent.com/21693578/140317326-a78cad1a-0325-48de-8bec-aa13b014712b.mp4

</details>

## Logs
<details><summary>Terminal output</summary>
<!-- Add "-v DEBUG" wh

en calling manim to generate more detailed logs -->

```
Manim Community v0.12.0

[11/04/21 14:01:31] DEBUG    Hashing ...                                                                                                                                                        hashing.py:344
                    DEBUG    Hashing done in 0.031731 s.                                                                                                                                        hashing.py:356
                    DEBUG    Hash generated :  1058058132_4167814554_2339748938                                                                                                                 hashing.py:359
                    INFO     Animation 0 : Using cached data (hash : 1058058132_4167814554_2339748938)                                                                                    cairo_renderer.py:74
                    DEBUG    List of the first few animation hashes of the scene: ['1058058132_4167814554_2339748938']                                                                    cairo_renderer.py:83
                    INFO     Combining to Movie file.                                                                                                                                 scene_file_writer.py:604
                    DEBUG    Partial movie files to combine (1 files): ['/media/frank/BigDrive/Recordings/MOTION/Part 1 - A single                                                    scene_file_writer.py:547
                             particle/media/videos/Motion/480p15/partial_movie_files/FlashError/1058058132_4167814554_2339748938.mp4']                                                                        
                    INFO                                                                                                                                                              scene_file_writer.py:718
                             File ready at '/media/frank/BigDrive/Recordings/MOTION/Part 1 - A single particle/media/videos/Motion/480p15/FlashError.mp4'                                                     
                                                                                                                                                                                                              
                    INFO     Rendered FlashError                                                                                                                                                  scene.py:234
                             Played 1 animations                                                                                                                                                              
                    INFO     Previewed File at: '/media/frank/BigDrive/Recordings/MOTION/Part 1 - A single particle/media/videos/Motion/480p15/FlashError.mp4' 
```

<!-- Insert screenshots here (only when absolutely necessary, we prefer copy/pasted output!) -->

</details>


## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)): Ubuntu 20.04
- RAM: 12 GB
- Python version (`python/py/python3 --version`): Python 3.8.10
- Installed modules (provide output from `pip list`):
```
Package                 Version             
----------------------- --------------------
apturl                  0.5.2               
argon2-cffi             21.1.0              
attrs                   21.2.0              
backcall                0.2.0               
bcrypt                  3.1.7               
bleach                  4.1.0               
blinker                 1.4                 
bottle                  0.12.19             
Brlapi                  0.7.0               
cairocffi               1.2.0               
CairoSVG                2.5.2               
certifi                 2019.11.28          
cffi                    1.14.6              
chardet                 3.0.4               
charset-normalizer      2.0.6               
click                   8.0.3               
click-default-group     1.2.2               
cloup                   0.7.1               
colorama                0.4.3               
colour                  0.1.5               
command-not-found       0.3                 
commonmark              0.9.1               
conan                   1.40.3              
cryptography            2.8                 
cssselect2              0.4.1               
cupshelpers             1.0                 
cycler                  0.10.0              
daemonize               2.4.7               
dbus-python             1.2.16              
debugpy                 1.5.1               
decorator               5.1.0               
defer                   1.0.6               
defusedxml              0.7.1               
distro                  1.4.0               
distro-info             0.23ubuntu1         
duplicity               0.8.12.0            
entrypoints             0.3                 
fasteners               0.14.1              
future                  0.18.2              
glcontext               2.3.4               
greenlet                0.4.15              
httplib2                0.14.0              
idna                    2.8                 
ipykernel               6.4.2               
ipython                 7.28.0              
ipython-genutils        0.2.0               
ipywidgets              7.6.5               
isosurfaces             0.1.0               
jedi                    0.18.0              
Jinja2                  2.11.3              
jsonschema              4.1.2               
jupyter                 1.0.0               
jupyter-client          7.0.6               
jupyter-console         6.4.0               
jupyter-core            4.8.1               
jupyterlab-pygments     0.1.2               
jupyterlab-widgets      1.0.2               
keyring                 18.0.1              
kiwisolver              1.3.2               
language-selector       0.1                 
launchpadlib            1.10.13             
lazr.restfulclient      0.14.2              
lazr.uri                1.0.3               
lockfile                0.12.2              
louis                   3.12.0              
macaroonbakery          1.3.1               
Mako                    1.1.0               
manim                   0.12.0              
ManimPango              0.3.1               
mapbox-earcut           0.12.10             
MarkupSafe              1.1.0               
matplotlib              3.4.3               
matplotlib-inline       0.1.3               
mistune                 0.8.4               
moderngl                5.6.4               
moderngl-window         2.4.0               
monotonic               1.5                 
mpmath                  1.2.1               
msgpack                 0.6.2               
multipledispatch        0.6.0               
nbclient                0.5.4               
nbconvert               6.2.0               
nbformat                5.1.3               
nest-asyncio            1.5.1               
netifaces               0.10.4              
networkx                2.6.3               
node-semver             0.6.1               
nose                    1.3.7               
notebook                6.4.5               
notify2                 0.3                 
numpy                   1.17.4              
oauthlib                3.1.0               
olefile                 0.46                
packaging               21.0                
pandas                  1.3.4               
pandocfilters           1.5.0               
paramiko                2.6.0               
parso                   0.8.2               
patch-ng                1.17.4              
pexpect                 4.6.0               
pickleshare             0.7.5               
Pillow                  7.0.0               
pip                     20.0.2              
pluginbase              1.0.1               
prometheus-client       0.11.0              
prompt-toolkit          3.0.21              
protobuf                3.6.1               
ptyprocess              0.7.0               
pycairo                 1.20.1              
pycparser               2.20                
pycups                  1.9.73              
pydub                   0.25.1              
pyglet                  1.5.21              
Pygments                2.10.0              
PyGObject               3.36.0              
PyJWT                   1.7.1               
pymacaroons             0.13.0              
PyNaCl                  1.3.0               
pynvim                  0.4.1               
pyparsing               3.0.1               
pyRFC3339               1.1                 
pyrr                    0.10.3              
pyrsistent              0.18.0              
python-apt              2.0.0+ubuntu0.20.4.6
python-dateutil         2.7.3               
python-debian           0.1.36ubuntu1       
pytz                    2019.3              
pyudev                  0.21.0              
pyxdg                   0.26                
PyYAML                  5.3.1               
pyzmq                   22.3.0              
qtconsole               5.1.1               
QtPy                    1.11.2              
reportlab               3.5.34              
requests                2.26.0              
requests-unixsocket     0.2.0               
rich                    10.12.0             
scipy                   1.7.1               
screen-resolution-extra 0.0.0               
screeninfo              0.6.7               
SecretStorage           2.3.1               
Send2Trash              1.8.0               
setproctitle            1.1.10              
setuptools              45.2.0              
simplejson              3.16.0              
six                     1.14.0              
skia-pathops            0.7.1               
sympy                   1.9                 
systemd-python          234                 
terminado               0.12.1              
testpath                0.5.0               
tinycss2                1.1.0               
tornado                 6.1                 
tqdm                    4.62.3              
traitlets               5.1.1               
ubuntu-advantage-tools  27.2                
ubuntu-drivers-common   0.0.0               
ufw                     0.36                
unattended-upgrades     0.1                 
urllib3                 1.26.7              
usb-creator             0.3.7               
wadllib                 1.3.3               
watchdog                2.1.6               
wcwidth                 0.2.5               
webencodings            0.5.1               
wheel                   0.34.2              
widgetsnbextension      3.5.1               
xkit                    0.0.0   
```
</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100
```
</details>

### PR DESCRIPTION
**Pull request by Viicos**
## Overview: What does this pull request change?

Fixes #2257. See the modified file as it is pretty straightforward.

EDIT: Oops, a commit from #2280 has been pushed with this one. Any idea how to fix this?

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by icedcoffeeee** [comment]
> a commit from #2280 has been pushed with this one. Any idea how to fix this?

You can revert a previous commit.

**Comment by Viicos** [comment]
> 
> 
> > a commit from #2280 has been pushed with this one. Any idea how to fix this?
> 
> You can revert a previous commit.

Ok managed to revert my commit. docs test is failing because it is using the following example:

```py
class UsingFlash(Scene):
    def construct(self):
        dot = Dot(color=YELLOW).shift(DOWN)
        self.add(Tex("Flash the dot below:"), dot)
        self.play(Flash(dot))
        self.wait()
```
and thus fails to do the following addition:
```py
line = Line(self.point, self.point + self.line_length * RIGHT)
```
as `__add__` is not implemented for mobjects. We could allow mobjets to be passed as the `point` parameter (and update the typing which currently is `point: np.ndarray`) or simply only allow iterables as coordinates of a point. What do you think?

**Comment by behackl** [comment]
I think it would be a good idea to allow passing Mobjects as well; the library actually already does that in many places. However, I don't think implementing `__add__` leads to particularly intuitive behavior; I think it would be better if `Flash.__init__` would check whether `isinstance(point_or_mobject, Mobject)`, and if so set `self.point` to the Mobject's center.

**Comment by Viicos** [comment]
> 
> 
> I think it would be a good idea to allow passing Mobjects as well; the library actually already does that in many places. However, I don't think implementing `__add__` leads to particularly intuitive behavior; I think it would be better if `Flash.__init__` would check whether `isinstance(point_or_mobject, Mobject)`, and if so set `self.point` to the Mobject's center.

I also think it's better to allow mobjects as well, and yes I do agree, better using `isinstance` than implementing `__add__`. I'll do the commit after a good night's sleep!

**Review by behackl — APPROVED** [review]
LGTM

**Pull request merged**
