### PR TITLE
Add width parameter and fix unit size

### PR DESCRIPTION
**Pull request by Pragyaan-6988**
## List of Changes

1. Fixed `unit_size` from `range / length` to `length / range`
2. Added a `width` parameter (defaults to `None`) to set the `NumberLine` to that width.

## Motivation

2. Many users might find it comfortable to just pass the width of their `NumberLine` instead of trial and error-ing with the `unit_size`. The `unit_size` will be overridden only if the argument `width` which is not `None` is passed, so if the preference is to go with `unit_size`, it is always possible. 

## Example

```py
class NumberLineTest(Scene):
    def construct(self):
        def num_line(unit_size=1, width=None):
            return NumberLine(
                        include_numbers=True, x_min=-50, x_max=50,
                        tick_frequency=10, unit_size=unit_size,
                        numbers_to_show=range(-50, 60,10),
                        width=width
                    )

        lines_width = VGroup(
            *[num_line(width=w) for w in range(8, 14, 2)]
            ).arrange(DOWN, buff=1).to_edge(DOWN)
        line_unit_size = num_line(unit_size=0.1).to_edge(UP)

        self.add(line_unit_size, lines_width)
```
NumberLineTest

## Acknowledgement
- [x] I have read the [Contributing Guidelines](https://github.com/ManimCommunity/manim/wiki/Documentation-guidelines-(WIP))

### CODE REVIEW

**Comment by leotrs** [comment]
Thanks @Pragyaan-6988 for another contribution! 

Will you please check the activity in #742? Something tells me that once that feature is merged, point number 2. in this PR would not be strictly necessary.

Point number 1. does look like a bug. Thanks for fixing that!

**Comment by Pragyaan-6988** [comment]
@leotrs If I understand it correctly, even after merging that feature, we can use `NumberLine(width=unit.m(<width>), other_parameters)`. Or is there another way we can set the width after merging that feature, which wouldn't make the `width` parameter necessary? Thanks.

**Comment by leotrs** [comment]
I guess I meant that you could use something like `NumberLine(unit_size=unit.m(<num_units / width>), ...)`. Though you are right, for convenience we could just offer both parameters.

**Review by leotrs — APPROVED** [review]

**Review by huguesdevimeux — APPROVED** [review]
SGTM!

**Comment by huguesdevimeux** [comment]
thanks for your contribution!

**Pull request merged**
