### PR TITLE
Fixed phi updater in :meth:`.ThreeDScene.begin_3dillusion_camera_rotation`

### PR DESCRIPTION
**Pull request by Viicos**
## Overview: What does this pull request change?

The phi updater in the `begin_3dillusion_camera_rotation` method uses a cosinus value, which is not equal to 0 when `dt` = 0, thus creating a small bump at the beginning of the rotation.
Also added typings, and removed the defaults phi and theta values so that the method can be used without passing the current camera position as arguments.

## Further Information and Comments

<details><summary>Before PR:</summary>

https://user-images.githubusercontent.com/65306057/144724763-6dcf923e-15f8-4231-9f82-f79bda068ebd.mp4

</details>

<details><summary>After PR:</summary>

https://user-images.githubusercontent.com/65306057/144724815-2bd90724-232a-4cd9-a879-afa03cc58d1d.mp4

</details>

<details><summary>Code:</summary>

```py
class Sample(ThreeDScene):
    def construct(self):
        self.set_camera_orientation(
            phi=40 * DEGREES,
            theta=80 * DEGREES
        )
        self.add(ThreeDAxes())
        self.wait()
        self.begin_3dillusion_camera_rotation(
            rate=1  # No need to specify origin_phi and origin_theta after PR.
        )
        self.wait(3)
```

</details>

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Review by behackl — CHANGES_REQUESTED** [review]
Apologies, was just cleaning out my tabs and saw that I had started, but never submitted the review for this. Please find some minor comments regarding docstrings and type hints below. Other than that, the changes look good to me.

**Review by Viicos — COMMENTED** [review]
Great thank you for the modifications! Thought `Optional` had to be used whenever the argument had a default value.

**Comment by behackl** [comment]
> Great thank you for the modifications! Thought `Optional` had to be used whenever the argument had a default value.

No, see the documentation here: https://docs.python.org/3/library/typing.html#typing.Optional :-)

**Review by behackl — APPROVED** [review]
LGTM!

**Pull request merged**
