### PR TITLE
Add configuration option ``zero_pad`` for zero padding PNGs.

### PR DESCRIPTION
**Pull request by DanielAdelodun**
also added the command line options `--zero_pad` and an alias `-0`.
`--zero_pad n` specifies `n` columns minimum to be appended to the filename for the frame number, left padded with zeros.

## Motivation

When frames are numbered without zero padding, the frame "OutFile12.png" comes before "OutFile2.png" when ordered lexicographically. This can be annoying. Also, tools like FFMPEG can be used to easily encode sequences of PNG files that have zero padded file name numbering. 
 
## Explanation for Changes

This gives users the option to output frames in a similar format as FFMPEG's image2. The default behaviour is now to pad output file names/frame number as `OutFile0001.png`, `OutFile0002.png` ... but the minimum number of columns can be configured. 

[Documentation Reference](https://manimce--####.org.readthedocs.build)

## Checklist
- [X] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [X] I have written a descriptive PR title (see top of PR template for examples)
- [X] I have written a changelog entry for the PR or deem it unnecessary
- [X] My new functions/classes either have a docstring or are private
- [X] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [X] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by behackl** [comment]
Hey, thank you for your contribution! I think this is a good idea; I even think that this should be the new default behavior. I'm sort of neutral when it comes to making the number of columns customizable (I think it would be great if it did that automatically, but I don't think we know the video length ahead of rendering).

**Comment by DanielAdelodun** [comment]
Thanks @behackl !

this is my first proper pull request, so let me know if I need to do anything and I'll give it my best. 
But I'm glad you like the idea.

**Comment by behackl** [comment]
> Thanks @behackl !
> 
> this is my first proper pull request, so let me know if I need to do anything and I'll give it my best.
> But I'm glad you like the idea.

Yes: could you modify your PR so that padding the number of frames becomes the default behavior? I'd say 4 columns would be a reasonable choice for the default size of the number.

**Review by Darylgolden — APPROVED** [review]
Thank you for your changes! LGTM

**Pull request merged**
