### PR TITLE
Upgrade pygments version to ^2.4.1

### PR DESCRIPTION
**Pull request by RickyC0626**
## Changelog / Overview

- Upgrade pygments version to ^2.4.1

## Motivation

Prevents installation errors

## Explanation for Changes

- jupyterlab-pygments 0.1.2 has requirement pygments >= 2.4.1
- nbconvert 6.0.7 has requirement pygments >= 2.4.1

## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [x] My new functions/classes either have a docstring or are private
- [x] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [x] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by naveen521kk** [comment]
irrc, poetry should be handling it right?

**Comment by RickyC0626** [comment]
> irrc, poetry should be handling it right?

When I used it, it wasn't handling it properly and kept pygments on 2.3.1

**Comment by naveen521kk** [comment]
> When I used it, it wasn't handling it properly and kept pygments on 2.3.1

I tried in a fresh env, Poetry installed `2.8.1`. Manim doesn't need a specific version of pygments (prove me wrong!), so I don't think we should specify a version.

**Comment by RickyC0626** [comment]
> > When I used it, it wasn't handling it properly and kept pygments on 2.3.1
> 
> I tried in a fresh env, Poetry installed `2.8.1`. Manim doesn't need a specific version of pygments (prove me wrong!), so I don't think we should specify a version.

It seems like a one time error as I'm unable to reproduce it anymore. It may have been caused by installing packages while in `poetry shell`. If it does happen again I'll post a screenshot of it.

**Pull request closed without merging**
