### PR TITLE
Smol fix : replaced set_style_data by set_style

### PR DESCRIPTION
**Pull request by huguesdevimeux**
I don't know when/why/how but `set_style_data` is not supported anymore by `VMobject` and has been replaced by `set_style`.

The change as supposedly be made by @3b1b some months ago, potentially [here](https://github.com/huguesdevimeux/manim/commit/ba881041770fc6fea40b525de9e16abcba4ce49f)

The most probaly hypothesis is that he forgot to update `BackgroundRectangle`.

~~Marked as draft, as I'll implement a nice test for this.~~

### CODE REVIEW

**Comment by huguesdevimeux** [comment]
**Update:** Testing would imply testing pretty much very methods of VMobject, which is not the aim of this PR. 

So, ready for review!

**Comment by leotrs** [comment]
Not sure why this would imply testing VMobject. What about the following?

```python
def my_super_duper_test():
    bgr = BackgroundRectangle()
    # assert fill opacity is the default value
    bgr.set_style(fill_opacity=my_super_duper_value)
    # assert fill opacity is my_super_duper_value
```

**Comment by huguesdevimeux** [comment]
@leotrs Unfortunalty it's more complicated than that, because `set_style` is not a simple setter, but calls in turn other setters and stuff that will process `set_style` parameters, and apply some stuff on the mobject.

So, testing it would require, in a matter of coherence, to test a lot of other getters and stuff.

**Comment by leotrs** [comment]
I'm not sure I agree, but I don't think this PR is the right place to discuss that. Let's just merge this one.

**Review by leotrs — APPROVED** [review]

**Review by behackl — APPROVED** [review]
LGTM

**Pull request merged**
