### PR TITLE
Remove deprecated function from `opengl_surface.py`

### PR DESCRIPTION
**Pull request by alembcke**
## Overview: What does this pull request change?

Remove deprecated function `~.set_fill_by_value()` from `opengl_surface.py`.

## Motivation and Explanation: Why and how do your changes improve the library?

The deprecated function never worked in the first place and has been deprecated since v0.16.0.  The function was originally copy and pasted from the Cairo version, which remains in place and does work.

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by MrDiver** [comment]
I would wait with this until we managed to keep up with 3b1b/manim again

**Comment by alembcke** [comment]
> I would wait with this until we managed to keep up with 3b1b/manim again

But this was never part of 3b1b/manim, it was something added after that and so removing it would likely make it easier to spot differences with 3b1b/manim.  Or do you have another reason for waiting until we match 3b1b/manim?

**Comment by MrDiver** [comment]
I am already working on a PR which ports all the changes and updates from 3b1b/manim and pushing this change would most likely result in github going crazy with code matching because it's a lot of changes

**Comment by alembcke** [comment]
Got it, that makes sense.

**Review by MrDiver — APPROVED** [review]

**Comment by MrDiver** [comment]
Have gone through the changes and decided i doesn't conflict. Thanks for the help!

**Pull request merged**
