### PR TITLE
Show inheritance in Documentation

### PR DESCRIPTION
**Pull request by behackl**
## List of Changes
- In the reference manual, classes now display where they are inherited from.
- #514 introduced some warnings during documentation build (due to a misformatted `testoutput` block). This is also fixed here.

## Further Comments
The doctest in `configuration.rst` is currently not run as part of the pipeline... maybe we should enable this. (Which would require calling `make doctest` from the `docs` directory.)

## Acknowledgement
- [x] I have read the [Contributing Guidelines](https://github.com/ManimCommunity/manim/wiki/Documentation-guidelines-(WIP))

### CODE REVIEW

**Review by leotrs — COMMENTED** [review]
I agree we should show inheritance. However, what is the change that required updating `configuration.rst`?

**Comment by behackl** [comment]
> I agree we should show inheritance. However, what is the change that required updating `configuration.rst`?

1. `make doctest` from `docs/` currently fails on master, this fixes it.
2. Compare the formatting of https://manimce.readthedocs.io/en/latest/tutorials/configuration.html to https://manimce--537.org.readthedocs.build/en/537/tutorials/configuration.html

**Review by leotrs — APPROVED** [review]

**Comment by leotrs** [comment]
TBH I kinda hate the way that configuration.rst looks like right now - when I made it it was just a lazy way of automatically documenting all the available flags, though we might want to do something better in the future. Thanks for fixing it for now tho.

**Comment by behackl** [comment]
> TBH I kinda hate the way that configuration.rst looks like right now - when I made it it was just a lazy way of automatically documenting all the available flags, though we might want to do something better in the future. Thanks for fixing it for now tho.

Same here. Agreed. Do you maybe want to open an issue for it? Reformatting `configuration.rst` is a good "first issue"-issue. :-)

**Comment by kolibril13** [comment]
Looks good, thanks!
I just tried some inheritance links, very useful.
Still one question:
https://manimce--537.org.readthedocs.build/en/537/reference/manim.container.Container.html#manim.container.Container
It saies:
`Bases: abc.ABC`
Do we want to add to the Container docstring what abc means?

**Review by kolibril13 — APPROVED** [review]

**Comment by leotrs** [comment]
It kind of already does in that the first three words in the second sentence are precisely "Abstract base class".

**Pull request merged**
