### PR TITLE
Fixed a few CLI and rendering bugs

### LINKED ISSUE #1532: CLI output does not point to the right file/folder when rendering in a non-mp4 format
## Description of bug / unexpected behavior
```
C:\Users\Daryl\manim-videos\manim-videos>manim --format gif circletest.py
Manim Community v0.6.0

[05/17/21 17:47:53] INFO     Animation 0 : Partial movie file written in {'C:\\Users\\Daryl\\m scene_file_writer.py:401
                             anim-videos\\manim-videos\\media\\videos\\circletest\\1080p60\\pa
                             rtial_movie_files\\CircleTest\\450974505_3098578322_3198892316.mp
                             4'}
[05/17/21 17:47:54] INFO                                                                       scene_file_writer.py:585
                             File ready at C:\Users\Daryl\manim-videos\manim-videos\media\vide
                             os\circletest\1080p60\CircleTest.mp4

                    INFO     Rendered CircleTest                                                           scene.py:217
                             Played 1 animations
```
The output points to `CircleTest.mp4` while it should actually be `CircleTest_ManimCE_v0.6.0.gif` (also the name is different, not sure if this is intended). `--format png` also points to the same wrong place when it should point to `media\images\circletest`. 

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
from manim import *

class CircleTest(Scene):
    def construct(self):
        a = Circle()
        self.play(Create(a))
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

### LINKED ISSUE #1533: Formatting to png does not give any output when run with caching enabled, and the scene has already been rendered to any file format
## Description of bug / unexpected behavior
Running
```
C:\Users\Daryl\manim-videos\manim-videos>manim --format png circletest.py
Manim Community v0.6.0

[05/17/21 17:54:39] INFO     Animation 0 : Using cached data (hash :                              cairo_renderer.py:100
                             450974505_3098578322_3198892316)
                    INFO                                                                       scene_file_writer.py:585
                             File ready at C:\Users\Daryl\manim-videos\manim-videos\media\vide
                             os\circletest\1080p60\CircleTest.mp4

                    INFO     Rendered CircleTest                                                           scene.py:217
                             Played 1 animations
```
after running the scene normally (and formatting to mp4) does not produce any images. Running
```
C:\Users\Daryl\manim-videos\manim-videos>manim --format png --disable_caching circletest.py
Manim Community v0.6.0

[05/17/21 17:55:07] INFO     Caching disabled.                                                     cairo_renderer.py:93
[05/17/21 17:55:11] INFO     Animation 0 : Partial movie file written in {'C:\\Users\\Daryl\\m scene_file_writer.py:401
                             anim-videos\\manim-videos\\media\\videos\\circletest\\1080p60\\pa
                             rtial_movie_files\\CircleTest\\uncached_00000.mp4'}
                    INFO                                                                       scene_file_writer.py:585
                             File ready at C:\Users\Daryl\manim-videos\manim-videos\media\vide
                             os\circletest\1080p60\CircleTest.mp4

                    INFO     Rendered CircleTest                                                           scene.py:217
                             Played 1 animations
```
correctly creates the images in the images folder.

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
Paste your code here.
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

### PR DESCRIPTION
**Pull request by ryanmccauley211**
## Changelog / Overview

Fixes #1532 and fixes #1533

- Corrected issue where Gifs were being logged with an incorrect extension
- Stopped outputting videos when format set to png
- Logged png output
- Added precedence handling when the`write_to_movie` flag would conflict with `--format png` config.
- Fixed issue that caused png image output to be ignored when caching was enabled and cached file was found in the partial movie directory

## Motivation

Fix issues around setting the format of output, improve logging and adding some precedence around `write_to_movie` and `--format`config makes it more useable. 
## Explanation for Changes

Fix bugs, improve logging that makes it easier to output the format you want

## Testing Status

Added tests to check that only the format requested is output and targets the correct location.

## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [x] My new functions/classes either have a docstring or are private
- [x] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [x] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Review by Darylgolden — CHANGES_REQUESTED** [review]
Hi @ryanmccauley211, sorry for the wait! I have two suggestions:

- Can you make it so that when using `--format png`, a message isn't given for each png generated, but just the directory is given at the end?
- Can you write the title and the points under the changelog section in a changelog style? eg. "Corrected issue where Gifs were being logged with an incorrect extension"

Other than that, LGTM!

**Comment by ryanmccauley211** [comment]
> Hi @ryanmccauley211, sorry for the wait! I have two suggestions:
> 
> * Can you make it so that when using `--format png`, a message isn't given for each png generated, but just the directory is given at the end?
> * Can you write the title and the points under the changelog section in a changelog style? eg. "Corrected issue where Gifs were being logged with an incorrect extension"
> 
> Other than that, LGTM!

Thanks @Darylgolden, I updated the PR with both of your' suggestions

**Comment by Darylgolden** [comment]
It still seems to give a message for each png, can you fix that?

**Comment by ryanmccauley211** [comment]
> It still seems to give a message for each png, can you fix that?

Hmm it is only printing once for me:

```
Manim Community v0.6.0

[06/03/21 16:51:11] INFO                                scene_file_writer.py:353
                             270 images ready at /Users                         
                             /ryan/PycharmProjects/mani                         
                             m-community/manim/media/im                         
                             ages/integrals/AxesExample                         
                                                                                
                    INFO     Rendered AxesExample                   scene.py:220
                             Played 10 animations                               
You are using manim version v0.6.0, but version v0.7.0 is available.
```

Can you share your logs and config please to help me reproduce it?

**Comment by Darylgolden** [comment]
I get
```
C:\Users\Daryl\manim-dev\manim>manim --format png circletest.py
Manim Community v0.6.0

Animation 0: Create(Circle):   0%|                                                              | 0/60 [00:00<?, ?it/s][06/05/21 10:43:56] INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test0.png

                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test1.png

Animation 0: Create(Circle):   3%|#8                                                    | 2/60 [00:00<00:04, 12.77it/s]                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test2.png

                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test3.png

Animation 0: Create(Circle):   7%|###6                                                  | 4/60 [00:00<00:04, 13.79it/s]                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test4.png

                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test5.png

Animation 0: Create(Circle):  10%|#####4                                                | 6/60 [00:00<00:03, 14.48it/s][06/05/21 10:43:57] INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test6.png

                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test7.png

Animation 0: Create(Circle):  13%|#######2                                              | 8/60 [00:00<00:03, 15.00it/s]                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test8.png

                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test9.png

Animation 0: Create(Circle):  17%|########8                                            | 10/60 [00:00<00:03, 14.70it/s]                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test10.png

                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test11.png

Animation 0: Create(Circle):  20%|##########6                                          | 12/60 [00:00<00:03, 15.08it/s]                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test12.png

                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test13.png

Animation 0: Create(Circle):  23%|############3                                        | 14/60 [00:00<00:02, 15.36it/s]                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test14.png

                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test15.png

Animation 0: Create(Circle):  27%|##############1                                      | 16/60 [00:01<00:02, 15.52it/s]                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test16.png

                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test17.png

Animation 0: Create(Circle):  30%|###############9                                     | 18/60 [00:01<00:02, 15.55it/s]                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test18.png

                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test19.png

Animation 0: Create(Circle):  33%|#################6                                   | 20/60 [00:01<00:02, 15.17it/s]                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test20.png

[06/05/21 10:43:58] INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test21.png

Animation 0: Create(Circle):  37%|###################4                                 | 22/60 [00:01<00:02, 14.85it/s]                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test22.png

                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test23.png

Animation 0: Create(Circle):  40%|#####################2                               | 24/60 [00:01<00:02, 15.14it/s]                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test24.png

                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test25.png

Animation 0: Create(Circle):  43%|######################9                              | 26/60 [00:01<00:02, 14.83it/s]                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test26.png

                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test27.png

Animation 0: Create(Circle):  47%|########################7                            | 28/60 [00:01<00:02, 14.63it/s]                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test28.png

                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test29.png

Animation 0: Create(Circle):  50%|##########################5                          | 30/60 [00:02<00:02, 14.99it/s]                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test30.png

                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test31.png

Animation 0: Create(Circle):  53%|############################2                        | 32/60 [00:02<00:01, 14.74it/s]                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test32.png

                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test33.png

Animation 0: Create(Circle):  57%|##############################                       | 34/60 [00:02<00:01, 15.08it/s]                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test34.png

                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test35.png

Animation 0: Create(Circle):  60%|###############################8                     | 36/60 [00:02<00:01, 14.79it/s][06/05/21 10:43:59] INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test36.png

                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test37.png

Animation 0: Create(Circle):  63%|#################################5                   | 38/60 [00:02<00:01, 14.60it/s]                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test38.png

                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test39.png

Animation 0: Create(Circle):  67%|###################################3                 | 40/60 [00:02<00:01, 13.98it/s]                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test40.png

                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test41.png

Animation 0: Create(Circle):  70%|#####################################                | 42/60 [00:02<00:01, 14.04it/s]                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test42.png

                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test43.png

Animation 0: Create(Circle):  73%|######################################8              | 44/60 [00:02<00:01, 14.05it/s]                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test44.png

                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test45.png

Animation 0: Create(Circle):  77%|########################################6            | 46/60 [00:03<00:00, 14.11it/s]                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test46.png

                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test47.png

Animation 0: Create(Circle):  80%|##########################################4          | 48/60 [00:03<00:00, 14.09it/s]                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test48.png

                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test49.png

Animation 0: Create(Circle):  83%|############################################1        | 50/60 [00:03<00:00, 14.10it/s][06/05/21 10:44:00] INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test50.png

                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test51.png

Animation 0: Create(Circle):  87%|#############################################9       | 52/60 [00:03<00:00, 14.13it/s]                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test52.png

                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test53.png

Animation 0: Create(Circle):  90%|###############################################7     | 54/60 [00:03<00:00, 14.13it/s]                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test54.png

                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test55.png

Animation 0: Create(Circle):  93%|#################################################4   | 56/60 [00:03<00:00, 14.14it/s]                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test56.png

                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test57.png

Animation 0: Create(Circle):  97%|###################################################2 | 58/60 [00:03<00:00, 14.16it/s]                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test58.png

                    INFO                                                                        scene_file_writer.py:589
                             File ready at
                             C:\Users\Daryl\manim-dev\manim\media\images\circletest\Test59.png

                    INFO     Rendered Test                                                                  scene.py:219
                             Played 1 animations
```

**Comment by Darylgolden** [comment]
Did you make sure you added and committed all your changes?

**Comment by Nikhil0504** [comment]
Hey I tried this PR in linux and I don't get the output as intended but I do get all the images after the rendering is done.
Here is the output that I got:
```
manim --format png ../testing_manim/graphs.py sphere                             
Manim Community v0.7.0

VGroup of 2 submobjects
[06/05/21 12:31:23] INFO     Animation 0 : Partial movie file written in {'/home/xxxx/Desktop/manim/media/videos/graphs/1080p60/partial_movie_files/sphere/4039617418_1986432116_2235843313.mp4'}                                                 scene_file_writer.py:401
                    INFO                                                                                                                                                                                                                            scene_file_writer.py:585
                             File ready at /home/xxxx/Desktop/manim/media/videos/graphs/1080p60/sphere.mp4                                                                                                                                                                
                                                                                                                                                                                                                                                                            
                    INFO     Rendered sphere                                                                                                                                                                                                                    scene.py:219
                             Played 1 animations       
```

**Comment by ryanmccauley211** [comment]
> Did you make sure you added and committed all your changes?

Yes I checked the diff on github and shows the changes I made. If you look at your logs, scene_file_writer.py:589 is an empty line on the file I have committed so I don't think your local is updated to this branch

**Review by Darylgolden — APPROVED** [review]
It seemed that after reinstalling manim in poetry, the changes worked. Thank you for your contributions, and sorry for the inconvenience!

**Review by Nikhil0504 — APPROVED** [review]
It works for me also. Thanks for the PR and sorry for the inconvience.
```
Manim Community v0.7.0

[06/05/21 19:09:25] INFO                                                                                                                                                                                                                            scene_file_writer.py:353
                             60 images ready at /media/xyz/Store/Coding/manim/media/images/testing/bar                                                                                                                                                                   
                                                                                                                                                                                                                                                                            
                    INFO     Rendered bar                                                                                                                                                                                                                       scene.py:219
                             Played 1 animations 
```

**Pull request merged**
