### PR TITLE
Add support for webm and jupyter transparency

### PR DESCRIPTION
**Pull request by ryanmccauley211**
## Changelog / Overview

- Add webm support via --format argument
- Handle transparency in jupyter by using webm format instead of mov

## Motivation

Currently .mov isn't supported in the main browsers and we currently have no other options that support transparency. Webm
has alpha channel support and more support in browsers for web rendering
## Explanation for Changes

Allows webm to be used as an alternative format that supports alpha channels to .mov 

## Testing Status

Added tests for the new formats and checks that -t flag still defaults to .mov when `--format webm` is not specified. Currently I haven't been able to find a good way of testing video outputs with jupyter, we can't use a temporary path because the ManimMagic class only uses relative paths:

```py
local_path = Path(config["output_file"]).relative_to(Path.cwd())
```

## Checklist
- [X] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [X] I have written a descriptive PR title (see top of PR template for examples)
- [X] I have written a changelog entry for the PR or deem it unnecessary
- [X] My new functions/classes either have a docstring or are private
- [X] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [X] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [x] The PR title is descriptive enough
- [x] The PR is labeled correctly
- [x] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by kolibril13** [comment]
Thanks for this contribution.
This will be really convenient to make e.g. contributions to Wikipedia.
I will test and review this on the weekend!

**Review by behackl — APPROVED** [review]
Adding webm support is a great new feature, and I think it is sensible to change the default output format in jupyter notebooks when transparency is requested to webm, especially given that most of the [current browsers support it properly](https://caniuse.com/webm).

I've tested it locally; it works as expected -- and the tests you've added are great as well. Thank you for another excellent contribution!

**Comment by kolibril13** [comment]
I agree, this is really great!
I just made a timing test: webm is about 16 times slower than rendering to mp4.
image
and then also, the file size increases with webm:
image
The higher file size is something I did not expect, and I guess that is due to manims really efficient way to write mp4 files.

Regarding the speed:
I think we should add documentation about the slowness somewhere.
Maybe as a warning "Warning: .webm rendering is a slower than .mp4 rendering".

I am also fine now with the idea, that -t is default to .webm in jupyter

**Comment by ryanmccauley211** [comment]
> Regarding the speed:
> I think we should add documentation about the slowness somewhere.
> Maybe as a warning "Warning: .webm rendering is a slower than .mp4 rendering".

Sure, I can add a warning, were you thinking in the docs or log the warning? I think logging makes sense when webm is set

**Comment by kolibril13** [comment]
Yes, logging when webm is set would be great!
I dont know where in the code would be the right place for that, I think anywhere it works is fine.

**Comment by behackl** [comment]
> I guess that is due to manims really efficient way to write mp4 files

Manim doesn't have anything to do with it, it's simply that VP9 is a more complex codec in comparison to H.264. See e.g. https://superuser.com/questions/1211786/why-is-encoding-vp8-9-so-slow-compared-to-h-264

Personally, I don't think a warning is required, but if one is printed it should come soon after the CLI call (and debug level info is certainly sufficient).

Btw, in case someone explicitly wants the .mov in a Jupyter notebook there is no way to do so it seems. It might be useful to allow `--format=mov` there as well.

**Comment by ryanmccauley211** [comment]
> Btw, in case someone explicitly wants the .mov in a Jupyter notebook there is no way to do so it seems. It might be useful to allow `--format=mov` there as well.

This is already handled with this line:

```py
            if "-t" in args and "--format" not in args:
                additional_args += ["--format", "webm"]
```

It only sets webm as a defauly if --format is not set explicitly



> Yes, logging when webm is set would be great!
> I dont know where in the code would be the right place for that, I think anywhere it works is fine.

Added warning

**Comment by ryanmccauley211** [comment]
> Btw, in case someone explicitly wants the .mov in a Jupyter notebook there is no way to do so it seems. It might be useful to allow `--format=mov` there as well.

Done, can now be set via --format option

**Comment by behackl** [comment]
> > Btw, in case someone explicitly wants the .mov in a Jupyter notebook there is no way to do so it seems. It might be useful to allow `--format=mov` there as well.
> 
> Done, can now be set via --format option

Thanks! I saw that it was technically possible before as well, but "mov" was not one of the passable render options; you've fixed that in 2ac10be though.

**Pull request merged**
