### PR TITLE
Fix graph updater to respect vertex boundaries

### LINKED ISSUE #2843: `self.play(Create(G))` connects edges to the centre of vertices unlike `self.add(G)` for Graphs
## Description of bug / unexpected behavior

The edges connect to the center of vertices in `self.play(Create(G))` 

## Expected behavior

I would expect it to output a graph similar to what happens in `self.add(G)`

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
from manim import *

class bugreport_expected(Scene):
    def construct(self):
        edges = [(1, 2), (1, 3), (2, 4), (2, 5), (2, 9), (3, 7), (3, 8), (4, 9), (9, 10), (5, 6), (6, 7), (6, 8), (7, 8), (8, 10), (10, 1)]
        vertices = list(range(1,11))
        vertex_config = {}
        for i in vertices:
            vertex_config[i] = {'radius': 0.2, 'color': WHITE}
        edge_config = {}
        for i in edges:
            edge_config[i] = {'stroke_width': 3, 'tip_length': 0.2, 'color': WHITE}
        labels = {}
        labels_text = "abcdefghij"
        for i in vertices:
            labels[i] = Tex(r''+labels_text[i-1], color=BLACK)
        G = Graph(vertices, edges, layout="circular", vertex_config=vertex_config, edge_config=edge_config, edge_type=Arrow, labels = labels)
        self.add(G)

class bugreport_actual(Scene):
    def construct(self):
        edges = [(1, 2), (1, 3), (2, 4), (2, 5), (2, 9), (3, 7), (3, 8), (4, 9), (9, 10), (5, 6), (6, 7), (6, 8), (7, 8), (8, 10), (10, 1)]
        vertices = list(range(1,11))
        vertex_config = {}
        for i in vertices:
            vertex_config[i] = {'radius': 0.2, 'color': WHITE}
        edge_config = {}
        for i in edges:
            edge_config[i] = {'stroke_width': 3, 'tip_length': 0.2, 'color': WHITE}
        labels = {}
        labels_text = "abcdefghij"
        for i in vertices:
            labels[i] = Tex(r''+labels_text[i-1], color=BLACK)
        G = Graph(vertices, edges, layout="circular", vertex_config=vertex_config, edge_config=edge_config, edge_type=Arrow, labels = labels)
        self.play(Create(G))
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

bugreport_ManimCE_v0 15 2

https://user-images.githubusercontent.com/5823408/174984342-1fbc91c4-5f1d-4f95-afa8-23dccc8f24f7.mp4

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g., Windows 10 v2004 or macOS 10.15 (Catalina)): Mac OS 12
- RAM: 8GB
- Python version (`python/py/python3 --version`): 3.10
- Installed modules (provide output from `pip list`): 
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020): TeX Live 2021
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

### PR DESCRIPTION
**Pull request by noamzaks**
## Overview: What does this pull request change?
The graph's updater now uses the underlying `_set_start_and_end_attrs` method of Line-based mobjects so that it respects the boundaries of the start/end mobjects.

Before:

https://user-images.githubusercontent.com/63877260/175780272-67605e57-7d61-47ae-a06a-af90fd61d56f.mp4

After:

https://user-images.githubusercontent.com/63877260/175780277-537a99d5-ba48-40c7-ba3c-09ed2139e443.mp4

For the snippet

```python
class Testing(Scene):
    def construct(self):
        g = Graph([0, 1], [(0, 1)], edge_type=Arrow, labels=True)
        self.add(g)
        self.wait()
        self.play(g.animate.shift(DOWN))
```

## Motivation and Explanation: Why and how do your changes improve the library?
While temporarily calling `clear_updaters()` helps, in any cases where there are moving vertices the animation must currently still not be continuous because while the constructor respects the start/end mobjects' boundaries, the updater doesn't.
This fix makes everything 'smooth' and continuous (and also, respect the mobjects' boundaries which is more visually pleasing).

## Further Information and Comments
Closes #2843.

- Unfortunately, this breaks edge cases where the `edge_type` doesn't have a `_set_start_and_end_attrs` method (which is possible only if it doesn't inherit from Line)
- Therefore, it **might** make sense to abstract the `_set_start_and_end_attrs` into another place, and perhaps even rename it.

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by noamzaks** [comment]
I'm guessing the file `tests/test_graphical_units/control_data/threed/MovingVertices.npz` needs to be replaced accordingly, but how does one create the appropriate `.npz`?

**Comment by MrDiver** [comment]
> [...] but how does one create the appropriate .npz?

Please refer to the contribution guide [here](https://docs.manim.community/en/stable/contributing.html) in the AddingTests section.

First check if the test really needs to be replaced.

**Comment by noamzaks** [comment]
> > [...] but how does one create the appropriate .npz?
> 
> Please refer to the contribution guide [here](https://docs.manim.community/en/stable/contributing.html) in the AddingTests section.
> 
> First check if the test really needs to be replaced.

Thank you!
I believe the test makes sure the frames of the animation in the ThreeD scene are as expected. Thus, if we change the behavior of the updater (which changes the edges' position) the resulting frames are different and should be different

**Comment by noamzaks** [comment]
It seems this change, accounting for the vertices' radiuses, looks worse in 3D scenes. Perhaps there is an underlying issue with `get_boundary_point`.

Here's the 3D scene from the test, with the new change:

https://user-images.githubusercontent.com/63877260/177015982-ea5a3e14-6ffa-4cf8-8b48-64767d9c4671.mp4

Here's it without doing so (the current state):

https://user-images.githubusercontent.com/63877260/177015992-1005fb65-5e3e-4a6f-b60c-5dfc8bcc494f.mp4



In any case, my so-called "solution" is not elegant at all;
Looking for thoughts about how to improve on it (perhaps detect a 3D scene automatically).

**Pull request closed without merging**
