### PR TITLE
Change `Union[float, int]` to just `float` according to PEP 484

### PR DESCRIPTION
**Pull request by kamilczerwinski22**
## Motivation

[#1409](https://github.com/ManimCommunity/manim/issues/1409)
## Explanation for Changes

Simple change according to PEP 484 standard.

## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by RickyC0626** [comment]
Duplicate of #1410. Please keep in mind in the future that you do not need to open a new PR when making new changes. You can continue to commit and push to the same branch, and it will update the PR accordingly.

Also, when linking PRs to issues you want to close, you can [use special keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) to close the issue automatically once the PR is merged.

**Comment by kamilczerwinski22** [comment]
> Duplicate of #1410. Please keep in mind in the future that you do not need to open a new PR when making new changes. You can continue to commit and push to the same branch, and it will update the PR accordingly.
> 
> Also, when linking PRs to issues you want to close, you can [use special keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) to close the issue automatically once the PR is merged.

I did not know that, thank you. Also, sorry for inconvenience

**Comment by RickyC0626** [comment]
> I did not know that, thank you. Also, sorry for inconvenience

No problem! Thanks for taking the time to contribute.

**Review by kolibril13 — APPROVED** [review]

**Review by naveen521kk — APPROVED** [review]
lgtm

**Comment by jsonvillanueva** [comment]
@naveen521kk please remember to label/make the PR name more descriptive before merging

**Pull request merged**
