### PR TITLE
Adding the ability to pass lists and generators to .play()

### PR DESCRIPTION
**Pull request by MrDiver**
Not much of a big change but adding the ability to pass generators to self.play because the `*` are at some point kind of a hassle, i would also suggest doing this for other things like animations where a list is expect like for animation groups. That would make it much more intuitive. For things like `FadeIn(a,b,c)` i think it makes sense to just leave it like that. But it general it doesn't hurt our functionality in any way because were just iterating over the arguments anyway.

Changes

- [x] `self.play` supports generators
- [x] `AnimationGroup` supports generators
- [ ] `VGroup` supports generators

```py
class Test6(Scene):
    def construct(self):
        l = [Dot().shift(RIGHT*i+5*LEFT) for i in range(10)]
        self.play(AnimationGroup(map(AnimationGroup,zip((FadeIn(x) for x in l[:5]), (FadeIn(x) for x in reversed(l[5:])))), lag_ratio=0.1))
```

### CODE REVIEW

**Review by JasonGrace2282 — APPROVED** [review]
Seems like a good addition to me :)

**Comment by JasonGrace2282** [comment]
If the above is added (which I think is a good idea), then this should definitely be documented as well.

**Comment by MrDiver** [comment]
Also should be added to VGroup and Group and all of those kinds of classes and or methods to do something

**Comment by MrDiver** [comment]
> It might be worth it to make the logic for parsing iterables a little more complex to deal with situations like
> 
> ```python
> self.play([anim1, anim2], anim3, anim4)
> ```
> 
> correctly too; currently this would throw away animations `anim3` and `anim4`.
> 
> If all iterables were unpacked correctly, something like
> 
> ```python
> self.play(
>   (anim(param) for param in space),
>   (other_anim(param) for param in other_space),
> )
> ```
> 
> would be possible too. What do you think?

Absolutely love it ❤️ 

Btw how/where should we document this ?

**Review by JasonGrace2282 — APPROVED** [review]
LGTM!

**Pull request merged**
