### PR TITLE
Let :class:`~.Create` work on :class:`~.OpenGLSurface`

### PR DESCRIPTION
**Pull request by Darylgolden**
## Motivation
Previously, when trying to run the `Create` animation on `OpenGLSurface`, such as in the following:

```py
from manim import *
from manim.mobject.opengl_three_dimensions import OpenGLSphere

class Test(Scene):
    def construct(self):
        a = OpenGLSphere()
        self.play(Create(a))
```

manim returns an error:

```
Manim Community v0.6.0

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\Daryl\manim-dev\manim\manim\cli\render\commands.py:109 in render                        │
│                                                                                                  │
│   106 │   │   │   │   │   scene_classes = scene_classes_from_file(file)                          │
│   107 │   │   │   │   │   SceneClass = scene_classes[0]                                          │
│   108 │   │   │   │   │   scene = SceneClass(renderer)                                           │
│ ❱ 109 │   │   │   │   │   status = scene.render()                                                │
│   110 │   │   │   │   │   if status:                                                             │
│   111 │   │   │   │   │   │   continue                                                           │
│   112 │   │   │   │   │   else:                                                                  │
│                                                                                                  │
│ C:\Users\Daryl\manim-dev\manim\manim\scene\scene.py:210 in render                                │
│                                                                                                  │
│    207 │   │   """                                                                               │
│    208 │   │   self.setup()                                                                      │
│    209 │   │   try:                                                                              │
│ ❱  210 │   │   │   self.construct()                                                              │
│    211 │   │   except EndSceneEarlyException:                                                    │
│    212 │   │   │   pass                                                                          │
│    213 │   │   except RerunSceneException as e:                                                  │
│                                                                                                  │
│ C:\Users\Daryl\manim-dev\manim\test.py:7 in construct                                            │
│                                                                                                  │
│   4 class Test(Scene):                                                                           │
│   5 │   def construct(self):                                                                     │
│   6 │   │   a = OpenGLSphere()                                                                   │
│ ❱ 7 │   │   self.play(Create(a))                                                                 │
│                                                                                                  │
│ C:\Users\Daryl\manim-dev\manim\manim\animation\creation.py:165 in __init__                       │
│                                                                                                  │
│   162 │   │   lag_ratio: float = 1.0,                                                            │
│   163 │   │   **kwargs,                                                                          │
│   164 │   ) -> None:                                                                             │
│ ❱ 165 │   │   super().__init__(mobject, lag_ratio=lag_ratio, **kwargs)                           │
│   166 │                                                                                          │
│   167 │   def _get_bounds(self, alpha: float) -> Tuple[int, float]:                              │
│   168 │   │   return (0, alpha)                                                                  │
│                                                                                                  │
│ C:\Users\Daryl\manim-dev\manim\manim\animation\creation.py:118 in __init__                       │
│                                                                                                  │
│   115 │                                                                                          │
│   116 │   def __init__(self, mobject: Union[Mobject, OpenGLVMobject, None], **kwargs):           │
│   117 │   │   if not isinstance(mobject, (VMobject, OpenGLVMobject)):                            │
│ ❱ 118 │   │   │   raise TypeError("This Animation only works on vectorized mobjects")            │
│   119 │   │   super().__init__(mobject, **kwargs)                                                │
│   120 │                                                                                          │
│   121 │   def interpolate_submobject(                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: This Animation only works on vectorized mobjects
```

despite `pointwise_become_partial` being defined on `OpenGLSurface` (thus allowing `Create` to work perfectly well, if not for the assert statement). This PR changes the assert statement so `OpenGLSurface`s are allowed to be passed into `Create`.

## Explanation for Changes

[Documentation Reference](https://manimce--####.org.readthedocs.build)

## Testing Status

An example of what it looks like:

https://user-images.githubusercontent.com/9102529/124720660-f4050900-df3a-11eb-9d0f-05be75d53b9e.mp4

## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by behackl** [comment]
I'd just like to understand: is `OpenGLSurface` not a `OpenGLVMobject` because its points array is used differently than usually for `OpenGLVMobject`?

**Comment by Darylgolden** [comment]
> 
> 
> I'd just like to understand: is `OpenGLSurface` not a `OpenGLVMobject` because its points array is used differently than usually for `OpenGLVMobject`?

Yes, `OpenGLVMobject` uses quadratic bezier shaders while `OpenGLSurface` uses the surface shaders. I don't think it makes sense to use quadratic beziers to render surfaces. Anyways, this isn't really related to the PR.

**Comment by behackl** [comment]
> > I'd just like to understand: is `OpenGLSurface` not a `OpenGLVMobject` because its points array is used differently than usually for `OpenGLVMobject`?
> 
> Yes, `OpenGLVMobject` uses quadratic bezier shaders while `OpenGLSurface` uses the surface shaders. I don't think it makes sense to use quadratic beziers to render surfaces. Anyways, this isn't really related to the PR.

It is, because if `OpenGLSurface` were a `OpenGLVMobject`, `Create` would already work. Given that `OpenGLSurface` explicitly sets the shaders that are used for it, I'm not sure why it wouldn't just inherit from `OpenGLVMobject`– is there any other argument that speaks against it?

**Comment by eulertour** [comment]
@behackl Some of the methods that are specific to `OpenGLVMobject`s don't make sense for `OpenGLSurface`s. For example, `add_bezier_curve_to` doesn't make sense on an `OpenGLSurface`.

**Review by eulertour — APPROVED** [review]

**Comment by behackl** [comment]
> @behackl Some of the methods that are specific to `OpenGLVMobject`s don't make sense for `OpenGLSurface`s. For example, `add_bezier_curve_to` doesn't make sense on an `OpenGLSurface`.

I see, that makes sense.

What about changing the implementation of `Create` so that, instead of checking for a class, it checks whether the passed mobject has a `pointwise_become_partial` method? (The name of that is actually also not great / very explicit, but let's change the world one issue at a time.)

**Comment by Darylgolden** [comment]
Done; I've also removed the `pointwise_become_partial` method from `Mobject` so the error is handled in one place.

**Review by behackl — APPROVED** [review]
LGTM now, thanks!

**Pull request merged**
