### PR TITLE
Calling reshape method on array in function "get_bezier_tuples_from_points" in file "manim/mobject/opengl/opengl_vectorized_mobject.py" results in AttributeError

### PR DESCRIPTION
**Pull request by NotAGameDev07**
## Summary of Changes
In function `get_bezier_tuples_from_points`, inside file `manim/mobject/opengl/opengl_vectorized_mobjet.py` , method `reshape` was called on a python array instead of a numpy array, this was changed so that `points = points[: len(points) - remainder]` is now `points = np.array(points[: len(points) - remainder])`

## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have added a test case to prevent software regression

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled appropriately
- [ ] Regression test(s) are implemented

### CODE REVIEW

**Comment by behackl** [comment]
Heya @NotAGameDev07 -- apologies for the long wait.

Do you by any chance have a code example or full stack trace where this error that you are fixing here occurs? I feel like this is more a problem of the calling function rather than `get_bezier_tuples_from_points`; Manim assumes that the structures containing points are `np.ndarray`s in many places, and as this function isn't really something that I expect users to call explicitly, it would be more consistent to fix whichever function calls this method.

**Comment by MrDiver** [comment]
I agree with @behackl on this point. I spent a lot of time trying to figure out many places from which this function is called and fix a lot of pain points where the function is called with the wrong arguments. So i wouldn't change it at this layer because it should be guaranteed that a numpy array is passed. Converting it in this function just makes for another point of casting.

In general i would also suggest doing `np.asarray` if you are "unsure" about which type of array you get as a parameter, such that you don't copy your array unnecessarily if you already pass a numpy array. Because it can cost you a lot of performance.

**Comment by jinliangyu** [comment]
I also met the same issue when running:
`python -m manim -p .\example_scenes\basic.py OpeningManim --renderer=opengl`
The terminal output:
```
Manim Community v0.17.3

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\ejalnii\PycharmProjects\manim\manim\cli\render\commands.py:97 in render                 │
│                                                                                                  │
│    94 │   │   │   │   for SceneClass in scene_classes_from_file(file):                           │
│    95 │   │   │   │   │   with tempconfig({}):                                                   │
│    96 │   │   │   │   │   │   scene = SceneClass(renderer)                                       │
│ ❱  97 │   │   │   │   │   │   rerun = scene.render()                                             │
│    98 │   │   │   │   │   if rerun or config["write_all"]:                                       │
│    99 │   │   │   │   │   │   renderer.num_plays = 0                                             │
│   100 │   │   │   │   │   │   continue                                                           │
│                                                                                                  │
│ C:\Users\ejalnii\PycharmProjects\manim\manim\scene\scene.py:223 in render                        │
│                                                                                                  │
│    220 │   │   """                                                                               │
│    221 │   │   self.setup()                                                                      │
│    222 │   │   try:                                                                              │
│ ❱  223 │   │   │   self.construct()                                                              │
│    224 │   │   except EndSceneEarlyException:                                                    │
│    225 │   │   │   pass                                                                          │
│    226 │   │   except RerunSceneException as e:                                                  │
│                                                                                                  │
│ C:\Users\ejalnii\PycharmProjects\manim\example_scenes\basic.py:31 in construct                   │
│                                                                                                  │
│    28 │   │                                                                                      │
│    29 │   │   transform_title = Tex("That was a transform")                                      │
│    30 │   │   transform_title.to_corner(UP + LEFT)                                               │
│ ❱  31 │   │   self.play(                                                                         │
│    32 │   │   │   Transform(title, transform_title),                                             │
│    33 │   │   │   LaggedStart(*(FadeOut(obj, shift=DOWN) for obj in basel)),                     │
│    34 │   │   )                                                                                  │
│                                                                                                  │
│ C:\Users\ejalnii\PycharmProjects\manim\manim\scene\scene.py:1080 in play                         │
│                                                                                                  │
│   1077 │   │   │   return                                                                        │
│   1078 │   │                                                                                     │
│   1079 │   │   start_time = self.renderer.time                                                   │
│ ❱ 1080 │   │   self.renderer.play(self, *args, **kwargs)                                         │
│   1081 │   │   run_time = self.renderer.time - start_time                                        │
│   1082 │   │   if subcaption:                                                                    │
│   1083 │   │   │   if subcaption_duration is None:                                               │
│                                                                                                  │
│ C:\Users\ejalnii\PycharmProjects\manim\manim\utils\caching.py:65 in wrapper                      │
│                                                                                                  │
│   62 │   │   │   "List of the first few animation hashes of the scene: %(h)s",                   │
│   63 │   │   │   {"h": str(self.animations_hashes[:5])},                                         │
│   64 │   │   )                                                                                   │
│ ❱ 65 │   │   func(self, scene, *args, **kwargs)                                                  │
│   66 │                                                                                           │
│   67 │   return wrapper                                                                          │
│   68                                                                                             │
│                                                                                                  │
│ C:\Users\ejalnii\PycharmProjects\manim\manim\renderer\opengl_renderer.py:424 in play             │
│                                                                                                  │
│   421 │   │   self.file_writer.begin_animation(not self.skip_animations)                         │
│   422 │   │                                                                                      │
│   423 │   │   scene.compile_animation_data(*args, **kwargs)                                      │
│ ❱ 424 │   │   scene.begin_animations()                                                           │
│   425 │   │   if scene.is_current_animation_frozen_frame():                                      │
│   426 │   │   │   self.update_frame(scene)                                                       │
│   427                                                                                            │
│                                                                                                  │
│ C:\Users\ejalnii\PycharmProjects\manim\manim\scene\scene.py:1208 in begin_animations             │
│                                                                                                  │
│   1205 │   │   """Start the animations of the scene."""                                          │
│   1206 │   │   for animation in self.animations:                                                 │
│   1207 │   │   │   animation._setup_scene(self)                                                  │
│ ❱ 1208 │   │   │   animation.begin()                                                             │
│   1209 │   │                                                                                     │
│   1210 │   │   if config.renderer == RendererType.CAIRO:                                         │
│   1211 │   │   │   # Paint all non-moving objects onto the screen, so they don't                 │
│                                                                                                  │
│ C:\Users\ejalnii\PycharmProjects\manim\manim\animation\transform.py:201 in begin                 │
│                                                                                                  │
│   198 │   │   # Note, this potentially changes the structure                                     │
│   199 │   │   # of both mobject and target_mobject                                               │
│   200 │   │   if config.renderer == RendererType.OPENGL:                                         │
│ ❱ 201 │   │   │   self.mobject.align_data_and_family(self.target_copy)                           │
│   202 │   │   else:                                                                              │
│   203 │   │   │   self.mobject.align_data(self.target_copy)                                      │
│   204 │   │   super().begin()                                                                    │
│                                                                                                  │
│ C:\Users\ejalnii\PycharmProjects\manim\manim\mobject\opengl\opengl_mobject.py:2306 in            │
│ align_data_and_family                                                                            │
│                                                                                                  │
│   2303 │                                                                                         │
│   2304 │   def align_data_and_family(self, mobject):                                             │
│   2305 │   │   self.align_family(mobject)                                                        │
│ ❱ 2306 │   │   self.align_data(mobject)                                                          │
│   2307 │                                                                                         │
│   2308 │   def align_data(self, mobject):                                                        │
│   2309 │   │   # In case any data arrays get resized when aligned to shader data                 │
│                                                                                                  │
│ C:\Users\ejalnii\PycharmProjects\manim\manim\mobject\opengl\opengl_mobject.py:2314 in align_data │
│                                                                                                  │
│   2311 │   │   for mob1, mob2 in zip(self.get_family(), mobject.get_family()):                   │
│   2312 │   │   │   # Separate out how points are treated so that subclasses                      │
│   2313 │   │   │   # can handle that case differently if they choose                             │
│ ❱ 2314 │   │   │   mob1.align_points(mob2)                                                       │
│   2315 │   │   │   for key in mob1.data.keys() & mob2.data.keys():                               │
│   2316 │   │   │   │   if key == "points":                                                       │
│   2317 │   │   │   │   │   continue                                                              │
│                                                                                                  │
│ C:\Users\ejalnii\PycharmProjects\manim\manim\mobject\opengl\opengl_vectorized_mobject.py:1221 in │
│ align_points                                                                                     │
│                                                                                                  │
│   1218 │   │   │   sp2 = get_nth_subpath(subpaths2, n)                                           │
│   1219 │   │   │   diff1 = max(0, (len(sp2) - len(sp1)) // nppc)                                 │
│   1220 │   │   │   diff2 = max(0, (len(sp1) - len(sp2)) // nppc)                                 │
│ ❱ 1221 │   │   │   sp1 = self.insert_n_curves_to_point_list(diff1, sp1)                          │
│   1222 │   │   │   sp2 = self.insert_n_curves_to_point_list(diff2, sp2)                          │
│   1223 │   │   │   new_subpaths1.append(sp1)                                                     │
│   1224 │   │   │   new_subpaths2.append(sp2)                                                     │
│                                                                                                  │
│ C:\Users\ejalnii\PycharmProjects\manim\manim\mobject\opengl\opengl_vectorized_mobject.py:1272 in │
│ insert_n_curves_to_point_list                                                                    │
│   1275 │   │   # Calculate insertions per curve (ipc)                                            │
│                                                                                                  │
│ C:\Users\ejalnii\PycharmProjects\manim\manim\mobject\opengl\opengl_vectorized_mobject.py:717 in  │
│ get_bezier_tuples_from_points                                                                    │
│                                                                                                  │
│    714 │   │   nppc = self.n_points_per_curve                                                    │
│    715 │   │   remainder = len(points) % nppc                                                    │
│    716 │   │   points = points[: len(points) - remainder]                                        │
│ ❱  717 │   │   return points.reshape((-1, nppc, 3))                                              │
│    718 │                                                                                         │
│    719 │   def get_bezier_tuples(self):                                                          │
│    720 │   │   return self.get_bezier_tuples_from_points(self.points)                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'list' object has no attribute 'reshape'
```
However, I think the issue was caused by the below function (manim/mobject/opengl/opengl_vectorized_mobject.py:1200):
```
def get_nth_subpath(path_list, n):
    if n >= len(path_list):
        # Create a null path at the very end
        return [path_list[-1][-1]] * nppc
    path = path_list[n]
    # Check for useless points at the end of the path and remove them
    # https://github.com/ManimCommunity/manim/issues/1959
    while len(path) > nppc:
        # If the last nppc points are all equal to the preceding point
        if self.consider_points_equals(path[-nppc:], path[-nppc - 1]):
            path = path[:-nppc]
        else:
            break
    return path
```
**Workaround**: change `return [path_list[-1][-1]] * nppc` to `return np.array([path_list[-1][-1]] * nppc)`

Besides, I also find another issue, like below:
```
Manim Community v0.17.3

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\ejalnii\PycharmProjects\manim\manim\cli\render\commands.py:97 in render                 │
│                                                                                                  │
│    94 │   │   │   │   for SceneClass in scene_classes_from_file(file):                           │
│    95 │   │   │   │   │   with tempconfig({}):                                                   │
│    96 │   │   │   │   │   │   scene = SceneClass(renderer)                                       │
│ ❱  97 │   │   │   │   │   │   rerun = scene.render()                                             │
│    98 │   │   │   │   │   if rerun or config["write_all"]:                                       │
│    99 │   │   │   │   │   │   renderer.num_plays = 0                                             │
│   100 │   │   │   │   │   │   continue                                                           │
│                                                                                                  │
│ C:\Users\ejalnii\PycharmProjects\manim\manim\scene\scene.py:223 in render                        │
│                                                                                                  │
│    220 │   │   """                                                                               │
│    221 │   │   self.setup()                                                                      │
│    222 │   │   try:                                                                              │
│ ❱  223 │   │   │   self.construct()                                                              │
│    224 │   │   except EndSceneEarlyException:                                                    │
│    225 │   │   │   pass                                                                          │
│    226 │   │   except RerunSceneException as e:                                                  │
│                                                                                                  │
│ C:\Users\ejalnii\PycharmProjects\manim\example_scenes\basic.py:68 in construct                   │
│                                                                                                  │
│    65 │   │   │   run_time=3,                                                                    │
│    66 │   │   )                                                                                  │
│    67 │   │   self.wait()                                                                        │
│ ❱  68 │   │   self.play(Transform(grid_title, grid_transform_title))                             │
│    69 │   │   self.wait()                                                                        │
│    70                                                                                            │
│    71                                                                                            │
│                                                                                                  │
│ C:\Users\ejalnii\PycharmProjects\manim\manim\scene\scene.py:1080 in play                         │
│                                                                                                  │
│   1077 │   │   │   return                                                                        │
│   1078 │   │                                                                                     │
│   1079 │   │   start_time = self.renderer.time                                                   │
│ ❱ 1080 │   │   self.renderer.play(self, *args, **kwargs)                                         │
│   1081 │   │   run_time = self.renderer.time - start_time                                        │
│   1082 │   │   if subcaption:                                                                    │
│   1083 │   │   │   if subcaption_duration is None:                                               │
│                                                                                                  │
│ C:\Users\ejalnii\PycharmProjects\manim\manim\utils\caching.py:65 in wrapper                      │
│                                                                                                  │
│   62 │   │   │   "List of the first few animation hashes of the scene: %(h)s",                   │
│   63 │   │   │   {"h": str(self.animations_hashes[:5])},                                         │
│   64 │   │   )                                                                                   │
│ ❱ 65 │   │   func(self, scene, *args, **kwargs)                                                  │
│   66 │                                                                                           │
│   67 │   return wrapper                                                                          │
│   68                                                                                             │
│                                                                                                  │
│ C:\Users\ejalnii\PycharmProjects\manim\manim\renderer\opengl_renderer.py:439 in play             │
│                                                                                                  │
│   436 │   │   │   self.animation_elapsed_time = scene.duration                                   │
│   437 │   │                                                                                      │
│   438 │   │   else:                                                                              │
│ ❱ 439 │   │   │   scene.play_internal()                                                          │
│   440 │   │                                                                                      │
│   441 │   │   self.file_writer.end_animation(not self.skip_animations)                           │
│   442 │   │   self.time += scene.duration                                                        │
│                                                                                                  │
│ C:\Users\ejalnii\PycharmProjects\manim\manim\scene\scene.py:1245 in play_internal                │
│                                                                                                  │
│   1242 │   │   for t in self.time_progression:                                                   │
│   1243 │   │   │   self.update_to_time(t)                                                        │
│   1244 │   │   │   if not skip_rendering and not self.skip_animation_preview:                    │
│ ❱ 1245 │   │   │   │   self.renderer.render(self, t, self.moving_mobjects)                       │
│   1246 │   │   │   if self.stop_condition is not None and self.stop_condition():                 │
│   1247 │   │   │   │   self.time_progression.close()                                             │
│   1248 │   │   │   │   break                                                                     │
│                                                                                                  │
│ C:\Users\ejalnii\PycharmProjects\manim\manim\renderer\opengl_renderer.py:450 in render           │
│                                                                                                  │
│   447 │   │   self.window.swap_buffers()                                                         │
│   448 │                                                                                          │
│   449 │   def render(self, scene, frame_offset, moving_mobjects):                                │
│ ❱ 450 │   │   self.update_frame(scene)                                                           │
│   451 │   │                                                                                      │
│   452 │   │   if self.skip_animations:                                                           │
│   453 │   │   │   return                                                                         │
│                                                                                                  │
│ C:\Users\ejalnii\PycharmProjects\manim\manim\renderer\opengl_renderer.py:470 in update_frame     │
│                                                                                                  │
│   467 │   │   for mobject in scene.mobjects:                                                     │
│   468 │   │   │   if not mobject.should_render:                                                  │
│   469 │   │   │   │   continue                                                                   │
│ ❱ 470 │   │   │   self.render_mobject(mobject)                                                   │
│   471 │   │                                                                                      │
│   472 │   │   for obj in scene.meshes:                                                           │
│   473 │   │   │   for mesh in obj.get_meshes():                                                  │
│                                                                                                  │
│ C:\Users\ejalnii\PycharmProjects\manim\manim\renderer\opengl_renderer.py:329 in render_mobject   │
│                                                                                                  │
│   326 │   │   │   if config["use_projection_stroke_shaders"]:                                    │
│   327 │   │   │   │   render_opengl_vectorized_mobject_stroke(self, mobject)                     │
│   328 │   │                                                                                      │
│ ❱ 329 │   │   shader_wrapper_list = mobject.get_shader_wrapper_list()                            │
│   330 │   │                                                                                      │
│   331 │   │   # Convert ShaderWrappers to Meshes.                                                │
│   332 │   │   for shader_wrapper in shader_wrapper_list:                                         │
│                                                                                                  │
│ C:\Users\ejalnii\PycharmProjects\manim\manim\mobject\opengl\opengl_vectorized_mobject.py:1539 in │
│ get_shader_wrapper_list                                                                          │
│                                                                                                  │
│   1536 │   │   back_stroke_shader_wrappers = []                                                  │
│   1537 │   │   for submob in self.family_members_with_points():                                  │
│   1538 │   │   │   if submob.has_fill() and not config["use_projection_fill_shaders"]:           │
│ ❱ 1539 │   │   │   │   fill_shader_wrappers.append(submob.get_fill_shader_wrapper())             │
│   1540 │   │   │   if submob.has_stroke() and not config["use_projection_stroke_shaders"]:       │
│   1541 │   │   │   │   ssw = submob.get_stroke_shader_wrapper()                                  │
│   1542 │   │   │   │   if submob.draw_stroke_behind_fill:                                        │
│                                                                                                  │
│ C:\Users\ejalnii\PycharmProjects\manim\manim\mobject\opengl\opengl_vectorized_mobject.py:1514 in │
│ get_fill_shader_wrapper                                                                          │
│                                                                                                  │
│   1511 │   │   return self                                                                       │
│   1512 │                                                                                         │
│   1513 │   def get_fill_shader_wrapper(self):                                                    │
│ ❱ 1514 │   │   self.update_fill_shader_wrapper()                                                 │
│   1515 │   │   return self.fill_shader_wrapper                                                   │
│   1516 │                                                                                         │
│   1517 │   def update_fill_shader_wrapper(self):                                                 │
│                                                                                                  │
│ C:\Users\ejalnii\PycharmProjects\manim\manim\mobject\opengl\opengl_vectorized_mobject.py:1519 in │
│ update_fill_shader_wrapper                                                                       │
│                                                                                                  │
│   1516 │                                                                                         │
│   1517 │   def update_fill_shader_wrapper(self):                                                 │
│   1518 │   │   self.fill_shader_wrapper.vert_data = self.get_fill_shader_data()                  │
│ ❱ 1519 │   │   self.fill_shader_wrapper.vert_indices = self.get_triangulation()                  │
│   1520 │   │   self.fill_shader_wrapper.uniforms = self.get_fill_uniforms()                      │
│   1521 │   │   self.fill_shader_wrapper.depth_test = self.depth_test                             │
│   1522                                                                                           │
│                                                                                                  │
│ C:\Users\ejalnii\PycharmProjects\manim\manim\mobject\opengl\opengl_vectorized_mobject.py:1456 in │
│ get_triangulation                                                                                │
│                                                                                                  │
│   1453 │   │   # Triangulate                                                                     │
│   1454 │   │   inner_verts = points[inner_vert_indices]                                          │
│   1455 │   │   inner_tri_indices = inner_vert_indices[                                           │
│ ❱ 1456 │   │   │   earclip_triangulation(inner_verts, rings)                                     │
│   1457 │   │   ]                                                                                 │
│   1458 │   │                                                                                     │
│   1459 │   │   tri_indices = np.hstack([indices, inner_tri_indices])                             │
│                                                                                                  │
│ C:\Users\ejalnii\PycharmProjects\manim\manim\utils\space_ops.py:705 in earclip_triangulation     │
│                                                                                                  │
│   702 │   │                                                                                      │
│   703 │   │   # Move the ring which j belongs to from the                                        │
│   704 │   │   # attached list to the detached list                                               │
│ ❱ 705 │   │   new_ring = next(filter(lambda ring: ring[0] <= j < ring[-1], detached_rings))      │
│   706 │   │   detached_rings.remove(new_ring)                                                    │
│   707 │   │   attached_rings.append(new_ring)                                                    │
│   708                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
StopIteration
```
After debugging, I think this code may have hidden risks (manim/utils/space_ops.py:705):
```
new_ring = next(filter(lambda ring: ring[0] <= j < ring[-1], detached_rings))
```
Because j may equal to ring[-1], it will make the filter return an empty iterator and then the next method will lead to "StopIteration" error.
**My workaround**: change < to <=, like below:
`new_ring = next(filter(lambda ring: ring[0] <= j <= ring[-1], detached_rings))`

I don't quite understand the algorithm, I just fixed it from the standpoint that the code is runnable.

**Comment by behackl** [comment]
I can't quite recall in which PR it happened, but I am fairly certain this has been fixed by now. Closing this.

**Comment by chopan050** [comment]
> I can't quite recall in which PR it happened, but I am fairly certain this has been fixed by now.

For the record, this bug, which was also mentioned in issue #3038, was fixed in #3790. It's the same workaround proposed by jinliangyu.

**Pull request closed without merging**
