### PR TITLE
Remove a hardcoded value in test_version.py

### PR DESCRIPTION
**Pull request by WampyCakes**
## Overview / Explanation for Changes
Replaces the hardcoded value `manim` with `__name__`.

## Oneline Summary of Changes
```
- Remove a hardcoded value in test_version.py (:pr:`PR NUMBER HERE`)
```

## Acknowledgements
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)

## Reviewer Checklist
- [ ] Newly added functions/classes are either private or have a docstring
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings
- [ ] The oneline summary has been included [in the wiki](https://github.com/ManimCommunity/manim/wiki/Changelog-for-next-release)

### CODE REVIEW

**Comment by MrMallIronmaker** [comment]
Naive question - what does this actually test, and how did this come up? I'm not too familiar with the inner workings of packages. Is it plausible those two values would be different?

**Comment by WampyCakes** [comment]
The test was made when `__version__` was added (which was when the commandline flag was added) to make sure `__version__` matched the version in `pyproject.toml` (or at least, that's what it should do). If you're referring to whether `manim` and `__name__` would be different, the answer is no. They're the same, and they have to be. But, in the future if the name was changed from manim to something else, it wouldn't need updated where `__name__` is used. The import would obviously need refactored, but that's the case all over the library. I think it's best to remove hardcoded values of that name when possible. I noticed it was hardcoded when reviewing a different PR so that's why this was made.

**Comment by MrMallIronmaker** [comment]
So in total, it's a minor refactor to avoid a spurious error in the case that manim's name is changed, and the point of the test is to double-check the version anyways. And `__version__` has to be hardcoded rather than pulled from `pyproject.toml` right?

If so, in sum it's no bad and small good, so I'm :+1:

**Comment by WampyCakes** [comment]
All correct except the last part. `__version__` is set here. https://github.com/ManimCommunity/manim/blob/master/manim/__init__.py#L8 When a user has this installed through, say, pip, they do not have a `pyproject.toml` to pull the version from, hence why it uses `importlib.metadata`. Overall, yes, no bad and small good.

**Review by behackl — APPROVED** [review]
LGTM.

**Review by jsonvillanueva — APPROVED** [review]

**Pull request merged**
