### PR TITLE
Rename get_submobject_index_labels to index_labels

### PR DESCRIPTION
**Pull request by kilacoda**
## Motivation

This function's name is a bit too long, which you discover when you need it for debugging stuff like TexMobject derivatives. Inspired from the name used in the 3b1b/shaders branch. Also makes more semantic sense when used with `Scene.add`:
```python
self.add(get_submobject_index_labels(mobject))
```
as opposed to 
```python
self.add(index_labels(mobject)) 
```
¯\\_(ツ)\_/¯

## Overview / Explanation for Changes

Function name change.
## Oneline Summary of Changes

```
- Changed get_submobject_index_labels to index_labels
```

## Testing Status

N/A
## Further Comments

N/A
## Acknowledgements
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)

## Reviewer Checklist
- [ ] Newly added functions/classes are either private or have a docstring
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings
- [ ] The oneline summary has been included [in the wiki](https://github.com/ManimCommunity/manim/wiki/Changelog-for-next-release)

### CODE REVIEW

**Comment by behackl** [comment]
I'm fine with this change, although we should think about whether we should include a deprecation period for this name change.

**Comment by leotrs** [comment]
Agreed - can you please add a deprecation warning?

**Comment by kilacoda** [comment]
Will a comment above the function do?

**Comment by leotrs** [comment]
No, I meant that instead of just changing the name, we should (a) create a new function, and (b) keep the old function and make it  print a warning and just call the new one.

**Review by eulertour — APPROVED** [review]

**Review by huguesdevimeux — CHANGES_REQUESTED** [review]
as @leotrs pointed out, this needs a depreciation warning.

**Comment by kilacoda** [comment]
Ok, added in cb5757a .

**Review by huguesdevimeux — APPROVED** [review]

**Comment by behackl** [comment]
This was merged with a failing `black` test, please look out for that.

**Comment by kilacoda** [comment]
Huh, I thought it passed, and also ran black on the file before committing. Guess I'll do it again.

**Pull request merged**
