### PR TITLE
Translation script from manim3b1b to manimce

### PR DESCRIPTION
**Pull request by kolibril13**
This script changes the import and converts TexMobject to MathTex.
I found it useful for myself and thought that others might be interested as well.
 Feel free to close this pr when you find it not necessary.

### CODE REVIEW

**Comment by leotrs** [comment]
@kolibril13 I believe you didn't commit the script itself :sweat_smile: I can only see the changelog in the diff.

Having said that, I'm hesitant about merging this. The main reason is that I'm not sure those are the only two user-facing changes that are necessary to translate a scene from 3b1b to CE. And if they are, they seem simple enough that they can be done manually. Doing them automatically is nice, but remember that every piece of code that we ship is more code that the end users will expect to work flawlessly, more code that we have to maintain, and more opportunities for something going wrong and pushing away more users.

Let's see the script itself and let's see what others think :smiley:

**Comment by kolibril13** [comment]
Ok, I have posted it right now and  removed it from the changelog again.

**Comment by kolibril13** [comment]
I am closing this for now, one can still find the script when searching for "translation script" in the pr section.

**Comment by kolibril13** [comment]
```py
from pathlib import Path

example_dict = Path.cwd() / "manim_folder"
all_py_files = example_dict.rglob('*.py')

text_to_search = "from manimlib.imports import *"
replacement_text = "from manim import *"

for py_file in all_py_files:
    text = py_file.read_text()
    text = text.replace(text_to_search, replacement_text)
    py_file.write_text(text)
    print(py_file)

text_to_search = "TexMobject"
replacement_text = "MathTex"

for py_file in all_py_files:
    text = py_file.read_text()
    text = text.replace(text_to_search, replacement_text)
    py_file.write_text(text)




# further, the following magnetudes were removed, however you can still use them by adding this:
"""
FRAME_WIDTH = config["frame_width"]
FRAME_HEIGHT = config["frame_width"]
TOP = config["frame_height"] / 2 * UP
BOTTOM = config["frame_height"] / 2 * DOWN
LEFT_SIDE = config["frame_width"] / 2 * LEFT
RIGHT_SIDE = config["frame_width"] / 2 * RIGHT
```

**Comment by behackl** [comment]
The script is preserved within the PR itself, so the attached branch can be deleted.

**Comment by kolibril13** [comment]
yep

**Pull request closed without merging**
