### PR TITLE
Migrate width/height/depth to properties

### PR DESCRIPTION
**Pull request by friedkeenan**
## Motivation

As discussed in #787, migrating mobject attributes to properties generally improves code.

## Overview / Explanation for Changes

`get_width/height/depth` and `set_width/height/depth` were removed (to be handled by the compatibility layer), and replaced by properties. To retain certain functionality (for instance, `Elbow` needed to pass `about_point=ORIGIN` to `set_width` before), `scale_to_fit_width/height/depth` methods have been added. Along the same vein, I've added some documentation to `stretch_to_fit_width` etc.

Additionally, while removing calls to the old getters and setters, I discovered some attributes that are closely tied to width etc., and decided to turn them into properties. The added properties are `Square.side_length`, and `ScreenRectangle`'s and `PictureInPictureFrame`'s `aspect_ratio` properties.

I believe I also fixed a bug with `ScreenRectangle` where the height wasn't being set correctly.

Breaking changes include no longer being able to pass more than one argument to `set_width` etc., having to pass `width` and `height` arguments to certain methods that before would have used `self.width` and `self.height` to get access to the arguments passed to the constructor, but since the arguments aren't the *true* width and height, I shifted the logic a bit, and I don't bother setting `Title`'s `underline_width` attribute anymore, as the user can just use `title.underline.width` instead.

## Oneline Summary of Changes

```
- Migrate width/height/depth to properties (:pr:`1024`)
```

## Testing Status

Tests pass locally. Here's some code in action:
```py
import manim as mn

class Test(mn.Scene):
    def construct(self):
        sq = mn.Square().set_color(mn.BLUE)
        sq_copy = sq.copy().set_stroke(mn.GRAY, opacity=0.5)

        self.add(sq_copy, sq)
        self.play(sq.animate.set(width=4))
```

https://user-images.githubusercontent.com/20881398/107696806-045cd480-6c78-11eb-97b0-4dbd390a22c4.mp4

## Further Comments

The documentation's a *tad* underwhelming; tips to make it better would be appreciated. Particularly I don't know how to show that a parameter can be any real number, whether that be `int`, `float`, `numpy.float64`, etc.

## Acknowledgements
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)

## Reviewer Checklist
- [ ] Newly added functions/classes are either private or have a docstring
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings
- [ ] The oneline summary has been included [in the wiki](https://github.com/ManimCommunity/manim/wiki/Changelog-for-next-release)

### CODE REVIEW

**Comment by friedkeenan** [comment]
The readthedocs build failing is not my fault, it's also failing in other PRs.

**Comment by friedkeenan** [comment]
Added some examples and such for the width/height properties. Not sure how to best demonstrate depth stuff though. Readthedocs build is working again if you wanted to peruse stuff

**Comment by jsonvillanueva** [comment]
LGTM! There could maybe be explicit pytests for this, but in the docs rendering a video seems enough.

**Comment by friedkeenan** [comment]
> LGTM! There could maybe be explicit pytests for this, but rendering a video in the docs seems enough.

There are doctests involving this feature too, and the other tests are wrapped up in this feature because objects interact with their own width and height

**Review by jsonvillanueva — APPROVED** [review]

**Review by behackl — APPROVED** [review]
I've read through the changes and tested this PR for a bit -- everything looks good to me, thank you very much for your efforts!

(For some reason, the RTD PR page does not exist anymore, but I've read through the docstrings and they looked good to me -- should there be any issues, we can also resolve them in a follow-up PR.)

**Pull request merged**
