### PR TITLE
Remove WebGL renderer

### PR DESCRIPTION
**Pull request by naveen521kk**
## Overview: What does this pull request change?

The WebGL renderer is broken and is unmaintained anymore. The support for it in Manim is removed.

## Motivation and Explanation: Why and how do your changes improve the library?
Fixes https://github.com/ManimCommunity/manim/issues/2629
See https://github.com/ManimCommunity/manim-renderer it's archived and is no longer maintained. Having the code to support it seems useless and I'm removing them in this PR.

## Reviewer Checklist
- [x] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Review by behackl — APPROVED** [review]
Thank you, I think this is fine, in particular because

- it is and has been broken / unmaintained for a while, and
- if the functionality should be re-introduced again one day, this is one clean commit that can be reverted for a starting point.

Only semi-related, but something that just crossed my mind: I think it would be worth to brainstorm in how far we'd have to push our plugin infrastructure to allow installing a custom rendering backend as a plugin.

**Comment by Darylgolden** [comment]
Is the rich bug fixed with 12.0.1?

**Comment by naveen521kk** [comment]
> Only semi-related, but something that just crossed my mind: I think it would be worth to brainstorm in how far we'd have to push our plugin infrastructure to allow installing a custom rendering backend as a plugin.

Yeah, we should do it. For starters, we should stop hardcoding `opengl` and `cairo` renderers though; rather the main difference between them is they are cubic vs quadratic curves in the `.points` attribute; why not have a config flag for that separately rather than checking for the renderers? Other than that I think it should be pretty simple to implement a renderer as a plugin (and probably use something like [pluggy](https://pluggy.readthedocs.io/en/stable/).

> Is the rich bug fixed with 12.0.1?

Yeah, I'll update the config file to ignore the `12.0.0` version.

**Review by Darylgolden — APPROVED** [review]
LGTM!

**Comment by naveen521kk** [comment]
Thanks for the reviews!

**Pull request merged**
