### PR TITLE
Read The Docs setup

### PR DESCRIPTION
**Pull request by leotrs**
This PR will allow us to have a fancy new RTD website whenever we push to master. Here is the current site:

https://manimce.readthedocs.io/en/rtd-setup/

Once this PR is merged, I will delete the `rtd-setup` branch and the website will change to

https://manimce.readthedocs.io/en/latest/

This will always be up to date with master. Once we have a stable/release branch, we can also set it up so that there are docs for the stable release.

### CODE REVIEW

**Comment by leotrs** [comment]
@eulertour with your permission sir, I would like to request to change the badge on the README that says "docs: EulerTour" to "docs: passing" from RTD ;)

**Review by kolibril13 — APPROVED** [review]

**Comment by kolibril13** [comment]
looks good!

**Comment by behackl** [comment]
I got 

```bash
$ make html
Running Sphinx v3.1.2

Extension error:
Could not import extension sphinx_rtd_theme (exception: No module named 'sphinx_rtd_theme')
Makefile:25: recipe for target 'html' failed
make: *** [html] Error 2
```

locally after running `pip3 install -r requirements.txt` and needed to install `sphinx_rtd_theme` separately. Should it also be added to `docs/requirements.txt`?

**Comment by leotrs** [comment]
Uuuh, that's legacy and deprecated, as we are actually not using the rtd_theme anymore. So the actual fix is to comment out the line adding `'sphinx_rtd_theme'` to the `extensions` list in `docs/source/conf.py`. 

(In fact, we just published the test documentation, see #381)

**Comment by eulertour** [comment]
@leotrs yeah go for it

**Review by huguesdevimeux — APPROVED** [review]

**Pull request merged**
