### PR TITLE
Fix become bug

### LINKED ISSUE #610: Follow-up to #562 -- bug with Transform / Mobject.become
`git bisect` says that merging #562 introduced a problem with `Mobject.become`: The example

```
class FadeInAndOut(Scene):
    def construct(self):
        square = Square(color=BLUE).shift(2 * UP)
        annotation = Text("Fade In", height=0.8)
        self.add(annotation)
        self.play(FadeIn(square))

        annotation.become(Text("Fade Out", height=0.8))
        self.add(annotation)
        self.play(FadeOut(square))
```
from our documentation renders as

FadeInAndOut

Same thing if the call to `become` is replaced by playing a `Transform` animation; the old text is simply kept on screen.

_Originally posted by @behackl in https://github.com/ManimCommunity/manim/pull/562#issuecomment-716033185_

### PR DESCRIPTION
**Pull request by eulertour**
Fixes #610 by using the old logic to separate static and non-static mobjects.

### CODE REVIEW

**Comment by huguesdevimeux** [comment]
Do you think you could add a test for this?

**Comment by eulertour** [comment]
To be honest I don't know how to add new tests. Is the process documented somewhere?

**Comment by huguesdevimeux** [comment]
Sure. https://github.com/ManimCommunity/manim/wiki/Testing

**Comment by behackl** [comment]
I am okay with reverting to the old logic, and adding a test for `Mobject.become` is certainly a good idea.

Just out of curiosity: is the problem with the new logic "just" that the background is not repainted after changing the `Mobject` with `.become`? Or is something else happening too?

**Comment by eulertour** [comment]
There's some problem with the logic for determining which mobjects are moving which considers the mobject to still be static after calling become(), so it gets painted to the screen.

**Comment by eulertour** [comment]
The tests are passing locally, so I'm not sure what's going on here.

**Comment by eulertour** [comment]
When I checkout either 653502a or bd9c5c9 and run the tests locally they pass. I think the config changes in the merge in 653502a may have broken the ability to add tests. In any case we shouldn't debug the problem in the PR (unless it's something simple I'm just missing).

**Comment by behackl** [comment]
Ah, that's a tricky one. I believe the problem is actually with the test itself: you add `Text` without specifying the font, so it uses some default font. These might differ between systems:

image
(The left side is rendered locally, the right is the image saved as numpy data.)

I don't know whether we can actually choose a font that is guaranteed to exist on all operating systems; but we could try using something really wide-spread like Arial or Times New Roman. (AFAIK, they are commonly not installed on mobile devices, but I think that we don't necessarily have to care for running the test suite on such a setup. For now. :-))

**Review by behackl — APPROVED** [review]

**Review by kolibril13 — APPROVED** [review]

**Pull request merged**
