### PR TITLE
CHORE: restructured imports

### PR DESCRIPTION
**Pull request by MrDiver**
Overall just trying to slowly fix the import structure of manim to not be as cyclic as it is right now. The first decision i thought would be useful is to remove all the imports from the `__init__.py` files except for those where it is useful for example the `manim/opengl/__init__.py` where it provides a sensible namespace.

Second i wanted to add a module which can then hold the imports seperate from the `__init__.py` file where users then can do `from manim.prelude import *` where everything is just exposed in the prelude module at least what is normally used by users. This provides a better seperation between what we need in the `__init__.py` and import paths for developing manim and what we want to provide our userbase as default imports.

Currently this will not work because there are a lot of missing imports still in the tests.

### CODE REVIEW

**Comment by MrDiver** [comment]
@behackl even if i dislike to say it, we should probably switch to enforcing module imports and discourage using something like `from manim.constants import PI` and instead encourage `from manim import constants as c` at least inside our codebase. This will reduce a lot of the recursiveness that we currently have in the import structure.

**Review by naveen521kk — CHANGES_REQUESTED** [review]
> Second i wanted to add a module which can then hold the imports seperate from the __init__.py file where users then can do `from manim.prelude import *` where everything is just exposed in the prelude module at least what is normally used by users

This will create confusion. This is quite a breaking change and I don't want to introduce it unless we really need to. Again, do we really need to change this?

**Comment by MrDiver** [comment]
> > Second i wanted to add a module which can then hold the imports seperate from the **init**.py file where users then can do `from manim.prelude import *` where everything is just exposed in the prelude module at least what is normally used by users
> 
> This will create confusion. This is quite a breaking change and I don't want to introduce it unless we really need to. Again, do we really need to change this?
No worries, it is just a try to restructure and experiment what can be done, not what should be done!

**Comment by behackl** [comment]
I fear we'll have to restart restructuring the imports from a clean slate, and maybe tackle this one module at a time.

(Feel free to reopen in case you disagree!)

**Comment by JasonGrace2282** [comment]
About restructuring imports, I feel like it should be done after experimental is merged.

**Pull request closed without merging**
