### PR TITLE
Fix 305: mobject.add should do input validation

### LINKED ISSUE #305: Mobject.add() should perform input type validation
Currently, the implementation of `Mobject.add` seems to assume that all its arguments are of type `Mobject`, but this is never guaranteed:

```python
    def add(self, *mobjects):
        if self in mobjects:
            raise ValueError("Mobject cannot contain self")
        self.submobjects = list_update(self.submobjects, mobjects)
        return self
```

Should we add this validation? I'm leaning toward yes, but I don't want to litter the whole codebase with input validation everywhere...

### PR DESCRIPTION
**Pull request by leotrs**
## List of Changes
- Moved input validation from Group.__init__ to Mobject.add
- Added a test

## Motivation
Before, type was being checked only when a Group was created. If one called Group.add() after creation, there was no input validation.

## Further Comments
Closes #305

### CODE REVIEW

**Review by behackl — APPROVED** [review]
LGTM!

**Review by eulertour — APPROVED** [review]

**Comment by eulertour** [comment]
It's still easy for someone to just add to the submobjects array directly with `mob.submobjects.append("foo")`. We should probably prepend `.submobjects`, `.points`, and probably a few other mobject attributes with underscores at some point.

**Comment by leotrs** [comment]
Good idea. In the long run, I would actually go further and create a custom class to hold `submobjects`, instead of having a plain list. Having a plain list is _extremely_ messy and leads to hacky stuff like all the contents of `utils/iterables.py` because that list needs to be kept without duplicates, in a certain order etc etc etc...

**Comment by leotrs** [comment]
In fact, I've already proposed that here #358

**Pull request merged**
