### PR TITLE
Moved comments in :class:`~.VMobject` to documentation

### PR DESCRIPTION
**Pull request by ycechungAI**
…docs

## Overview: What does this pull request change?

* changed "vectorized_mobject.py" to move comments to be placed within the doc-strings of the class/method/function

## Motivation and Explanation: Why and how do your changes improve the library?

Documentation 
## Links to added or changed documentation pages

https://github.com/ycechungAI/manim  - issue-1172 branch
## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by ycechungAI** [comment]
where is the correct place to place it then?

**Comment by jsonvillanueva** [comment]
> where is the correct place to place it then?

They are meant to be placed within the docstrings of the class/method/function you are updating. This is a great example:
https://github.com/ManimCommunity/manim/blob/main/manim/mobject/graph.py#L162-L353

For further information, see the contribution guidelines: https://docs.manim.community/en/latest/contributing/docstrings.html

**Comment by ycechungAI** [comment]
made the changes as requested

**Comment by ycechungAI** [comment]
@Darylgolden i made the changes, please review and let me know

**Pull request merged**
