### PR TITLE
Made `frames_comparsion` testing utility a proper module of the library

### PR DESCRIPTION
**Pull request by behackl**
## Overview: What does this pull request change?

This moves the `frames_comparison` decorator used for our graphical tests inside `manim.utils` so that third parties (plugin developers) can utilize Manim's testing framework without having to copy code around.

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by behackl** [comment]
The tests are fixed now for this PR.

**Comment by hydrobeam** [comment]
Wouldn't other files in `tests` like `video_tester.py` need to also be moved or is that not necessary?

**Comment by huguesdevimeux** [comment]
I'm fine with that, as I think `frames_comparison` would be used by a lot of plugins, and this reasoning does not apply to `video_tester`.

**Review by huguesdevimeux — APPROVED** [review]

**Comment by behackl** [comment]
Let's ship this as-is, if there is demand for the other utilities as well we can still revisit this. :-)

**Pull request merged**
