### PR TITLE
DEV: Decorator-based deprecation system

### LINKED ISSUE #1372: Implementing an official and stable deprecation system
## Description of proposed feature

Our current way of deprecating functions and classes could be improved to be more user and developer friendly. Perhaps we can implement a decorator-based system where the developer can input the following information:
- Version since deprecation
- Version until deletion
- Reason for deprecation

## How can the new feature be used?

```py
@deprecated(since="0.5.0". until="0.7.0", reason="Use Create instead.")
class ShowCreation(Create):
    ...
    
class Animation(object):
    @deprecated(since="0.1.0", until="0.3.0", reason="Use animation.interpolate() instead.")
    def update(self, alpha):
        ...
```

## Additional comments

We could also implement helper methods and/or CLI commands that can:
- List deprecated classes/methods
- Sort classes/methods by version since deprecation
- Warn developers if there is any deprecated code that has not been deleted at the expected version
    - i.e. If `until="0.6.0"` and current version is `0.6.0` or later, a warning will be shown as a reminder to delete the deprecated code

### PR DESCRIPTION
**Pull request by RickyC0626**
## Changelog / Overview

Implemented a more stable and reliable deprecation system that promotes ease of use for both developers and users.

Continuation of #1404 
Resolves #1372 

## Motivation

As described in #1372, our current system is not reliable and hard to keep track of.

## Explanation for Changes

Also described in #1372, using a decorator-based system to annotate classes, functions and function parameters in need of deprecation and/or replacement. This makes deprecated code easier to use and handle, while also providing users with predictable behavior and accurate documentation.

## Checklist
- [X] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [X] I have written a descriptive PR title (see top of PR template for examples)
- [X] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by huguesdevimeux** [comment]
Why did you not commit directly to @AntonBallmaier branch ? 

(I believe there is a reason, just asking)

**Comment by RickyC0626** [comment]
> Why did you not commit directly to @AntonBallmaier branch ?
> 
> (I believe there is a reason, just asking)

I believe I need to have write access to his repo in order to make commits there. Also I'll be able to update any additional details in the PR description here.

**Comment by AntonBallmaier** [comment]
> Why did you not commit directly to @AntonBallmaier branch ?
> 
> (I believe there is a reason, just asking)

I for one don't know how that is possible :D

**Comment by Darylgolden** [comment]
I don't think it's good practice to "overwrite" that PR. You may not have write access but you can still PR to @AntonBallmaier's branch directly.

**Comment by RickyC0626** [comment]
> I don't think it's good practice to "overwrite" that PR. You may not have write access but you can still PR to @AntonBallmaier's branch directly. I believe this PR should be closed.

Yeah, I guess so, as the reviews are in the other PR. @AntonBallmaier if you're fine with merging PRs to your branch from time to time.

**Pull request closed without merging**
