### PR TITLE
refactor copy/deepcopy. Closes #294

### LINKED ISSUE #294: All classes should implement copy() as deepcopy
There are 6 classes that define a `copy` method:
- `geometry.Arrow`
- `brace.BraceLabel`
- `probability.BarChart`
- `mobject.Mobject`
- `image_mobject.AbstractImageMobject`
- `animation.Animation`

Of those, the only non-trivial definitions are `Mobject` and `BraceLabel`. All the others just return `deepcopy(self)`. 

This is a bit disorganized, and raises all kind of questions for developers: When does a class implement `copy`? Why or why not? When is `copy` just a renaming of deepcopy? Is this overriding a definition of a parent class? Etc.

Note also that all of these classes except for `Animation` are classes that inherit from `Mobject`. So the situation is that `Mobject` has a non-trivial definition of `copy`, and all of the others are just overriding that with `deepcopy(self)`. This is a sign of bad design, as usually you want the definitions of methods in base classes to be as general as possible. In this case, we have it the other way around. (In fact, the definition of `Arrow.copy` contains the following comment: `# TODO, should this be the default for everything?`)

I suggest we do either one of the following:
1. Define `Mobject.copy` as just `return deepcopy(self)`. In this case, none of the classes that inherit from `Mobject` would need to define `copy` again. I think this is the easiest solution, but I don't have enough familiarity with `Mobject`to determine if this change is safe.
2. Instead of having `Mobject` have a less-general definition and a bunch of its inherited classes have more-general definitions, just create a global function `manim.copy` that calls `deepcopy(mobject)` unless the object has a more especial defiinition.

@eulertour do you think (1) is possible? This would be by far the best solution.

### PR DESCRIPTION
**Pull request by leotrs**
Refer to #294 for discussion.

cc ~~Lego Batman~~ @huguesdevimeux for tests.

### CODE REVIEW

**Comment by leotrs** [comment]
Can't tell why the tests are failing... they pass locally.

**Comment by huguesdevimeux** [comment]
Lego Batman here.

Tests fail surely because you haven't set text_dir and tex_dir folder ;)

**Comment by leotrs** [comment]
Wait. What. How. Where?

**Comment by huguesdevimeux** [comment]
`BraceLabel`  uses LaTex things, that are as you might know cached in `tex_dir` directory. (specified in config, generally).

So, manim tries to use this data but can't as `tex_dir` is not specified.

I don't really know how to fix that, but the idea would be to specify this dir before.

**Comment by leotrs** [comment]
You mean to say that we can't test anything that has anything to do with latex until #293 is fixed?

**Comment by huguesdevimeux** [comment]
> You mean to say that we can't test anything that has anything to do with latex until #293 is fixed?

I don't know, it depends on whether it's possible to specify a custom config without a `manim.cfg`. I did that for SceneTester in `testing_utils.py`.

But here it is kind of an edgy case, as there is no scene declared, so I don't really know :/ 
Maybe the question is, why manim tries to open this file ?

**Comment by leotrs** [comment]
Tests are passing now.

**Pull request merged**
