### PR TITLE
update pangocffi and pangocairocffi version

### PR DESCRIPTION
**Pull request by naveen521kk**
## Motivation
Update `pangocffi` and `pangocairocffi` version. It allows setting DLL files using environment variable and this will be super helpful for windows users, as well as chocolatey package.

## Overview / Explanation for Changes
Update:
pangocffi - 0.9.0
pangocairocffi - 0.5.0

## Oneline Summary of Changes
```
- Update Pangocffi and Pangocairocffi (:pr:`871`)
```

## Acknowledgements
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)

## Reviewer Checklist
- [ ] Newly added functions/classes are either private or have a docstring
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings
- [ ] The oneline summary has been included [in the wiki](https://github.com/ManimCommunity/manim/wiki/Changelog-for-next-release)

### CODE REVIEW

**Comment by behackl** [comment]
If this actually allows to circumvent DLL hell, this is golden. I just triggered the pipeline again, hoping that the tests for macos-latest and python 3.8, as well as python 3.9 were just transient errors.

(I don't *really* see a reason for a segmentation fault not occurring for macos-latest + py3.7, if there were a problem with the latest version of the packages.)

**Comment by naveen521kk** [comment]
Segmentation fault happens for all the CI runs of MacOS. Possibly something wrong with GitHub CI. Or someother things, no just this one.

> If this actually allows to circumvent DLL hell, this is golden.

Partly helps, though not fully. It tries to load a DLL specified in variable, but deps of those DLL aren't bound to this fix though.

**Comment by leotrs** [comment]
Tests still not passing :(

**Comment by naveen521kk** [comment]
Closing in favour of #878

**Pull request closed without merging**
