### PR TITLE
Add Brace mobject to OpenGL

### PR DESCRIPTION
**Pull request by TRoboto**
## Changelog / Overview

Added OpenGL-compatible Brace mobject.

## Explanation for Changes

Created `opengl_brace.py` which is mostly copied from `brace.py`.
## Testing Status

Tested locally.
## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [x] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [x] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [x] The PR title is descriptive enough
- [x] The PR is labeled correctly
- [x] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Review by jsonvillanueva — CHANGES_REQUESTED** [review]
Works locally for me. As this is mainly a port from the Cairo Brace, I'm okay merging this soon in this release, but I do think the documentation should be updated to reflect the proper OpenGL classes (particularly the examples)

**Comment by TRoboto** [comment]
> Works locally for me. As this is mainly a port from the Cairo Brace, I'm okay merging this soon in this release, but I do think the documentation should be updated to reflect the proper OpenGL classes (particularly the examples)

Docstrings should look good now.

**Review by jsonvillanueva — APPROVED** [review]
LGTM

**Comment by behackl** [comment]
I think it is better to use the metaclass approach instead. Closing this in favor of #1572.

**Pull request closed without merging**
