### PR TITLE
Remove stray or erroneous linebreaks in README

### PR DESCRIPTION
**Pull request by fj**
## Motivation and Explanation: Why and how do your changes improve the library?
Corrects inconsistent or incorrect linebreaks in several spots in the README.

## Links to added or changed documentation pages
 
N/A.

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by behackl** [comment]
Hello! Can you explain why you feel the line breaks in the README are unnecessary / erroneous?

In principle, they are there so that the lines don't get too long; the linebreaks don't matter for the rendered version of the markdown file, and they should make the text easier to read when opening it in a text-only editor.

**Comment by fj** [comment]
Sure:

1. Double line breaks do have rendering differences — they start new
paragraphs in Markdown. The PR removes erroneous double line breaks. The
statement that it's an editor-visible concern only isn't accurate in that
case, IMO.

2. Most text editors have natural word wrap (e.g. vim, emacs, vscode,
etc.). Certainly this is a matter of preference, but adding nonsemantic
line breaks seems like it doesn't add much value.

3. The lines were not broken at consistent lengths, so even disregarding
(2) that still seems like something that ought to be corrected.

Happy to make any changes you'd like if you find this to be not very useful
as is.

**Comment by behackl** [comment]
Thank you, I missed that you removed a double line break when I looked through the changes earlier. I did mean single line breaks in my response above.

Personally, I prefer manual line breaks with an effort to break at a somewhat consistent line length, mainly because I find that diffing changes is a bit easier; that might not be the best argument for the README though.

Before we decide on the next steps here, it would be good to hear some more opinions about this from other developers.

**Comment by hydrobeam** [comment]
I don't have a strong opinion about this, but I think I have a slight preference for manual line breaks since it's easier to see the changes. I took a look at some other repositories to see how they handle this and they seem to vary:

https://github.com/numpy/numpy/edit/main/README.md - manual line breaks
https://github.com/scipy/scipy/edit/master/README.rst - manual line breaks
https://github.com/facebook/react/edit/main/README.md - not manual

**Comment by Darylgolden** [comment]
From the responses it seems like most of us have a preference for manual line lengths. Since this is purely a matter of preference, I think we should stick to using them.

**Comment by fj** [comment]
Sounds good; I'll withdraw this PR.

**Pull request closed without merging**
