### PR TITLE
Enable module doctests

### PR DESCRIPTION
**Pull request by behackl**
## List of Changes

Enable running the doctests in the `*.py` files in the module.

## Motivation

Module doctests are, in my opinion, an especially low-barrier type of tests that can be added very fast while at the same time improving the reference manual part of the documentation.

Many functionalities of manim can be tested without actually rendering the scenes; especially mathematical correctness of certain operations (e.g., scaling, moving, ...) come to my mind.

## Explanation for Changes
Empty `__init__.py` files are required in order to resolve relative import issues `pytest` runs into otherwise. After this, doctests can be run by executing `pytest --doctest-modules manim` from the repository root directory.

## Testing Status
Currently, there are no doctests in the module. #366 adds some.

## Acknowledgement
- [x] I have read the [Contributing Guidelines](https://github.com/ManimCommunity/manim/wiki/Documentation-guidelines-(WIP))

### CODE REVIEW

**Comment by leotrs** [comment]
This all sounds good but I'm having trouble picturing the end product. You mean to add a doctest in each of a module's docstring? If so, how is this different than just running `make doctest` from the `docs/` folder? I don't see why the empty init files are necessary.

**Comment by behackl** [comment]
While working on #366, I found that `make doctest` in `docs/` only considers doctests put into the `*.rst` files. It did not execute the tests I added in `mobject/geometry.py`. This branch actually runs these tests. (If there is another, easier way that I have missed, I'd be happy for some pointers. :-))

Regarding the empty `__init__.py` files: running `pytest --doctest-modules manim` without them yields

```bash
$ pytest --doctest-modules manim
======================================================= test session starts =======================================================
platform linux -- Python 3.8.5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/behackl/Dokumente/git/etc/manim
collected 0 items / 65 errors                                                                                                     

============================================================= ERRORS ==============================================================
__________________________________________ ERROR collecting manim/animation/animation.py __________________________________________
manim/animation/animation.py:11: in <module>
    from ..mobject.mobject import Mobject
E   ImportError: attempted relative import with no known parent package
_________________________________________ ERROR collecting manim/animation/composition.py _________________________________________
manim/animation/composition.py:4: in <module>
    from ..animation.animation import Animation
E   ImportError: attempted relative import with no known parent package
...
===================================================== short test summary info =====================================================
ERROR manim/animation/animation.py - ImportError: attempted relative import with no known parent package
ERROR manim/animation/composition.py - ImportError: attempted relative import with no known parent package
ERROR manim/animation/creation.py - ImportError: attempted relative import with no known parent package
ERROR manim/animation/fading.py - ImportError: attempted relative import with no known parent package
ERROR manim/animation/growing.py - ImportError: attempted relative import with no known parent package
ERROR manim/animation/indication.py - ImportError: attempted relative import with no known parent package
ERROR manim/animation/movement.py - ImportError: attempted relative import with no known parent package
ERROR manim/animation/numbers.py - _pytest.pathlib.ImportPathMismatchError: ('numbers', '/usr/lib/python3.8/numbers.py', PosixPa...
ERROR manim/animation/rotation.py - ImportError: attempted relative import with no known parent package
ERROR manim/animation/specialized.py - ImportError: attempted relative import with no known parent package
ERROR manim/animation/transform.py - ImportError: attempted relative import with no known parent package
ERROR manim/animation/update.py - ImportError: attempted relative import with no known parent package
ERROR manim/camera/camera.py - ImportError: attempted relative import with no known parent package
ERROR manim/camera/mapping_camera.py - ImportError: attempted relative import with no known parent package
ERROR manim/camera/moving_camera.py - ImportError: attempted relative import with no known parent package
ERROR manim/camera/multi_camera.py - ImportError: attempted relative import with no known parent package
ERROR manim/camera/three_d_camera.py - ImportError: attempted relative import with no known parent package
ERROR manim/mobject/changing.py - ImportError: attempted relative import with no known parent package
ERROR manim/mobject/coordinate_systems.py - ImportError: attempted relative import with no known parent package
ERROR manim/mobject/frame.py - ImportError: attempted relative import with no known parent package
ERROR manim/mobject/functions.py - ImportError: attempted relative import with no known parent package
ERROR manim/mobject/geometry.py - ImportError: attempted relative import with no known parent package
ERROR manim/mobject/matrix.py - ImportError: attempted relative import with no known parent package
ERROR manim/mobject/mobject.py - ImportError: attempted relative import with no known parent package
ERROR manim/mobject/mobject_update_utils.py - ImportError: attempted relative import with no known parent package
ERROR manim/mobject/number_line.py - ImportError: attempted relative import with no known parent package
ERROR manim/mobject/numbers.py - _pytest.pathlib.ImportPathMismatchError: ('numbers', '/usr/lib/python3.8/numbers.py', PosixPath...
ERROR manim/mobject/probability.py - ImportError: attempted relative import with no known parent package
ERROR manim/mobject/shape_matchers.py - ImportError: attempted relative import with no known parent package
ERROR manim/mobject/three_d_shading_utils.py - ImportError: attempted relative import with no known parent package
ERROR manim/mobject/three_d_utils.py - ImportError: attempted relative import with no known parent package
ERROR manim/mobject/three_dimensions.py - ImportError: attempted relative import with no known parent package
ERROR manim/mobject/value_tracker.py - ImportError: attempted relative import with no known parent package
ERROR manim/mobject/vector_field.py - ImportError: attempted relative import with no known parent package
ERROR manim/mobject/svg/brace.py - ImportError: attempted relative import with no known parent package
ERROR manim/mobject/svg/code_mobject.py - ImportError: attempted relative import with no known parent package
ERROR manim/mobject/svg/drawings.py - ImportError: attempted relative import with no known parent package
ERROR manim/mobject/svg/svg_mobject.py - ImportError: attempted relative import with no known parent package
ERROR manim/mobject/svg/tex_mobject.py - ImportError: attempted relative import with no known parent package
ERROR manim/mobject/svg/text_mobject.py - ImportError: attempted relative import with no known parent package
ERROR manim/mobject/types/image_mobject.py - ImportError: attempted relative import with no known parent package
ERROR manim/mobject/types/point_cloud_mobject.py - ImportError: attempted relative import with no known parent package
ERROR manim/mobject/types/vectorized_mobject.py - ImportError: attempted relative import with no known parent package
ERROR manim/scene/graph_scene.py - ImportError: attempted relative import with no known parent package
ERROR manim/scene/moving_camera_scene.py - ImportError: attempted relative import with no known parent package
ERROR manim/scene/reconfigurable_scene.py - ImportError: attempted relative import with no known parent package
ERROR manim/scene/sample_space_scene.py - ImportError: attempted relative import with no known parent package
ERROR manim/scene/scene.py - ImportError: attempted relative import with no known parent package
ERROR manim/scene/scene_file_writer.py - ImportError: attempted relative import with no known parent package
ERROR manim/scene/three_d_scene.py - ImportError: attempted relative import with no known parent package
ERROR manim/scene/vector_space_scene.py - ImportError: attempted relative import with no known parent package
ERROR manim/scene/zoomed_scene.py - ImportError: attempted relative import with no known parent package
ERROR manim/utils/bezier.py - ImportError: attempted relative import with no known parent package
ERROR manim/utils/cfg_subcmds.py - ImportError: attempted relative import with no known parent package
ERROR manim/utils/color.py - ImportError: attempted relative import with no known parent package
ERROR manim/utils/config_utils.py - ImportError: attempted relative import with no known parent package
ERROR manim/utils/debug.py - ImportError: attempted relative import with no known parent package
ERROR manim/utils/hashing.py - ImportError: attempted relative import with no known parent package
ERROR manim/utils/images.py - ImportError: attempted relative import with no known parent package
ERROR manim/utils/paths.py - ImportError: attempted relative import with no known parent package
ERROR manim/utils/rate_functions.py - ImportError: attempted relative import with no known parent package
ERROR manim/utils/sounds.py - ImportError: attempted relative import with no known parent package
ERROR manim/utils/space_ops.py - ImportError: attempted relative import with no known parent package
ERROR manim/utils/tex.py - ImportError: attempted relative import with no known parent package
ERROR manim/utils/tex_file_writing.py - ImportError: attempted relative import with no known parent package
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 65 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================================= 65 errors in 0.85s ========================================================
```

An explanation is given in https://stackoverflow.com/questions/52808625/layout-and-importing-for-pytest-in-python3, for example.

**Comment by behackl** [comment]
Sorry, missed your question.

> You mean to add a doctest in each of a module's docstring?

I want to make sure that when doctests are added in any place -- be it the module docstring, some class docstring, or some docstring of a method -- that these tests are also checked in the pipeline.

**Comment by leotrs** [comment]
Ok this makes perfect sense then. I didn't realize make doctest only ran test in .rst files by default.

**Comment by behackl** [comment]
The failing pipelines were due to the fact that there were no doctests which could have been checked yet, which I find somewhat amusing. Added a thing in 735ae0cc, also checked that the documentation renders correctly:

image

**Comment by huguesdevimeux** [comment]
Maybe a mention of that should be added on the wiki ?

**Review by huguesdevimeux — APPROVED** [review]

**Pull request merged**
