### PR TITLE
Improved structure of the :mod:`.mobject` module

### LINKED ISSUE #2445: Refactor `manim/mobject` into grouped directories.
## Enhancement proposal

There was some discussion on making the codebase easier to digest and moving away from having dangling files in `manim/mobject`.

Here are some suggestions for how modules can be grouped

```
graphing
├── coordinate_systems.py
├── functions.py
├── number_line.py
├── probability.py
└── scale.py
```

```
text
├── code_mobject.py
├── numbers.py
├── tex_mobject.py
└── text_mobject.py
```

by splitting apart `geometry.py`:
```
geometry/
├── line.py
├── polygram.py
├── tipable.py
└── tips.py
```

```
opengl
├── opengl_compatibility.py
├── opengl_mobject.py
├── opengl_point_cloud_mobject.py
├── opengl_surface.py
├── opengl_three_dimensions.py
└── opengl_vectorized_mobject.py
```

This would entail moving some files around out of other files.

Here's the full overview of `/mobject` after these changes

```
.
├── boolean_ops.py
├── changing.py
├── frame.py
├── geometry
├── graphing
├── graph.py
├── __init__.py
├── logo.py
├── matrix.py
├── mobject.py
├── mobject_update_utils.py
├── opengl
├── shape_matchers.py
├── svg
├── table.py
├── text
├── threed
├── types
├── value_tracker.py
└── vector_field.py
```

There were some modules that I wasn't sure how to group, so were just left hanging in the directory. `table.py`/`matrix.py`/`graph.py` feel ""vaguely"" related? but i'm not sure if that's my brain scrambling for connections to try to group more files. Also, `mobject.py/vectorized_mobject.py` should probably be together.

### PR DESCRIPTION
**Pull request by hydrobeam**
## Overview: What does this pull request change?
closes #2445 
Files in `manim/mobject` (and a bit of `manim/animation`) were grouped into categories / split into separate files. Git history was kept so git blame will still work.

### `graphing`
- `coordinate_system.py`
- `number_line.py`
- `probability.py`
- `functions.py`
- `scale.py`

**rationale:** these files all have to do with graphing/plotting

### `three_d`
- `three_dimensions.py`
- `three_d_utils.py`
- `polyhedra.py`

**rationale:** three dimensional files.

### `opengl`
- `dot_cloud.py`
- `opengl_compatiblity.py`
- `opengl_geometry.py`
- `opengl_mobject.py`
- `opengl_point_cloud.py`
- `opengl_surface.py`
- `opengl_vectorized_mobject.py`
- `opengl_vectorized_mobject.py`

**rationale:** even though `opengl_compatiblity.py` isn't really a mobject, i still thought it was worth grouping them here for the sake of convenience. `dot_cloud` only works with `OpenGLPMobject`, hence why it's here.

### `text`
- `code_mobject.py`
- `numbers.py`
- `tex_mobject.py`
- `text_mobject.py`

**rationale:** files that have to do with numbers/words/text

### `geometry`
Moved `boolean_ops.py` and `shape_matchers` here since they have to do with shapes/figures. 

`geometry.py` was split into:
- `arc.py` : mobjects with a curve (e.g. `ArcPolygon`, `Circle`)
- `line.py` : mobjects that are lines / variations of them (e.g. `TangentLine` / `Line`)
- `polygram.py` : mobjects that are regular shapes (e.g. `Polygram` / `Rectangle`)
- `tips.py` : tip mobjects (`FilledTriangleTip`)

The original `geometry.py` had 40 elements in `__all__`, the sum of these four files' `__all__` has `40` elements, so nothing was dropped. (Cutout feels a bit weird and should probably be in `boolean_ops.py` tbh)

Some imports had to be adjusted to avoid circular import errors.

Also some redundant imports were removed.

> Some files were also moved out of `mobject`:

### `animation/updaters`
- `mobject/value_tracker.py` -> `animation/updaters/value_tracker.py`
- `mobject/mobject_update_utils` -> `animation/updaters/mobject_update_utils`
- `animation/update.py` -> `animation/updaters/update.py`

**rationale**: updaters are alternate methods of animation, better suited in `/animation`

#### `mobject/changing.py` -> `animation/changing.py`
**rationale**: file exclusively deals with animations and moving things.

Most file movements were done using PyCharm's refactoring tool, meaning that imports and references were handled automatically, except in the case of splitting geometry.py, where I managed outdated imports and references manually.

This had the side effect of changing relative imports to absolute import since PyCharm just does that automatically (for some reason).

Arrow tips now have to be imported from ``manim.mobject.geometry.tips`` instead of ``manim.mobject.geometry``.

## Motivation and Explanation: Why and how do your changes improve the library?

Makes the codebase easier to naviagte and work with.

`geometry` was too large to reasonably use and its organization was very poor.
The rest of the changes were to group files with a similar goal/purpose. Also, makes potentially factoring out into separate plugins more reasonable.

## Further Information and Comments

If you're curious about why `__init__.py` is included:
https://www.python.org/dev/peps/pep-0420/ 

> If a developer knows that her package will never be a portion of a namespace package, then there is a performance advantage to it being a regular package (with an __init__.py). Creation and loading of a regular package can take place immediately when it is located along the path. With namespace packages, all entries in the path must be scanned before the package is created.

If you have any further suggestions for how files can be grouped or split, please let me know. (I think `coordinate_system.py` can be split up into (a smaller) `coordinate_system.py`, `plane.py` and `axes.py`, but this PR is already large enough as is).

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by Darylgolden** [comment]
What do you think about putting the Mobjects that don't fit any category into a "special" folder, like how scipy organizes its functions?

**Comment by hydrobeam** [comment]
> What do you think about putting the Mobjects that don't fit any category into a "special" folder, like how scipy organizes its functions?

I don't really think that's a great idea since they aren't really "special" mobjects. I think there's probably a grouping that works for `vmobject.py` + `mobject.py`, but apart from that having some loose files is fine imo

**Review by Darylgolden — APPROVED** [review]

**Review by behackl — APPROVED** [review]
Awesome! I'd like to merge this as the last PR before pushing out the upcoming release; fixing potential conflicts is probably easier here.

**Comment by behackl** [comment]
I just did something semi-risky and rebased @hydrobeam's branch to the latest main branch. There were a lot of conflicts, but most of them were comparatively easy to resolve. The drawback is: I need someone else to look over the current set of changes to see whether what I did *looks* correct.

**Comment by behackl** [comment]
Actually, there is one aspect here that I disagree with and would like to see discussed: moving `ValueTracker` out of the `mobject` and into the `animation` module doesn't make sense to me, semantically.

I'll merge this for now, I don't want to push further changes to this very large PR.

**Pull request merged**
