### PR TITLE
Allow non-numerical values to be added to :class:`~.NumberLine`/:class:`~.Axes`

### LINKED ISSUE #1672: Allow non-numerical values to be passed into `add_numbers`
## Description of proposed feature

Sometimes you want more than just numbers to be added to a set of `Axes` or `NumberPlane`. For example, days of the week (Monday, Tuesday, Wednesday). 

I think this could be done by passing a dictionary consisting of a point on the `NumberLine` with the  label that is at that point. `{1: "Monday", 2: "Tuesday"}`

## How can the new feature be used?

Expands the functionality of a `NumberLine` which extends over into `coordinate_systems.py`. Would also be useful for adding dates to a particular axis and showing change over that period (`2021-03-01, 2021-03-02`) which is currently not possible. 

## Additional comments

This functionality could be added to a new function.

### PR DESCRIPTION
**Pull request by hydrobeam**
## Motivation

Closes #1672 

## Explanation for Changes

Added a separate function that's similar to `add_numbers` called `add_labels` which accepts a dict and handles it. I did this instead of adding checks to `add_numbers` since I think having `.add_numbers` be specialized to numbers makes more sense than having it be a catch-all method. This does mean that it's currently not possible to add labels when initializing the `NumberLine`/`Axes`. 

Also, `.add_coordinates` can accept dicts in addition to a list of numbers. I've added an example in the docs showing this.

[Documentation Reference](https://manimce--####.org.readthedocs.build)

## Testing Status

Code used to test

```py
class b(Scene):
    def construct(self):
        a = Axes(x_range=[0, 10])

        a.add_coordinates(
            dict(zip([x for x in range(1, 10)], ["str" for _ in range(1, 10)]))
        )
        self.add(a)
```

image

## Further Comments

~~The labels are not affected by the size scaling of the axes since they can be handled by the user. Not sure about how much control vs convenience to give to the user, but this feels appropriate.~~

EDIT: they are now

## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [x] My new functions/classes either have a docstring or are private
- [x] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [x] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Review by jsonvillanueva — COMMENTED** [review]
I've tried this PR locally and it works; however, I'd still prefer if this functionality were introduced with the ability to add the labels via the constructor such that if a certain keyword arg (e.g. labels) were added and not `None`, the label would be added to the corresponding NumberLine. Also, it might be worth adding a few shorthand methods for creating common labels, for instance:
```py
        self.axes.add_coordinates(
            dict(
                zip(
                    [x for x in np.arange(-4 * PI, 5 * PI, PI)],
                    [
                        MathTex(f"{x}\\pi")
                        if abs(x) > 1
                        else MathTex("\\pi")
                        if x == 1
                        else MathTex("-\\pi")
                        if x == -1
                        else 
                        ""
                        for x in range(-4, 5)
                    ],
                )
            )
        )
```

which produces:
        
image

**Comment by behackl** [comment]
> I've tried this PR locally and it works; however, I'd still prefer if this functionality were introduced with the ability to add the labels via the constructor such that if a certain keyword arg (e.g. labels) were added and not `None`, the label would be added to the corresponding NumberLine. Also, it might be worth adding a few shorthand methods for creating common labels, for instance:

I'm not sure I fully understand the first half of your comment, but I agree with easy-access custom formatting functionality. For now, I think this can be merged as-is (I'm about to read the changes in detail), and further improvements can be handled in a follow-up PR.

**Review by behackl — APPROVED** [review]
Implementation and documentation seems fine to me. I'm willing to include this in the upcoming release if a test is added.

**Comment by jsonvillanueva** [comment]
> > I've tried this PR locally and it works; however, I'd still prefer if this functionality were introduced with the ability to add the labels via the constructor such that if a certain keyword arg (e.g. labels) were added and not `None`, the label would be added to the corresponding NumberLine. Also, it might be worth adding a few shorthand methods for creating common labels, for instance:
> 
> I'm not sure I fully understand the first half of your comment, but I agree with easy-access custom formatting functionality.

Essentially the labels to the NumberLine/Axes have to be added after instantiation of the object via the `.add_coordinates()` method. It'd be better if this were made possible via the constructor in the `__init__()` in some manner. I'm okay with adding that after in a future release though as this is still a useful enhancement. I agree there should be a test.

**Comment by hydrobeam** [comment]
I've added the tests 👍

> Essentially the labels to the NumberLine/Axes have to be added after instantiation of the object via the .add_coordinates() method. It'd be better if this were made possible via the constructor in the __init__() in some manner. I'm okay with adding that after in a future release though as this is still a useful enhancement. I agree there should be a test.

While it wouldn't hurt to have this be possible, I think it's generally easier to work with a method as opposed to a cramped `__init__`. Especially since `NumberLine`'s `__init__` holds so many parameters already, that it feels better to work with the `NumberLine` post-creation.

> Also, it might be worth adding a few shorthand methods for creating common labels

I think this is a solid idea, and I've done something similar in #1812 to create custom labels for logarithmic scaling. That functionality could probably exteneded away from purely scaling to general utility.

**Comment by virgotatus** [comment]
I'm trying this feature too.  There is a comment: 
the add_labels function in number_line class have parameters **font_size**, 
```
def add_labels(
        self,
        dict_values: Dict[float, Union[str, float, "Mobject"]],
        direction=None,
        buff=None,
        **font_size=None,**
    )
```
But 'create_label_tex' called in add_labels can't apply font_size, without this parameters. So the Tex of string will be set in default size, but given font size.

Seting label.font_size is a easy way to fix it. like this:
```
def add_labels(....)
     ...
      for x, label in dict_values.items():
          label = self.create_label_tex(label)
          **label.font_size = font_size**
          label.next_to(self.number_to_point(x), direction=direction, buff=buff)
          labels.add(label)
     ...
```
Maybe you can find another well-designed way to fix it, please check it, thank you !

**Comment by hydrobeam** [comment]
Good catch! I'll make a PR that should make `create_label_tex` work properly.

**Pull request merged**
