### PR TITLE
Add more flexible opengl rendering orders

### LINKED ISSUE #2006: Line can be seen through vertex dots when using `~.get_line_graph()` in OpenGL
## Description of bug / unexpected behavior

When drawing a line graph with vertex dots using the OpenGL renderer, the line is visible through the vertex dots:

LineGraphExample_ManimCE_v0 10 0_OpenGL

Now compare this to the Cairo-rendered version:

LineGraphExample_ManimCE_v0 10 0_Cairo

The lines are behind the vertex dots, as they should be.

## Expected behavior

The vertex dots should fully cover the lines.

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
from manim import *

class LineGraphExample(Scene):
    def construct(self):
        plane = NumberPlane(
            x_range = (0, 7),
            y_range = (0, 5),
            x_length = 7,
            axis_config={"include_numbers": True},
        )
        plane.center()
        line_graph = plane.get_line_graph(
            x_values = [0, 1.5, 2, 2.8, 4, 6.25],
            y_values = [1, 3, 2.25, 4, 2.5, 1.75],
            line_color=RED,
            vertex_dot_style=dict(stroke_width=3,  fill_color=BLUE),
            stroke_width = 4,
        )
        self.play(Create(VGroup(plane, line_graph)))
        self.wait(1)
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)): Ubuntu 21.04
- RAM: 32GB
- Python version (`python/py/python3 --version`): 3.9.5
- Installed modules (provide output from `pip list`):
```
Package                 Version
----------------------- ---------------------
manim                   0.10.0
moderngl                5.6.4
moderngl-window         2.4.0
```
</details>

### PR DESCRIPTION
**Pull request by ryanmccauley211**
## Motivation and Explanation: Why and how do your changes improve the library?

Currently there are two ways of handling z-indexing for opengl. The first is two use depth-testing and set the z-indexes for objects, however if the objects have the same z-index, then it is handled by the order the objects are rendered. This PR makes the second option a bit more flexible for grouping objects. It creates a class `OrderedVGroup` that extends `OpenGLVGroup`. This takes in an order strategy for how the user wants mobjects to be rendered. I only added two for now, however more can be added such as a custom strategy that a user could pass in.

This PR began as I was looking for a way to resolve #2006 and this includes a way to fix this issue by using the below code

```py
class LineGraphExample(Scene):
    def construct(self):
        plane = NumberPlane(
            x_range = (0, 7),
            y_range = (0, 5),
            x_length = 7,
            axis_config={"include_numbers": True},
        )
        plane.center()
        line_graph = plane.get_line_graph(
            x_values = [0, 1.5, 2, 2.8, 4, 6.25],
            y_values = [1, 3, 2.25, 4, 2.5, 1.75],
            line_color=RED,
            vertex_dot_style=dict(stroke_width=3,  fill_color=BLUE),
            stroke_width = 4,
        )
        self.play(Create(OrderedVGroup(plane, line_graph, order_strategy=OrderStrategy.PRIORITY)))
        self.wait(1)
        self.interactive_embed()
```

I began by trying to adding the stroke behind fill, but this causes other issues as it will put the stroke behind fill for all mobjects in the `VGroup`, so the line graph lines were behind the plane. Using the new `OrderedVGroup` fixes it

Screenshot 2021-10-27 at 18 17 36

So this will give us flexibility when rendering 2D scenes and we want more control over the rendering order

## Further Information and Comments

Update: added two more strategies, REVERSE_PRIORITY that renders the more recently added mobjects first, and a CUSTOM strategy. The custom strategy allows the user to pass in their own function to control the order objects are rendered. For example the below code will render the even indexed mobjects followed by the odd:

```py
class EvenThenOddOrdering(Scene):
    def construct(self):
        a = Circle().set_fill(RED, 1.0).shift(UP)
        b = Circle().set_fill(GREEN, 1.0).shift(RIGHT)
        c = Circle().set_fill(RED, 1.0).shift(DOWN)
        d = Circle().set_fill(GREEN, 1.0).shift(LEFT)

        def even_then_odd(objs):

            all_shader_wrappers = []
            for i, obj in enumerate(objs):
                if i % 2 == 0:
                    if obj.has_fill():
                        all_shader_wrappers.append(obj.get_fill_shader_wrapper())
                    all_shader_wrappers.append(obj.get_stroke_shader_wrapper())
            for i, obj in enumerate(objs):
                if i % 2 == 1:
                    if obj.has_fill():
                        all_shader_wrappers.append(obj.get_fill_shader_wrapper())
                    all_shader_wrappers.append(obj.get_stroke_shader_wrapper())
            return all_shader_wrappers

        ordered_group = OpenGLVGroup(a, b, c, d, order_strategy=OrderStrategy.CUSTOM, order_func=even_then_odd)
        self.add(ordered_group)
        self.wait()
```
Screenshot 2021-10-31 at 16 26 48

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by behackl** [comment]
Have not looked at the code, but I like the idea a lot. I'm a bit worried that this needs a separate mobject and I'd be in favour of adding this feature directly to `OpenGL(V)Group`. Maybe there could be another ordering option that behaves just like the current default behavior of the group?

**Comment by ryanmccauley211** [comment]
> Have not looked at the code, but I like the idea a lot. I'm a bit worried that this needs a separate mobject and I'd be in favour of adding this feature directly to `OpenGL(V)Group`. Maybe there could be another ordering option that behaves just like the current default behavior of the group?

Yea I can try doing that and defaulting to the current behaviour. I do like the idea of reusing the existing one like @hydrobeam said, was just concerned about breaking existing behaviour but I guess we can try to default to existing behaviour like you say

**Comment by ryanmccauley211** [comment]
> Have not looked at the code, but I like the idea a lot. I'm a bit worried that this needs a separate mobject and I'd be in favour of adding this feature directly to `OpenGL(V)Group`. Maybe there could be another ordering option that behaves just like the current default behavior of the group?

Done, and added a couple more strategies

**Comment by Darylgolden** [comment]
Since `OpenGLVGroup` is actually just an `OpenGLVMobject`, why not add it to that instead?

**Comment by ryanmccauley211** [comment]
> Since `OpenGLVGroup` is actually just an `OpenGLVMobject`, why not add it to that instead?

I'm happy to add it to that instead if you think it is better, OpenGLVGroup doesn't seem to have much logic so extending either seems fine

**Comment by Darylgolden** [comment]
I think it'll be better, yes

**Comment by Darylgolden** [comment]
Though I wonder if it'll make things more complicated with merging Mobject and OpenGLMobject. @behackl do you have any thoughts on this?

**Comment by behackl** [comment]
> Though I wonder if it'll make things more complicated with merging Mobject and OpenGLMobject. @behackl do you have any thoughts on this?

No, I think it is fine. In the worst case, if we ever manage to get it down to one Group class, there might just be a keyword argument that doesn't do anything for a given shader. This sort of inconsistent behavior is unavoidable.

**Comment by ryanmccauley211** [comment]
> I think it'll be better, yes

As I was doing it I changed my mind about it, it seems to me that it would be better to stay in a specialized group class. I think it would bloat `OpenGLVMobject` as a lot of time it will not be grouping elements and so won't be used. I think it would be better for a user to use the specialized `OpenGLVGroup`class extending  when they want to group elements. Also in the future we might want to add other group-related features so seems better to have this special class for it. What you think?

**Comment by MrDiver** [comment]
We will come back to this with the issue and discuss a better solution when the time is ready!

**Pull request closed without merging**
