### PR TITLE
Revert "this was well-hidden.  (╯°□°）╯︵ ┻━┻"

### LINKED ISSUE #610: Follow-up to #562 -- bug with Transform / Mobject.become
`git bisect` says that merging #562 introduced a problem with `Mobject.become`: The example

```
class FadeInAndOut(Scene):
    def construct(self):
        square = Square(color=BLUE).shift(2 * UP)
        annotation = Text("Fade In", height=0.8)
        self.add(annotation)
        self.play(FadeIn(square))

        annotation.become(Text("Fade Out", height=0.8))
        self.add(annotation)
        self.play(FadeOut(square))
```
from our documentation renders as

FadeInAndOut

Same thing if the call to `become` is replaced by playing a `Transform` animation; the old text is simply kept on screen.

_Originally posted by @behackl in https://github.com/ManimCommunity/manim/pull/562#issuecomment-716033185_

### PR DESCRIPTION
**Pull request by eulertour**
This reverts commit 8e6e0cab495df9f44b68817f2b4ffa070c1199df.

I don't understand why, or even if this is correct, but this seems to fix #610.

### CODE REVIEW

**Comment by behackl** [comment]
Wait. What? 😂

**Comment by leotrs** [comment]
Oh man

**Comment by behackl** [comment]
Locally, this change does not fix it for me. Same output:

FadeInAndOut

**Comment by behackl** [comment]
(I needed to clear the entire `media` directory every time when building; there was something weird going on with the caching as well. I should have mentioned that earlier, sorry.)

**Comment by eulertour** [comment]
You're right, this is just a discrepancy between when scene caching is and isn't used.

**Pull request closed without merging**
