### PR TITLE
Rework example for :class:`~.Variable`

### PR DESCRIPTION
**Pull request by UraniumCronorum**
## Motivation

Pull request for [this hackathon submission](https://discord.com/channels/581738731934056449/843450687249580052/850807347436716064).

(My Discord tag: UraniumCronorum#9747)

## Explanation for Changes

[Documentation Reference](https://manimce--1706.org.readthedocs.build/en/1706/reference/manim.mobject.numbers.Variable.html)

## Checklist
- [ ] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [ ] I have written a descriptive PR title (see top of PR template for examples)
- [ ] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by PhotonSpheres** [comment]
Hey there, thank you for your contribution! 
Unfortunately, I don't think this example fits well: Since you interpolate linearly between the beginning and numbers and their respective end numbers, there will be wrong equations on-screen during the animation, see the screenshot below. 
I guess one fix would be to calculate the square number for each frame.
ex

**Comment by PhotonSpheres** [comment]
If you don't mind a little more input, I can suggest the following changes to your example:

```py
class VariableExample(Scene):
    def construct(self):
        x = 0
        x_sqr = x**2
        x_display = Variable(x, "x", num_decimal_places=3)
        sqr_display = Variable(x_sqr, "x^2", num_decimal_places=3).next_to(x_display,DOWN)
        Group(x_display, sqr_display).center()
        self.play(
            Write(x_display),
            Write(sqr_display)
        )
        x_tracker = x_display.tracker
        sqr_tracker = sqr_display.tracker
        x = 5.6
        x_sqr = x**2
        self.play(
            x_tracker.animate(rate_func=linear).set_value(x),
            sqr_tracker.animate(rate_func=lambda x: x**2).set_value(x_sqr),
        )
        self.wait()
```

https://user-images.githubusercontent.com/44864613/122675083-2c38e780-d1d8-11eb-8fd9-f057a588c9ec.mp4

**Comment by UraniumCronorum** [comment]
Hi, thanks for the feedback.

I tried running the code you suggested and it seems to work fine, but when I change the initial value of x to something other than 0, the results start to get out of sync again. I'm trying to figure out how to fix this, but I haven't made much progress yet.

I also tried your suggestion about calculating the values for each frame, and this seems to work:
```py
class VariableExample(Scene):
    def construct(self):
        start = 2.0

        x_var = Variable(start, 'x', num_decimal_places=3)
        sqr_var = Variable(start**2, 'x^2',
                           num_decimal_places=3).next_to(x_var, DOWN)
        self.add(x_var, sqr_var)

        x_var.tracker.add_updater(lambda m, dt: m.set_value(m.get_value()+dt))
        sqr_var.tracker.add_updater(lambda m:
                                    m.set_value(x_var.tracker.get_value()**2))
        self.add(x_var.tracker)
        self.add(sqr_var.tracker)

        self.wait(3)

```

**Comment by PhotonSpheres** [comment]
> I tried running the code you suggested and it seems to work fine, but when I change the initial value of x to something other than 0, the results start to get out of sync again. I'm trying to figure out how to fix this, but I haven't made much progress yet.

This is due to how `rate_func`. I don't know how easy it would be to generalize my suggestion to other start values than 0.

> I also tried your suggestion about calculating the values for each frame, and this seems to work:

I really like your example, just adding the tracker to the scene seems a bit weird to me. I think, building up on your idea, this might be a bit cleaner

```py
class VariableExample(Scene):
    def construct(self):
        start = 2.0

        x_var = Variable(start, 'x', num_decimal_places=3)
        sqr_var = Variable(start**2, 'x^2', num_decimal_places=3)
        Group(x_var, sqr_var).arrange(DOWN)

        sqr_var.add_updater(lambda v: v.tracker.set_value(x_var.tracker.get_value()**2))

        self.add(x_var, sqr_var)
        self.play(x_var.tracker.animate.set_value(5), run_time=2, rate_func=linear)
        self.wait(0.1)
```

What do you think?

**Comment by behackl** [comment]
I like the latest suggestion by @PhotonSpheres, +1 for reworking the example from this PR in that direction.

Also, instead of removing the current example, I suggest to keep the current one and add this as an additional example.

**Review by PhotonSpheres — APPROVED** [review]
LGTM! Cheers again

**Review by behackl — APPROVED** [review]
LGTM! Thanks for your contribution!

**Pull request merged**
