### PR TITLE
Run autopep8 formatter

### PR DESCRIPTION
**Pull request by safinsingh**
Ran `autopep8 --in-place --recursive .` to format with `autopep8`
Side note: should there be a step in Travis/Github actions to automatically do this? (see https://github.com/marketplace/actions/autopep8)

### CODE REVIEW

**Comment by naveen521kk** [comment]
Aren't we planned to use [black](https://github.com/psf/black)?

**Comment by leotrs** [comment]
I thought someone mentioned black in the past, but I don't think we reached any consensus.

I'm not partial to any one autoformatter AS LONG AS it can easily be ran from within travis. I know black can be ran from travis. Is this true for autopepe8?

**Comment by safinsingh** [comment]
Travis is basically just like your own machine so it _could_ do it by itself, im just saying we could have it in a github workflow since i think that's what we're using for PyPi. If not, I can spin up an addition to travis to do it.

**Comment by leotrs** [comment]
In that case, I'm not partial to either autopep8 or black, though we should reach ask other devs and reach a consensus.

**Comment by eulertour** [comment]
If we don't enforce this with a CI solution the code will break the standard pretty quickly.

**Comment by naveen521kk** [comment]
It would be better to ask the developer to run it locally in his/her machine and check whether the code is up to standards in Travis/Github Action using autopep8/black. If we ran it on CI and then commit it we could have a lot of problems like their could some merge confilicts and it is not necessary. But keeping it as a check is alway good.

**Comment by leotrs** [comment]
Agreed. The contribution guidelines should include that the developer must run the formatter and run the tests before submitting a PR.

**Pull request closed without merging**
