### PR TITLE
Fix bug introduced in Tex rendering via #2574

### LINKED ISSUE #2586: Rendering TeX strings containing % broken
This unfortunately broke rendering of TeX strings containing `%`. Trying to create `Tex(r"\%")` fails in v0.15.0.

_Originally posted by @behackl in https://github.com/ManimCommunity/manim/issues/2574#issuecomment-1054726581_

### PR DESCRIPTION
**Pull request by Kiran-Raj-Dev**
## Overview: What does this pull request change?

Fixes #2586

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by behackl** [comment]
Thank you! Please also add a (non-graphical) unit test making sure that `Tex(r"\%")` compiles as intended.

**Comment by Kiran-Raj-Dev** [comment]
Done!

**Review by Darylgolden — COMMENTED** [review]
It's fine as is, but I think it'll be better if the `%` test was split into its own test.

**Comment by Kiran-Raj-Dev** [comment]
What should I name it in that case?

**Comment by Darylgolden** [comment]
Perhaps `test_percent_char_rendering`?

**Review by behackl — APPROVED** [review]

**Pull request merged**
