### PR TITLE
Reorganized some unit tests

### PR DESCRIPTION
**Pull request by Darylgolden**
## Overview: What does this pull request change?
The first part (of many) working towards #2591. This PR reorganizes most of the test files previously located in the main tests directory, moving them into `module` or `miscellaneous` directories respectively. Moving last remaining files causes issues, so I've decided to move them in a separate PR. Reorganizing the graphical unit tests will also cause the files changed to be rather large, so I also think it's best done in another PR.

## Further Information and Comments
For reference, the total number of tests before was 609, and remains at 609 after these changes.

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Review by behackl — APPROVED** [review]
Good work, thank you!

**Comment by behackl** [comment]
@Darylgolden could you resolve the merge conflict and then merge this?

**Comment by MrDiver** [comment]
What is the state of this ?

**Comment by Darylgolden** [comment]
I tried resolving the merge conflicts and messed up the history. I'll look into it more next week.

**Comment by behackl** [comment]
Superseded by #2866.

**Pull request closed without merging**
