### PR TITLE
Concurrent ApplyMethod calls to same Mobject should work

### PR DESCRIPTION
**Pull request by Pragyaan-6988**
## List of Changes

- Enabled multiple `ApplyMethod` calls in a single `play` call.

## Motivation

A possible fix for #713 and #722 

## Explanation for Changes

The reason why multiple `ApplyMethod` calls currently don't work is, I believe, because a new target is created through a copy of `mobject` for each `ApplyMethod` call.

My idea is to generate a new target to the `mobject` only if no targets are generated till that point. This can be done by checking if the attribute `target` is `None` (which means there are no targets generated so far). If `mobject.target` is not `None`, meaning a target was previously set, no new target will be generated.

## Testing Status

<details><summary>Working example</summary>

```py
class ApplyMethodTest(MovingCameraScene):
    def construct(self):
        c = Circle()
        self.add(c)
        self.wait()
        c.generate_target()
        c.target.scale(2)
        self.play(MoveToTarget(c))
        self.play(
            ApplyMethod(c.to_edge),
            c.set_color, BLUE,
            c.set_opacity, 0.5
        )
        self.wait()
        self.play(*map(FadeOut, self.mobjects))
        self.wait()

        r = Rectangle()
        self.play(ShowCreation(r))
        self.wait()
        self.play(
            ApplyMethod(r.set_height,6,True),
            r.set_opacity,1,
            ApplyMethod(r.set_color,RED)
        )
        self.wait()
        self.play(*map(FadeOut, self.mobjects))
        self.wait()
        
        c = Circle()
        c.shift(UR * 2)
        c.set_fill(ORANGE, opacity=1)
        gc = c.get_center()
        gcw = c.get_width()
        
        self.add(c)
        self.wait()
        self.play(
            ApplyMethod(self.camera_frame.move_to, gc),
            self.camera_frame.set_width, gcw * 2,
            )
        self.wait()
```

ApplyMethodTest

## Acknowledgement
- [x] I have read the [Contributing Guidelines](https://github.com/ManimCommunity/manim/wiki/Documentation-guidelines-(WIP))

### CODE REVIEW

**Comment by leotrs** [comment]
This makes sense to me. @behackl would you be able to comment? I believe you are working on something similar with AnimationGroup.

@Pragyaan-6988 this is something that could *really* use adding new tests. Would you be able to add a couple of simple unit tests so we don't regress on this feature in the future? If you don't know how, let us know and we can help you.

**Comment by leotrs** [comment]
Also, unfortunately the docs are not building with the following error. 

```python
File "/home/docs/checkouts/readthedocs.org/user_builds/manimce/envs/772/lib/python3.8/site-packages/manim/mobject/types/image_mobject.py", line 229, in interpolate_color
    assert mobject1.pixel_array.shape == mobject2.pixel_array.shape, (
AssertionError: Mobject pixel array shapes incompatible for interpolation.
Mobject 1 (ImageMobjectFromCamera) : (90, 180, 4)
Mobject 2 (ImageMobjectFromCamera) : (60, 360, 4)

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/manimce/envs/772/lib/python3.8/site-packages/manim/mobject/types/image_mobject.py", line 229, in interpolate_color
    assert mobject1.pixel_array.shape == mobject2.pixel_array.shape, (
AssertionError: Mobject pixel array shapes incompatible for interpolation.
Mobject 1 (ImageMobjectFromCamera) : (90, 180, 4)
Mobject 2 (ImageMobjectFromCamera) : (60, 360, 4)
```

This makes me think that your change broke one of the examples in our gallery. I don't have a ton of time right now, but I can help you figure out which example it is later. (Or someone else reading this will!)

**Comment by behackl** [comment]
>  (Or someone else reading this will!)

The example broken by this change is https://docs.manim.community/en/latest/examples.html#movingzoomedscenearound -- something weird seems to be happening. I can't investigate right now whether the fact that this broke is okay (because it shouldn't have worked in the first place), or because this uncovers a problem with this PR.

**Comment by Pragyaan-6988** [comment]
> @Pragyaan-6988 this is something that could _really_ use adding new tests. Would you be able to add a couple of simple unit tests so we don't regress on this feature in the future? If you don't know how, let us know and we can help you.

@leotrs I've spent some time trying to figure out why this fails but couldn't come to a meaningful conclusion. May be I'm overlooking something. I'll look into this further when I have time, but if you guys have any ideas, please do share. I'm on the discord (Abhijith) if you'd like to discuss it there. Also, I have no idea about the unit tests. I'll ask for help when this issue is resolved. Thank you.

**Comment by leotrs** [comment]
@Pragyaan-6988 sorry for the delay - I'm looking into it, though unfortunately I am not an expert in this part of the codebase. Let's see if anyone on discord can figure it out.

**Comment by Pragyaan-6988** [comment]
> @Pragyaan-6988 sorry for the delay - I'm looking into it, though unfortunately I am not an expert in this part of the codebase. Let's see if anyone on discord can figure it out.

@leotrs No worries, this one is tricky  😅. I've actually realized that this isn't a good approach. Take this code for example:
```py
class ApplyMethodTest(Scene):
    def construct(self):
        c = Circle()
        c.generate_target()
        c.target.to_edge()

        self.add(c)
        self.play(ApplyMethod(c.scale, 2))
```
The circle gets scaled and also moves to the left edge which shouldn't happen. 
I made some changes to `Scene.compile_play_args_to_animation_list` and the results look good..

**Review by huguesdevimeux — CHANGES_REQUESTED** [review]
SGTM, Thanks for your cotnribution!

Nevertheless this would require a test. Read the wiki on github for more infos. 
I'm not sure what would be better between a classic unit test or a graphical unit test.

**Comment by Pragyaan-6988** [comment]
> SGTM, Thanks for your cotnribution!
> 
> Nevertheless this would require a test. Read the wiki on github for more infos.
> I'm not sure what would be better between a classic unit test or a graphical unit test.

Thanks for the review @huguesdevimeux ! I think I have to update this PR to work with the new `.animate` syntax. I haven't looked into it yet. I should also learn about the unit tests, so I'll update this PR with all that stuff in few days. Thank you.

**Comment by Pragyaan-6988** [comment]
Hi, sorry for not updating on this for so long. So I was requested to add unit tests to this, however I don't think this PR is relevant anymore, given that the `.animate` syntax (together with method chaining) potentially replaces `ApplyMethod` entirely once [1118](https://github.com/ManimCommunity/manim/pull/1118)  is merged. 

The only drawback is that it'd still not support multiple method animations on same mobject (each with different animation kwargs - which method chaining doesn't support). I believe this is an extremely rare situation, but still it'd be good if we can support that. However that shouldn't be in this PR, so I'm closing this.

**Pull request closed without merging**
