### PR TITLE
Lock the Media Directory when Manim is Running

### PR DESCRIPTION
**Pull request by naveen521kk**
## Changelog / Overview

This will ensure that no two instances of Manim will work on the same directory. 
Also, now, the version will only print when Manim makes sure that it can start, unlike previously where it just printed on start.

## Motivation
This is required because it could create PermissionError when manim calls FFmpeg is operating on the same directory.

## Explanation for Changes
This uses system API, `msvcrt.locking` on Windows and `fcntl.flock` on other platforms, to lock a file called `manim.lock` inside the media directory. If Manim fails to get the lock on that file it fails, with an error message.

## Testing Status
I have tested this on Windows and also on Linux, don't know about macOS though, but it should work ideally. I have added tests, which should be testing it on the CI. Let's see.

## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [x] My new functions/classes either have a docstring or are private
- [x] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by naveen521kk** [comment]
> I really can foresee potential times when you might want two installations of manim to use the same media directory.

IMO, that would always be problematic. That's mainly because Manim does a *lot* of things with media directory and could create PermissionError's and that would be out of our control. Could you explain of how would using same media directory by two instances help?

**Comment by WampyCakes** [comment]
I can just see times where you might need multiple versions using the same media folder for automated testing or server backends or such. Or maybe even locally, if I want to do it, who are you to say I can't? 😠 jk. But seriously, why not provide an override? If the lock is in place by default, then new users won't have a problem.

Also, to say that this would "always be problematic" seems overkill as I've not once seen a PermissionError on my machine due to this. We've made it this far, haven't we? I'm not saying that this is a bad idea; I think it's a good one. But adding an override seems harmless to me.

**Comment by naveen521kk** [comment]
> I can just see times where you might need multiple versions using the same media folder for automated testing or server backends or such. 

It's always *not* recommended (at least by me) to use the same media directory to run multiple instances of Manim, because of the way how caching works and the way how Manim calls FFmpeg. You can always create temp directories as media dirs...

> who are you to say I can't? :angry: jk.

Manim Community Dev Team (jk)

> But adding an override seems harmless to me.

Maybe it should be fine, at least it can be around as an option if this didn't work out as expected.

**Comment by kilacoda** [comment]
So CMIIW, but does this effectively mean that you can't run simultaneous renders (in two or more terminal windows) on the same file/with the same media dir anymore? IIRC some people render that way to speed things up.

**Comment by naveen521kk** [comment]
> but does this effectively mean that you can't run simultaneous renders (in two or more terminal windows) on the same file/with the same media dir anymore?

Pretty much yes, but you can run the same file but with different media directories. The locks are on Media Directory and not the file itself.

> IIRC some people render that way to speed things up.

Does that really speed up things? I don't think so? 
I would say this would lead to unwanted problems, and it's always better to avoid that.

**Comment by AntonBallmaier** [comment]
I would also really like an option to turn this of since I regularly render multiple videos in parallel in the same directory.

**Comment by naveen521kk** [comment]
> I would also really like an option to turn

There is a CLI flag, `--no_lock_media_dir`

> I regularly render multiple videos in parallel in the same directory.

This would still be error-prone...(don't complain)

**Comment by naveen521kk** [comment]
Hmm, is this PR worth its effort?

**Pull request closed without merging**
