### PR TITLE
Update README.md - Replaced new discord link

### PR DESCRIPTION
**Pull request by NikhilSharma03**
## Changelog / Overview
Replaced the old https://discord.gg/mMRrZQW to https://www.manim.community/discord/

## Motivation
The contributors can find and access the right discord link.

## Explanation for Changes
I updated README.md for the new discord links

## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [x] My new functions/classes either have a docstring or are private
- [x] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [x] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by naveen521kk** [comment]
Please follow the PR template. @NikhilSharma03

**Comment by NikhilSharma03** [comment]
I am new to this platform. Can you please tell me where to find it?

**Review by Darylgolden — CHANGES_REQUESTED** [review]
Hi @NikhilSharma03, thank you for your PR! Can you fix the links in the documentation too (located in the docs folder)? You can use your code editor to search the repository for the discord link to change.

**Comment by NikhilSharma03** [comment]
yeah sure

**Comment by Darylgolden** [comment]
> 
> 
> I am new to this platform. Can you please tell me where to find it?

You can find it at https://github.com/ManimCommunity/manim/blob/master/.github/PULL_REQUEST_TEMPLATE.md. It should have been filled up automatically when you created the pull request.

**Comment by NikhilSharma03** [comment]
Can you please check the template.

**Comment by Darylgolden** [comment]
The template is fine.

**Comment by Darylgolden** [comment]
Are you having trouble adding new changes to the PR? To do that, you should push your changes onto the patch-1 branch.

**Comment by NikhilSharma03** [comment]
Sorry for the trouble. I have created a new pull request where I have updated all the links in the docs. Can you please review it? Sorry for the inconvinience.

**Pull request closed without merging**
