### PR TITLE
bump dependencies

### PR DESCRIPTION
**Pull request by haraldschilly**
## Overview: What does this pull request change?

Update pinned dependencies and as a first step, I want to see if the tests pass.

## Motivation and Explanation: Why and how do your changes improve the library?

see #3241 – and in particular in my case, I want to use a newer networkx

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by behackl** [comment]
That's a familiar name; hey there @haraldschilly!

Seems like the cloup upgrade messes with the formatting of `deprecated` in the CLI test, nothing serious. I'm happy to merge this once the test is fixed. 👍

**Comment by haraldschilly** [comment]
:wink: @behackl  … github is a small world :grinning:

**Review by behackl — APPROVED** [review]
LGTM now, thanks!

**Comment by haraldschilly** [comment]
cool, thx!

**Pull request merged**
