### PR TITLE
Added config to enable opengl wireframe for debugging

### PR DESCRIPTION
**Pull request by ryanmccauley211**
## Motivation and Explanation: Why and how do your changes improve the library?

It is useful when debugging opengl to see the vertices and edges of objects, this adds a config option to enable wireframe mode in opengl

```py
class Test(Scene):
    def construct(self):
        a = Dot(radius=2)
        self.add(a)
        self.interactive_embed()
```

__Normal mode__

Screenshot 2021-09-11 at 19 30 48

__wireframe mode__

Screenshot 2021-09-11 at 19 31 11

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by GameDungeon** [comment]
maybe add a check that throws an error if you are not in opengl mode?

**Comment by ryanmccauley211** [comment]
> maybe add a check that throws an error if you are not in opengl mode?

I could add a check, thinking logging a warning to say it is an unsupported flag for cairo might be better than throwing an error though? Since the flag technically won't affect cairo's behaviour?

**Comment by GameDungeon** [comment]
Both could work. Your right that a warning is probably better.

**Review by naveen521kk — APPROVED** [review]
Lgtm

**Review by behackl — APPROVED** [review]

**Pull request merged**
