### PR TITLE
Added example for :class:`~.BulletedList`

### PR DESCRIPTION
**Pull request by peaceheis**
## Changelog / Overview

Added a simple example for the BulletedList class

## Motivation

There was previously no example for this; adding examples leads to a more well-documented Manim.
## Explanation for Changes

[Documentation Reference](https://manimce--####.org.readthedocs.build)

## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by Darylgolden** [comment]
[Courtesy link](https://manimce--1631.org.readthedocs.build/en/1631/reference/manim.mobject.svg.tex_mobject.BulletedList.html?highlight=bulletedlist)

**Review by Darylgolden — CHANGES_REQUESTED** [review]
The example doesn't appear to be formatted properly, did you use the bot to format it?

**Comment by peaceheis** [comment]
> The example doesn't appear to be formatted properly, did you use the bot to format it?

I think I did, but I might have made a typo in the process of copying it.

**Comment by jsonvillanueva** [comment]
> The example doesn't appear to be formatted properly, did you use the bot to format it?

I already fixed it @Darylgolden, but it was an issue of starting the docstring dedented by 4 spaces @peaceheis

**Comment by peaceheis** [comment]
> but it was an issue of starting the docstring dedented by 4 spaces @peaceheis (8 spaces in some places)

Ah, that’s good to know. Thank you!

**Review by jsonvillanueva — APPROVED** [review]

**Review by Darylgolden — APPROVED** [review]
Works now. LGTM, thank you for your efforts!

**Pull request merged**
