### PR TITLE
specify minimal required version of rich

### LINKED ISSUE #245: AssertionError on test_logging.py solved by strip()
I have an assertion error on `logs == expected, logs` on the last line of test_logging.py when running pytest.
I think it is simply an issue with trailing spaces as replacing the end of the file by
```python
logs = logs.strip()
expected = expected.strip()
assert logs == expected, logs
```
yields a test success.

### PR DESCRIPTION
**Pull request by behackl**
## List of Changes
- Set minimum requirement for version of `rich` in `requirements.txt`

## Motivation
Resolves #245 

## Explanation for Changes
See https://github.com/ManimCommunity/manim/issues/245#issuecomment-668498765 and the related issue https://github.com/willmcgugan/rich/issues/190

## Acknowledgement
- [x] I have read the [Contributing Guidelines](https://github.com/ManimCommunity/manim/wiki/Documentation-guidelines-(WIP))

### CODE REVIEW

**Comment by leotrs** [comment]
Great! Can you share how did you decided that 4.2.1 was the appropriate version to fix here? In general we do not want to latest version as people may not have it installed yet (or it may contain bugs), but we also do not want an old version.
cc. @naveen521kk

**Comment by Aathish04** [comment]
> Great! Can you share how did you decided that 4.2.1 was the appropriate version to fix here? In general we do not want to latest version as people may not have it installed yet (or it may contain bugs), but we also do not want an old version.
> cc. @naveen521kk

Version 4.2.1 and above allow us to prevent the truncation of URLs and file paths via attributes to `rich.Console()`.

This is required to have a uniform amount of characters in the log, so character by character comparisons can take place.

The issue that asked for this over at `rich`'s own repo was https://github.com/willmcgugan/rich/issues/190 and in that, `rich`'s author states that they have introduced the feature that we need (the one that allows us to disable truncating URLs and file paths) in v4.2.1.

**Comment by behackl** [comment]
> > Great! Can you share how did you decided that 4.2.1 was the appropriate version to fix here? In general we do not want to latest version as people may not have it installed yet (or it may contain bugs), but we also do not want an old version.
> The issue that asked for this over at `rich`'s own repo was [willmcgugan/rich#190](https://github.com/willmcgugan/rich/issues/190) and in that, `rich`'s author states that they have introduced the feature that we need (the one that allows us to disable truncating URLs and file paths) in v4.2.1.

Precisely, this issue over there was the reason I tried with 4.2.1 -- however, I also just tried with 4.2.0 and the tests also passed there. In fact, this seems to be the first version where the additional newline in the end is not a problem: the previous version, 4.1.0, still fails.

**Comment by Aathish04** [comment]
> Precisely, this issue over there was the reason I tried with 4.2.1 -- however, I also just tried with 4.2.0 and the tests also passed there. In fact, this seems to be the first version where the additional newline in the end is not a problem: the previous version, 4.1.0, still fails.

Perhaps your paths weren't long enough to be truncated?

**Comment by leotrs** [comment]
Well if they're using semantic versioning, it will probably always be better and not problematic to use 4.2.1 instead of 4.2.0. Merge at will!

**Comment by naveen521kk** [comment]
Guys! Please do the same in `setup.py` nobody is actually using `requirements.txt`. @behackl

**Comment by behackl** [comment]
> Guys! Please do the same in `setup.py` nobody is actually using `requirements.txt`. @behackl

Will provide another PR. But I do want to mention that https://github.com/ManimCommunity/manim#installing-manim-community-itself explicitly says:

Finally, run the following:
```
python3 -m pip install -r requirements.txt
```

(which is also how I installed manim, so "nobody" is not quite true. ;-))

**Comment by leotrs** [comment]
Yeah, the requirements.txt file will be used by anyone who will try to develop on this repo.

**Comment by naveen521kk** [comment]
But anyhow making in `setup.py` is necessary as that decides if we do `pip install -e .`. Also, our CI uses it.

**Comment by behackl** [comment]
Don't worry, I was not trying to argue. :-)

Sorry for missing the `setup.py` in the first iteration, I was not really thinking. Follow-up: #247

**Pull request merged**
