### PR TITLE
New thematic guide: a deep dive into the internals of the library

### PR DESCRIPTION
**Pull request by behackl**
## Overview: What does this pull request change?

New document explaining the code flow of rendering an animation from start to finish.

## Motivation and Explanation: Why and how do your changes improve the library?

The complexity of the library and the fact that the render loop is not documented properly anywhere really makes it difficult for new contributors to get into the library. This is an attempt at documenting the render flow from start to finish.

## Links to added or changed documentation pages
https://manimce--2550.org.readthedocs.build/en/2550/guides/deep_dive.html

### CODE REVIEW

**Comment by JeroSQ** [comment]
Looks really good so far. Thank you for this, I really think this will be extremely useful for new animators and contributors. I only have one _suggestion_: Maybe it would be better to have the `ToyExample` variables' names be a word instead of a single letter? Like `square` instead of `s`, or `circle` instead of `c`.

I think these could be benefitial for a couple reasons:

1. Having the complete variable names makes the whole code very understandable, it would be just plain English, for example:
```py
dot.add_updater(lambda mob: mob.next_to(circle, DOWN))
self.play(Create(dot))
self.play(circle.animate.shift(RIGHT))
```
   It is very simple to understand, you can clearly see what's going on and you don't have to do any translation in your head from `d` to `dot` and `s` to `square` and so on. What I mean is that it's much more readable, and I think that's important for beginners.

2. If the library has one-letter variable names, we are encouraging people to use the same variable names, and their animations will surely be more complex than the examples, so the code might not be as readable. If they were to report issues or even create pull requests, they will probably use the same variable names as in the examples, since they consider that to be _correct_, and the library code cleanliness could deteriorate. 

I can see how people could get confused by having `square` as a variable name and `Square` as a class, only differing by a single upper case letter. However, python is a case-sensitive language, so the new animators would have to live with that anyway. If that's too big of an issue, we could have another variable name which isn't just one letter and also can't be confused with the classes, like `orange_square` or something. Would be interesting to hear your thoughts🤔

**Comment by behackl** [comment]
> Looks really good so far. Thank you for this, I really think this will be extremely useful for new animators and contributors.

Thank you! I'll try to finish this up over the next few days.

> I only have one _suggestion_: Maybe it would be better to have the `ToyExample` variables' names be a word instead of a single letter? Like `square` instead of `s`, or `circle` instead of `c`.
> 

I agree, good point.

> I can see how people could get confused by having `square` as a variable name and `Square` as a class, only differing by a single upper case letter. However, python is a case-sensitive language, so the new animators would have to live with that anyway. If that's too big of an issue, we could have another variable name which isn't just one letter and also can't be confused with the classes, like `orange_square` or something. Aditionally, many of the existing examples have `dot` or `square` as variable names. Would be interesting to hear your thoughts🤔

IIRC I thought about that for a while for some of my video tutorials. My solution was to use variable names like `orange_square` etc to be more explicit and distinguish them cleaner from the classes. We could do something similar here, maybe `my_square`  etc or something like that will do.

**Comment by behackl** [comment]
There is now a very rough sketch of the rest of the content in this article. I toured through the render loop [on stream](https://www.twitch.tv/videos/1417496675) in case anyone wants to see my thoughts and more details. I hope to find some time over the next few days to continue fleshing this out.

**Comment by behackl** [comment]
Another update: this now contains a digression on Mobjects and VMobjects, as well as everything up to the initialization of the orange square. We are getting somewhere!

**Comment by behackl** [comment]
With the latest commit, the subsection on mobject initialization is complete. Next up will be `Scene.add`, and then we might actually move into rendering territory. :-)

**Comment by behackl** [comment]
A thorough explanation of `Scene.add` has been added. There are two, at most three more subsections that are still missing: the initialization of animations, and the actual description of the render loop. We are probably, like, 75% or so done. (I hope.)

**Comment by behackl** [comment]
New update, more content ~ there is a readable overview now, and the third chapter (on animations and the render loop) contains everything up to (and not including, yet) rendering the first frame.

**Comment by behackl** [comment]
The tutorial is now feature-complete and ready for review. I propose to carry out larger changes in follow-up PRs to get this here merged as soon as possible. :-)

**Review by Kiran-Raj-Dev — APPROVED** [review]
Ez approve

**Comment by Kiran-Raj-Dev** [comment]
Thanks!

**Pull request merged**
