### PR TITLE
feat: migrate to Pathlib

### PR DESCRIPTION
**Pull request by manu-chroma**
Addresses https://github.com/ManimCommunity/manim/issues/485

Picked some of the files not addressed by previous or currently pending PRs

### CODE REVIEW

**Comment by manu-chroma** [comment]
cc: @leotrs @huguesdevimeux

**Review by leotrs — APPROVED** [review]

**Comment by leotrs** [comment]
Thanks for your contribution!

**Comment by manu-chroma** [comment]
Thanks. I will probably pick more files in subsequent PRs when I find time 👍

**Comment by leotrs** [comment]
Sounds good!

@behackl I know the docs are building correctly, but would it be possible for you to eye-ball real quick the changes to the manim-directive before merging? I feel RTD can be a bit brittle...

**Comment by manu-chroma** [comment]
@leotrs Corrected a minor typo I had left behind: https://github.com/ManimCommunity/manim/pull/630/commits/2205086c57b9107b636f220ab60e9f7e5caca886

**Review by behackl — CHANGES_REQUESTED** [review]
Something is not right: in the rendered version of the documentation there seem to be no videos. See, e.g., https://manimce--630.org.readthedocs.build/en/630/tutorials/quickstart.html for comparison.

I can't quite tell why the videos are not in the correct directory, and unfortunately I don't have time to debug this right now. Whatever happens, something weird has to happen locally as well; try building the documentation using `make html` in the `docs` directory (potentially after `pip install -r docs/requirements.txt`).

**Comment by manu-chroma** [comment]
Has anyone seen similar exception before? 

```
(venv3) ➜  docs git:(path_lib) ✗ make html
Running Sphinx v3.1.2

Exception occurred:
  File "/Users/manvendra.s/work/learn/manim/venv3/lib/python3.8/site-packages/pangocairocffi/__init__.py", line 11, in <module>
    from ._generated.ffi import ffi
ModuleNotFoundError: No module named 'pangocairocffi._generated.ffi'
The full traceback has been saved in /var/folders/r2/drncpk212xxdw_zd5ns7nrrn09q2nk/T/sphinx-err-s2gtdcs3.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by behackl** [comment]
> Has anyone seen similar exception before?

Yes: see https://docs.manim.community/en/latest/installation/troubleshooting.html

**Comment by leotrs** [comment]
Oh my god I love having a functional troubleshooting page *chef's kiss*

**Comment by kolibril13** [comment]
@manu-chroma : Looks really great!
 can you merge the current master into your branch?
There are currently two merge conflicts.

**Comment by manu-chroma** [comment]
@kolibril13 I still haven't solved the issue highlighted by @behackl in the above comments. 

If that's ok, I'd be happy to resolve the merge conflicts.

**Comment by kolibril13** [comment]
@manu-chroma : any updates on this?

**Comment by kolibril13** [comment]
I merged master into this, and as manim_derective had changed a lot, I discarded the changes to pathlib there.

**Review by leotrs — APPROVED** [review]

**Review by behackl — APPROVED** [review]

**Pull request merged**
