### PR TITLE
enable z_index in Circumscribe

### PR DESCRIPTION
**Pull request by vahndi**
## Overview: What does this pull request change?

adds `z_index` parameter to `Circumscribe` constructor so it can be used for the `z_index` of the `frame` (`SurroundingRectangle` or `Circle`)

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by huguesdevimeux** [comment]
That SGTM, but I'd rather wait for @behackl approval.

Do you mind trying to add some test about that ? It's actually a corner case of manim interesting to test (the behaviour of surrounding shapes when z_index is special)

**Comment by vahndi** [comment]
Sure - I'll take a look at the test suite at the weekend and see what I can do.

**Review by behackl — COMMENTED** [review]
In principle, this change looks fine to me. However, I do wonder whether, instead of just implementing this for `z_index`, it would be worth to move all arguments passed to mobjects except for maybe the color to a separate `mobject_kwargs` dictionary which is then passed as `**mobject_kwargs` to either `SurroundingRectangle` or `Circle`.

Looking more at the implementation actually confuses me some more; why is `buff` passed to `SurroundingRectangle` but not to `Circle.surround`, where the buffer is fixed to 1? Why is the `Rectangle` class passed when in fact `SurroundingRectangle` is used? Wouldn't it make more sense to not make any distinction between the two and just do something like

```py
frame = shape(color=color, ..., **mobject_kwags).surround(mobject, buffer_factor=buff)
```

... but this doesn't really have anything to do with this PR, so I'll try to keep my confusion to myself.

Any thoughts regarding allowing to pass other keyword arguments than `z_index` too? Or are there no further relevant arguments, what do you think?

**Comment by MrDiver** [comment]
Keep in mind the effects for the opengl renderer! It doesn't support `z_index`

**Comment by chopan050** [comment]
> Keep in mind the effects for the opengl renderer! It doesn't support `z_index`

Just to piggyback on what MrDiver said :sweat: I don't really like the concept of `z_index` in general and IMO it is more intuitive to replace that with a change of the Z-coordinate in general.

But apart from that, I think that everything that the three of us said is not really in the scope of this PR, and I also like the changes.

I would like to again spark some discussion about this :eyes:

**Comment by MrDiver** [comment]
I would be on team @behackl and think we should move it and maybe also have something like a Constructor parameter for a more general Circumscribe animation? But that's just an idea.

But mainly moving the parameters would be great!

**Comment by behackl** [comment]
Closing due to inactivity.

**Pull request closed without merging**
