### PR TITLE
Speed up plotting

### PR DESCRIPTION
**Pull request by Darylgolden**
## Overview: What does this pull request change?
Lets `ParametricFunction` create an array function from the user supplied function, then applies this function to the `t_range` array directly rather than using a list comprehension. This is substantially faster than the alternative.

## Further Information and Comments
Currently, this does not work with plotting on a coordinate system yet because of `coords_to_point`. Not sure how to make it work, help would be greatly appreciated.

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by JeroSQ** [comment]
I'm happy to help. I've read your code but I don't seem to understand what the problem is. Is it that `coords_to_point` can't be passed an array of coords and return an array of points? Is that what `coords_array_to_point_array` should do?

**Comment by Darylgolden** [comment]
> I'm happy to help. I've read your code but I don't seem to understand what the problem is. Is it that `coords_to_point` can't be passed an array of coords and return an array of points? Is that what `coords_array_to_point_array` should do?

Yeah, that's the problem. I can't figure out how to arrayify `coords_to_point`.

**Comment by MrDiver** [comment]
https://github.com/ManimCommunity/manim/compare/main...MrDiver:speedup_plotting?diff=unified

## Before 
grafik
## After
grafik

I hope this helps

**Comment by MrDiver** [comment]
Probably closed by
- #2739

**Comment by Darylgolden** [comment]
Closed in favor of #2739.

**Pull request closed without merging**
