### PR TITLE
Try pytest-xdist for parallelization in tests

### PR DESCRIPTION
**Pull request by naveen521kk**
## Changelog / Overview

Possibly enabling this plugin should reduce the time spend on CI(or locally) to run tests.

## Motivation
Faster tests in CI.

## Explanation for Changes
Added `pytest-xdist` dependency with `psutil`(`pytest-xdist` needs it for finding the number of CPU available) and added `-n auto` argument to pytest.

## Testing Status
Locally it ran a bit faster.

## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by naveen521kk** [comment]
For linux: 02:17 -> 01:30
For macOS: 03:28 -> (failed)
For Windows: 03:57 -> 02:08

**Comment by naveen521kk** [comment]
Ok, something is wrong with either deprecation decorators or pytest `caplog` feature, which makes the test fail if there are more than 2 cores running the test. I can locally reproduce them on Windows also.

**Comment by naveen521kk** [comment]
Looks like this will require quite some work.

**Comment by naveen521kk** [comment]
This is ready :).

**Review by jsonvillanueva — COMMENTED** [review]
LGTM and works locally on my Windows box; however, I'm not sure why the `test_deprecation.py` *needs* a wrapper around pytest's caplog. Maybe the bug you ran into with caplog only had to do with using `warnings` instead of `logging`? The original code doesn't seem to take advantage of the `from manim import logger` statement which does use the `logging` package.

**Comment by GameDungeon** [comment]
I tried this once and things broke. Wish you better luck then.

**Comment by naveen521kk** [comment]
> I'm not sure why the test_deprecation.py needs a wrapper around pytest's caplog.

That was for telling the caplog fixture to capture only from `manim` fixture in warning level.

> Maybe the bug you ran into with caplog only had to do with using warnings instead of logging? 

Could be no idea, but if is done it should be done for the whole code base.

> The original code doesn't seem to take advantage of the from manim import logger statement which does use the logging package.

What do you mean by "original code"?

**Comment by naveen521kk** [comment]
> I tried this once and things broke. Wish you better luck then.

CI passes, things work locally for me and @jsonvillanueva. What really broke?

**Comment by GameDungeon** [comment]
I forgot, but I believe it was just some test failing. Probably just did something stupid. Also, anything that gets deprication.py to shut up is fine with me :P

**Comment by jsonvillanueva** [comment]
> What do you mean by "original code"?

I mean the original code before this PR in`test_deprecation.py` module written by @AntonBallmaier ~2 weeks ago.

> That was for telling the caplog fixture to capture only from manim fixture in warning level.

After a closer look, it seems unnecessary, but I guess it's fine... In 6c0d749, only 2 test cases actually *need* to have logging.WARNING level set (test_deprecate_class_since_and_until and test_deprecate_nested_func) which you could just set in their respective test cases instead of making all of them set to logging.WARNING. 

Also, pytest has a [default logging level](https://docs.pytest.org/en/latest/how-to/logging.html#how-to-manage-logging) of logging.WARNING, so somewhere else the logging level is being set which seems unintended. I'll approve since this is only a minor nuance/unrelated to this PR.

**Review by jsonvillanueva — APPROVED** [review]

**Comment by naveen521kk** [comment]
Gonna merge this after fixing conflicts.

**Pull request merged**
