### PR TITLE
Rewrite VMobject stroke shaders

### PR DESCRIPTION
**Pull request by eulertour**
## Changelog / Overview

Rewrite VMobject stroke shaders to be compatible with projection matrices

## Motivation

Rewrites VMobject stroke shaders to be compatible with projection matrices, which makes it much easier to control their positioning.

## Explanation for Changes

Updates vectorized_mobject_rendering.py, which contains functions to render vectorized mobject stroke using the algorithms [here](https://www.shadertoy.com/view/ltXSDB) and [here](https://www.shadertoy.com/view/llcfR7). Also adds a --use_projection_stroke_shaders flag to control when the new shaders are used.

[Documentation Reference](https://manimce--####.org.readthedocs.build)

## Testing Status

Tested with the following scene and the `--use_projection_stroke_shaders` flag
```py
class TextTest(Scene):
    def construct(self):
        import string
        text = OpenGLText(string.ascii_lowercase, stroke_width=4, stroke_color=BLUE).scale(4)
        text2 = OpenGLText(string.ascii_uppercase, stroke_width=4, stroke_color=BLUE).scale(4).next_to(text, DOWN)
        self.add(text, text2)
        self.interactive_embed()
```

## Further Comments

Joints are not implemented yet, so rendering with an opacity other than 1 will show artifacts where curves join.

Depends on #1679 

## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [x] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [x] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by eulertour** [comment]
Depends on #1679

**Comment by Darylgolden** [comment]
When I added this scene to `example_scenes/opengl.py`:

```py
class Square(Scene):
    def construct(self):
        a = OpenGLSquare()
        self.play(Create(a))
```

I get this traceback:

```
manim -p --renderer=opengl --use_projection_stroke_shaders --disable_caching example_scenes\opengl.py Square
Manim Community v0.6.0

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\Daryl\manim-dev\manim\manim\cli\render\commands.py:131 in render                        │
│                                                                                                  │
│   128 │   │   │   │   │   scene_classes = scene_classes_from_file(file)                          │
│   129 │   │   │   │   │   SceneClass = scene_classes[0]                                          │
│   130 │   │   │   │   │   scene = SceneClass(renderer)                                           │
│ ❱ 131 │   │   │   │   │   status = scene.render()                                                │
│   132 │   │   │   │   │   if status:                                                             │
│   133 │   │   │   │   │   │   continue                                                           │
│   134 │   │   │   │   │   else:                                                                  │
│                                                                                                  │
│ C:\Users\Daryl\manim-dev\manim\manim\scene\scene.py:214 in render                                │
│                                                                                                  │
│    211 │   │   """                                                                               │
│    212 │   │   self.setup()                                                                      │
│    213 │   │   try:                                                                              │
│ ❱  214 │   │   │   self.construct()                                                              │
│    215 │   │   except EndSceneEarlyException:                                                    │
│    216 │   │   │   pass                                                                          │
│    217 │   │   except RerunSceneException as e:                                                  │
│                                                                                                  │
│ C:\Users\Daryl\manim-dev\manim\example_scenes\opengl.py:510 in construct                         │
│                                                                                                  │
│   507 class Square(Scene):                                                                       │
│   508 │   def construct(self):                                                                   │
│   509 │   │   a = OpenGLSquare()                                                                 │
│ ❱ 510 │   │   self.play(Create(a))                                                               │
│   511                                                                                            │
│                                                                                                  │
│ C:\Users\Daryl\manim-dev\manim\manim\scene\scene.py:866 in play                                  │
│                                                                                                  │
│    863 │   │   │   return np.max([animation.run_time for animation in animations])               │
│    864 │                                                                                         │
│    865 │   def play(self, *args, **kwargs):                                                      │
│ ❱  866 │   │   self.renderer.play(self, *args, **kwargs)                                         │
│    867 │                                                                                         │
│    868 │   def wait(self, duration=DEFAULT_WAIT_TIME, stop_condition=None):                      │
│    869 │   │   self.play(Wait(run_time=duration, stop_condition=stop_condition))                 │
│                                                                                                  │
│ C:\Users\Daryl\manim-dev\manim\manim\utils\caching.py:58 in wrapper                              │
│                                                                                                  │
│   55 │   │   │   "List of the first few animation hashes of the scene: %(h)s",                   │
│   56 │   │   │   {"h": str(self.animations_hashes[:5])},                                         │
│   57 │   │   )                                                                                   │
│ ❱ 58 │   │   func(self, scene, *args, **kwargs)                                                  │
│   59 │                                                                                           │
│   60 │   return wrapper                                                                          │
│   61                                                                                             │
│                                                                                                  │
│ C:\Users\Daryl\manim-dev\manim\manim\renderer\cairo_renderer.py:46 in wrapper                    │
│                                                                                                  │
│    43 │   def wrapper(self, scene, *args, **kwargs):                                             │
│    44 │   │   self.animation_start_time = time.time()                                            │
│    45 │   │   self.file_writer.begin_animation(not self.skip_animations)                         │
│ ❱  46 │   │   func(self, scene, *args, **kwargs)                                                 │
│    47 │   │   self.file_writer.end_animation(not self.skip_animations)                           │
│    48 │   │   self.num_plays += 1                                                                │
│    49                                                                                            │
│                                                                                                  │
│ C:\Users\Daryl\manim-dev\manim\manim\renderer\opengl_renderer.py:357 in play                     │
│                                                                                                  │
│   354 │   │   # TODO: Handle data locking / unlocking.                                           │
│   355 │   │   if scene.compile_animation_data(*args, **kwargs):                                  │
│   356 │   │   │   scene.begin_animations()                                                       │
│ ❱ 357 │   │   │   scene.play_internal()                                                          │
│   358 │                                                                                          │
│   359 │   def clear_screen(self):                                                                │
│   360 │   │   window_background_color = color_to_rgba(config["background_color"])                │
│                                                                                                  │
│ C:\Users\Daryl\manim-dev\manim\manim\scene\scene.py:969 in play_internal                         │
│                                                                                                  │
│    966 │   │   for t in self.time_progression:                                                   │
│    967 │   │   │   self.update_to_time(t)                                                        │
│    968 │   │   │   if not skip_rendering and not self.skip_animation_preview:                    │
│ ❱  969 │   │   │   │   self.renderer.render(self, t, self.moving_mobjects)                       │
│    970 │   │   │   if self.stop_condition is not None and self.stop_condition():                 │
│    971 │   │   │   │   self.time_progression.close()                                             │
│    972 │   │   │   │   break                                                                     │
│                                                                                                  │
│ C:\Users\Daryl\manim-dev\manim\manim\renderer\opengl_renderer.py:365 in render                   │
│                                                                                                  │
│   362 │   │   self.window.swap_buffers()                                                         │
│   363 │                                                                                          │
│   364 │   def render(self, scene, frame_offset, moving_mobjects):                                │
│ ❱ 365 │   │   self.update_frame(scene)                                                           │
│   366 │   │                                                                                      │
│   367 │   │   if self.skip_animations:                                                           │
│   368 │   │   │   return                                                                         │
│                                                                                                  │
│ C:\Users\Daryl\manim-dev\manim\manim\renderer\opengl_renderer.py:385 in update_frame             │
│                                                                                                  │
│   382 │   │   self.refresh_perspective_uniforms(scene.camera)                                    │
│   383 │   │                                                                                      │
│   384 │   │   for mobject in scene.mobjects:                                                     │
│ ❱ 385 │   │   │   self.render_mobject(mobject)                                                   │
│   386 │   │                                                                                      │
│   387 │   │   view_matrix = scene.camera.get_view_matrix(format=False)                           │
│   388 │   │   opengl_view_matrix = opengl.matrix_to_shader_input(view_matrix)                    │
│                                                                                                  │
│ C:\Users\Daryl\manim-dev\manim\manim\renderer\opengl_renderer.py:277 in render_mobject           │
│                                                                                                  │
│   274 │   │   │   │   render_opengl_vectorized_mobject_fill(self, mobject)                       │
│   275 │   │   │                                                                                  │
│   276 │   │   │   if config["use_projection_stroke_shaders"] and mobject.has_stroke():           │
│ ❱ 277 │   │   │   │   render_opengl_vectorized_mobject_stroke(self, mobject)                     │
│   278 │   │                                                                                      │
│   279 │   │   shader_wrapper_list = mobject.get_shader_wrapper_list()                            │
│   280                                                                                            │
│                                                                                                  │
│ C:\Users\Daryl\manim-dev\manim\manim\renderer\vectorized_mobject_rendering.py:290 in             │
│ render_opengl_vectorized_mobject_stroke                                                          │
│                                                                                                  │
│   287 │   shader.set_uniform("manim_unit_normal", tuple(-mobject.data["unit_normal"][0]))        │
│   288 │                                                                                          │
│   289 │   vbo = renderer.context.buffer(stroke_data.tobytes())                                   │
│ ❱ 290 │   vao = renderer.context.simple_vertex_array(                                            │
│   291 │   │   shader.shader_program,                                                             │
│   292 │   │   vbo,                                                                               │
│   293 │   │   *stroke_data.dtype.names,                                                          │
│                                                                                                  │
│ C:\Users\Daryl\AppData\Local\pypoetry\Cache\virtualenvs\manim-WZ_QM4hs-py3.9\lib\site-packages\m │
│ oderngl\context.py:1201 in simple_vertex_array                                                   │
│                                                                                                  │
│   1198 │   │   if type(buffer) is list:                                                          │
│   1199 │   │   │   raise SyntaxError('Change simple_vertex_array to vertex_array')               │
│   1200 │   │                                                                                     │
│ ❱ 1201 │   │   content = [(buffer, detect_format(program, attributes)) + attributes]             │
│   1202 │   │   return self.vertex_array(program, content, index_buffer, index_element_size)      │
│   1203 │                                                                                         │
│   1204 │   def program(self, *, vertex_shader, fragment_shader=None, geometry_shader=None,       │
│                                                                                                  │
│ C:\Users\Daryl\AppData\Local\pypoetry\Cache\virtualenvs\manim-WZ_QM4hs-py3.9\lib\site-packages\m │
│ oderngl\program.py:241 in detect_format                                                          │
│                                                                                                  │
│   238 │   │   else:                                                                              │
│   239 │   │   │   raise ValueError('invalid format mode: {}'.format(mode))                       │
│   240 │                                                                                          │
│ ❱ 241 │   return ' '.join('%d%s' % fmt(program[a]) for a in attributes)                          │
│   242                                                                                            │
│                                                                                                  │
│ C:\Users\Daryl\AppData\Local\pypoetry\Cache\virtualenvs\manim-WZ_QM4hs-py3.9\lib\site-packages\m │
│ oderngl\program.py:241 in <genexpr>                                                              │
│                                                                                                  │
│   238 │   │   else:                                                                              │
│   239 │   │   │   raise ValueError('invalid format mode: {}'.format(mode))                       │
│   240 │                                                                                          │
│ ❱ 241 │   return ' '.join('%d%s' % fmt(program[a]) for a in attributes)                          │
│   242                                                                                            │
│                                                                                                  │
│ C:\Users\Daryl\AppData\Local\pypoetry\Cache\virtualenvs\manim-WZ_QM4hs-py3.9\lib\site-packages\m │
│ oderngl\program.py:76 in __getitem__                                                             │
│                                                                                                  │
│    73 │   │   │   # Still when writing byte data we need to use the `write()` method             │
│    74 │   │   │   program['color'].write(buffer)                                                 │
│    75 │   │   """                                                                                │
│ ❱  76 │   │   return self._members[key]                                                          │
│    77 │                                                                                          │
│    78 │   def __setitem__(self, key, value):                                                     │
│    79 │   │   """Set a value of uniform or uniform block                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: 'previous_curve'
```

**Comment by eulertour** [comment]
@Darylgolden That error happens when you try to pass data to a shader that doesn't take that data, which is complicated by the fact that the shaders will optimize out values that aren't used. For my computer it works to [read the value and do nothing](https://github.com/ManimCommunity/manim/pull/1680/commits/882c5d4b1114b54a14b8d63b71b2999bb434360d#diff-3882484ae1a34d9eace8c608b703f415fde0961b798e0977a072b1b0856b8977L78-L84) but your GPU(?) seems to be smarter than that. But it might work better now.

**Comment by Darylgolden** [comment]
> 
> 
> @Darylgolden That error happens when you try to pass data to a shader that doesn't take that data, which is complicated by the fact that the shaders will optimize out values that aren't used. For my computer it works to [read the value and do nothing](https://github.com/ManimCommunity/manim/pull/1680/commits/882c5d4b1114b54a14b8d63b71b2999bb434360d#diff-3882484ae1a34d9eace8c608b703f415fde0961b798e0977a072b1b0856b8977L78-L84) but your GPU(?) seems to be smarter than that. But it might work better now.

It works now! And on Intel too!

**Review by behackl — APPROVED** [review]
Tested, works like a charm (I don't get any weird fragments here, in contrast to #1679 when rendering with just the new stroke shaders). I essentially have the same comment as for #1679, I'm fine merging this at any point.

Thank you for your efforts!

**Pull request closed without merging**
