### PR TITLE
Removed BezierSpline from the example gallery

### PR DESCRIPTION
**Pull request by kolibril13**
## Changelog / Overview
I removed my BezierSpline example from the gallery.
It looks nice, but the code is maybe a bit too complicated to be included in this section, which gives the "first impression" of manim and should therefore not be too difficult.
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [x] My new functions/classes either have a docstring or are private
- [x] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [x] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by WampyCakes** [comment]
Instead of completely removing it, should it just be moved to document something like the `add_cubic_bezier` method?

**Comment by behackl** [comment]
> Instead of completely removing it, should it just be moved to document something like the `add_cubic_bezier` method?

I think it would be better to remove it, and to add a simpler example to `VMobject.add_cubic_bezier_curve` or so. While it is nice to look at, I agree that the example is a bit too complex for what it effectively does.

**Review by behackl — APPROVED** [review]

**Review by WampyCakes — APPROVED** [review]
I can agree with that.

**Comment by GameDungeon** [comment]
I agree, It seemed pointless and just intimidated me when I was first starting.

**Pull request merged**
