### PR TITLE
Made the default arrowhead size for :class:`~.Arrow3D` smaller

### PR DESCRIPTION
**Pull request by Iced-Tea3**
## Motivation

The default sizes for Arrow 3D looks uncanny as explained in #1684 . I do understand it is a matter of opinion, but I find it unlikely anyone uses the default.
## Explanation for Changes

[Documentation Reference](https://manimce--1693.org.readthedocs.build/en/1693/reference/manim.mobject.three_dimensions.Arrow3D.html)

## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by WampyCakes** [comment]
[Proposed look](https://manimce--1693.org.readthedocs.build/en/1693/reference/manim.mobject.three_dimensions.Arrow3D.html#manim.mobject.three_dimensions.Arrow3D)
[Current look](https://docs.manim.community/en/stable/reference/manim.mobject.three_dimensions.Arrow3D.html#manim.mobject.three_dimensions.Arrow3D)

I like the proposed look much better, but I think it might be a wee bit small. I think the current one is far too large, but it's hard to see the exact shape of the proposed look IMO. Also, comparing it to the size of the arrows on the ThreeDAxes makes it look a little out of proportion (not saying they should be the same size).

**Review by WampyCakes — CHANGES_REQUESTED** [review]
I see that you deleted the test data. You will need to replace it with new data by regenerating it as described [here](https://docs.manim.community/en/stable/contributing/testing.html).

**Comment by Iced-Tea3** [comment]
>  I think it might be a bit small.

Hm.. i do see that.. i'l try and adjust again.

> I see that you deleted the test data

I already replaced it. Otherwise CI test failed.

**Comment by WampyCakes** [comment]
Um, GitHub doesn't show me that you added any new test data :eyes:

**Comment by Iced-Tea3** [comment]
I'll try again

**Comment by Iced-Tea3** [comment]
I changed the test file, but it only comes up as removing it.. 🧐

**Review by Darylgolden — APPROVED** [review]
It doesn't seem like the binary data was removed, it just shows that it changed. Anyways, the new size LGTM

**Review by WampyCakes — APPROVED** [review]

**Comment by WampyCakes** [comment]
I will merge it once the checks all pass again. It seems rather odd that GitHub isn't showing what you did correctly. I would expect it to say the file was deleted and added again OR changed. Instead, it only shows me that it was removed. Though, I can see where you added it in a commit. I will double check `main` after this is merged, but I think it'll work fine.

**Pull request merged**
