### PR TITLE
Fix pre-commit pipeline

### PR DESCRIPTION
**Pull request by kolibril13**
## Motivation
Flake8 is currently checking all files in a pr, where it only should check the changed files.
Maybe this pr will fix this problem

## Checklist
- [ ] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [ ] I have written a descriptive PR title (see top of PR template for examples)
- [ ] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by kolibril13** [comment]
I think I found now a satisfying solution.
It was not possible for me to make pre-commit/flake8 to only consider the changed files (note, for isort and black, this is working).
But on my local machine, there were no errors.
So I decided to add a "skip" option only for github:
```
ci:
    skip: [flake8]
```
That only skips the flake8 pre-commit hook on github. 
Locally it is still there, as I tested with this example:
```py
def notGoodFunction(  bad ,styling, is_t, bad):
    wow = None
    if wow == True:
       return True
    else:
       return "A" + "Super long line that flake probably won't like" + "at" + "    all"
``` 
(thanks to @jsonvillanueva )
Unbenannt
And now the good part:
As we have flake8 checking already in our current git workflow, we don't need it on the git pre-commit.
With this said, I think we can then remove the isort and black format check from github, as pre-commit takes care of it. (Maybe we wait one week to make sure that no other bugs are there.)

**Comment by behackl** [comment]
Is there a disadvantage to simply fixing the files which make pre-commit.ci currently fail and removing our separate black / flake8 / isort checks in the pipeline?

Fewer of our own custom setup pipelines also means fewer breaking points.

**Comment by kolibril13** [comment]
> simply fixing the files which make pre-commit.ci currently fail

If it was easy to fix these lines, then I would totally with you to remove flake8 from the custom pipeline.
Unfortunately, I am not able to find this line.
Also, the documentation about the flake8 is not very large: https://flake8.pycqa.org/en/latest/user/using-hooks.html
As this current solution is working properly, I would stick to it.
But if someone has an idea to fix it, we can still try to make it work.
Or we open an issue at https://github.com/pre-commit/pre-commit , because as can be seen in the screenshot above, the local behaviour is different than the GitHub behaviour.

**Comment by jsonvillanueva** [comment]
I don't think the solution to this is to disable flake8 with pre-commit.ci -- instead, since pre-commit.ci is supposedly faster than GitHub Actions/workflows, I'd rather disable the style checking workflows under our repos `.github` directory removed/disabled.

**Comment by behackl** [comment]
I also prefer the solution from #1278 over this here.

**Pull request closed without merging**
