### PR TITLE
Removed unwanted parameters in geometry

### PR DESCRIPTION
**Pull request by Nikhil0504**
## Changelog / Overview

Removed `anchors_span_full_range`, `close_new_points`, `anchors_span_full_range`, `dash_spacing `, `preserve_tip_size_when_scaling`, `mark_paths_closed ` and `close_new_points `

## Motivation

These changes just lessen the confusion of the parameters of the geometry.
## Explanation for Changes

[Documentation Reference](https://manimce--1552.org.readthedocs.build)

## Testing Status

All tests passes locally.
## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [x] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by hydrobeam** [comment]
You should also check that functions which involve these parameters are removed. For example: `calculate_positive_space_ratio`  under `DashedLine`

**Comment by WampyCakes** [comment]
I do not feel comfortable merging this until people with knowledge of the original uses of these parameters discuss this. For example, I think that instead of removing `dash_spacing`, we should implement it for real. I suspect that this (re-implementing rather than removing) may be the best case with other parameters.

**Comment by Nikhil0504** [comment]
> I do not feel comfortable merging this until people with knowledge of the original uses of these parameters discuss this. For example, I think that instead of removing `dash_spacing`, we should implement it for real. I suspect that this (re-implementing rather than removing) may be the best case with other parameters.

I am fine with re-implementation for these parameters but if they were to be reimplemented we would have had some comments or discussions about them.
Moreover `anchors_span_full_range`, `close_new_points`, `mark_paths_closed` was added by Grant but wasn't used anywhere but the `CONFIG`
`preserve_tip_size_when_scaling` was also added by Grant but was removed again in `d489b5df5c77a597a71c4fd89597e3d48d5b4d9a`

`dash_spacing` is being used so I'll just revert back that.

I'll also check for other parameters in `geometry.py` as see if I can clean it up.

**Review by eulertour — APPROVED** [review]

**Comment by behackl** [comment]
> I do not feel comfortable merging this until people with knowledge of the original uses of these parameters discuss this. For example, I think that instead of removing `dash_spacing`, we should implement it for real. I suspect that this (re-implementing rather than removing) may be the best case with other parameters.

I think it is fine to have all of them removed by now. @eulertour might have an idea of what some of these parameters did at some point, but he approved this already -- and anyways, keeping them around for the sake of making them functional again eventually seems like unnecessary clutter to me.

**Review by behackl — APPROVED** [review]

**Pull request merged**
