### PR TITLE
Removed -s / --save_last_frame flag from CLI arguments

### LINKED ISSUE #3174: `--save_last_frame` appears twice in options
## Description of bug / unexpected behavior

When using `manim render --help`, you can see `--save_last_frame` appearing twice, once marked as deprecated:

```
  -s, --save_last_frame
...
  -s, --save_last_frame          Save last frame as png (Deprecated).
```

This is also visible i n [reference manual](https://docs.manim.community/en/stable/guides/configuration.html#:~:text=webm%7Cmov%5D%0A%20%20%2Ds%2C%20%2D%2D-,save_last_frame,-%2Dq%2C%20%2D%2Dquality%20%5Bl).

## Expected behavior

The option appears exactly once

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```bash
> manim render --help | grep 'save_last_frame'
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g., Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

## Additional comments

This is probably a code cleanup issue, as you can clearly see the option being declared twice in [`render_options.py`](https://github.com/ManimCommunity/manim/blob/main/manim/cli/render/render_options.py):

```py
# line 61
    option("-s", "--save_last_frame", is_flag=True, default=None),
# line 125:131
    option(
        "-s",
        "--save_last_frame",
        default=None,
        is_flag=True,
        help="Save last frame as png (Deprecated).",
    ),
```

I can create a PR to remove one of them, just need info which one should be removed - the first one without help, or the second one marking it deprecated (easiest to just remove the "deprecated" keyword as it's formated nicely, and get rid of the first one).

Should I also report it as a bug in [cloup](https://github.com/janLuke/cloup) that it doesn't check for duplicates?

### PR DESCRIPTION
**Pull request by Gixtox**
## Motivation and Explanation: Why and how do your changes improve the library?

Remove deprecated functionality and make the codebase cleaner. Resolve #3174

## Links to added or changed documentation pages

https://manimce--3528.org.readthedocs.build/en/3528/

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by behackl** [comment]
Hey there! Thank you very much for your efforts!

Regrettably, I realized that the way I wrote the comment on #3174 leaves little room for understanding it in the way I meant it. I actually did not mean that the functionality and general use of the `-s` / `--save_last_frame` CLI flag should be removed (and practically, we have never really deprecated the usage) -- but rather that the duplicate documentation of it should be removed.

Sorry, I realize that it really is impossible to read it like that if you don't already know what I had meant. This actually also simplifies the change that has to be made significantly: it's basically just removing the second option in `render_options.py` and adding the documentation to the first one.

Would you still be interested in carrying out this change?

(Again, sorry for my unclear wording!)

**Comment by Gixtox** [comment]
@behackl that's quite alright! I actually stared at the comment for a while trying to determine whether or not it meant to completely remove the functionality as I did. I'll be sure to ask questions if I'm unsure in the future! I'm hoping to help the project more so this confusion gave me nice intro to the codebase. 

I'll be happy to make the change! It sounds like a quick cut and paste. Should I remove the `(Deprecated)` from the documentation?

**Comment by behackl** [comment]
Editing this PR here is fine, just as you did -- perfect!

Yes, the "(Deprecated)" can for sure be removed, and the help text could be made a little more verbose. Perhaps along the lines of `"Only renders and saves the last frame of a scene as a PNG image."`. Do you think that would be better?

**Comment by Gixtox** [comment]
That's a good call and I like that wording. Change has been made.

**Comment by Gixtox** [comment]
@behackl Since I need to wait for a final review, should I hold off on merging the latest changes from main until the final review is finished?

**Review by behackl — APPROVED** [review]
Looks great, thanks for your efforts -- and sorry for the wait!

**Pull request merged**
