### PR TITLE
Added 3D shape Cuboid with variable length, breadth, height and faces to include

### PR DESCRIPTION
**Pull request by manisar2**
## Added 3D shape Cuboid with variable length, breadth, height and faces to include

Added 3D shape Cuboid with variable length, breadth, height and faces to include.

## Motivation

A frequently used shape - Cuboid - will add to the usefulness of manim.
Just the way manim already has Rectangle and Square, having Cuboid along with the already-present Cube should be useful.

## Explanation for Changes

These changes will let the user have another useful shape - Cuboid - at their disposal.

[Documentation Reference](https://manimce--####.org.readthedocs.build)

## Testing Status

Successful. A cuboid was added using non-default arguments.

## Checklist
- [X] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [X] I have written a descriptive PR title (see top of PR template for examples)
- [X] I have written a changelog entry for the PR or deem it unnecessary
- [X] My new functions/classes either have a docstring or are private
- [X] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [X] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by Darylgolden** [comment]
Hi @manisar2, thank you for your PR! Actually, the unfortunately misnamed `Prism` already does this. However, there is consensus in the Discord to rewrite `Cuboid` and `Cube` to inherit from `Polyhedron`. Since `Polyhedron` takes in a list of vertex coordinates and face lists, I think it makes sense to make `Cuboid` inherit from `Polyhedron` and `Cube` to inherit from `Cuboid`. Can you rewrite your PR to focus on this instead?

**Comment by manisar2** [comment]
Thanks for the info. Understood and noted.
I'll join discord and bring myself on the same page as others in this regard.
I'm not sure if it should be me closing this PR, or one of the approvers does that.
Please do as appropriate.

I'll start looking into the rewrite(s) you mentioned, and will definitely be happy to contribute in my capacity.
Thanks for maintaining this wonderful tool!

**Comment by Darylgolden** [comment]
I don't think we need to close this PR since the changes are roughly in the same vein anyways, unless you want to.

**Comment by manisar2** [comment]
No I would not 🙂.

**Comment by behackl** [comment]
I'll mark this PR as a draft until it is ready to be reviewed.

**Comment by manisar2** [comment]
@behackl Sorry for the dumb question as a first time contributor, but is there an action item on me (PR author) for making this PR Ready for review?
I see this button - Ready for review - and am not sure if I should click on it.
I had already done all my checks before creating the PR, so it is ready from my side thought.

**Comment by behackl** [comment]
> @behackl Sorry for the dumb question as a first time contributor, but is there an action item on me (PR author) for making this PR Ready for review?
> I see this button - Ready for review - and am not sure if I should click on it.
> I had already done all my checks before creating the PR, so it is ready from my side though.

The discussion you had with @Darylgolden above read like you were looking into changing the proposed implementation (which made sense to me given that Prism already has this functionality).

Can you and/or @Darylgolden clarify what the result of your discussion above is/was?

**Comment by Darylgolden** [comment]
Yep, the result is that @manisar2 should change their implementation. From the commit history however, it doesn't seem like you've done so. Perhaps you've forgotten to commit/push?

**Comment by manisar2** [comment]
Ok, got it.
No, I haven't changed the implementation yet.
Thanks for the clarification.

**Comment by Darylgolden** [comment]
@manisar2 Hi, what's the status of this PR? Are you still interested in doing this?

**Comment by manisar2** [comment]
Hi, I got caught up in some urgent work, and it doesn't seem I'll be off the hook for next couple of months.
I'm very much interested, but if the delay is not acceptable, please advise on what I should do of this in-draft PR.
Please accept my apologies for leaving it in limbo.

**Comment by Darylgolden** [comment]
I think switching the implementation of cubes and cuboids is fairly important, and if you're not able to work on it for a "couple of months", it's pretty likely that I/someone else will make the changes before then. Therefore, I'll close this PR now; if you find the time to work on it before anyone else has, then feel free to reopen it. Thank you for your interest in contributing to Manim!

**Comment by manisar2** [comment]
Thanks much for your time and advice, and once again for your contribution to manim!

**Pull request closed without merging**
