### PR TITLE
Delete deprecated classes and functions `until 0.12.0`

### PR DESCRIPTION
**Pull request by kolibril13**
In VS Code, I searched everywhere for @deprecated and deleted all functions/classes that had the tag "until="v0.12.0",

### CODE REVIEW

**Comment by behackl** [comment]
> Make sure to remove the imports too 👍. Also, items with `until="v0.12.0"` should be deleted next release

Do you mean the imports of the `deprecated` decorator, @hydrobeam?

**Review by christopher-besch — APPROVED** [review]
LGTM

**Review by Darylgolden — CHANGES_REQUESTED** [review]
Can you modify this so that only classes and functions until 0.11 are removed?

**Comment by christopher-besch** [comment]
> Can you modify this so that only classes and functions until 0.11 are removed?

Wait, doesn't 'until="v0.12.0"' mean v0.11.x is the last one with that function?

**Comment by Darylgolden** [comment]
If I'm not wrong, it means 0.12 is the last version with those features.

**Comment by christopher-besch** [comment]
image
And what about all these?
Most of them are deprecated parameters.

**Comment by Darylgolden** [comment]
Yeah, the 0.11 ones should be removed too. Tbh it might be easier to create a new PR removing the 0.11 ones, then merging this PR after the release.

**Comment by kolibril13** [comment]
> Yeah, the 0.11 ones should be removed too. Tbh it might be easier to create a new PR removing the 0.11 ones, then merging this PR after the release.

True, I just made this a draft pr and will make a second pr for the until 0.11.0 right now.

**Comment by hydrobeam** [comment]
@kolibril13 A lot of the 0.11 deprecations are `font_size` related, and require a little more work to handle, I can take care of it if you'd like (since I'm the one who deprecated them 😅)

**Comment by kolibril13** [comment]
> @kolibril13 A lot of the 0.11 deprecations are `font_size` related, and require a little more work to handle, I can take care of it if you'd like (since I'm the one who deprecated them 😅)

Thanks for your offer, I just made a pull request for that,  https://github.com/ManimCommunity/manim/pull/2245 I hope i did it the right way. If not, feel free to commit directly to my branch ;)

**Comment by Darylgolden** [comment]
@kolibril13 Is this PR ready? Otherwise, are you planning to finish working on it before the next release?

**Comment by kolibril13** [comment]
> @kolibril13 Is this PR ready? Otherwise, are you planning to finish working on it before the next release?

It's not yet ready, and currently, I don't have time to work on this. Sorry!

**Pull request closed without merging**
