### PR TITLE
Handle user-defined centers for Wiggle animation

### PR DESCRIPTION
**Pull request by dmillard**
## Overview: What does this pull request change?

Fixes a minor bug in the Wiggle animation where user-defined centers are ignored.

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Review by Kiran-Raj-Dev — APPROVED** [review]

**Comment by Kiran-Raj-Dev** [comment]
Thank you for your contribution!

**Review by behackl — APPROVED** [review]
Thanks, indeed!

Ideally, a small test to check that the functionality now works as expected would have been nice, could you add one? It is fine if you don't want to, then one of us can take care of it -- just let us briefly know!

**Comment by dmillard** [comment]
I don't know enough about your testing methodologies to do this now, but I'd be happy to try with some more information.

I see the file https://github.com/ManimCommunity/manim/blob/main/tests/test_graphical_units/test_indication.py has some very basic tests for `Wiggle`, but I don't know if this is the right place to test user defined centers. I'm also not sure what a `@frames_comparison` test really does.

**Comment by behackl** [comment]
Great!

> I see the file https://github.com/ManimCommunity/manim/blob/main/tests/test_graphical_units/test_indication.py has some very basic tests for `Wiggle`, but I don't know if this is the right place to test user defined centers. I'm also not sure what a `@frames_comparison` test really does.

To answer your question regarding `@frames_comparison` first: with this decorator, our test framework is made aware of the fact that it should render a scene with the decorated function as the `construct` method, and then compare the output to control data (the `.npz` files in the `control_data` directory).

I don't think, however, that a frame comparison test actually is necessary here -- a normal test that instantiates `Wiggle` with some custom about poitns and then checks that the two methods you fixed are working as intended should be fine. Just add a function

```py
def test_Wiggle_custom_about_points():
   wiggle_animation = Wiggle(...)
   assert wiggle_animation.bla() == ...
```

Feel free to give it a shot, I'm happy to help if you have further questions! :-)

**Comment by dmillard** [comment]
Thanks for the pointers! I've added the test.

**Review by behackl — APPROVED** [review]
Great! :-)

**Pull request merged**
