### PR TITLE
TRY2: Fixing reference inheritance graphs

### PR DESCRIPTION
**Pull request by kolibril13**
Same as https://github.com/ManimCommunity/manim/pull/2056, but this time trying to revert the reference.rst file back to the status it was, when all was working, as in 
https://raw.githubusercontent.com/ManimCommunity/manim/v0.8.0/docs/source/reference.rst

### CODE REVIEW

**Comment by kolibril13** [comment]
see here: https://manimce--2119.org.readthedocs.build/en/2119/reference.html

**Comment by behackl** [comment]
I don't think this is a good approach to fix the problem: it also brings back the old (unordered) structure in the sidebar of the reference manual and effectively just reverts #1778.

I think this can be fixed without destroying the new structure by moving them to some `rst` file in `docs/source` (like `reference.rst`), as mentioned in #2056.

**Comment by kolibril13** [comment]
I've moved them, but now there are no links at all left:
https://manimce--2119.org.readthedocs.build/en/2119/ref_mobjects.html
Also, the whole reference API is not build:
image
I guess some path has to be adjusted, of which I don't know where to make the change.

**Comment by behackl** [comment]
I meant it in a different way. See #2122.

**Comment by behackl** [comment]
Closed via #2122.

**Comment by kolibril13** [comment]
Thanks for making the new pr!

**Pull request closed without merging**
