### PR TITLE
docs: add localized with Crowdin badge

### PR DESCRIPTION
**Pull request by naveen521kk**
## Overview: What does this pull request change?
When contacting them about adding their logo to the sponsored section on our homepage they asked to add this badge instead.

## Links to added or changed documentation pages

https://manimce--2352org.readthedocs.build/en/2352

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by hydrobeam** [comment]
Maybe the image should be centered? It looks a little off here:
image

**Comment by naveen521kk** [comment]
I will see how that can be done soon.

**Comment by Darylgolden** [comment]
Perhaps we can just add it to our README?

**Comment by naveen521kk** [comment]
> Perhaps we can just add it to our README?

We aren't translating the README, right? I think it makes more sense to have it on the docs page since we are translating that one.

**Comment by Darylgolden** [comment]
> > Perhaps we can just add it to our README?
> 
> We aren't translating the README, right? I think it makes more sense to have it on the docs page since we are translating that one.

Well the project is localized with Crowdin, so it wouldn't be out of place. I think it looks weird at the bottom of the docs index.

**Comment by naveen521kk** [comment]
> Well the project is localized with Crowdin, so it wouldn't be out of place. I think it looks weird at the bottom of the docs index.

Hmm, where in the readme @Darylgolden? I kinda accept it looks weird in the README.

**Comment by behackl** [comment]
I feel it is perfectly reasonable to have it in the documentation.

**Comment by behackl** [comment]
Not my favourite solution right now, but it is better than nothing. Ideally, I'd like to have the logo in the README and ta reference to Crowdin in the documentation footer – the latter doesn't seem to be quite so straightforward and would require that we modify our Sphinx theme manually a bit.

My suggestion: merge this as-is, so that Crowdin is mentioned somewhere (semi-prominent) in our documentation, then think about further improvements later on.

**Comment by naveen521kk** [comment]
> My suggestion: merge this as-is, so that Crowdin is mentioned somewhere (semi-prominent) in our documentation, then think about further improvements later on.

In which case I'm marking this PR as ready.

**Review by Darylgolden — APPROVED** [review]
I think it's fine for now.

**Pull request merged**
