### PR TITLE
Simplifying Manim's color handling

### PR DESCRIPTION
**Pull request by ludwigjo**
## Overview: What does this pull request change?
This PR improves the color handling by removing uses of the `Colors` class and replace usage of the Enums with color constants as specified in #2451 . At this point, a deprecation warning is raised when trying to use the `Colors` class using `manim.utils.deprecation`.

Some of the functions previously defined in `color.py` that has existing functionality in the `colour` module has also been replaced.

For instance:
`rgb_to_hex()` has been replaced by `rgb2hex()`.

## Motivation and Explanation: Why and how do your changes improve the library?

The overall goal is to simplify the use of color by standardizing the approach as stated in #2451 . By deprecating the use of the Enums and providing a way of using the constants in a similar way, we're creating a standard for how colors should be used. 

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by Darylgolden** [comment]
Looks like these changes broke some part of `BarChart`, as can be seen from the docbuild. Can you fix it?

**Comment by Darylgolden** [comment]
I've converted this into a draft for now. Feel free to unconvert once the docbuild passes, and let us know if you need any help.

**Comment by Darylgolden** [comment]
Hello, are you planning to continue working on this?

**Comment by MrDiver** [comment]
I think i will go about my way doing this in a few days

**Pull request closed without merging**
