### PR TITLE
Implementation of VideoMobject 

### PR DESCRIPTION
**Pull request by kolibril13**
This is an VideoMobject, that gives the opportunity to put videos into manim scenes.
The following thing is happening:
1.  The video is added to a scene by : 
```py
vid = VideoMobject(file_directory)
self.add(vid.image_canvas)
```
2. VideoMoject calls init_frames, a function that breaks the video apart into all their frames and saves them as png files.
3. You can start the video with `vid.play()` in the scene file, which attaches an updater to the image canvas. 
4. When the imported video is done, frame_updater realizes that and staies at the last frame.

### CODE REVIEW

**Comment by kolibril13** [comment]
In this pull request, there is furthermore a file "FrameCounterVideo" that creates an example video that displays some numbers.
This can be used to run ExampleVideoMobject, where the video can be a part of the scenes and where you can try eg.
```py
vid.play()
self.wait(1)
vid.pause()
```
Some thoughts what can be changed in order to make this even better:
* Add functionality so that the move, shift, and scale functions are applicable.
* Maybe find a better way then extracting each frame from a video and saving it to png, because this can consume quite a lot of memory.
* Finding a place, where we place the file VideoMobject in manim.
* Maybe finding a way, to delete all the single frames after manim is cloesed.

**Comment by kolibril13** [comment]
Here is my output from ExampleVideoMobject to give you an example:
output

**Comment by Tony031218** [comment]
This may be a good idea.

But there is still much room for improvement. As you said, this method takes up a lot of space.
And you'd better implement control of the playback rate of `VideoMobject`.
And unify the frame rate of `VideoMobject` and the frame rate of video generated by manim, otherwise this will look strange.

If you save space and implement functions such as movement, this will be a very simple and useful operation. But at present, it does not have more advantages than using external video editing software to add video.

**Comment by leotrs** [comment]
I tend to agree with @Tony031218 here.

And additionally, I'm a bit weary of continuing to add new functionality before having more extensive documentation/tests.

**Comment by kolibril13** [comment]
ok, then I will come back with this in a few month.

**Comment by safinsingh** [comment]
@kolibril13 any progress on this PR?

**Comment by kolibril13** [comment]
@safinsingh No, this is the most current version

**Comment by leotrs** [comment]
If the current plan is to "come back to this in a few months", I vote we close this until that time. By that time there will have been a bunch of other additions and the PR will essentially be entirely different. Closing for now. @kolibril13 feel free to reopen right now if you have more updates. Or please open a new PR in the future.

**Pull request closed without merging**
