### PR TITLE
Simplify file writer handling of directories

### PR DESCRIPTION
**Pull request by leotrs**
## Motivation
SceneFileWriter is a mess. The main purpose of this PR is to simplify the logic in SceneFileWriter.init_output_directories by making use of the new ManimConfig class.

## Explanation for Changes
The ManimConfig class was built purposefully so that certain directories could be defined in terms of others. For example, the value of `config.tex_dir` is `{media_dir}/Tex` by default. In order to get the *actual* directory, you need to call `get_dir()`:
```python
>>> config.tex_dir
'{media_dir}/Tex'
>>> config.get_dir("tex_dir")
PosixPath('media/Tex')
```

This is done in a lazy way, at the last possible minute, so that you always get the correct directory:
```python
>>> config.media_dir = 'my_media_dir'
>>> config.get_dir("tex_dir")
PosixPath('my_media_dir/Tex')
```

There are also other directories that are a bit more complicated. For example, the default value of `video_dir` includes the name of the input file and the quality (e.g. 480p15). This is not information contained in `config` so it has to be supplied:
```python
>>> config.video_dir
'{media_dir}/videos/{module_name}/{quality}'
>>> config.get_dir("video_dir")
# -> KeyError
>>> config.get_dir("video_dir", module_name="myfile")
PosixPath('media/videos/myfile/1080p60')
```

The last trick is to do this recursively. For example, I have added a new option `config.partial_movie_dir` that depends on video_dir, which in turn depends on media_dir:
```python
>>> config.partial_movie_dir
'{video_dir}/partial_movie_files/{scene_name}'
>>> config.get_dir("partial_movie_dir")
# -> KeyError
>>> config.get_dir("partial_movie_dir", module_name="myfile", scene_name="myscene")
PosixPath('media/videos/myfile/1080p60/partial_movie_files/myscene')
```

Given all of this, SceneFileWriter can happily just use these config options without having to create the paths itself. This simplifies `SceneFileWriter.output_directories` by a ton. Additionally, the manim-directive is also affected and simplified (@ManimCommunity/docs ).

The default values of each of the `*_dir` options can be changed by a .cfg file. This gives the user a *great deal of freedom*. Now the user can customize the whole output directory structure by changing their .cfg files.

## List of Changes
- simplified SceneFileWriter.init_output_directories
- Simplified manim-directive
- implemented/changed/fixed ManimConfig.get_dir
- deleted a couple of getter methods in SceneFileWriter
- added partial_movie_dir config option
- added test for --custom_folders

PENDING: I will add documentation and update the changelog in an upcoming PR :)

## Testing Status
Local pass.

## Further Comments
Finally, given this architecture, the `--custom_folders` flag is a bit unnecessary, as a user could do that by manually changing the config options and keeping a .cfg file. However, I think it's nice that manim gives two different options by default (the usual and the one given by --custom_folders). If neither is good for the user, then they can use a .cfg file. I do suggest that we change `--custom_folders` to `--simple_folders`, as the name "custom" is now misplaced. I think the main person interested in this will be @kolibril13.

### CODE REVIEW

**Comment by leotrs** [comment]
BTW this is one of the main reasons why I wanted to implement ManimConfig in the first place! Six PRs later, I am so happy to see this bad boi finally up here!

**Review by behackl — APPROVED** [review]
This is absolutely great, I love how clean the interaction with the various directories now is.

While I am fine with merging this in its current form, I do have one request: could you also have a look at https://github.com/ManimCommunity/manim/pull/640/files#diff-78c9eefa17cfaca7699cff2d940cbd4c57cfdf42ce6b278d0c2453ec5c3994cfL239-L249 where currently the location of the file is built as a concatenation of `video_dir` and `quality_dir` -- could you also change this according to your refactor? :-)

**Review by behackl — APPROVED** [review]
Thank you! I've just pushed a commit fixing black; everything should work now. 👍

**Comment by leotrs** [comment]
Lol I forgot about black. Thanks!

**Comment by kolibril13** [comment]
Looks good to me as well!
I don't mind too much if it will be --custom_folders or --simple_folders , just personally I am already familiar to use custom_folders, so that is what I would prefer, but feel free to change it if you would prefer it that way.

**Review by kolibril13 — APPROVED** [review]

**Comment by leotrs** [comment]
WOOHOO

**Pull request merged**
