### PR TITLE
Fixed ``CLI.tex_template_file`` config file setting

### PR DESCRIPTION
**Pull request by NotWearingPants**
## Overview: What does this pull request change?
Manim supports a setting called `tex_template_file` under the `CLI` key in `manim.cfg`, and apparently this setting has been broken for almost 2 years, since 8f4506da43464a739789bc311f895dbce2856391 which renamed a kwarg but not all of its usages.

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by naveen521kk** [comment]
Adding a test is better to avoid breaking this again. Thanks.

**Review by behackl — APPROVED** [review]
I have added an appropriate test for the config setting, otherwise this looks good to me. Will merge once pipeline passes.

Thanks!

**Comment by behackl** [comment]
One observation made when writing the first version of this test: if `config.tex_template_file` is set *after* `config.tex_template` has been populated, `config.tex_template` is **not** regenerated.

Feels like something that should perhaps be fixed (or at least investigated some more).

**Comment by NotWearingPants** [comment]
> One observation made when writing the first version of this test: if `config.tex_template_file` is set _after_ `config.tex_template` has been populated, `config.tex_template` is **not** regenerated.
> 
> Feels like something that should perhaps be fixed (or at least investigated some more).

I also came across this when trying to write a test, but I found [you made the choice intentionally to not regenerate](https://github.com/ManimCommunity/manim/pull/2888/commits/56efa4e91dbe1bb78b15e3f3f5a1421142c6ef41), so I wasn't sure how to proceed. I was thinking maybe the "decoupling" you wanted was to avoid repeating the logic, so maybe adding a `this._tex_template = None` is acceptable.

Also I think these two lines are relevant
https://github.com/ManimCommunity/manim/blob/bf0ea29338694b24e3ec3d7eb087a5aff523b357/manim/_config/utils.py#L367-L368

I think if we add a reset then this test should also be added:
```py
with tempconfig({"tex_template_file": "foo.tex"}):
    assert config.tex_template.body == "from foo.tex"
    config.tex_template.body = "not from foo.tex"
    with tempconfig({"tex_template_file": "bar.tex"}):
        assert config.tex_template.body == "from bar.tex"
    assert config.tex_template.body == "not from foo.tex"
```
i.e. that reverting back to a config (calls `.update`) that sets `tex_template_file` does not reset the changes to the `tex_template` object itself

**Pull request merged**
