### PR TITLE
Get help of some multiprocessing for the rtd-docs build

### PR DESCRIPTION
**Pull request by Kiran-Raj-Dev**
## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by Kiran-Raj-Dev** [comment]
988 seconds and before it was 991.

Not very substantial

**Comment by Darylgolden** [comment]
> 988 seconds now and before it was 991.
> 
> Not very substantial

We'll need to ask RTD to enable multiprocessing

**Comment by Kiran-Raj-Dev** [comment]
hmm, maybe worth it?

**Comment by behackl** [comment]
I am not sure this would work properly without changing the way the manim directive is implemented.

**Comment by Kiran-Raj-Dev** [comment]
If I understand properly, the manim directive is for rendering manimations whereas this is just multiprocessing for the docs build itself. But the change is not very substantial (~10 seconds). I think I'll close this for now, untill I have something more substantial.

**Pull request closed without merging**
