### PR TITLE
Added support for Python 3.11, dropped support for Python 3.7

### PR DESCRIPTION
**Pull request by naveen521kk**
## Overview: What does this pull request change?

- Drop support for Python 3.7

Depends on #3029 

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Comment by behackl** [comment]
Looks like there is problems from an update of `moderngl`.

**Comment by naveen521kk** [comment]
> Looks like there is problems from an update of `moderngl`.

Will have a look.

**Comment by naveen521kk** [comment]
Hmm, I think the Cairo update on manimpango wheels (macOS) causing issues. Something related to SVG being invalid. Tried reproducing this on Windows, but seems this happens only on macOS (I think it should be from the wheels, so intel mac), can anyone provide me with the SVG file that manim fails to parse?

**Comment by naveen521kk** [comment]
> Hmm, I think the Cairo update on manimpango wheels (macOS) causing issues. Something related to SVG being invalid. Tried reproducing this on Windows, but seems this happens only on macOS (I think it should be from the wheels, so intel mac), can anyone provide me with the SVG file that manim fails to parse?

This should be fixed with the v0.4.3 release. Will rebase this PR.

**Comment by behackl** [comment]
> This should be fixed with the v0.4.3 release. Will rebase this PR.

Thanks for your efforts!

**Comment by naveen521kk** [comment]
Not sure why the tests are failing :(

**Comment by behackl** [comment]
> Not sure why the tests are failing :(

I'll take a closer look later. The difference in the torus and point cloud tests seemed small enough that they should be covered by our tolerance though, so I am a bit confused why they didn't just pass. And some tests failed due to the weird rate limit that we always run into when I start editing PR titles and descriptions for the changelog.

**Comment by behackl** [comment]
@naveen521kk I think we can revert the version restriction to pycairo again, now that the pixel error tolerance is in place. Will do so and see whether the pipeline passes then.

**Review by behackl — APPROVED** [review]

**Pull request merged**
