### PR TITLE
Fixing `GrowArrow()`

### PR DESCRIPTION
**Pull request by PhotonSpheres**
## Motivation

~~The animation `GrowArrow()` is broken. It sends the boolean `scale_tips=True` to the function `scale()` and ultimativeley to `apply_points_function_about_point()`. Those function have no parameter `scale_tips` though.~~

EDIT
`GrowArrow()` only works for class `Arrow`, not for `Arrow3D` since it utilizes the own `scale` method of `Arrow`. This `scale` method relies on `Arrow` being a `TipableVMobject`, which `Arrow3D` is not. I have all suggestions listed in Issue #1741 .

## Checklist
- [ ] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [ ] I have written a descriptive PR title (see top of PR template for examples)
- [ ] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

**Comment by abhi3019** [comment]
Hi, `Arrow` implements its own `scale` method which allows the parameter `scale_tips`
https://github.com/ManimCommunity/manim/blob/1e01feb70dccbe493d173ef76046a3d1b851e685/manim/mobject/geometry.py#L1275
It would probably be better to add the `scale` method to `Arrow3D` as well (I'm not sure if its logic would be the same as that of `Arrow.scale`), instead of removing the `scale_tips` parameter ?

**Comment by PhotonSpheres** [comment]
> Hi, `Arrow` implements its own `scale` method which allows the parameter `scale_tips`
> 
> https://github.com/ManimCommunity/manim/blob/1e01feb70dccbe493d173ef76046a3d1b851e685/manim/mobject/geometry.py#L1275
> 
> 
> It would probably be better to add the `scale` method to `Arrow3D` as well (I'm not sure if its logic would be the same as that of `Arrow.scale`), instead of removing the `scale_tips` parameter ?

Good catch, I should have seen that... I will mark this as a draft and think about the logic for `Arrow3D`.

**Comment by behackl** [comment]
Sorry for the *very* late response! I think instead of modifying the `GrowArrow` animation, it would make more sense to implement a custom `Arrow3D.scale` method that behaves similar to the `Arrow.scale` method -- including the optional keyword argument `scale_tips`.

**Comment by MrDiver** [comment]
Closing this for now due to inactivity

**Pull request closed without merging**
