### PR TITLE
Fix axes plotting bug with logarithmic x-axis

### LINKED ISSUE #2543: Weird line when plotting staircase function
## Description of bug / unexpected behavior
I tried to plot a staircase function with a logarithmic x axis. The function is plotted correctly but there is a line in the graph that does not belong to the staircase function.


## Expected behavior
Do not print the line that does not belong to the function.


## How to reproduce the issue

Put the below code in `staircase.py` and run `manim -pql staircase.py BuggyStaircase`.

<details><summary>Code for reproducing the problem</summary>

```py
from manim import *

class BuggyStaircase(Scene):
    def construct(self):
        axes = Axes(
            x_range=[-1, 5, 1],
            y_range=[0, 30, 5],
            x_axis_config={"scaling": LogBase()},
        )

        price = lambda x: 21 if x < 180 else 10 if x < 6000 else 6

        graph = axes.plot(price, x_range=[-1, 4.9, 0.001], use_smoothing=False)

        self.add(axes, graph)
```

</details>


## Additional media files
<!-- Paste in the files manim produced on rendering the code above. -->

<details><summary>Images/GIFs</summary>

![bug](https://user-images.githubusercontent.com/39318299/153752124-dd204987-56a2-49d9-a7fc-f247f7e52878.png)

</details>


## Logs
<details><summary>Terminal output</summary>
<!-- Add "-v DEBUG" when calling manim to generate more detailed logs -->

```
Manim Community v0.14.0

[02/13/22 13:02:25] INFO                                                                                                                                      scene_file_writer.py:729
                             File ready at '/home/something/something/media/images/staircase/BuggyStaircase_ManimCE_v0.14.0.png'                                                   
                                                                                                                                                                                      
                    INFO     Rendered BuggyStaircase                                                                                                                      scene.py:237
                             Played 0 animations                                                                                                                                      
                    INFO     Previewed File at: '/home/something/something/media/images/staircase/BuggyStaircase_ManimCE_v0.14.0.png'                               file_ops.py:202
```

<!-- Insert screenshots here (only when absolutely necessary, we prefer copy/pasted output!) -->

</details>


## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g., Windows 10 v2004 or macOS 10.15 (Catalina)): Arch Linux
- RAM: 16 GB
- Python version (`python/py/python3 --version`): 3.10.2
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:
<!-- output of `tlmgr list --only-installed` for TeX Live or a screenshot of the Packages page for MikTeX -->
</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

## Additional comments
<!-- Add further context that you think might be relevant for this issue here. -->

### PR DESCRIPTION
**Pull request by ackxolotl**
The scaling function was not applied to the last x-value to be evaluated, resulting in a wrong point of the function plot and a weird line from the second-last to the last point when using a scaled x-axis. This PR fixes #2543.

## Overview: What does this pull request change?

Run `manim -pql scene.py Staircase` on `scene.py` containing this code:

```
from manim import *


class Staircase(Scene):
    def construct(self):
        axes = Axes(
            x_range=[-1, 4],
            y_range=[0, 3],
            x_axis_config={"scaling": LogBase()},
        )

        price = lambda x: 2 if x < 10 else 1

        graph = axes.plot(price, x_range=[-1, 4], use_smoothing=False)

        self.add(axes, graph)

```

Before:

before

After:

after

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

### CODE REVIEW

**Review by icedcoffeeee — CHANGES_REQUESTED** [review]
Looks great! Thank you for your contribution. Could you add tests for graphs on log axes?

**Comment by ackxolotl** [comment]
Like this? I tried to add a unit test just for `ParametricFunction.generate_points()` but that's a bit tricky.

**Comment by icedcoffeeee** [comment]
> Like this? I tried to add a unit test just for ParametricFunction.generate_points() but that's a bit tricky.

Sorry for being clear, I meant a graphical test, you can refer [here](https://docs.manim.community/en/stable/contributing/testing.html#graphical-unit-test)

**Review by icedcoffeeee — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
